### ISSUE TITLE
Support index configuration as a part of pushbutton deploy. 

### ISSUE THREAD

**Issue by HemantPuranik** [marklogic/marklogic-data-hub#10]
Index configuration by dropping config items into the right directory so it gets picked up by the pushbutton deploy. (OOTB with mlgradle)

**Comment by maeisabelle** [comment]
Hi @paxtonhare ,

Do we already have this feature? I had an upcoming project for MarkLogic that requires this and I'm curious how this can be done. I can work on this one if this is not yet implemented.

**Comment by paxtonhare** [comment]
@maeisabelle This is done in the develop branch. It will be included in the next release.
