### ISSUE TITLE
Cannot follow REST Client API example for ingest

### ISSUE THREAD

**Issue by lifan0127** [marklogic/marklogic-data-hub#1016]
#### The issue

After setting up a ml-data-hub using the Gradle plugin following the instruction here: https://marklogic.github.io/marklogic-data-hub/project/gradle/

I was not able to ingest document using the REST API following the example here:
https://marklogic.github.io/marklogic-data-hub/ingest/rest/

#### Tech details

Which Operating System are you using? CentOS7

Which version of MarkLogic are you using? 9.0_5

Which version of the Data Hub Framework are you using? 3.0

Is this a QuickStart UI bug? If so, which browser are you using? No

#### The devil is in the details...

If I just ingest a document using the REST API, everything is fine:

Request:
```bash
curl --anyauth --user user:password -T ./my-content -i \
  -X PUT -H 'Content-type: application/xml' \
  'http://localhost:8010/v1/documents?uri=/my/test.xml'
```

Response:
```bash
HTTP/1.1 201 Created
Location: /v1/documents?uri=/my/test.xml
Server: MarkLogic
Content-Length: 0
Connection: Keep-Alive
Keep-Alive: timeout=5
```
If I add the `transform`, `trans:entity-name` and `trans:flow-name`, I will get a 400 bad request error
Request:
```bash
curl --anyauth --user user:password -T ./my-content -i \
  -X PUT -H 'Content-type: application/xml' \
  'http://localhost:8010/v1/documents?uri=/my/test.xml&transform=run-flow&trans:entity-name=doc&trans:flow-name=input-doc'
```

Response:
```
HTTP/1.1 400 Bad Request
Content-type: application/json; charset=UTF-8
Server: MarkLogic
Content-Length: 327
Connection: Keep-Alive
Keep-Alive: timeout=5

{"errorResponse":{"statusCode":400, "status":"Bad Request", "messageCode":"RESTAPI-INVALIDREQ", "message":"RESTAPI-INVALIDREQ: (err:FOER0000) Invalid request:  reason: Extension run-flow or a dependency does not exist: XDMP-MODNOTFOUND: (err:XQST0059) Module /marklogic.rest.transform/run-flow/assets/transform.xqy not found"}}
```

If I further include the `trans:options` and `trans:job-id`, I will get a 401 Unauthorized error
Request:
```bash
curl --anyauth --user user:password -T ./my-content -i \
  -X PUT -H 'Content-type: application/xml' \
  'http://localhost:8010/v1/documents?uri=/my/test.xml&transform=run-flow&trans:entity-name=doc&trans:flow-name=input-doc&trans:options={"your":"options"}&trans:job-id=someString'
```

Response:
```bash
HTTP/1.1 401 Unauthorized
Server: MarkLogic
WWW-Authenticate: Digest realm="public", qop="auth", nonce="363e10f2969b92:fTRvs/O9m/03pcgOcYuJrw==", opaque="47af98f471cfc221"
Content-Type: application/json; charset=utf-8
Content-Length: 104
Connection: close

{"errorResponse":   {"statusCode":401,
   "status":"Unauthorized",
   "message":"401 Unauthorized"
  }
}
```

┆Status: New

**Comment by grechaw** [comment]
Hi @lifan0127 you've found a bug in our documentation, which we will update.

the transform name is ml:inputFlow, if your flow is XQuery, and ml:sjsInputFlow if it is JavaScript.

The 401 error you've gotten is because 'user:password' is intended to be an actual set of credentials on the server.  try using admin:admin since you've done that elsewhere, and I think you will be set.

**Comment by grechaw** [comment]
Hi @lifan0127 I've gone ahead and updated the docs.  Thanks for reporting the issue!

**Comment by lifan0127** [comment]
Thanks, it works for me now.

**Comment by lifan0127** [comment]
@grechaw Could you please also take a look at this SO post: https://stackoverflow.com/questions/50369100/marklogic-9-0-5-and-dhf-3-0-fail-to-load-mlcp-module-on-mldeploy

It is related to invoking DHF input flow in MLCP. Thanks!
