### ISSUE TITLE
Add REST scaffolding

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#102]
Need scaffolding to generate REST stuff.

For REST extensions use the provided parameters from the sidecar xml to auto place let vars inside the code. Saves the end user some time.

**Comment by maeisabelle** [comment]
Hi @paxtonhare,

Where can we find the sidecar xml you're referring to?

**Comment by paxtonhare** [comment]
For REST services the sidecar files are in the services/metadata folder.
See here:
https://github.com/marklogic/marklogic-data-hub/tree/master/marklogic-data-hub/src/main/resources/ml-modules/services

**Comment by maeisabelle** [comment]
Hi @paxtonhare,

I already pushed my commits for this and created a PR: https://github.com/marklogic/marklogic-data-hub/pull/134. 

Though I have a question on duplicate REST service extensions and transforms. Those are possible as I observed when I tried to install them via DataHub (copying to my plugins directory and deploying them to the server), the uri used have the following format:

/marklogic.rest.resource/**_myExtension_**/assets/metadata.xml
/marklogic.rest.resource/**_myExtension_**/assets/resource.sjs
/marklogic.rest.resource/**_myExtension_**/assets/resource.xqy
/marklogic.rest.transform/**_myExtension_**/assets/metadata.xml
/marklogic.rest.transform/**_myExtension_**/assets/transform.sjs

Given such, how can we ensure that one extension / transform won't overwrite another one even if they belong to a different entity? Will we use a standard for names where we prepend the entity name to the extension name provided?

**Comment by paxtonhare** [comment]
@maeisabelle for now please create a new ticket with this issue. We can address it later with code or with documentation.

**Comment by maeisabelle** [comment]
Hi @paxtonhare,

I created https://github.com/marklogic/marklogic-data-hub/issues/143 for this.
