### ISSUE TITLE
gradle task running an importflow will fail because it is not running in query mode

### ISSUE THREAD

**Issue by peetkes** [marklogic/marklogic-data-hub#1032]
I'm running on ml9.0-5 with the datahub 3.0.0
I created a gradle task to run an input flow, pretty similar as what is generated when using the quickstarter
In the gradle task you need to add the following switch -modules_root / to force it to query mode
This is missing from the documentation
Example:
````
task importUsers(type: com.marklogic.gradle.task.MlcpTask) {
    classpath = configurations.mlcp
    command = "IMPORT"
    port = mlStagingPort.toInteger()
    document_type="xml"
    input_file_path = userLocation
    input_file_type = "documents"
    output_collections = "User,Raw,input,OASIS,"+userJobId
    output_uri_prefix = "/OASIS/Users"
    output_permissions = "rest-reader,read,rest-writer,update"
    output_uri_replace = userUriReplace
    transform_module = "/MarkLogic/data-hub-framework/transforms/mlcp-flow-transform.xqy"
    transform_namespace = "http://marklogic.com/data-hub/mlcp-flow-transform"
    transform_param = "entity-name=User,flow-name=ImportUsers,dhf.jobId="+userJobId
}
````
This one is failing
````
 importUsers(type: com.marklogic.gradle.task.MlcpTask) {
    classpath = configurations.mlcp
    command = "IMPORT"
    port = mlStagingPort.toInteger()
    document_type="xml"
    input_file_path = userLocation
    input_file_type = "documents"
    output_collections = "User,Raw,input,OASIS,"+userJobId
    output_uri_prefix = "/OASIS/Users"
    output_permissions = "rest-reader,read,rest-writer,update"
    output_uri_replace = userUriReplace
    transform_module = "/MarkLogic/data-hub-framework/transforms/mlcp-flow-transform.xqy"
    transform_namespace = "http://marklogic.com/data-hub/mlcp-flow-transform"
    transform_param = "entity-name=User,flow-name=ImportUsers,dhf.jobId="+userJobId
    args = ["-modules_root","/"]
}
````

This one is working!

**Comment by damonfeldman** [comment]
The error thrown by the DHF code's update check is "XDMP-AS" because the empty timestamp can't be cast to a number. Instead, this should probably throw a descriptive error about update mode. Perhaps some hit about this modules setting could be put there, because it will be hard to find this in the docs. (similarly for .sjs, whatever that does)

**Comment by popzip** [comment]
Is this broken code or just a documentation fix and possibly error reporting enhancement?

**Comment by popzip** [comment]
fyi an inbound conversation: https://stackoverflow.com/questions/50369100/marklogic-9-0-5-and-dhf-3-0-fail-to-load-mlcp-module-on-mldeploy

**Comment by aebadirad** [comment]
This should no longer be an issue in 4.0.0, so closing, BUT we should refer to this for the better-errors epic.
