### ISSUE TITLE
UI messaging on entity that has no properties on Map

### ISSUE THREAD

**Issue by ayuwono** [marklogic/marklogic-data-hub#1034]
QuickStart version 3.0.0
Branch: develop
Browser: Chrome
OS: Mac

Steps
=====
1) Create an entity without any property
2) Go to Flows, create an input flow and load data using the input flow
3) Create a harmonize flow
4) Click on Create Map

There should be a UI messaging on entity that has no properties

┆Status: New

**Comment by ayuwono** [comment]
<img width="1564" alt="screen shot 2018-05-30 at 11 23 21 am" src="https://user-images.githubusercontent.com/7096668/40741085-5dbf1580-63ff-11e8-84b1-d6e0ef83af8e.png">

**Comment by wooldridge** [comment]
@ayuwono, this should be fixed with PR #1048. When a model entity has no properties, messaging is displayed under the model column and includes a link to the Entities view, where properties can be added.

**Comment by ayuwono** [comment]
Verified passed on mapping/menu-sources branch
