### ISSUE TITLE
Auto Generate Indexes based on entity defs

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#105]
This is assuming the usage of entity services in ML9.

Hoping entity services allows us to:
- Index generation.
- Maybe generate options nodes for searches.

**Comment by grechaw** [comment]
Yes, it will do both.  
The index generation will be in the form of a JSON database-properties file, which can be stored in the appropriate place in ml-app-deployer structure.

Same goes for search options nodes.
