### ISSUE TITLE
On mapping, a data that starts with a number then followed by non-number character is interpreted as number

### ISSUE THREAD

**Issue by ayuwono** [marklogic/marklogic-data-hub#1051]
QuickStart version 3.0.0
Branch: mapping/menus-source
Browser: Chrome
OS: Mac

On mapping, if your data starts with a number then followed by a non-number character, the type is displayed as number. Examples on the screenshot: 7.0-1, 7.0-nightly

It should be string

<img width="1357" alt="screen shot 2018-06-04 at 1 06 18 pm" src="https://user-images.githubusercontent.com/7096668/40939081-7f0af72a-67f8-11e8-87a9-4bb7a0b46b4c.png">

┆Status: New

**Comment by wooldridge** [comment]
@ayuwono, can you check that #1055 fixes this issue?

**Comment by ayuwono** [comment]
Verified passed on mapping/source-menu branch
