### ISSUE TITLE
Online shopping tutorial - Product Harmonize flow output is not as expected

### ISSUE THREAD

**Issue by lsheth** [marklogic/marklogic-data-hub#1063]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue
I am running the online shopping tutorial - Product Harmonize flow in Javascript and output in final database is not as expected. It generates "attachment" node twice in an envelope. Once inside the Product instance (Here it is NOT expected) and "attachment" as separate node inside "envelope" root to show the original data. screenshot of final document is attached. I have the same code for content.js for this flow as mentioned in tutorial documentation but output is different then shown in tutorial document. To test this issue further, I created Product Harmonize flow using XQUERY and out of the XQUERY flow is perfect as expected. It has only ONE "attachment" node in "envelope" root node. I have attached content.js and content.xqy files as well as out of final document from both the flows.

Short description of the problem: 
Product Harmonize module in JavaScript for online shopping tutorial is repeating the "attachment" node in "Product Instance"

What behavior are you expecting?
Not expecting repeating "attachment" node in Product "Instance" in envelope node. there is something wrong with the Javascript module of the Harmonize flow. Same flow generated in XQuery works as expected.

#### Tech details

Which Operating System are you using? Mac-OS

Which version of MarkLogic are you using? ML 9.0-5

Which version of the Data Hub Framework are you using? v 3.0.0

Is this a QuickStart UI bug? If so, which browser are you using? Using QuickStart in Firefox

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`
<img width="698" alt="screen shot 2018-06-07 at 11 08 47 am" src="https://user-images.githubusercontent.com/14844495/41118008-7a12d9a2-6a43-11e8-835e-77ccef619155.png">
<img width="708" alt="screen shot 2018-06-07 at 11 06 30 am" src="https://user-images.githubusercontent.com/14844495/41118010-7bd5ad50-6a43-11e8-83c5-3558bf243b60.png">

[Archive.zip](https://github.com/marklogic/marklogic-data-hub/files/2081614/Archive.zip)

**Comment by aebadirad** [comment]
This should now be fixed as well with 4.0.0, please open if that's not the case
