### ISSUE TITLE
make search options handle proper namespaces

### ISSUE THREAD

**Issue by peetkes** [marklogic/marklogic-data-hub#1067]
When you create an entity with namespaces and you define range indexes on some fields, the search options will be generated in the entity-config folder but they lack the namespace definition in the extract-path definition:
For instance when you define an entity named User with namespace definitions like this:
```
  "definitions" : {
    "User" : {
      "namespace": "http://acme.com/somesystem/user",
      "namespacePrefix": "usr",
      ....
```

It will generate search options like this:
```
<search:extract-document-data selected="include">
    <search:extract-path>//*:instance/usr:User</search:extract-path>
</search:extract-document-data>
```
It is lacking the namespace definition in the extract-path element
It should read like this:
```
<search:extract-document-data selected="include">
    <search:extract-path xmlns:usr="http://acme.com/somesystem/user">//*:instance/usr:User</search:extract-path>
</search:extract-document-data>
```
I'm using DHF 3.0.0 on MarkLogic 9.0-5

**Comment by grechaw** [comment]
Thanks for reporting @peetkes .  This has been reported already.  If you use entity services directly then there is indeed a namespace declaration.  I'll find the existing  bug number and link here later today.

**Comment by popzip** [comment]
@grechaw poke. whats the related bug #?

**Comment by grechaw** [comment]
Here it is https://github.com/marklogic/marklogic-data-hub/issues/744

**Comment by rjrudin** [comment]
I verified that this is working correctly in 5.4, and it may be in 5.2 as well. You can verify it in the examples/reference-entity-model project, where the NamespacedCustomer entity has an "oex" namespace prefix, and this appears in the search:extract-path:

```
//*:instance/(Address|Customer|Order|oex:NamespacedCustomer|Zip)
```
