### ISSUE TITLE
Quickstart UI Entity screen can become broken and existing entities no longer display

### ISSUE THREAD

**Issue by danielholgate** [marklogic/marklogic-data-hub#1077]
DHF Quickstart 3.0.0, MarkLogic 9.0.5 running on Centos7

I have a DHF project which somehow has become broken and the Entity screen no longer displays my entities (Entity screen stays blank, plus button is there to add new entities).  I decided to trying adding a new Entity called "testentity" with the plus button and this succeeded and it now displays in the UI but the other 4 entities still don't and each time that screen is accessed the errors I've included below are generated. 
**Update** I noticed after I logged this that testentity gets created, but if I try add a harmonize flow which uses the "Create Structure from Entity Definition" option then the flow is not created and the same error is logged (without that option the flow can be created) 

I'm not sure of the original cause of the problem but it feels like the Quickstart UI should be more robust. If one entity somehow has a problem it shouldn't stop the whole screen working. I'm putting everything here in case it leads to a solution, or further fixes to make the Quickstart more robust in the field.

Error from Quickstart UI is here:  [Quickstart-UI-error.txt](https://github.com/marklogic/marklogic-data-hub/files/2102100/Quickstart-UI-error.txt)
Error from MarkLogic server is here: [ML-Server-error.txt](https://github.com/marklogic/marklogic-data-hub/files/2102101/ML-Server-error.txt)
plugins directory from my project is here:  [plugins.zip](https://github.com/marklogic/marklogic-data-hub/files/2102105/plugins.zip)

<img width="1440" alt="screen shot 2018-06-14 at 1 32 02 pm" src="https://user-images.githubusercontent.com/13762269/41409709-64b38c34-6fd7-11e8-9de7-42f268a5e501.png">

**Comment by aebadirad** [comment]
Closing out old issue that no longer applies to the latest major release. Should be resolved there.
