### ISSUE TITLE
How can I use ml-unit-test in DHF?

### ISSUE THREAD

**Issue by lukasz1234567890** [marklogic/marklogic-data-hub#1090]
#### The issue

I'd like to cover xquery code I'm using in my hub with unit test. I saw there has been small refactoring effort recently that had pulled out unit tests framework out of roxy into a standalone [ml-gradle module](https://github.com/marklogic-community/ml-unit-test). However, I can't seem to find a way to make the two work.

Is there a way to write unit test within DHF project?

#### Tech details

Which Operating System are you using?
Windows 10

Which version of MarkLogic are you using?
9.0-5

Which version of the Data Hub Framework are you using?
3.0.0

Is this a QuickStart UI bug? If so, which browser are you using?
No.

#### The devil is in the details...

Deployment goes just fine, producing DHF databases and app servers, but all ml-unit-test related settings are ignored.

┆Status: New

**Comment by dmcassel** [comment]
@lukasz1234567890 please see [this example project](https://github.com/marklogic-community/ml-gradle/tree/dev/examples/unit-test-project) showing how to include ml-unit-test in an ml-gradle project. If that doesn't work, please post your configuration and more information about what isn't working.

**Comment by lukasz1234567890** [comment]
@dmcassel I forked and added DHF to this example project. Commit [here](https://github.com/lukasz1234567890/ml-gradle/commit/4e991d905055472ac4cc252abdcc3c7eb86caeee). The project is scaffolded using quickstart 3.0 plus some manual changes to the `build.gradle` and `properties`. Then I've run ` ./gradlew mldeploy -PenvironmentName=local -i` that ended with success. However no test appserver on port `8135` is created.

**Comment by rjrudin** [comment]
This should work - This should work - https://github.com/marklogic-community/ml-unit-test/wiki/Integrating-with-DHF

**Comment by lukasz1234567890** [comment]
Thank you @rjrudin - I suppose I should start the thread in ml-unit-test repo. In case of any follow up issues I'll post it there.

**Comment by rjrudin** [comment]
A quick note - the Wiki page I wrote up addresses how to make mlWatch work - I need to expand it to address how to ensure the ml-unit-test modules get loaded in the first place.
