### ISSUE TITLE
DHF Quickstart doesn't catch error at save time where modules are incorrectly referenced

### ISSUE THREAD

**Issue by danielholgate** [marklogic/marklogic-data-hub#1091]
DHF Quickstart 3.0, Marklogic 9.0.5

The Quickstart UI helpfully catches code errors in Flow processing code and shows a 'bug' icon for most errors, but doesn't catch incorrect modules being referenced. Example:

`import module namespace es2 = "http://marklogic.com/entity-services2" at "/MarkLogic/entity-services/entity-services2.xqy";`

Including the above (reference to a non-existent module) in a flow does not produce a bug at save time, but fails at run time

**Comment by aebadirad** [comment]
Data Hub 5.0 has dropped this kind of flow. While this could be valuable for 4.x still, a better tool to support custom steps is more in line with the 5.0 direction. So putting effort there and closing this out.
