### ISSUE TITLE
Harmonize flow ends with "FAILED" status if no documents collected by collector. 

### ISSUE THREAD

**Issue by danielholgate** [marklogic/marklogic-data-hub#1130]
DHF 3.0.0 , MarkLogic 9.0.5

As per the title. If there is any (non-syntactic) problem in the collector portion of a harmonize flow which results in no documents being collected, then the flow ends with FAILED status but no logging to indicate why. This can lead to wasted developer time hunting through logs etc. No documents being collected doesn't really seem like it should be a "failed" status but should rather be "success" with a message noting "0 documents collected" etc be logged somewhere. 

For example: if the default collector code is used but the Entity has somehow changed name
`cts:uris((), (), cts:collection-query(map:get($options, "entity")))`
or if a custom collection routine is being used
`cts:uris((), (), cts:collection-query("myEntityCollection"))`

If there is no collection called _myEntityCollection_ or no documents in it then the result of the harmonize flow looks like this:
```
{
  "jobId" : "e18ce95a-d521-4d56-9d4b-fc319788f98c",
  "flowType" : "harmonize",
  "flowName" : "MyHarmonizeFlow",
  "entityName" : "SomeEntityName",
  "jobName" : null,
  "startTime" : "2018-07-03T15:59:42.357Z",
  "endTime" : "2018-07-03T15:59:43.720Z",
  "jobOutput" : null,
  "status" : "FAILED",
  "successfulEvents" : 0,
  "failedEvents" : 0,
  "successfulBatches" : 0,
  "failedBatches" : 0
}
```
The quickstart UI trace for the job looks like this:
<img width="1399" alt="screen shot 2018-07-03 at 6 02 03 pm" src="https://user-images.githubusercontent.com/13762269/42242466-3c729f8a-7f0e-11e8-887c-25b41ad49ab6.png">

No logs are generated on the MarkLogic server as this is not a syntactic problem

**Comment by mhuang-ml** [comment]
Issue was duplicated by https://github.com/marklogic/marklogic-data-hub/issues/1715

**Comment by aebadirad** [comment]
This is no longer the behavior of data hub 4.x and 5.0 allows for the user to see the results of a flow, including attempted documents vs. successful/failed documents.
