### ISSUE TITLE
Generated mlcp command in QuickStart import always fails

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#1148]
#### The issue
Input flows must include -modules-root / to work, because this somehow causes mlcp ingests to be in query mode. However, QuickStart generates an mlcp command without this option, so it fails.

This is really quite confusing on three fronts:
* There is no documentation of this issue
* It is counterintuitive
* The error thrown is a cryptic XMDMP-AS saying
   * XDMP-AS: (err:XPTY0004) let $_must_run_in_query_mode as xs:unsignedLong := xdmp:request-timestamp() -- Invalid coercion: () as xs:unsignedLong

I suggest a number of changes. These are not alternates, but rather could all be done

change the error detection code to something like:
let$_ := if (empty(xdmp:request-timestamp()) then error(xs:QName("INPUT_IN_UPDATE_MODE"), "Input flows must run in query mode. Eliminate updates or include -modules-root  in mlcp command") else ()

Document the issue

Include the magic option in the generated mlcp command in QuickStart

Update mlcp to have a readable option to run in query mode

What behavior are you expecting?

#### Tech details

Which Operating System are you using?

Which version of MarkLogic are you using?

Which version of the Data Hub Framework are you using?

Is this a QuickStart UI bug? If so, which browser are you using?

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by kcoleman-marklogic** [comment]
I think we need to understand the underlying cause of the problem and not just slap an undocumented option on the mlcp command line. 

Does DHF use `-fastload` or `-output_directory`? (The latter implies `-fastload`.) 

You cannot perform updates with `-fastload`. This is intentional, I believe to avoid duplicate URIs. It also imposes some limitations on a server-side transformation.

**Comment by kcoleman-marklogic** [comment]
OK, we at least finally figured out this mlcp option was added on behalf of internal but 35872. It's meant to be user-facing.

**Comment by aebadirad** [comment]
in 4.0.0, this should be fixed and not require the modules root setting anymore.
