### ISSUE TITLE
Able to create maps with duplicate names

### ISSUE THREAD

**Issue by ayuwono** [marklogic/marklogic-data-hub#1176]
QuickStart v3.1.0
develop branch
Chrome on MacOSX

Able to create maps with duplicate names. Doing so will overwrite the existing map with the same name either on the same entity or the other entity

Expected behavior: should not be able to do that, should have a check that will throw an error message

┆Status: To Do

**Comment by wooldridge** [comment]
This problem should be fixed with the merge #1182.
