### ISSUE TITLE
Display information about Flows in Flow Info tab

### ISSUE THREAD

**Issue by rahulvudutala** [marklogic/marklogic-data-hub#1213]
The issue

Short description of the problem:
Cannot see the flow related information in the Flow Info tab for a harmonization flow. It will be good to see information such as Plugin Type, Mapping Used, Data Format

What behavior are you expecting?
See information such as Plugin Type, Mapping Used, Data Format used for creating the harmonization flow

Tech details
Which Operating System are you using?
Mac OS X

Which version of MarkLogic are you using?
ML 9.0-20180720

Which version of the Data Hub Framework are you using?
DHF 3.1.0 (latest develop, commit ID: f230e50)

Is this a QuickStart UI bug? If so, which browser are you using?
Chrome 67.0.3396.99

**Comment by aebadirad** [comment]
These are now visible in data hub 5.0.
