### ISSUE TITLE
Gradle properties and deploying modules with Kerberos configuration

### ISSUE THREAD

**Issue by PatrickTFT** [marklogic/marklogic-data-hub#1258]
### Welcome Hub enthusiast!

We are using (almost) the latest versions of MarkLogic and the Data Hub Framework, and want to switch from Digest to Kerberos authentication for all App Servers.

#### The issue

We have configured the App Services with Kerberos-ticket configuration.
That's nice: automatically login using Active Directory without entering credentials.
Now we have a problem with deploying the modules.

#### Tech details

The Operating System we are using is Windows 10.
The MarkLogic version is v9.0.5.
And the version of the Data Hub Framework v3.0.0.

The problem occurs when deploying the modules.

#### The devil is in the details...
Before implementing the changes from Digest to Kerberos, deploying was done correctly.

Kerberos authentication is now working fine, using App Servers for Query Console, Admin Console, etc.

Security settings are also changed for Staging and Final to Kerberos-ticket.

Changed following in gradle.properties:
mlStagingAuth=digest  => mlStagingAuth=kerberos
mlFinalAuth=digest       => mlFinalAuth=kerberos

  **for gradle:**  
  `gradlew mlRedeployModules --debug'

following error:
* What went wrong:
Execution failed for task ':hubInstallModules'.
> Unable to obtain Principal Name for authentication

**Comment by aebadirad** [comment]
Can you please retry using vanilla ml-gradle kerbos auth settings?
