### ISSUE TITLE
Harmonize flow finishes with "CANCELED" status even though successful

### ISSUE THREAD

**Issue by danielholgate** [marklogic/marklogic-data-hub#1259]
DHF 3.0.0

Under some conditions a Harmonize flow will consistantly return a status of "CANCELED" when it in fact successfully processed all documents and was not stopped/cancelled.

I have done a little debugging and the mis-reporting occurs in FlowRunnerImpl.java https://github.com/marklogic/marklogic-data-hub/blob/47764071f1e79e4d5fe9b36b4e1009dd344d8dd4/marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java#L309

For most flows, uris.size() at this point correctly returns the original number of uris collected and the status reporting is correct. However, it seems over a certain number of uris (in my experience, 5000)  uris.size() will be the correct number before spawning the new thread here https://github.com/marklogic/marklogic-data-hub/blob/47764071f1e79e4d5fe9b36b4e1009dd344d8dd4/marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java#L294

_but then is different by the time we evaluate the status and causes this problem_. Presumably some multi-threading thing

**To reproduce:**

1. Create an entity and ingest this simple csv test file. It has 5004 lines of data.
Make sure you have delimited text and "generate uris" option selected to avoid overwriting any URIs
[test_data.zip](https://github.com/marklogic/marklogic-data-hub/files/2270035/test_data.zip)

2. Create a harmonize flow. Do not edit/customise the flow at all, just let it move the documents from staging to final.
3. Run the flow (from Quickstart UI or gradle command line)
4. Job status incorrectly shows "CANCELED", as all 5004 documents can be found in the FINAL db
<img width="807" alt="screen shot 2018-08-08 at 1 09 33 pm" src="https://user-images.githubusercontent.com/13762269/43833831-5a3f97d8-9b0c-11e8-92b4-b7c6c2b64dfa.png">

I had some debugging code in during this scenario and uris.size() = 5004 before we start, but at the end when status is determined uris.size() = 4 for some reason and that causes the mis-reporting.

**Note: If we add [1 to 5000] to the collector and re-run we get a correct "FINISHED" status**
<img width="797" alt="screen shot 2018-08-08 at 1 12 33 pm" src="https://user-images.githubusercontent.com/13762269/43833974-ca8e6514-9b0c-11e8-8c1b-13a4b8cb6528.png">

**Comment by nic-gibson** [comment]
The same issue occurs in v2.04

**Comment by grechaw** [comment]
I have heard of conversations involving @paxtonhare and @danielholgate about a fix in progress.  We'd like some confirmation of the progress and what needs to happen in the DHF project.

**Comment by danielholgate** [comment]
My fix (for 2.0.4) is attached. I'm simply grabbing the uri.size() count and assigning it to a temp variable and using that, instead of referring back to uri where the size has changed. this solves the status reporting problem but not the underlying change in uri.size() (if that is important anywhere else)
[FlowRunnerImpl.java.zip](https://github.com/marklogic/marklogic-data-hub/files/2274824/FlowRunnerImpl.java.zip)

**Comment by grechaw** [comment]
From how you describe it, sounds like a general bugfix for the problem.  We'll take this, see about covering it with a test and incorporate into the newer branches.  Thanks for taking it on, @danielholgate

**Comment by aebadirad** [comment]
Released in 2.0.6

**Comment by ableasdale** [comment]
Hi All,

Can we also make sure Paxton's changes end up in future releases (rather: the next release) of DHF?

We want to make sure future upgrades don't reopen this particular issue back up.   

Thanks very much in advance.
