### ISSUE TITLE
Document how to load schemas

### ISSUE THREAD

**Issue by rjrudin** [marklogic/marklogic-data-hub#1260]
https://marklogic.github.io/marklogic-data-hub/understanding/project-structure/ is a super-handy page, but one detail it's missing is where to put files that should be put into the schema database. The answer (as of 3.0.0) is "./user-config/schemas", so that should be documented into the "user-config" section of that page.

**Comment by aebadirad** [comment]
We now follow ml-gradle convention and scaffold out the folders for schemas for the harmonize schemas database as vanilla ml-schemas and the schemas for the hub (aka staging schemas database) in hub-internal-config/schemas on every project.
