### ISSUE TITLE
Document -PuseES in hubCreateInputFlow documentation

### ISSUE THREAD

**Issue by dmcassel** [marklogic/marklogic-data-hub#1265]
https://marklogic.github.io/marklogic-data-hub/docs/gradle-tasks/#hubcreateinputflow does not mention the useES parameter.

**Comment by grechaw** [comment]
That is so.  In fact, the default was changed for 4.0.0 to true.  And we don't want to encourage use without ES anymore, so I'm open to the idea of leaving it undocumented...

**Comment by dmcassel** [comment]
Changing the default makes sense to me. I think the question of whether to document it depends on when v4 will come out. Right now, doing things the way we want people to do them requires either digging into the gradle task implementation or hand-coding it.

**Comment by kcoleman-marklogic** [comment]
What's the upgrade story if we pretend there is no such thing? Doesn't the change to the default have a significant impact on upgrading, such that someone might choose to turn it off?

**Comment by dmcassel** [comment]
Since this is a scaffolding function, I think it's less likely to have been automated. I still lean toward documenting, even with changing the default.

**Comment by kcoleman-marklogic** [comment]
So it doesn't affect the shape of the envelope documents or the plugin code that DHF generates?

**Comment by grechaw** [comment]
it absolutely does affect the envelope. qs always uses it.  it's just a matter of what the gradle functions do.  In 3.0.0 if you don't use useES=true, the results are pretty confusing if you're expecting it to look at entities.

But you're right @dmcassel -- im too future looking to think we don't need to document it, even if i wish 3.0.0 would go away :)

**Comment by mhuang-ml** [comment]
A similar issue https://github.com/marklogic/marklogic-data-hub/issues/1406 was opened up to document the usage of the ```-PuseES=true``` parameter.  Since we're making the push to have the user use entity services and the fact that calling ```gradle hubCreateEntity -PentityName=[entity name]``` will generate the vanilla ES descriptor then the impact of this might be smaller.  However, if you have a legacy DHF project that wasn't using ES, then there are definitely upgrade considerations that need to be factored in.

**Comment by aebadirad** [comment]
Closing this as we're now enforcing this in data hub 5.0 and will only support the lack of -PuseES with a current customer who has support to limit this legacy style from perpetuating. Closing for now.
