### ISSUE TITLE
cannot save main.sjs from quickstart

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/marklogic-data-hub#1277]
If I modify main.sjs in my harmonization flow, QS is unable to save it. It doesn't save it to disk and it doesn't deploy the changes to the server. You just get The Spinning Cursor of Doom where it displays Saving. 

Eventually you start getting socket timeout errors, but I think they're a side-effect of QS being hung.
```
 WARN  o.s.w.s.m.s.DefaultHandlerExceptionResolver - Failed to read HTTP message: org.springframework.http.converter.HttpMessageNotReadableException: I/O error while reading input message; nested exception is java.net.SocketTimeoutException
```
The Chrome dev tools do report a couple errors, but only at the point when the socket timeout starts, and they're not in DHF code AFAICT.

There is not a problem with the change I introduced to main.sjs: I just stuck a comment in. I can save changes to the other plugins. Only main.sjs screws up.

I have reproduced this behavior with both DHF 2.0.6/ML 9.0-4 and DHF 3.1/ML 9.0-6ish (head of the develop branch and a post-9.0-6 nightly). In both cases, I had a project created using 2.0.6. The 3.1 case was just an upgrade scenario.

Chrome on Windows, with ML & QS running on RHEL 7.

All I have to do to reproduce:
1. Create the Product entity from the tutorial (or anything, really)
1. Create an input flow and run it. Again, I used the tutorial data.
1. Create a harmonize flow. 
1. Edit the main.sjs plugin code, such as adding or modifying a comment.
1. Click Save. QS hangs.

**Comment by ayuwono** [comment]
Not seeing this issue anymore
