### ISSUE TITLE
Documentation request: adding details about ensuring UTF-8 is used in cases where the user OS may be using a different file encoding.

### ISSUE THREAD

**Issue by ableasdale** [marklogic/marklogic-data-hub#1296]
We recently saw a case where harmonization processes were failing with unexpected `SVC-UTF8SEQ` exceptions.  In this case, the host OS was configured with the default character encoding of ANSI_X3.4-1968.

Can we add a note to the DHF documentation that in the event where the host OS uses a different file encoding, the file encoding can and should also be set (in the gradle jvmargs) to UTF-8 for machines whose default encoding is not already set to UTF-8.

In the case of the above example, adding this to the `gradle.properties` file solved the problem:

``` 
org.gradle.jvmargs='-Dfile.encoding=UTF-8’
```

**Comment by aebadirad** [comment]
This should be resolved in Data Hub 4.2.2 without the need to use the above workaround.
