### ISSUE TITLE
Addition of `-restrict_hosts` option to DHF

### ISSUE THREAD

**Issue by ableasdale** [marklogic/marklogic-data-hub#1297]
MLCP has a very useful `-restrict_hosts` switch which allows users to target a specific set of hosts for operations:

https://docs.marklogic.com/guide/mlcp/import#id_78805

Would it be possible to get this same feature ported to DHF?

**Comment by grechaw** [comment]
The restrict hosts option is now used in a load balancer environment for DHF.

DHF sets the restrict-hosts to true if the gradle property mlIsLoadBalancer=true

This functionality was added in DHF 4.0.1
