### ISSUE TITLE
Scaffold out test directories and include a testing framework

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#1300]
When the data hub installs and creates a directory structure (plugins, user-conf, etc.) there should also be a testing directory that works with included testing code. 

the "ml-unit-test" project is a likely start, having branched off from the rather mature Roxy project to cover testing.

Best practices and helper methods on testing a flow should be added or documented, to run a particular flow or particular plugin on known input, and verify the output is correct.

**Comment by popzip** [comment]
Thanks for logging the interest, will be glad to hear other votes for ml-unit-test, specific needs, or alternatives. 
related to https://github.com/marklogic/marklogic-data-hub/issues/138 and others.

**Comment by kosed** [comment]
We are using TDD (Tests-Driven Development) at a customers so it is sort of mandatory to have tests. Capitalizing on multiple inputs and feedbacks we came to some pretty nice pattern:

First configure your dependencies as shown [here](https://github.com/marklogic-community/ml-unit-test/wiki/Integrating-with-DHF)

Then check sample below which creates a specific task for deploying tests modules (ml-unit-test + test cases).
see [dhf-issue-910](https://github.com/marklogic/marklogic-data-hub/issues/910#issuecomment-398393215)

you can provide a test suite root path for your tests cases with:

    -PtestsRootPath=src/test/ml-modules (relative to DHF root project, this is the default)
    
With the setting above, the "dummy-suite" test suite will be stored at (relative to DHF root project):

    src/test/ml-modules/root/test/suites/dummy-suite
    
And be deployed at path below in your modules db:

    /test/suites/dummy-suite
    
Snippet task and dependencies in build.gradle

    task mlUnitTestLoadModules(type: com.marklogic.gradle.task.client.LoadModulesTask) {
        def testsRootPath = project.findProperty('customTestsRootPath') ?: 'src/test/ml-modules'
        getAppConfig().setModulePaths([testsRootPath])
        dependsOn mlPrepareRestApiDependencies
        mustRunAfter mlClearModulesDatabase
    }
    
    //Handling of timestamp files at once
    task mlGradleDeleteModuleTimestampsFile(type: com.marklogic.gradle.task.DeleteModuleTimestampsFileTask)
    mlUnitTestLoadModules.dependsOn mlLoadModules
    mlLoadModules.dependsOn mlDeleteModuleTimestampsFile
    mlDeleteModuleTimestampsFile.dependsOn mlGradleDeleteModuleTimestampsFile
