### ISSUE TITLE
Incorrect output from harmonize/content plugin when flow created from Entity definition

### ISSUE THREAD

**Issue by timmytva** [marklogic/marklogic-data-hub#1302]
#### The issue

I have a single entity. I create a harmonization flow and base it on the Entity definition. In the content plugin, I get the createContent() and extractInstanceMyEntity() functions as expected. If I include an array in the return of my extractInstanceMyEntity() function like this:

return {
    '$attachments': attachments,
    '$type': 'provider',
    '$version': '0.0.1',
    'cars': [{'make': 'Audi'}, {'make': 'BMW'}, {'make': 'VW'}]
  }

The cars array in the instance section of my output documents looks like this:

"cars": [
          {
            "undefined": {
              "make": "Audi"
            }
          },
          {
            "undefined": {
              "make": "BMW"
            }
          },
          {
            "undefined": {
              "make": "VW"
            }
          }
        ]
}

Notice that each car object is wrapped in an undefined object. Interestingly, this does not happen under these circumstances:

1. I create the flow using Blank Template option instead of Entity Definition option
2. I create flowing using Entity Definition option BUT do not return any of the properties starting with $. For instance, if I have a harmonization flow created using Entity Definition but my return looks like this:

return {
    'cars': [{'make': 'Audi'}, {'make': 'BMW'}, {'make': 'VW'}]
  }

The output is as expected: no undefined wrapper objects. 

Also interesting, if I return exactly the same thing in the headers plugin of either type of harmonize flow, I get the expected output.

The issue only arises with a harmonize flow created based on Entity Definition where the extractInstanceXXX() function includes the $ properties in the return statement.

#### Tech details

Which Operating System are you using?
MacOS

Which version of MarkLogic are you using?
9.0-5

Which version of the Data Hub Framework are you using?
3.0

Is this a QuickStart UI bug? If so, which browser are you using?
Chrome

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by grechaw** [comment]
You are right, the inclusion of $type is a marker that the DHF is to use the entity-services style of making envelopes.  Entity services style extractions expect this $type attribute to be present also in the array sub-objects.  I suspect that if you included

`{'$type':'Car', 'make': 'Audi'}` 

in each of these objects then the value 'Car' would replace 'undefined.'

**Comment by grechaw** [comment]
Now, if you're next to ask 'why?' im afraid we'll have to sit down for a while...

**Comment by timmytva** [comment]
Yep, just as you said. I guess my issue can be closed as DHF is working as designed. I just didn’t understand it!

Tim

**Comment by grechaw** [comment]
Well, I think maybe it could be a little less obscure, too...  What's going on is that every complex structure is a type in ES right now, so it's expecting that both 'cars' and 'providers' are parts of your model.  If you'd generated code from a model with both types in it, then the extraction functions would have been set up to provide the $type property for you.

**Comment by grechaw** [comment]
Thanks for discussing the issue, @timmytva

**Comment by ayuwono** [comment]
Fixed on 4.1.1
