### ISSUE TITLE
Support or default to having one database rather than two

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#1309]
The FinServe Blueprint group identified many cases where one single (Raw+Curated) DB is preferable. Advantages include
* Optic across final+staging
   * E.g. clear the “attachment” data from Curated entities, and link back to Raw in real time
* transactional updates to both 
   * E.g. mark a Raw document as processed once the Curated doc is written or updated

This seems like a good idea, particularly now that we can achieve physical separation via Forests instead of via Databases, by using range-assignment-policy on a range-indexed property such as {rawOrCurated: “..”}.

Physical separation was most of the goal of the two DBs originally, to:
* Easily clear the Raw data if you don’t want to keep forever after incorporating into Curated
* Easily clear the Curated data to rebuild from Raw (if you kept all the raw, and perhaps changed harmonization)
* Back up Raw and Curated separately, on separate schedules, to separate locations
* Allow hardware separation within a cluster to reduce ingest impact on egress performance
* Allow HA on Curated but not Raw
 * Etc.

It will not address some other per-DB configuration options that are still nice to separate:
* Overall indexing, particularly text
* Encrypted vs not
* Journal archiving vs not (I think – or is that per forest too?)
* Other DB-wide options such as timestamp distribution

A likely implementation would include:
* a single DB is configured by default
* the raw vs curated range-assignment-policy is set up for the single DB
* code generation includes the range query when generating: the collector, content and writer plugins
* with a single DB, all flows run against it by
* ability or default for QuickStart to run Ingest to the single "Final" DB (not Staging)
* convenience functions to back up only Staging or Final
* Quick Start and/or hub "clear DB" functions to clear only the relevant forests

Incrementally, I think a single-DB deploy with forest-assignment-policy (range or query) would do. People would have to use the options to select which DB to run against, and would have to include range queries in their code to gain some of the optimization from that.

**Comment by freshie** [comment]
Typically there are a lot more indexes on the Final data base than the Stage database. The backup requirements might also be different on staging than final.  

 I'd recommend defaulting to two but allow for one.

**Comment by damonfeldman** [comment]
Final typically has more indexes, but those that are specific to elements (paths, ranges) won't typically affect the raw data.

Text indexes being an exception. If you have a "content" use case with wildcards, positions etc. that can be a big impact that you would not necessarily want to apply to raw data.

**Comment by grechaw** [comment]
@freshie that's a question of where the data ends up eventually -- the data for a production system could still be partitioned, and populated by some other process like flexrep.  the notion from the DHF perspective is that it has its own end-to-end processing space.

**Comment by freshie** [comment]
@grechaw so after its Harmonized then it would get moved to a different database that has the indexes needed for queries for the downstream system? That could work, you'd have to be more careful about your queries with in the flows. IE; you might get harmonized data in a collector if the have the same collection. Or if you have a query that grabs another document in a flow you'd want to make sure you are getting the right type of document.  That might add confusion.

**Comment by damonfeldman** [comment]
Note that physical separation still has large benefit. Reference support case 20758 which shows that IOPS basically doubles when stands double. So if we do this, we should try to ensure that most reads are only to the right forests (raw forests or harmonized forests) meaning that it is easy to specify the appropriate range index that will drive traffic to only the relevant forests - maybe functions that do this automatically such as   datahub.searchRaw(....) and datahub.searchHarmonized() which would mimic and pass through to cts.search() but with the required range index.

**Comment by aebadirad** [comment]
Data Hub 5.0 allows for much more refined control of database. If two databases are not desired, please do all of the work in the staging or final database and expose the data from there. Both now contain all the artifacts necessary to operate the hub.

As a note, you'll still have to maintain the separate DB, but you can scale down the forests and it should be a minimal impact. Therefore, closing of this as this is the workaround for the foreseeable future.
