### ISSUE TITLE
Add documentation for how to create a gradle task to run an input flow

### ISSUE THREAD

**Issue by jkerr5** [marklogic/marklogic-data-hub#1331]
Creating MLCP gradle tasks to run input flows can be very useful for development. There's documentation about how to create gradle tasks to run harmonization flows via gradle and how to run input flows via MLCP but not how to create MLCP tasks to run input flows via gradle. Can we add examples one or both of these pages:

https://marklogic.github.io/marklogic-data-hub/ingest/mlcp/
https://marklogic.github.io/marklogic-data-hub/docs/gradle-tasks/

**Comment by wooldridge** [comment]
@grechaw has ideas about this so assigning to him. @kcoleman-marklogic, you may also have something to say as there's a docs component.

**Comment by damonfeldman** [comment]
This should include clarification of differences between input flows and harmonize, quickstart and command line. 

Particularly that Harmonize flows always track job info, and QuickStart input flows also track job info including the mlcp logs in the jobs DB; but command line mlcp or the REST or Java DMSDK code examples (https://marklogic.github.io/marklogic-data-hub/ingest/marklogic-client-api/ ) will not track mlcp logs or create a job record. 

However the mlcp "logOutputUri" will store the log output from mlcp in ML.

**Comment by aebadirad** [comment]
Data Hub 5 now allows for this.
