### ISSUE TITLE
Best practices for resolving reference data

### ISSUE THREAD

**Issue by aajacobs** [marklogic/marklogic-data-hub#1339]
#### The issue

Short description of the problem:
Document a best practice for using DHF to easily resolve reference data

What behavior are you expecting?
Make it easy for users to understand the best practice for resolving reference data in harmonization flows

#### Tech details

Which Operating System are you using?
CentOS 7 on Docker
Which version of MarkLogic are you using?
9.0-6
Which version of the Data Hub Framework are you using?
3.0
Is this a QuickStart UI bug? If so, which browser are you using?
No

As a DHF user, I want an easy way to bring in reference data and be able to resolve it as a part of a harmonization flow.  Ideally, there would be a DHF specific pattern or even input flows and harmonization functions to bring in this reference data and make it available to all of the nodes as a part of specific harmonization flows.

For example, should users create maps or objects, then pass them in as a part of options?  If so, are a lot of places in the scaffolding code where the function signatures would need to be modified in order to pass in and access options. 

Should users use server maps?

Is there another best practice way for doing this? 

Could the work to actually do this be abstracted away within DHF so a user could just call things like dhf:setReferenceData(mapName, map/object), dhf:resolveReferenceData(mapName, value).  So given something like:
```
// pseudocode
const g = {
  "gender": {
    "m": "male",
    "f": "female"
  }
}

// do this in harmonization flow instantiation or main.xqy
dhf:setReferenceData("gender", g)

//within a harmonization flow
canonicalobject.gender = dhf:resolveReferenceData("gender", $instance/path/to/gendercode/in/raw)
```
And DHF would automatically take care of making it available to all nodes.

This seems like a very common use case and it would be nice to have a best practice for how to do it in DHF at a minimum, but ideally supported by some DHF specific functions that would obviously require passing reference data in format that DHF expects.

**Comment by popzip** [comment]
@yasht2010 can you keep an eye on this wrt Mapping roadmap, whether resolving reference data is an (eventual) 80% task or a custom one.

**Comment by aajacobs** [comment]
Thanks @popzip.  As you consider this for the mapping framework over the longer term, having some documentation in the short term would be nice.  I've done this by adding it to the options but I ended up having to change the function signatures in the generated code to pass the options down, so I'm hoping there's a better way.
