### ISSUE TITLE
Forest configuration for DHF 4.0

### ISSUE THREAD

**Issue by lifan0127** [marklogic/marklogic-data-hub#1352]
With Data Hub 4.0 release, the project structure has changed substantially. Therefore the forest configuration wiki page is out of date now.

https://github.com/marklogic/marklogic-data-hub/wiki/Customizing-Forest-Configurations

**Comment by bsrikan** [comment]
Wiki contents will be removed at some point as stated in this link. https://github.com/marklogic/marklogic-data-hub/wiki/Getting-Started

Forests are created with same name as the database followed by a hyphenated number. You can configure number of forests required with the variable ml{X}ForestsPerHost and custom data path can be set with mlCustomForestPath in gradle.properties.

Let us know if you need more info.

**Comment by lifan0127** [comment]
Thanks, @bsrikan! I am interested in specifying a custom data path (say "\Data{number}\forests"). I tried something like `mlCustomForestPath=\Data1\forests,\Data2\forests` but it doesn't seem to be working.

**Comment by grechaw** [comment]
I think these will have to be forward slashes, @lifan0127

**Comment by aebadirad** [comment]
Due to length of time of ticket, closing, please reopen if you need further help.
