### ISSUE TITLE
Port 8000 is hardcoded for DeployAmpsCommand

### ISSUE THREAD

**Issue by kosed** [marklogic/marklogic-data-hub#1353]
#### The issue

Port 8000 is hardcoded for DeployAmpsCommand
Therefore mlAppServicesPort is not considered

#### Tech details

Which version of the Data Hub Framework are you using?
4.0.0

**Comment by kosed** [comment]
9.0-6.2

**Comment by grechaw** [comment]
OK, for that we do have the fix in place for 4.0.1

**Comment by kosed** [comment]
Great thanx @grechaw !
