### ISSUE TITLE
online-store example has 1800 orders but 1000 unique IDs

### ISSUE THREAD

**Issue by grechaw** [marklogic/marklogic-data-hub#1361]
In versions up to 4.0.1, the online store example has 1800 orders in it, but only 1000 unique ids.  This does not cause an error in loading with mlcp, but causes unexpected results (only 1000 orders).

It may be that the csv is for lines, not orders, in which case the ids should be modified to be unique.

**Comment by kcoleman-marklogic** [comment]
I reorg'd the Product data for 4.0.0, on behalf of model to model mapping. I wouldn't expect that to cause a problem with orders, but I suppose it is not impossible, depending on how the expected behavior is determined.

**Comment by aebadirad** [comment]
Should be resolved in the sample data now.
