### ISSUE TITLE
Modules location and deployment in DHF400

### ISSUE THREAD

**Issue by kosed** [marklogic/marklogic-data-hub#1362]
#### The issue

Short description of the problem:

Some observations regarding modules deployments in DHF400.
Considering this docs source: https://marklogic.github.io/marklogic-data-hub/understanding/project-structure/

Trying fo deploy modules to final attached modules DB, I have tried putting modules in :
- src/main/ml-modules
- src/main/ml-modules-staging
- even src/main/ml-modules-final (as there are some traces of it in debug mode)
Nothing actually gets deployed into the final DB (besides the jar extracted options).

I also noticed that the ml-gradle src/main/ml-modules-staging/root and src/main/ml-modules/services structure is not actually aligned with DHF400 as the docs say.
(albeit the docs are not extremely clear or possibly misleading on this because not suggesting the root and services subfolders)
The result is that no services get deployed as REST extensions if you put them in src/main/ml-modules-staging/services.
They just get copied to the modules DB (attached to staging) as just /services/* modules files.
modules put in src/main/ml-modules-staging/root/xxx will be found as /root/xxx in the DB too.

Finally, things works as expected (almost) if you use the src/main/ml-modules folder (with root or services subfolder)
As the exception that everything gets deployed in the staging attached modules DB instead of final one as said in the docs

#### Tech details

Which Operating System are you using?
MacOs

Which version of MarkLogic are you using?
9.0-6.2

Which version of the Data Hub Framework are you using?
4.0.0

Is this a QuickStart UI bug? If so, which browser are you using?
No

**Comment by kosed** [comment]
I would say that ml-modules works it does with ml-gradle albeit deploying to staging modules instead of final modules. but this choice is just dependant on you guys. just make sure that it's aligned with the docs.

ml-modules-staging however is not working as expected 9in the ml-gradle way) though.

**Comment by bsrikan** [comment]
In 4.0.1, we now will have only 1 modules DB for both staging and final content DB. This should resolve the issue you are running into. There is just one ml-modules directory.

It is a bug in 4.0.0 that content from ml-modules directory is not getting deployed in Final modules DB.

**Comment by kosed** [comment]
Thanx both @mtcotton @bsrikan

**Comment by grechaw** [comment]
https://project.marklogic.com/jira/browse/DHFPROD-1421

**Comment by grechaw** [comment]
I've made an internal issue to track all of the ml-deploy things I'm seeing today. Thanks for capturing @kosed

**Comment by kosed** [comment]
Great, thanx @grechaw !

**Comment by josvanroosmalen** [comment]
TEMPORAL configuration is affected as well. Temporal configuration should as workaround be placed in the internal hub config folder, because a mlDeploy is not picking up the temporal folders in ml-config/databases/<name>/temporal/*. Please fix.

**Comment by kkanthet** [comment]
Fixed as part of Release 4.1.0
