### ISSUE TITLE
mlDeploy fails if mlUsername not defined

### ISSUE THREAD

**Issue by kosed** [marklogic/marklogic-data-hub#1363]
#### The issue

Short description of the problem:

mlDeploy will fail if mlUsername is not provided
This with mlManageUsername and mlSecurityUsername defined

Is that the expected behavior ?

#### Tech details

Which version of MarkLogic are you using?
9.0-6.2

Which version of the Data Hub Framework are you using?
4.0.0

#### The devil is in the details...

Deployed app dhf400
:mlDeploySecurity (Thread[Task worker for ‘:’,5,main]) completed. Took 0.7 secs.
:hubPreInstallCheck (Thread[Task worker for ‘:’,5,main]) started.

> Task :hubPreInstallCheck FAILED
Task ‘:hubPreInstallCheck’ is not up-to-date because:
Task has not declared any outputs despite executing actions.
Sending XML GET request as user ‘admin’ to path: /manage/v2/servers
Sending XML GET request as user ‘admin’ to path: /manage/v2/servers/Admin/properties?group-id=Default
Sending XML GET request as user ‘admin’ to path: /manage/v2/servers/App-Services/properties?group-id=Default
Sending XML GET request as user ‘admin’ to path: /manage/v2/servers/central-int-dh-FINAL/properties?group-id=Default
Sending XML GET request as user ‘admin’ to path: /manage/v2/servers/central-int-dh-JOBS/properties?group-id=Default
Sending XML GET request as user ‘admin’ to path: /manage/v2/servers/central-int-dh-STAGING/properties?group-id=Default
Sending XML GET request as user ‘admin’ to path: /manage/v2/servers/central-int-dh-TEST/properties?group-id=Default
Sending XML GET request as user ‘admin’ to path: /manage/v2/servers/central-int-dh-TRACING/properties?group-id=Default
Sending XML GET request as user ‘admin’ to path: /manage/v2/servers/HealthCheck/properties?group-id=Default
Sending XML GET request as user ‘admin’ to path: /manage/v2/servers/Manage/properties?group-id=Default
:hubPreInstallCheck (Thread[Task worker for ‘:’,5,main]) completed. Took 0.16 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ‘:hubPreInstallCheck’.
> No user provided

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
4 actionable tasks: 4 executed
No user provided

**Comment by grechaw** [comment]
It's expected in the sense that I agree, you need to provide both sets of credentials. 
This issue does make me wonder whether preInstallCheck is using the wrong set of credentials though...  We should look into it.

**Comment by kosed** [comment]
hubPreInstallCheck is definitely using the mlUsername creds.
If both credentials mlUsername and mlManageUsername are needed, then what are the minimum privileges for both ? 
Also why is it mandatory to use mlUsername (besides falling back to it when another user is missing) since we now have data-hub-user and hub-admin-role ?

**Comment by grechaw** [comment]
"Why" questions are still pretty hard to answer, as we're only discovering how the hub works as we go alone.  hubPreInstallCheck is problematic because it was something that only ever worked with admin credentials in 3.0.0 and before.  Indeed, checking whether a system is ready for install will either a) always fail since we don't have admin access, or b) require a user that is not installed by the DHF itself to succeed.

So hubPreInstallCheck should be using manage user, but since it's not part of ml-gradle it doesn't have access to those credentials.  That's  a statement of the problem but not how to fix it.  It might be best to do away with it.

**Comment by kosed** [comment]
Thanx @grechaw for the answers. It helps us in the field when things are not that intuitive.
And one good thing about the "why"s, even when the answer is not there, is that they kick a questioning process which ultimately can lead to improvements.

**Comment by grechaw** [comment]
:+1:

**Comment by grechaw** [comment]
It is understandable.  I'm making a story to rip-out or revamp the preinstall check, because it's silly.
