### ISSUE TITLE
4.0.0 - "How to update a Hub Project" link returns 404

### ISSUE THREAD

**Issue by xbonnamy-marklogic** [marklogic/marklogic-data-hub#1371]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue
Short description of the problem:

Via QuickStart, after re logging got Update success message with (surprising)
 "Update it" button (see screenshot: update_congrats_message).
Clicking on the "How to update a Hub Project" link returns 404 (see screenshot attached: update_error_link)

What behavior are you expecting?
Link "How to update a Hub Project" opens page

#### Tech details
Which Operating System are you using?
MacOS Sierra 10.12.6 

Which version of MarkLogic are you using?
9.0-6.2

Which version of the Data Hub Framework are you using?
4.0.0

Is this a QuickStart UI bug? If so, which browser are you using?
Yes, Google Chrome

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

<img width="459" alt="update_congrats_message" src="https://user-images.githubusercontent.com/15095183/46203866-6c1a5b00-c31b-11e8-81b6-9cd7c390880a.png">
<img width="1167" alt="update_error_link" src="https://user-images.githubusercontent.com/15095183/46203868-6cb2f180-c31b-11e8-9da0-8f6ce3c21700.png">

**Comment by bsrikan** [comment]
Thanks for filing the bug. We will look into it.
This is the page you are looking for:
https://marklogic.github.io/marklogic-data-hub/understanding/updating/

**Comment by aebadirad** [comment]
This should no longer be the case in 4.2.0
