### ISSUE TITLE
Design Tests for Plugins as Part of the Hub

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#138]
The hub should make testing a priority. When scaffolding you should get tests automatically. Running them should be easy. It should encourage the user to write tests.

@damonfeldman suggested maybe using JUnit to run them. Put JUnit inside of the hub?

Add a button to run the tests from the UI.

**Comment by maeisabelle** [comment]
Hi @paxtonhare,

Will the test from the UI run per plugin or as a whole for all plugins inside the flow? If the former, it will just be a button beside load data/run flow. If per plugin, I'm thinking of having a checkbox per plugin that the user can select to run.

**Comment by aebadirad** [comment]
Closing out old issue that no longer applies to the latest major release.
