### ISSUE TITLE
DHF 4.0.0: mlDeployDatabases not deploying config from src/main/ml-config (same for mlDeploySecurity)

### ISSUE THREAD

**Issue by kosed** [marklogic/marklogic-data-hub#1382]
#### The issue

Short description of the problem:
- Create a DHF 4.0.0 project
- Add some custom indexes for the final DB in src/main/ml-config/databases
- Run you normal mlDeploy task:
  - This will deploy all configurations as expected and your indexes will show up on the Admin UI
- Run mlDeployDatabases
  - This will remove the custom indexes defined for final DB in src/main/ml-config/databases

Generally speaking, it seems like running the lower granularity mlDeployXXXX task will not consider the custom configurations config in src/main/ml-config, only those in src/main/hub-internal-config.
I have experienced the same behavior for mlDeploySecurity.
I have also tried the -PmlConfigPaths switch bu no success.

The problem is that it is not really practical to run mlDeploy every time there is some config update.
and the scoped mlDeployXXXX tasks provided more granularity and control over what is subsequently deployed after the initial application bootstrap.

#### Tech details

Which Operating System are you using?
MacOs

Which version of MarkLogic are you using?
9.0-6-2
9.0-7

Which version of the Data Hub Framework are you using?
4.0.0

Is this a QuickStart UI bug? If so, which browser are you using?
No

**Comment by grechaw** [comment]
Perhaps similar to #1383

**Comment by grechaw** [comment]
https://project.marklogic.com/jira/browse/DHFPROD-1421

**Comment by kkanthet** [comment]
Fixed as part of Release 4.1.0
