### ISSUE TITLE
mlDatabaseNamesWithForestsOnOneHost property is ignored

### ISSUE THREAD

**Issue by jonesyface** [marklogic/marklogic-data-hub#1383]
#### The issue

There is a ml-gradle property called "mlDatabaseNamesWithForestsOnOneHost" that is described on https://github.com/marklogic-community/ml-gradle/wiki/Property-reference whose purpose is to limit forests to just one host within a cluster for a defined database. A good use of this is for modules DBs that have limited content (which is my particular use case).

I have defined this in my gradle properties as a comma-delimited string of DB names as instructed by the documentation, i.e.
mlDatabaseNamesWithForestsOnOneHost=projectName-MODULES,projectName-final-MODULES

However, this seems to have no effect and I'm still seeing a forest created on each of the hosts in my 3-node cluster.

I was hoping this issue would be fixed with v4.0.0 of DHF as I understood this was more consistent with a generic ml-gradle project but unfortunately not.

(This does assume the "mlDatabaseNamesWithForestsOnOneHost" property works in a vanilla ml-gradle project, I haven't checked this out. If not then this ticket should probably go under that project.)

#### Tech details

Which Operating System are you using?
MacOS Sierra 10.12.6

Which version of MarkLogic are you using?
9.0-5

Which version of the Data Hub Framework are you using?
Tested on both 3.0.0 and 4.0.0

Is this a QuickStart UI bug? If so, which browser are you using?
No

#### The devil is in the details...

N/A

**Comment by grechaw** [comment]
Do you have a working vanilla ml-gradle project using this property?  I've not come across this one before.  We're moving away from DHF in custom environments in favor of provisioned ones, so I'm not sure how to best fix it.  Maybe a workaround using a vanilla gradle project in conjunction with a DHF one...

**Comment by mhuang-ml** [comment]
This issue should be resolved as of release 4.1 which added more support for vanilla ml-gradle project structures and I believe it should honor the **mlDatabaseNamesWithForestsOnOneHost** property.  Could you please grab at least release 4.1 or 4.1.1 (recently released) and please retest to see if the property is still not honored?

**Comment by aebadirad** [comment]
This should be resolved, closing, if not please reopen.
