### ISSUE TITLE
PII page refers to old module location

### ISSUE THREAD

**Issue by aajacobs** [marklogic/marklogic-data-hub#1391]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:
Documentation bug: https://marklogic.github.io/marklogic-data-hub/govern/pii/ refers to a user-config folder in the project root to manage ELS config instead of the new ml-gradle location (src/main/ml-config)

**Comment by kcoleman-marklogic** [comment]
Thank you kindly for your report. This problem has already been corrected in development and will be published soon. Corrections can be found here, for now:

https://github.com/marklogic/marklogic-data-hub/blob/docs-develop/_pages/govern/pii.md
