### ISSUE TITLE
File lists on GUI should sort alpha or other ways

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#1400]
#### The issue

Some file choosers are long, but have no sorting. Alpha would be good, and most-recent sort a nice option.

What behavior are you expecting?

Hub 4.0.0

This is a QuickStart RFE

**Comment by grechaw** [comment]
There's probably some standard component that would provide a better file chooser.  It's probably already on @alexsmr 's mind.  I'll assign to him to chat with you about this and other UI issues.

**Comment by kcoleman-marklogic** [comment]
_Perhaps_ peripherally related to #1054 (DHFPROD-946). This bug may be about the file pickers in the flow creation wizard, though. Same problem in the end.

**Comment by aebadirad** [comment]
Alphabetical sorting now occurs in QuickStart on Data Hub 5 for all browsers/file selection.
