### ISSUE TITLE
Feature : Add scrolling for entity definition

### ISSUE THREAD

**Issue by epoilvet** [marklogic/marklogic-data-hub#1401]
When entity definition has many fields, the UI does not allow to scroll down/up.

Similar to "#1388 Add bottom space and scrolling for mapping menus"

**Comment by grechaw** [comment]
Assigned to Mike because I think I saw an internal issue about this very thing.  If I'm right, we'll let you know what's going on @epoilvet and provide a link.

**Comment by ayuwono** [comment]
This issue is tested and passed
