### ISSUE TITLE
Extra levels of data appear in harmonized entities

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#1404]
#### The issue
Short description of the problem:
Unexpected multiple levels of elements are created in in the Harmonized entities.

What behavior are you expecting?
A structure with the entity name directly below "instance":
```
{envelope: {
  {headers:{}},
  {instance: {member: {ssn: "234324234", address: { ...}}}
   ...
```
#### Tech details
Which Operating System are you using? OSX
Which version of MarkLogic are you using? 9.0-6
Which version of the Data Hub Framework are you using? 4.0.1
Is this a QuickStart UI bug? no.

**Comment by srinathgit** [comment]
Damon,
Can you provide the expected and the current output you are getting after harmonization ?

**Comment by grechaw** [comment]
What you're seeing is the expected document structure if the instance name is "member".
We serialize that extra step to capture the type information as a potential XPath expression part.
Is this a change from how you've seen it work in the past?

**Comment by aebadirad** [comment]
Closing out issue due to lack of response.
