### ISSUE TITLE
Need documentation on the -PuseES flag when running DHF gradle commands

### ISSUE THREAD

**Issue by sastafford** [marklogic/marklogic-data-hub#1406]
#### The issue

Short description of the problem: I could not create an ingest flow without adding the -PesUse flag. This is not documented anywhere. 

What behavior are you expecting?

#### Tech details

Which Operating System are you using? Windows

Which version of MarkLogic are you using? 9.0-6

Which version of the Data Hub Framework are you using? 4.0.1

  
  `gradle hubCreateInputFlow -PentityName=recipe -PflowName=loadRecipes -PdataFormat=json -PpluginFormat=sjs`

**Comment by grechaw** [comment]
So basically, when you don't have an entity and don't specify -PuseEs=false, it's throwing some error based on no entity file available?  That would be my guess of what's going on here.

**Comment by mhuang-ml** [comment]
@sastafford, with the newer releases of the DHF, then the goal is to push the user towards utilizing entity services out of the box and therefore you must have an [entity name].json file deployed.  As of release 4.1, then if you run the gradle task ```gradle hubCreateEntity -PentityName=recipe``` that should create the default entity services json file.  With this change, then as a user, you should **NOT** need to use the ```-PuseEs=false``` parameter.

**Comment by aebadirad** [comment]
Closing this as we're now enforcing this in data hub 5.0 and will only support the lack of -PuseES with a current customer who has support to limit this legacy style from perpetuating. Closing for now.
