### ISSUE TITLE
Deployed DHF via gradle commands but cannot bring up QuickStart application.  

### ISSUE THREAD

**Issue by sastafford** [marklogic/marklogic-data-hub#1407]
#### The issue

Deployed DHF via gradle commands but cannot bring up QuickStart application.  

What behavior are you expecting?

I should be able to deploy DHF with Gradle commands (hubInit, createEntity, createInputFlow) and then bring up QuickStart.  

#### Tech details

Which Operating System are you using? Windows / Docker

Which version of MarkLogic are you using? 9.0-6

Which version of the Data Hub Framework are you using? 4.0.1

Is this a QuickStart UI bug? If so, which browser are you using? Chrome

#### The devil is in the details...

Brand new MarkLogic installation.  
Ran the following gradle commands: hubInit, mlDeploy, hubCreateEntity, hubCreateInputFlow
Tried starting the QuickStart application and was presented with the following notice.  

Congratulations on updating to version 4.0.1
But...your project doesn't seem to match this version of DHF!

Please update your project before proceeding onward! [How to update a Hub Project](https://marklogic.github.io/marklogic-data-hub/understanding/updating/401)

FYI the link on the update project page is broken.

**Comment by grechaw** [comment]
Yes, you are right.  Damn links embedded in code.
So the documentation is sufficient, but not findable from the link in the project.  Sounds like a bug to me, simple to fix.

**Comment by grechaw** [comment]
https://project.marklogic.com/jira/projects/DHFPROD/issues/DHFPROD-1420?filter=addedrecently

**Comment by aebadirad** [comment]
Should be fixed now with the release of 4.0.2
