### ISSUE TITLE
Changing drive in QuickStart

### ISSUE THREAD

**Issue by bgeorge11** [marklogic/marklogic-data-hub#1413]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:
I have my data in D: and I have Quick start running from C:. But, In quick start, I am unable to change the directory from C:\ to D: for a input flow. Quickstart hangs and an exception is thrown as below 
20:42:00.384 [SimpleAsyncTaskExecutor-1] INFO  c.m.hub.impl.EntityManagerImpl - min modified: 1532021936656
20:42:01.350 [SimpleAsyncTaskExecutor-1] INFO  c.m.hub.util.PerformanceLogger - PERFORMANCE: DataHubService.installUserModules took 1.187235802s
20:42:12.319 [http-nio-8080-exec-2] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: 'other' has different root] with root cause
java.lang.IllegalArgumentException: 'other' has different root
        at sun.nio.fs.WindowsPath.relativize(Unknown Source)
        at sun.nio.fs.WindowsPath.relativize(Unknown Source)
        at com.marklogic.quickstart.web.UtilController.searchPath(UtilController.java:65)
**Note that it is in Windows**
What behavior are you expecting?
I think the change in drive should be supported

#### Tech details

Which Operating System are you using?
Windows
Which version of MarkLogic are you using?
9.6
Which version of the Data Hub Framework are you using?
3.0
Is this a QuickStart UI bug? If so, which browser are you using?
Yes. Chrome.

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by grechaw** [comment]
Thanks for the bug report @bgeorge11 .   The team will triage it and see how it fits into the backlog.  I agree that it should be supported, but there are a lot of critical issues in the mix right now and quick start portability might not be the most pressing one.

**Comment by popzip** [comment]
Do you have a workaround?
