### ISSUE TITLE
Automatically assign a collection to docs based on flow and entity names

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#142]
This requires some discussion. Documents should have collection(s) applied to them automatically. At least for ingest flows. 

Perhaps:

${entityName}
${flowName}
(input|conformance)

**Comment by maeisabelle** [comment]
I applied the suggested collections in loading data per flow. The pull request is here: https://github.com/marklogic/marklogic-data-hub/pull/148. Let me know if this is what is required and if I missed anything. Thanks!
