### ISSUE TITLE
QuickStart entity editor: too many properties, buttons are hidden

### ISSUE THREAD

**Issue by wooldridge** [marklogic/marklogic-data-hub#1432]
If I add too many properties to my entity in the entity editor, the Save and Cancel buttons are hidden and, since the browser view is not scrollable, I can't access them. 

<img width="1173" alt="entity-props" src="https://user-images.githubusercontent.com/477757/46841666-3c893b00-cd7e-11e8-814c-63f1c17033a3.png">

**Comment by akshaysonvane** [comment]
Thanks for capturing the issue @wooldridge 
Created an internal issue to track this.
https://project.marklogic.com/jira/browse/DHFPROD-1433

**Comment by mhuang-ml** [comment]
@wooldridge, I saw that you've already submitted a PR for this: https://github.com/marklogic/marklogic-data-hub/pull/1684.

Can this issue be closed now?

**Comment by ayuwono** [comment]
This issue is tested and passed
