### ISSUE TITLE
Conditional mlcp import flow

### ISSUE THREAD

**Issue by grtjn** [marklogic/marklogic-data-hub#1434]
#### The issue

Currently, if you use an MLCP input flow, it will attempt to save exactly one envelope for each input file or record. It would be nice if you could also return null, to let the import know you like to skip over that file. It would help skip over faulty input data, or just constrain the volume that gets loaded into Staging.

It would be even more fun if you could also return multiple envelopes, as to indicate you like to split one input file into multiple parts, though that is something that can be organized within harmonize as well.

#### Tech details

I managed to implement this (handling of returning null) with just a few lines of code. Inside mlcp-flow-transform.sjs, you just need to replace `return content` with:

```
  if (envelope) {
    return content;
  } else {
    return Sequence.from([]);
  }
```

As a workaround, I copied that transform file, applied that change, and am running the input flow using Gradle.

**Comment by aebadirad** [comment]
Data Hub 5 now allows for multiple output to be written. Closing.
