### ISSUE TITLE
mldeploy error java.lang.NoClassDefFoundError: org/apache/http/impl/client/HttpClientBuilder

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#1436]
#### The issue

Short description of the problem:
mldeploy had failures on some machines in a team, but not others. Java class loading issue.

#### Tech details

Which Operating System are you using?  Windows (version unknown)
Which version of MarkLogic are you using?  9.0-6
Which version of the Data Hub Framework are you using?   4.0.1
Is this a QuickStart UI bug? no

#### Workaround
Add a specific build.gradle dependency on ml data hub 4.0.1

**Comment by rahulvudutala** [comment]
@damonfeldman Can you provide more information on the issue and steps to reproduce if possible

**Comment by aebadirad** [comment]
Closing out issue unless reproduction can be done. Please reopen if this happens again.
