### ISSUE TITLE
Harmonize job fails after upgrade to DHF 4.0.1

### ISSUE THREAD

**Issue by dmcassel** [marklogic/marklogic-data-hub#1441]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem: 
I upgraded a DHF 3.0.0 to DHF 4.0.1. After doing so, my harmonize job throws an error. I'm running using grade. 

What behavior are you expecting?
Successful run of the harmonize job. 

#### Tech details

Which Operating System are you using?
Windows 10 Pro, with MarkLogic running in a Docker container. 

Which version of MarkLogic are you using?
9.0-7

Which version of the Data Hub Framework are you using?
4.0.1

Is this a QuickStart UI bug? If so, which browser are you using?
No

#### The devil is in the details...

Observations: 
- The error is on line 111 of trace-lib.xqy, which is `rfc:get-trace($rfc:item-context)`. From debugging, I can see that `rfc:get-trace` is returning `()`. 
- Some DHF code in the stack is under `/data-hub/4/`, other stuff is under `/MarkLogic/data-hub-framework/`. The switch happens when it hits my main.xqy. Is there something wrong with how the job is being called? 
- Full example available [here](https://github.com/marklogic-community/smart-mastering-core/tree/mdm-566/examples/dhf-flow). (Run `gradle setupExample`, which will call mldeploy and other commands and will trigger the error.) 

If possible, rerun the command with -d for debugging output and attach the output:

[harmonize.txt](https://github.com/marklogic/marklogic-data-hub/files/2483970/harmonize.txt)

**Comment by rahulvudutala** [comment]
@dmcassel In 4.0, the modules will be deployed to data-hub-MODULES database. All the references to /MarkLogic/data-hub-framework/ in harmonization flow should be changed to /data-hub/4/.

I have looked into the example. The gradle.properties file has properties of DHF 3.0. They should be updated to 4.0.1

When you upgrade from 3.0 to 4.0, there are few manual steps which you should perform for successful upgrade. Please look into the internal JIRA tickets attached below for steps to upgrade DHF

https://project.marklogic.com/jira/browse/DHFPROD-1197?focusedCommentId=144416&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-144416

https://project.marklogic.com/jira/browse/DHFPROD-1196?focusedCommentId=144417&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-144417

**Comment by sbayatpur-ml** [comment]
@rahulvudutala Please create a bug for the documentation if https://marklogic.github.io/marklogic-data-hub/understanding/updating/ doesn't convey all the necessary upgrade steps. That page needs to be our one source of truth on upgrade.

**Comment by rahulvudutala** [comment]
@dmcassel The documentation is available at https://marklogic.github.io/marklogic-data-hub/understanding/upgrading/. But there is some upgrade documentation missing.
Please follow internal JIRA ticket DHFPROD-1500 for status of the issue

**Comment by dmcassel** [comment]
This was related to trying to upgrade a Smart Mastering Core example project to use DHF4. That works, so I think this bug can be closed.

**Comment by rahulvudutala** [comment]
@dmcassel Thank you. I will close the issue
