### ISSUE TITLE
Database clear functions also clear match/merge configurations from Smart Mastering

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#1443]
#### The issue

The skull icon (admittedly that's a hint you're going to do something dangerous) clears config as well as data. 

What behavior are you expecting?
Harmonized records cleared, but configuration preserved. It is too low level to know how the hub and smart mastering choose to store internal configuraitons such as entity definitions, match&merge configs, etc., so the QuickStart should reasonably be expected to undo it's own quickstart operations, but not clear config from smart mastering or modeling.

#### Tech details

Which Operating System are you using? osx
Which version of MarkLogic are you using? 9.0-6
Which version of the Data Hub Framework are you using? 4.0.1

Is this a QuickStart UI bug? Arguably yes, or RFE.

--

One idea - define certain directories that are protected somehow, such as /hub-config or /config. They could reasonably be loaded to memory and restored after DB clear to keep the clear fast.

**Comment by aajacobs** [comment]
+1

**Comment by aebadirad** [comment]
Data Hub 5.0 now stores match/merge configurations on flow documents for the mastering steps.
