### ISSUE TITLE
Refactor the Spring Boot API

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#145]
Right now the Spring Boot API is returning a LoginForm that bundles up a large amount of information. This makes it difficult to do more granular requests and updates.

This ticket is to create a design spec for a refactored REST API that is more granular. At the very least the Login information should be separate from the entity information.

**Comment by divino** [comment]
Proposed solution:

1. Split the service to configuration and authentication
2. Create a login form
3. Create a configuration form that would be part of the "Welcome, <username>" menu.
4. Convert current login for as install form and use the services mentioned on #1.

**Comment by paxtonhare** [comment]
I'd like to see a wiki document that details the entire REST api. Something like:

### POST /login
#### params
- user
- password
- host
- staging port
- final port
- plugin dir

#### response
LoginForm
```json
{
  "stuff": "here"
}
```

### GET /entities
#### params
none
#### response
List of entities
```json
[
  {
    "name": "entity 1",
    ...
  }
]
```

Not only will it help us nail the design, but it will help anyone new to the team to understand what QuickStart does.

**Comment by divino** [comment]
for your review: 

https://github.com/marklogic/marklogic-data-hub/wiki/QuickStart-Admin-REST-API

https://github.com/marklogic/marklogic-data-hub/wiki/QuickStart-Entity-REST-API

https://github.com/marklogic/marklogic-data-hub/wiki/QuickStart-TaskManager-REST-API

https://github.com/marklogic/marklogic-data-hub/wiki/QuickStart-Utilities-REST-API

**Comment by paxtonhare** [comment]
I was just looking at the Admin Rest API. I noticed that login and configure are 2 separate endpoints. 

I'm wondering if we even need an /admin/login endpoint? This is me starting a discussion, btw. I'm not dictating anything. But why have a login? We don't really "login" to anything. I do get that tomcat is storing some stuff in a session to make it easier to talk to MarkLogic between calls. But are we really authenticated?

I kind of think of it like "connecting" to a particular MarkLogic instance.

Maybe login still makes sense to most people. I don't know. Thoughts?

**Comment by damonfeldman** [comment]
I saw Task wait/stop, but not start in the TaskManager API. Is /start somewhere else and does that call generate the task ID?

Also, I suggest we call that something other than TaskManager to avoid confusion with the MarkLogic Task Server. Maybe call these jobs or flow-runs and move the API to a FlowControl API or something?

**Comment by damonfeldman** [comment]
I talked to Paxton about the login question today. I see his point that we are not really securing the Tomcat/QuickStart session - if it were shared it would not work anyway, as there is only one set of DBs and modules.

So the "login" info is actually _configuration_ info where we are telling QuickStart how to access MarkLogic: {rawPort, finalPort, IP, user, password, plugins} can be thought of as a complete set of config. In that case, we'd move user/pass into the config call.

What do people think?

**Comment by divino** [comment]
Agree on the "login". On the form, we can change the name to "Settings" and the button to "Configure". We can also change the service name from "login" to "configuration".

**Comment by divino** [comment]
Agree on the "taskmanager", we can consolidate all the flow endpoints and include the wait and stop. My only concern is that wait and stop from what I see is reusable to all asynch endpoints.

**Comment by divino** [comment]
Created a wiki for the proposed control flow API. Update the Admin API to reflect my proposal above.

**Comment by paxtonhare** [comment]
@divino for the Admin REST API https://github.com/marklogic/marklogic-data-hub/wiki/QuickStart-Admin-REST-API

We are talking about automatically choosing the Staging and Final ports for the user. This would mean changing `PUT /admin/configuration` to not require ports as parameters.

But it would still return them in the `GET /admin/configuration`

I'll make this change on the API

**Comment by paxtonhare** [comment]
@divino I added comments to some of the REST API wiki pages. grep for @paxtonhare and you fill see my comments
