### ISSUE TITLE
Running mlDeploy on a freshly created dhf4 project fails when deployed to a 3node cluster 

### ISSUE THREAD

**Issue by peetkes** [marklogic/marklogic-data-hub#1490]
Steps to reproduce:
create new dhf4.0.1 project
I have  a 3node cluster (http://ericsson-1.demo.marklogic.com, http://ericsson-2.demo.marklogic.com and http://ericsson-3.demo.marklogic.com)

ports 8010, 8011 and 8013 are free on the cluster, erickson-1 is the master so deploying to that node

running gradle mlDeploy -i will produce an error which I included in the attached stacktrace.
I also attached my dhf4-test project

[dhf4-test-master.zip](https://github.com/marklogic/marklogic-data-hub/files/2538895/dhf4-test-master.zip)
[stacktrace.txt](https://github.com/marklogic/marklogic-data-hub/files/2538897/stacktrace.txt)

**Comment by grechaw** [comment]
Are all the servers up after you've run this?  The failure seems to be a plain ol' "nothing running here" when inserting modules.

**Comment by peetkes** [comment]
I wonder why the non REST modules are deployed against the final server instead of the default 8000 server? I believe that was the way ml-gradle did  deployments

**Comment by peetkes** [comment]
What is the status on this?

**Comment by srinathgit** [comment]
1. Is this happening consistently ? Can you try this with 4.0.3 ?
2. The writing of modules to the data-hub-MODULES seems to have to failed due to 
15:46:04.756 [ERROR] [system.err] Exception in thread "ThreadPoolTaskExecutor-1" com.marklogic.client.MarkLogicIOException: **java.net.SocketException: Broken pipe (Write failed)**

Can you confirm the data-hub-FINAL was up and running  ?
3. We will consider using port 8000 to deploy modules

**Comment by peetkes** [comment]
1. Yes, this happens consistently and I did try it with the latest and greatest (4.0.3)
2. Yes Final server is up and running.
3. Great

To add to this issue. This occurs when I deploy from another machine. When I execute the deployment local (on the primary node) it all works OK.
You can test it out for yourself on the ericsson cluster (ericsson-1.demo.marklogic.com, ericsson-2.demo.marklogic.com, ericsson-3.demo.marklogic.com)
Ping me for the admin password

**Comment by srinathgit** [comment]
Can you please send me an email with all details for reproducing the issue ?

**Comment by aebadirad** [comment]
This should now be resolved as of 4.1.1 or later. Please reopen if it isn't.
