### ISSUE TITLE
tutorial links to old version ( 3.0.0 ) of QuickStart.war

### ISSUE THREAD

**Issue by patrickmcelwee** [marklogic/marklogic-data-hub#1506]
Short description of the problem: This page links to the 3.0.0 version, when I believe it should link to the latest: https://marklogic.github.io/marklogic-data-hub/tutorial/install/

I believe you can remove the hard-coding and just link to the latest: https://help.github.com/articles/linking-to-releases/#linking-to-the-latest-release

**Comment by srinathgit** [comment]
Thanks for logging the case. We will remove the hard-coding
