### ISSUE TITLE
Allow for easy override of default options node for quickstart search

### ISSUE THREAD

**Issue by netdance** [marklogic/marklogic-data-hub#1509]
This request is explicitly an RFE.

#### The issue

Short description of the problem:

It does not appear to be easy to allow overriding the default options node used by searches on the DHF Quickstart.  For creating a very quick and dirty demo, this would be incredibly useful.

At current, we need to manually add the new option node with curl (or a related gradle task).

What behavior are you expecting?

Creating `src/main/ml-modules/options/default.xml` then running `gradle mlDeploy` should work.

#### Tech details

Which Operating System are you using?  Amazon, Mac

Which version of MarkLogic are you using? 9.0.7

Which version of the Data Hub Framework are you using? 4.0

Is this a QuickStart UI bug? If so, which browser are you using?  Not a UI bug, it's expected to work thru gradle

**Comment by aebadirad** [comment]
@rjrudin this should be possible now, as of 4.1.1 or later, yes?

**Comment by rjrudin** [comment]
@aebadirad Yes
