### ISSUE TITLE
'Productize' Flow Runner

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic/marklogic-data-hub#1520]
Currently flows can be run via Gradle. However, a lot of clients do not want Gradle to be installed in production (gradle is a build tool). We need a runnable 'flowrunner,jar' which like mlcp simply take as arguments the host/username/password/flow info to run it. The gradle task should under water use this JAR. 

You simply cannot expect that clients are going to install gradle in PROD, or that they setup custom Java development to run flows, even if it is simple. If the JAR is vendor supplied then onboarding a flowrunner.jar is easier once MarkLogic is approved as software vendor. 

Using a REST call (as alternative) for harmonization is not an option: it is not distributed and you can run into timeout issues.

**Comment by rjrudin** [comment]
Closing this, as the 5.2.0 release will provide a new executable jar for running a flow in a fashion similar to using Gradle, but Gradle will not be required.
