### ISSUE TITLE
The Flow Runner Java code requires a project directory

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic/marklogic-data-hub#1521]
The FlowRunner Java code requires access to the DHF project directory on the filesystem:

`HubConfig dataHubConfig = HubConfigBuilder.newHubConfigBuilder("/path/to/your/project")`

However, this is not realistic in a PROD environment. All DHF (meta)info should be uploaded to the server, and the API should be changed to download the data via a `DatabaseClient`:

`HubConfigBuilder.downloadHubConfigFromServer(DatabaseClient client)`

**Comment by rjrudin** [comment]
Closing this, as DHF 5.2.0 will provide a solution for this (the solution is already on the develop branch).
