### ISSUE TITLE
Do staging and final in the same database

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic/marklogic-data-hub#1522]
What is the rationale for doing staging and final in a separate database? Separation can be achieved by using eg collections.  Transactions cannot run across databases, so e.g. if I harmonized item A, I cannot e.g. mark staging harmonized (addCollection) or delete the document from the staging database in the same transaction. Different database settings can be applied on staging vs final, however the disadvantages (transactions/switching context) out-weight this I think.

**Comment by mhuang-ml** [comment]
@josvanroosmalen, you can specify the source (sourceDB) and target (destDB) database names as parameters passed into the harmonization flow, so in theory if you want to do everything in a single database, then you should be able to achieve updating documents within a single transaction.

**Comment by aebadirad** [comment]
4.x can be specified this way, data Hub 5 allows for same database action and 'straight through'.

If  you do not wish to use the staging or final database, simply direct everything to staging or final. Both contain all artifacts necessary to perform all operations.
