### ISSUE TITLE
RFC: Google style Search front end with faceting deployed as app server

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic/marklogic-data-hub#1523]
Come up with a DHF UI Google Style free style text search:

- Using GROVE
- Should be deployable internal in ML (AppServer). So not rely on QuickStart. Preferable the data search in QuickStart should be redirect to this new feature. 
- Should offer google style free text search
- Configurable facetting, eg on buckets, date/number sliders, etc. Cram as much as features which /v1/search offers in the UI via configuration. 
- View the JSON/XML. 
- Run SQL.

**Comment by popzip** [comment]
Who is the target user? Demos? End User conducting business analysis on harmonized data? Developer exploring whats in the database?

**Comment by josvr** [comment]
I think:

* (Pre)sales
* This can act as a baseline separate UI which dev teams can build on.

**Comment by rjrudin** [comment]
Closing this, as the new Explorer app is intended to address this.
