### ISSUE TITLE
DHF Facility to only harmonize data ingested with a particular MLCP/REST ingest.

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic/marklogic-data-hub#1534]
We need better control over ingest/harmonization coordination.

Currently all examples I can find, run harmonization on all source collection(s) in scope. However that is not realistic in the real world. We need some facility how to do a MLCP/REST ingest, and only harmonize data ingested by that MLCP/REST run. The same strategy should work for REST ingest eg via JMS/MQ.

A solution (for MLCP) is to add the optional 'job-id' as a collection in the staging data. The harmonizer can then use a fast `cts:collectionQuery` to lookup all documents produced by that ingest.  The same approach should work for the REST API (where job-id then act as a message-id). 

Also we need a nice DHF Example to demonstrate this. 

As workaround we can now add an collection in the `output_collection` (jobid) parameter of MLCP. I did not look into a solution for the REST ingest, however we need one common approach to do this.

**Comment by kosed** [comment]
+1 tracing

**Comment by jmakeig** [comment]
Are you assuming that the raw data doesn’t land in staging? If the raw data is written to staging, no matter who is writing it, a collector can pick it up with a query. What am I missing?

**Comment by aebadirad** [comment]
Data Hub 5 can now allow users to 'on the fly' specify collections: [array,of,collections] when submitting to the REST tier as part of the options json object.

This will apply the collections specified, which can be a job-id in this case. This should resolve this particular use-case.
