### ISSUE TITLE
single-step-ingest should be part of the official distribution

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic/marklogic-data-hub#1535]
The single-step-ingest example (which is a REST endpoint to do ingest and harmonize e.g. processing realtime data from e.g. a message queue) should become (or in a somewhat different form) an standard rest extension shipped with the product.  This is obviously a standard functionality to RT process data. 

Also the job-id should be put into the collection in the staging/final database doc. This is simply the reference from the outside world (e.g. JMS MessageId) bread crumb to staging and final. 

See also #1534 . I believe Damon Feldman @damonfeldman is coordinating some efforts to get better control over realtime and batch loads.

**Comment by aebadirad** [comment]
This is now possible with Data Hub 5.0, as any step can be fed data through rest or mlcp.
