### ISSUE TITLE
Harmonize Orders fails - missing element range index on id

### ISSUE THREAD

**Issue by wpaven** [marklogic/marklogic-data-hub#1549]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:

Going through the walkthrough.  Harmonize orders will fail because of a missing element range index on id in the data hub staging DB. Not sure if this is a documentation issue, or if the quick start is supposed to create the index as part of creating the Order entity.

https://marklogic.github.io/marklogic-data-hub/tutorial/harmonizing-order-data/

I just created the element range index in admin and re-ran harmonize and all is well. but I knew what I was doing.  someone new to MarkLogic and the hub will probably get frustrated here.

#### Tech details

Which Operating System are you using? Windows 10

Which version of MarkLogic are you using? 9.0-7.2

Which version of the Data Hub Framework are you using? quick-start-4.0.2.war

Is this a QuickStart UI bug? If so, which browser are you using? firefox.  it doesn't work in chrome.  should I be using something else? i didn't see the browser specified in the docs.

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by srinathgit** [comment]
The page in the tutorial prior to the one you have mentioned in the case involves modelling the "Order" entity 
https://marklogic.github.io/marklogic-data-hub/tutorial/modeling-order-entity/ . In that page, users  are instructed to create element range index on 'id' by clicking on the lightning bolt icon and after saving the entity to update the indexes.

**Comment by wpaven** [comment]
Ahh. the fine print.  thanks.  not sure how I missed it.  Thanks for pointing it out.  PEBCAK
