### ISSUE TITLE
Having mlDatabaseHosts on DHF 2.x

### ISSUE THREAD

**Issue by ltnd** [marklogic/marklogic-data-hub#1552]
#### The issue

We are using 2 DHF 2.0.6 for 2 projects running on a single cluster. 
In order to isolate the storage of the databases for the 2 projects, we want to set databases for the 1st DHF on 3 nodes and the ones for the 2nd DHF on the 2 other nodes.
 
There is the parameter mlDatabaseHosts (https://github.com/marklogic-community/ml-gradle/wiki/Property-reference ) available on ml-gradle that would do exactly what we want, but I don’t see it in DHF 2.x ?
 
How could we do this on the DHF v2 ?

**Comment by srinathgit** [comment]
As per the documentation you have cited, "mlDatabaseHosts" is supported frm ml-gradle 3.2.0 onwards
DHF 2.0.6 plugin uses ml-gradle 3.4.0 . So, you should be able to use the "mlDatabaseHosts" property. Have you tried using it ? Did you face any issues when using ""mlDatabaseHosts" ?

**Comment by ltnd** [comment]
mlDatabaseHosts is only for one database. How I can set it for staging, final, jobs and tracing db with the same property ?

**Comment by aebadirad** [comment]
Closing out old issue that no longer applies to the latest major release. Also should have resolved itself with documentation.
