### ISSUE TITLE
SJS MLCP Flow transformer not properly logging errors

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic/marklogic-data-hub#1561]
Hi,

The SJS MLCP Flow Transform, is missing 1 big try-catch block. It should get a big try-catch block, log the error and stacktrace (eg xdmp.log or db trace), and rethrow the error to MLCP.

The problem is now, that if an error occur, **we do not get the stack trace. MLCP is by default not outputting that.** 

```
function transform(content, context) {
    try {
      <existing logic>
    } catch (err) {
        xdmp.log(err.stack)
        throw err
    }
    return content
}
```

**Comment by rjrudin** [comment]
Closing, this is being tracked by DHFPROD-1573.
