### ISSUE TITLE
DHF code hard to hotfix due to mlgradle and DHF setup

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic/marklogic-data-hub#1572]
In order to hotfix #1561 (where we lose stacktrace information when transformation goes wrong via MLCP), I decided to hotfix `mlcp-flow-transform.sjs`and placed this file in `ml-modules` what you can see in the screenshot below (`data-hub\data-hub`will go to the right URI in modules db)

However this is not 100% working:

- If we run `mlWatch` (using the workaround HubWatchTask to address #1429 / #1435) this file overwrites the original DHF transform (so then we get the desired output with the stacktrace). 
- However if we run 'mlDeploy' and related (mlRedeploy etc), then the **DHF code gets priority over the `ml-modules` files.**  So then I lose the stacktrace in case the MLCP transform fails. 

So, this is not consistent. We need a reliable way to hotfix DHF code simply we in the field cannot always wait on fixes etc. ( @rjrudin ). 

![screenshothotfixdhf](https://user-images.githubusercontent.com/9380618/48887465-9d04a100-ee2f-11e8-8b1a-fed15093cf35.png)

**Comment by josvanroosmalen** [comment]
I think the problem is bigger. I believe that entire 'ml-modules' is not loaded on mlDeploy. Also my non DHF hotfix stuff in ml-modules does not get deployed on a 'mlDeploy' etc.

**Comment by mhuang-ml** [comment]
@josvanroosmalen, with the alignment of the DHF with vanilla ml-gradle with release 4.1, then is this still an issue?

**Comment by aebadirad** [comment]
This should be resolved in 4.1.1 or later. Closing.
