### ISSUE TITLE
[WORKAROUND] DHF does not deploy REST extensions

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic/marklogic-data-hub#1574]
**_Workarround is at the end of this this thread_**

DHF is unable to install REST Resource Extensions, and I even can proof via a standard shipped example!

Here we go:

**Env:** OS X, ML 9.0-7, Java 1.8.0_144

* {Paranoide mode: delete your ML Data, initialize ML, it does not help}
* `rm -rf marklogic-data-hub`
* `git clone https://github.com/marklogic/marklogic-data-hub.git`
* `cd marklogic-data-hub/examples/single-step-ingest`
* `wget https://github.com/marklogic/marklogic-data-hub/releases/download/4.0.3/quick-start-4.0.3.war`

### First attempt: via quickstart  -> Tries to install resource prior to DHF in Modules

* `java -jar quick-start-4.0.3.war`

Go to: http://localhost:8080
* Choose browse
* Ensure **single-step-ingest** is selected -> next button
* Keep defaults -> initialize button
* project initialized -> next button
* local -> next button
* admin/admin -> login button
* install button

I now get:
**"You Have a Partially Installed Hub"**

It is aborted on:

> com.marklogic.client.FailedRequestException: Local message: config/resources write failed: Bad Request. Server Message: RESTAPI-INVALIDCONTENT: (err:FOER0000) Invalid content: invalid run-ingest-harmonize extension: could not parse XQuery extension run-ingest-harmonize; please see the server error log for detail XDMP-MODNOTFOUND: (err:XQST0059) Module /data-hub/4/impl/consts.xqy not found; run-ingest-harmonize either is not a valid module or does not provide extension functions (delete, get, put, post) in the http://marklogic.com/rest-api/resource/run-ingest-harmonize namespace

data-hub-MODULES contains 2 files:

`/marklogic.rest.resource/run-ingest-harmonize/assets/metadata.xml`
`/marklogic.rest.resource/run-ingest-harmonize/assets/resource.xqy`

**_Conclusion: Via quickstart it tries to install the resource prior to installing the DHF stuff (that is the error about const about)._** 

### Second attempt: Via `mlDeploy`. This populates DHF modules, but not the resource!

* `gradle mlUndeploy -Pconfirm=true`
* Check everything is gone in admin panel
* I manually deleted `data-hub-user/admin` and related roles (is there an issue for as well?)
* Run `gradle mlDeploy`

Now data-hub-MODULES gets populated with 151 files, however now the resource stuff (`metdata.xml` and `resource.xqy`) is not there!! Even if I go to: http://localhost:8010/v1/config/resources it is not listed there of course.

**_Conclusion: via `mlDeploy`, DHF is deployed, but the resource is never!!_**

**Comment by rjrudin** [comment]
I did the following (didn't try QS app):

1. Created new project with build.gradle that imports only the properties and DHF plugins (v 4.0.3)
1. Ran "gradle hubInit" - worked
1. Ran "gradle -i mlDeploy" - worked; verified there are 137 modules in data-hub-MODULES
1. Ran "gradle -PresourceName=test -PresourceType=sjs mlCreateResource" - worked (created a new module under src/main/ml-modules)
1. Ran "gradle mlReloadModules" to clear the modules database and force all modules to be loaded - ended up with 140 total modules (correct)
1. Went to localhost:8011/v1/config/resources - saw the "test" module there (correct)
1. Went to localhost:8010/v1/config/resources - did not see the "test" module there (I am guessing this is "working as designed" but not sure if it's expected)

**Comment by grechaw** [comment]
It seems like the work on ml-gradle/DHF that is ongoing now will address this issue as well. Is the workaround by @rjrudin sufficient pending those improvements?

**Comment by josvanroosmalen** [comment]
@grechaw @rjrudin . The solution of Rob is **NOT** working. If you do 1 "gradle mlReloadModules" afterwards that service is GONE again.

Full reproduction:

- mkdir thisiswrong
- cd thisiswrong
- set build.gradle to `plugins {id 'com.marklogic.ml-data-hub' version '4.0.3'}`
- `gradle hubInit`
- Set mlUsername/password in gradle.properties (empty by default)
- `gradle -i mlDeploy`
- I have now **_137 files_** in data-hub-MODULES. So far so good.
- `gradle -PresourceName=test -PresourceType=sjs mlCreateResource`
- `gradle mlReloadModules`
- I have now **_140 files_** in data-hub-MODULES. So far so good.
- **NOW LET IT BREAK:**
- gradle mlReloadModules
- I have now **_137 files again_** in data-hub-MODULES. **My test is GONE!!**

I really need a work-around for this!!!

**Comment by grechaw** [comment]
Yes, agreed.  I've linked this issue to the internal umbrella bug https://project.marklogic.com/jira/browse/DHFPROD-1421

**Comment by kkanthet** [comment]
Fixed as part of Release 4.1.0
