### ISSUE TITLE
Tutorial Documentation: Wrong Product Ingest folder?

### ISSUE THREAD

**Issue by nizdobs** [marklogic/marklogic-data-hub#1578]
In the DHF tutorial on https://marklogic.github.io/marklogic-data-hub/tutorial/load-products-as-is/ the Load-Products ingest flow screen shot indicates that the user should load data from input/products/games. After running the ingest flow the job output screenshot shows that there were 450 OUTPUT_RECORDS_COMMITTED. 

First, I don't have an input/products/games directory. When I extract the sample data files I have a store-data/products/games directory. 

Also, if I use the store-data/products/games directory for my Load-Products input flow I only end up with 270 documents in Staging. It's only when I load from store-data/products that I get a document count of 450 in Staging. 

So, is the specified directory correct and the expected count incorrect? Or is the count correct but it should load from the parent directory?

#### Tech details

Which Operating System are you using?
MacOS

Which version of MarkLogic are you using?
9.0.7

Which version of the Data Hub Framework are you using?
4.0.3

Is this a QuickStart UI bug? If so, which browser are you using?

No.

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:
[QuickStartOutput.txt](https://github.com/marklogic/marklogic-data-hub/files/2617164/QuickStartOutput.txt)

**Comment by srinathgit** [comment]
1. https://marklogic.github.io/marklogic-data-hub/tutorial/install/ specifies you to "move the subfolders of sample data (campaigns/, customers/, etc.) into the input folder you just created." So, the path is correct
2. Regarding the document count, you are correct, choosing input/products ingests 450 docs whereas input/products/games ingests only 270. We will fix that doc issue.

**Comment by ayuwono** [comment]
The document count documentation issue has been tracked on JIRA

**Comment by ayuwono** [comment]
Documentation is updated
