### ISSUE TITLE
getFlow does not return null if flow does not exist but throws Invalid coercion

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic/marklogic-data-hub#1589]
**DHF 4.0.2**

`getFlow` in `flow-lib.sjs`, does a `json.transformToJson` which requires a `node()`. 

In case the flow is not found, this result in a `"XDMP-AS: $src as node() -- Invalid coercion: null as node()\nin /data-hub/4/impl/flow-lib.sjs, at 56:16, in getFlow()"`

**In case the flow does not exist, it should return null, so that we can check against it.**

Now we can only catch in the exception handling.

**Comment by ayuwono** [comment]
Tracking this on JIRA: https://project.marklogic.com/jira/browse/DHFPROD-1644

**Comment by damonfeldman** [comment]
+1 on this
For DHS we hit this bug when we did not set up ports for deploy properly (we had defaults in place which does a module load via port 8000, and instead DHS needs mlManagePort=8002 and/or mlAppServicesPort=8002 ... or either/both set to 8004). This caused plugins to not be deployed, and triggered the error above.

"Plugin  named 'xyz' for [input|harmonze] flow 'pdq' not found" would have been clearer.
