### ISSUE TITLE
MLCP SJS transform works fine, but the XQY one causes MISSING_CURRENT_TRACE.

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic/marklogic-data-hub#1590]
**DHF 4.0.2**

If I MLCP stuff in , it works fine when I use:

`transform_module = "/data-hub/4/transforms/mlcp-flow-transform.sjs"`

However, if I change this to the xqy impl:

`transform_module = "/data-hub/4/transforms/mlcp-flow-transform.xqy"` it fails with:

`error (MISSING_CURRENT_TRACE): fn.error(xs.QName("MISSING_CURRENT_TRACE"))`

When I flip back to the SJS one (and that is the only change I make), then it works fine again!

**Comment by aebadirad** [comment]
Yes, sjs for sjs flows, xqy for xqy flows.

We can perhaps make that more clear, but for now to keep the code paths clear (all v8 or all xquery) each one works only with its respective language type.

**Comment by josvanroosmalen** [comment]
That is not mentioned anywhere. DHF can also check for that instead of giving this vague error.
