### ISSUE TITLE
mlFinalForestsPerHost is ignored

### ISSUE THREAD

**Issue by netdance** [marklogic/marklogic-data-hub#1596]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:

mlFinalForestsPerHost is ignored.  On mlDeploy, only one forest is created.

What behavior are you expecting?

if mlFinalForestsPerHost=4, I want 4 forests.

#### Tech details

Which Operating System are you using?

MacOS, Linux

Which version of MarkLogic are you using?
9.0-7

Which version of the Data Hub Framework are you using?
4.01

Is this a QuickStart UI bug? If so, which browser are you using?
No.

#### The devil is in the details...

Create a hub with the quickstart.

then run gradle mlUndeploy -Pconfirm=true
then run gradle mlDeploy

Note that the value of mlFinalForestsPerHost is ignored.

**Comment by srinathgit** [comment]
Thanks for filing the issue. I can see it in 4.0.3 as well. We will work on fixing it. https://project.marklogic.com/jira/browse/DHFPROD-1568

**Comment by srinathgit** [comment]
This issue is fixed in 4.1.0
