### ISSUE TITLE
FlowRunner Java API example is completely outdated.

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic/marklogic-data-hub#1630]
**DHF 4.0.2**:

Can someone update:

https://marklogic.github.io/marklogic-data-hub/harmonize/java/

This is **completely outdated**. E.g.:

`new FlowManager(dataHubConfig);`

Does not work because FlowManager is now abstract. This should be replaced by `FlowManager.create(dataHubConfig)`

Also all packages are changed. E.g. `com.marklogic.hub.Flow` is now `com.marklogic.hub.flow.Flow` etc.

It is **incomplete** e.g: it has a databaseclient and options which are not set. 

Make this a working example again.

**Comment by ayuwono** [comment]
Thanks @josvanroosmalen, will assign this issue to @eltesoro-ml to update the documentation

**Comment by josvanroosmalen** [comment]
This seems to be fixed now.

**Comment by josvanroosmalen** [comment]
PLEASE Close this one.

**Comment by mhuang-ml** [comment]
@sbayatpur and @aebadirad, can either of you please close this issue as it Jos has confirmed that the documentation in 4.1.0 resolved it.
