### ISSUE TITLE
Version 3x Tutorial pages missing

### ISSUE THREAD

**Issue by masyukun** [marklogic/marklogic-data-hub#1641]
#### The issue

Short description of the problem: All links in "Table of Contents" section give 404 errors in version 3x of the Tutorial https://marklogic.github.io/marklogic-data-hub/tutorial/3x/

What behavior are you expecting? Tutorial pages like in the 2x Tutorial

#### Tech details

Which Operating System are you using? Mac OS X High Sierra

Which version of MarkLogic are you using? 9.0-6

Which version of the Data Hub Framework are you using? 4.0.1

Is this a QuickStart UI bug? If so, which browser are you using? no

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

Try clicking any of the TOC links at https://marklogic.github.io/marklogic-data-hub/tutorial/3x/
Or try this link: https://marklogic.github.io/marklogic-data-hub/tutorial/3x/install/

**Comment by masyukun** [comment]
Ah, ok. The link from the left menu "Learning DHF" -> "Quickstart Tutorial" https://marklogic.github.io/marklogic-data-hub/tutorial/ lands you on a page where you select the version you want to see. Three was the highest number, so I went with that. Perhaps the default could go to the non-versioned page URL.

**Comment by eltesoro-ml** [comment]
@masyukun: Thank you for the heads-up! The fixes to the tutorial links and other links are coming soon. (Just waiting for the pull request to be reviewed and accepted.) Please try again tomorrow.

@sbuxton: Thanks for your reply! That tutorial is intended for DHF 3.x, so the link makes sense. The next iteration of the tutorial (no ETA yet) will likely be more generalized. All releases are available in https://github.com/marklogic/marklogic-data-hub/releases/ .

**Comment by sbuxton** [comment]
Sorry, I'm still not entirely clear.
Are you saying that V3 of the tutorial is meant to be run with V3 of DHF?
Does that mean there's no version of the tutorial that works on V4 of DHF?

If I want to run a tutorial today to familiarize myself with DHF, should I run the V3 tutorial against V3 of Quickstart and DHF? Or run the V3 tutorial against V4 of Quickstart and DHF (and expect some mismatches)? Or should I not run a DHF tutorial until the V4 tutorial is ready?

**Comment by eltesoro-ml** [comment]
Not at all. I simply meant that those tutorial pages were originally intended for DHF 3.x. They were probably written before DHF 4.0 was released.

You can probably use DHF 4.x on the 3.x tutorial, but I don't know if the instructions have been tested with DHF 4.x.

**Comment by sbuxton** [comment]
Thanks muchly!
I'll give it a shot ...

**Comment by ayuwono** [comment]
This issue is resolved, you can navigate to table of contents now on 3.x documentation. Example: https://marklogic.github.io/marklogic-data-hub/tutorial/3x/create-order-entity/
