### ISSUE TITLE
Incomplete DHF command error messages when missing parameters

### ISSUE THREAD

**Issue by JackYoungblood** [marklogic/marklogic-data-hub#1643]
#### The issue
It's not clear which parameters are expected to be passed to DHF gradle commands. "gradle tasks" for DHF commands don't show the required parameters and if you type a command missing multiple parameters the error only exposes one missing parameter at a time.
 
If you run the command `gradle hubRunFlow` you'll first get an error stating that`entityName property is required`. 

Now you run the command `gradle hubRunFlow -PentityName=myEntity` and you get an error stating `flowName property is required`

If you issue a command where you are missing any required parameters the error message should list all required parameters.

And the info shown in gradle tasks  should include all required and optional parameters

This is using DHF 4.0.3

**Comment by akshaysonvane** [comment]
Thanks for filing the issue. This seems like a nice to have improvement. Tracking it via https://project.marklogic.com/jira/browse/DHFPROD-1631

Meanwhile, you can use this as reference: https://marklogic.github.io/marklogic-data-hub/refs/gradle-tasks/

**Comment by rjrudin** [comment]
We aren't likely to adjust the DHF 4 Gradle tasks, and the DHF 5 hubRunFlow task only has one argument, but point taken here - more recent DHF 5 Gradle tasks are better about listing out all required task arguments instead of only throwing an error for the one not specified.
