### ISSUE TITLE
Entity name and case-sensitive issue while running flow

### ISSUE THREAD

**Issue by mthahir** [marklogic/marklogic-data-hub#1645]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:
I have an entity named "Employee" with uppercase "E".  However, when I create a harmonize flow, I used the entity name as "employee" - all lowercase. It did create the flow. But, when I run the flow I get an error "the requested flow not found".  The only way to resolve is to delete and recreate the flow with the entity name matching case-sensitive. 
Here is my flow:
1. /gradlew hubCreateHarmonizeFlow -PentityName="employee" PflowName="harmonizeEmployeeRdbms"    -pUseES=false .       (success)
2. ./gradlew hubRunFlow -PentityName="employee" -PflowName="harmonizeEmployeeRdbms" -PflowType="harmonize"                  (flow not found)
3. ./gradlew hubRunFlow -PentityName="Employee" -PflowName="harmonizeEmployeeRdbms" -PflowType="harmonize"       (error)
4. delete the flowfile from plugin directory, recreate the flow with entity name "Employee" matching the original entity name, and copy all original code
5. rerun flow as in step-3 above.  (success)

What behavior are you expecting?
Expecting, the create flow complain about entity name mismatch. I assume it created because of the use of -PUseES=false and the file system folder names are not case-sensitive.  If so, not sure why Step 3 failed. 

#### Tech details

Which Operating System are you using?
mac OS 10.13.6
Which version of MarkLogic are you using?
9.0-7
Which version of the Data Hub Framework are you using?
4.0.1
Is this a QuickStart UI bug? If so, which browser are you using?
no
#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by ayuwono** [comment]
We're tracking this on JIRA and will discuss it with the team:
https://project.marklogic.com/jira/browse/DHFPROD-1643

**Comment by akshaysonvane** [comment]
Fixed in version 4.2.0
