### ISSUE TITLE
DataHub::isInstalled() is not sufficient

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#165]
Right now isInstalled() returns a boolean. There are actually more than 2 cases.
1. never installed. no hub artifacts exist on the server
2. installed but not the same. hub was installed but something is wrong. different ports maybe?
3. hub is installed and matches the current config.

for case 2 we can't just reinstall because it will fail. We would need to uninstall then reinstall.

I propose a couple of changes:
1. change isInstalled() to return an enum of possible states. Maybe change the function name to make better sense.
2. change the UI code to handle case 2 above. Right now this case is not handled. This will require asking the user what to do. I propose a few choices:
   1. don't do anything. If the user doesn't want to do anything go back to the "login" screen
   2. Reinstall. If they choose this we need to make it clear that we are nuking their install then redoing it. This is a dangerous choice.

**Comment by divino** [comment]
> change the UI code to handle case 2 above. Right now this case is not handled. This will require asking the user what to do. I propose a few choices:

>    don't do anything. If the user doesn't want to do anything go back to the "login" screen

It might be nice also to suggest using the currently deployed version instead.

>    Reinstall. If they choose this we need to make it clear that we are nuking their install then redoing it. This is a dangerous choice.

This should include a message that it will delete the data from the previous install. Colored in RED probably and with a prefix of "WARNING:".
