### ISSUE TITLE
Sample code for Unit/Integration Testing a Hub Implementation

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic/marklogic-data-hub#1650]
We need an a (ml/J) UnitTest example project, which offer a bunch of convenience functions to do typical testing stuff such as unit-testing and integration testing. 

This sample project:
- Should e.g. have 1 entity
- Have some sample code (e.g. CSV)
- The JUnit Test will:
    - Ingest the CSV
    - Check the staging
    - Run harmonization
    - Check harmonization (e.g. count based.
- For this we need a set of Java convenience functions which:
  - can ingest data (e.g. a convenience function around MLCP)
  - Retrieve 1 document, and run some xpaths against it to check.
  - Java function which returns the number of documents having a certain set of collections
  - Can run a harmonization flow (convenience function around FlowRunner)
  - clean everything up (teardown)

**Comment by akshaysonvane** [comment]
Hi @josvanroosmalen, thanks for creating this request. 
Tracking it internally via https://project.marklogic.com/jira/browse/DHFPROD-1639

**Comment by jamesagardner** [comment]
This seems related: https://github.com/marklogic-community/marklogic-unit-test/issues/74

**Comment by rjrudin** [comment]
This is addressed for DHF4 via https://github.com/marklogic/marklogic-data-hub/tree/master/examples/dhf4/dhf4-with-tests . An internal JIRA ticket exists for tracking this for DHF 5.
