### ISSUE TITLE
Cannot run runWriter after harmonization flow in SJS

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic/marklogic-data-hub#1669]
**DHF 4.0.2: I am working on a Realtime single-step ingest point in SJS.** 

However the `runWriters` is not working.

```
    const harmonizeFlow = flowlib.getFlow(entity, flowName,consts.HARMONIZE_FLOW);
    let options={}; 
    ....
    flowlib.setDefaultOptions(options, harmonizeFlow);
    let mainFunc = flowlib.getMainFunc(flow.main);
    for ( let i = 0 ; i < idsToHarmonize.length ; i++ ) {
        const id = idsToHarmonize[i];
        flowlib.writerQueue['TESTER']="1";
        flowlib.runFlow(jobId, flow, id, null, options, mainFunc); 
    }
    flowlib.runWriters(idsToHarmonize);
```
The root cause is this:

If I add the logging below to `flow-lib.sjs`, and `idsToHarmonize.length == 1` with `idsToHarmonize[0]='TheUnqiueId'`then the output is:

> ADDED TO QUEUE
> ['TheUniqueId']
> WRITER QUEUE KEYS
> ['TESTER']

Ergo: this TESTER is coming from the original source (for loop), **however the `dhf:runWriter` seens it run in a different Javascript context** which causes 'TheUniqueId' not to be visible in the runWriters. 

```
function runWriter(writerFunction, id, envelope, options) {
  flowlib.queueWriter(writerFunction, id, envelope, options);
};
```

**Logging:**

```
function queueWriter(writerFunction, identifier, envelope, options) {
  writerQueue[identifier] = {
    writerFunction: writerFunction,
    envelope: envelope,
    options: options
  };
   xdmp.log("ADDED TO QUEUE ")
   xdmp.log(Object.keys(writerQueue))
}

function runWriters(identifiers) {
  xdmp.log("WRITER QUEUE KEYS");
   xdmp.log(Object.keys(writerQueue)); 
   ...
}
```

**Comment by akshaysonvane** [comment]
Thanks, @josvanroosmalen for filing the issue.
We are looking into this.
Tracking it via https://project.marklogic.com/jira/browse/DHFPROD-1666

**Comment by rjrudin** [comment]
Closing as OBE.
