### ISSUE TITLE
Provide “context” that is passed between plugins in DHF flows

### ISSUE THREAD

**Issue by jkerr5** [marklogic/marklogic-data-hub#1670]
Since the options object lifecycle is at the batch level, DHF needs another object that can be used as some sort of context to pass information between plugins. Right now, people use work arounds like (list not exhaustive)

``` 
options[id] = {
  “a” : “some stuff I want to pass to the next plugin”
}
```

or

``` 
content.envelope.context = {
  “a” : “some stuff I want to pass to the next plugin”
}
```
and then call
```
delete content.envelope.context;
```

in the writer before the insert.

**Comment by ayuwono** [comment]
Thanks @jkerr5 , we will look into this issue

**Comment by ayuwono** [comment]
Tracking this on JIRA: https://project.marklogic.com/jira/browse/DHFPROD-1641

**Comment by jkerr5** [comment]
I believe it was in a much older version that the options were at the document level but I don't recall exactly. 

Regardless, there is not mechanism in the current plugin framework that I can find and it would be very helpful.

**Comment by mchiarelli** [comment]
The options object was at the document level in 2.x

**Comment by mchiarelli** [comment]
I believe the behavior for 4.x is any changes to the options object will be retained within a flow, context->headers->triples, but then you get the last changes to the value of the batch going into the writer. The queueWriters is taking a reference to the options object, not taking a copy.

**Comment by mchiarelli** [comment]
related to https://github.com/marklogic/marklogic-data-hub/issues/1188

**Comment by aebadirad** [comment]
Data Hub 5.0 now supports universal context in each step, including options.
