### ISSUE TITLE
If you call your harmonize flow "harmonize", it doesn't work (v4.1.0)

### ISSUE THREAD

**Issue by derms** [marklogic/marklogic-data-hub#1708]
#### The issue

If you call your harmonize flow "harmonize", you get the following error when you try to run a harmonize flow

"could not read resource at resources/ml:flow. Server Message: The requested flow was not found"

#### Tech details

OS: Mac
ML Version: 9.0-7
DHF Version: 4.1.0

Is this a QuickStart UI bug? If so, which browser are you using?

#### The devil is in the details...

Create a harmonize flow called harmonize and run it either from the quickstart gui or gradle.

12:12:37.220 [http-nio-8080-exec-9] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.marklogic.client.ResourceNotFoundException: Local message: Could not read resource at resources/ml:flow. Server Message: The requested flow was not found] with root cause
com.marklogic.client.ResourceNotFoundException: Local message: Could not read resource at resources/ml:flow. Server Message: The requested flow was not found
        at com.marklogic.client.impl.OkHttpServices.checkStatus(OkHttpServices.java:4313)
        at com.marklogic.client.impl.OkHttpServices.getIteratedResourceImpl(OkHttpServices.java:3098)
        at com.marklogic.client.impl.OkHttpServices.getIteratedResource(OkHttpServices.java:3075)
        at com.marklogic.client.impl.ResourceServicesImpl.get(ResourceServicesImpl.java:61)
        at com.marklogic.client.impl.ResourceServicesImpl.get(ResourceServicesImpl.java:57)
        at com.marklogic.hub.impl.FlowManagerImpl.getFlow(FlowManagerImpl.java:221)
  

  **for gradle:**  
  `gradle hubRunFlow -PentityName=profileCard -PflowName=harmonize

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':hubRunFlow'.
> Local message: Could not read resource at resources/ml:flow. Server Message: The requested flow was not found

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed`

**Comment by ayuwono** [comment]
Fixed and passed qa
