### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic/marklogic-data-hub#1711]
https://marklogic.github.io/marklogic-data-hub/harmonize/gradle/ is mentioning:

> ./gradlew hubCreateEntity -PEntityName="My Awesome Entity"

However this result in a FAILURE: "entityName property is required. Supply the parameter with -PentityName=Yourentity"

**Comment by akshaysonvane** [comment]
Yes, the parameter should have been "entityName" instead of "EntityName"
Thanks for filing this issue @josvanroosmalen 
Assigning to @eltesoro-ml to make the necessary changes in docs.

**Comment by sbayatpur** [comment]
Created a doc bug to track this: https://project.marklogic.com/jira/browse/DHFPROD-1689

**Comment by eltesoro-ml** [comment]
Fixed.
