### ISSUE TITLE
Documentation Error #2

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic/marklogic-data-hub#1712]
This page:

https://marklogic.github.io/marklogic-data-hub/project/gradle/

Is still listing DHF version 4.0.1 in the build.gradle.

**Comment by akshaysonvane** [comment]
Thanks for noticing the issue and filing the bug.
Assigning to @eltesoro-ml for the doc change.

**Comment by sbayatpur** [comment]
Thanks — this issue will be fixed as part of https://project.marklogic.com/jira/browse/DHFPROD-1621

**Comment by aebadirad** [comment]
Resolved, so closing.
