### ISSUE TITLE
Documentation Missing #1

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic/marklogic-data-hub#1713]
No instructions to create a Input flow using gradle. So documentation is inconsistent.

**Comment by akshaysonvane** [comment]
Input Flows can be created as follows:
`./gradlew hubCreateInputFlow -PentityName=yourentityname -PflowName=yourflowname -PdataFormat=(xml|json) -PpluginFormat=(xqy|sjs)`

Yes, it would be nice to have the instructions to create an input flow via gradle.
For now you can refer this page for gradle tasks: https://marklogic.github.io/marklogic-data-hub/refs/gradle-tasks/ which includes information about creation of input flows as well.

**Comment by mhuang-ml** [comment]
@sbayatpur, I can't speak for @josvanroosmalen's original ticket (i.e. if he couldn't find the information or if he needs further instructions).

But just looking at all of the parameters for the hubCreateInputFlow, is that parameter list 100% all inclusive?  I remember in previous versions of DHF then there was the useES parameter.  Is this parameter deprecated from release 4.x altogether?

**Comment by sbayatpur** [comment]
I'm not sure. @aebadirad Do you know whether the useES parameter still exists or was deprecated?

**Comment by mhuang-ml** [comment]
Ok that makes sense then.  So all of the documentation for the parameters that are listed right now are all of the parameters that we want people to be able to use out of the box.  Just wondering if there are any other parameters that are supported but we would consider them more "advanced" gradle usage or something along those lines.

**Comment by aebadirad** [comment]
Closing out old issue that no longer applies to the latest major release.
