### ISSUE TITLE
Unable to generate the TDE of an entity containing references to other entities (DHF 4.1.0)

### ISSUE THREAD

**Issue by maachou** [marklogic/marklogic-data-hub#1717]
#### The issue

Based on the DHF QuickStart tutorial (Online Shopping Hub) I was unable to generate the Order entity TDE with the command:

`gradle hubGenerateTDETemplates -PentityNames=Order`

I’m getting the following error:

⇒  gradle hubGenerateTDETemplates -PentityNames=Order

> Task :hubGenerateTDETemplates FAILED
About to generate a template for the following entities: [Order] into directory /Users/mmaachou/Projects/marklogic/demos/marklogic-datahub-demo/src/main/ml-schemas

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':hubGenerateTDETemplates'.
> Local message: failed to apply resource at eval: Internal Server Error. Server Message: ES-MODEL-INVALID: Local reference #/definitions/Product must resolve to local entity type.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
1 actionable task: 1 executed

#### From the query console: 

I’m able to generate a TDE of this entity with the following code :
`
'use strict';
const es = require('/MarkLogic/entity-services/entity-services');
es.extractionTemplateGenerate(cts.doc('/marklogic.com/entity-services/models/Order.entity.json'));
`

#### Tech details

Mac OS
MarkLogic 9.0-7.2
DHF 4.1.0
the DHF was bootstrapped with quick-start-4.1.0.war

Here is my model:

<img width="1175" alt="screen shot 2018-12-25 at 22 46 20" src="https://user-images.githubusercontent.com/879083/50426791-8078e000-0897-11e9-9b96-8de2e5a5bde2.png">

The content of my Order.entity.json:

[Order.entity.json.txt](https://github.com/marklogic/marklogic-data-hub/files/2709060/Order.entity.json.txt)

**Comment by aebadirad** [comment]
This should be fixed in 4.1.1
