### ISSUE TITLE
Javascript trace errorCount stuck at 1 

### ISSUE THREAD

**Issue by mchiarelli** [marklogic/marklogic-data-hub#1721]
#### The issue

Short description of the problem:
The Error statistics are incorrect when there are exceptions in the content or writers. The error count from the trace-lib does not advance beyond 1 if there are multiple errors. Additionally, non-error items  that appear in the traces in the event of an exception will get an internal error message assigned due to uninitialized data in trace-lib.  

Note: there are other issues #1705 that also relate to poor error accounting, but that issue has to do with exception on completion of the flow.

#### Tech details

Which Operating System are you using? Mac OS
Which version of MarkLogic are you using? 9.0.5
Which version of the Data Hub Framework are you using? 4.1
Is this a QuickStart UI bug? If so, which browser are you using? N/A

#### The devil is in the details...
Simple example project attached.  To run unzip, do mlDeploy and either run it from the provided runHarmonization.sh script or run harmonize flow from quick start. Fix for issue is provide in fixes directory and will post a pull request soon.

Job status return will be 
{
"jobId": "xxxxxx", 
"flowType": "harmonize", 
"flowName": "HarmonizeEHTest1", 
"entityName": "EHandlerTest", 
"jobName": null, 
"jobOutput": null, 
"status": "FINISHED_WITH_ERRORS", 
"successfulEvents": 5,                **// excepted 3 successes**
"failedEvents": 1,                          **// expected 3 failures**
[dhf-test.zip](https://github.com/marklogic/marklogic-data-hub/files/2715936/dhf-test.zip)

"successfulBatches": 1, 
"failedBatches": 0
}

**Comment by ayuwono** [comment]
Tracking this on: https://project.marklogic.com/jira/browse/DHFPROD-1680

Will update the progress after PR is submitted

**Comment by bsrikan** [comment]
PRs merged. Fixed in develop and 4.x-develop branch.

**Comment by aebadirad** [comment]
Fixed in version 4.2.0
