### ISSUE TITLE
Support for periodic data ingest

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#173]
Think about how the hub will support a production workflow where daily (or hourly, or per minute) deltas are regularly being ingested into multiple collections, then joined together to conformed data. (and code changes if needed to ensure it works well)

E.g. an insurance company may have a daily load of new/expired members and new claims. Some claims can be for the new members, so both need to be loaded to RAW overnight and then joined after successful load.

**Comment by aebadirad** [comment]
Since Data Hub 5.0, we've moved to external orchestration tools that can move data through the flow at its own discretion.
