### ISSUE TITLE
Tutorial is still 3.x

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic/marklogic-data-hub#1733]
The tutorial (https://marklogic.github.io/marklogic-data-hub/tutorial/) is still pointing to version 3.x as the latest tutorial.

Also the 3.x tutorial is referencing to the 3.x quickstart WAR, so if a new user is following this guide, it will use the 3.x quickstart.

Solution:

* Copy the 3.x guide to 4.x, list the 4.1.0 quickstart, and add the 4.x link to /tutorial/index.html
* (Better) also update the tutorial with the 4.x features (if any).

**Comment by aebadirad** [comment]
4.x is now available https://marklogic.github.io/marklogic-data-hub/tutorial/4x/
