### ISSUE TITLE
ml:sjsInputFlow transform is very slow in batch processes

### ISSUE THREAD

**Issue by rjrudin** [marklogic/marklogic-data-hub#1750]
I have a NiFi CSV->MarkLogic ingest process that uses GetFile, SplitText with a batch size of 1k lines, and then PutMarkLogicRecord with a batch size of 200 lines and a thread count of 32. In my test environment, the use of a REST transform and what it does has a huge impact on ingest performance:

- No transform = around 2100 docs/sec
- SJS transform, just returns content = around 1150 docs/sec
- SJS transform, calls dhf.makeEnvelope = around 735 docs/sec
- DHF ml:sjsInputFlow transform = around 460 docs/sec

The biggest change is simply from introducing an SJS transform - performance is roughly halved. So this isn't really DHF-specific, and perhaps it's really a server / REST API issue. 

Note that MLCP is better, though not much better - MLCP with the mlcp-flow-transform.sjs transform averages around 900 docs/sec in the same environment. But if that transform is necessary, clearly MLCP would be better, since it's twice as fast (also in these tests, I'm running ML on the same machine as NiFi/MLCP. MLCP performs much better - around 2500 docs/sec - when it's run on a separate machine). 

Right now, the best approach seems to be to generate the JSON that we want within NiFi (or generally, the external tool). I'm going to explore that path with a custom JSON RecordSetWriter.

**Comment by damonfeldman** [comment]
Is this DHF 4.1 ?

**Comment by rjrudin** [comment]
Yes, though it really seems to be a matter specific to SJS REST transforms. I am guessing that the number of "require" statements matters (which is why simply importing dhf.sjs to use dhf.makeEnvelope further slows down ingest).

**Comment by rjrudin** [comment]
More numbers - in our AWS environment, with NiFi and ML on separate machines, the "no transform" averages around 2000 docs/s and the DHF SJS transform averages around 500 docs/s. MLCP in that environment (with MLCP running on a separate machine) runs at 2500 docs/s, and that's with the DHF SJS MLCP transform being used.

**Comment by rjrudin** [comment]
I'm attaching a zip file with the following items in it:

1. A zipped ml-gradle project that deploys the DHF application (it has very little to it)
1. The sample CSV file used for testing
1. The NiFi template
1. Instructions on how to set things up for testing, along with logging examples that show the performance with and without the DHF transform

[nifi-dhf-ingest-test.zip](https://github.com/marklogic/marklogic-data-hub/files/2769480/nifi-dhf-ingest-test.zip)

**Comment by rjrudin** [comment]
As a follow up, I did some testing on ML 9.0-9 with a Java program that uses a WriteBatcher and the ml:sjsInputFlow transform. For writing approx 10k documents, I noted the following times:

1. Without a transform - 7 to 8s
1. With ml:sjsInputFlow on ML 9.0-8 - 32 to 33s
1. With ml:sjsInputFlow on ML 9.0-9 - 20 to 22s

So performance is definitely better with ML 9.0-9. Closing this issue.
