### ISSUE TITLE
How to update a Hub Project link produces error

### ISSUE THREAD

**Issue by xbonnamy-marklogic** [marklogic/marklogic-data-hub#1754]
#### The issue
Clicking "How to update a Hub Project" link in the DHF upgrade dialog produces an error (another tab opens with display below:

**Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Jan 17 16:18:21 CET 2019
There was an unexpected error (type=Not Found, status=404).
No message available**

What behavior are you expecting?
Access the link's page

#### Tech details
macOS X (10.12.6)
MarkLogic 9.0-8
DHF 4.1.1
QuickStart Issue - Using FF 64.0.2
#### The devil is in the details...

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by akshaysonvane** [comment]
Thanks for opening this issue, @xbonnamy-marklogic 
Tracking it via https://project.marklogic.com/jira/browse/DHFPROD-1726
For now, here's the link: https://marklogic.github.io/marklogic-data-hub/upgrade/

**Comment by akshaysonvane** [comment]
Yes, its localhost:8080/null

**Comment by brucean52** [comment]
Fix has been merged into 4.x-develop branch
