### ISSUE TITLE
hubGenerateTDETemplates fails when there are relations between entities

### ISSUE THREAD

**Issue by xbonnamy-marklogic** [marklogic/marklogic-data-hub#1771]
# The issue
Issuing a gradle hubGenerateTDETemplates command for a DH with entities with 1/N relations fails.
 
Short description :
Order and Product entities (Order --> 1/N --> Product)
When issuing  the following error displays:

> Local message: failed to apply resource at eval: Internal Server Error. Server Message: ES-MODEL-INVALID: Local reference #/definitions/Product must resolve to local entity type.

Expected behavior:
TDE should generate without errors.

# Technical details
macOS Sierra 10.12.6
MarkLogic 9.0-8
DHF 4.1.1
gradle 4.1

# More details
Here is the command output

> Task :hubGenerateTDETemplates
About to generate a template for the following entities: [Order, Product] into directory <project-path>/data-hub-trunk/src/main/ml-schemas 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':hubGenerateTDETemplates'.
> Local message: failed to apply resource at eval: Internal Server Error. Server Message: ES-MODEL-INVALID: Local reference #/definitions/Product must resolve to local entity type.

**Comment by akshaysonvane** [comment]
Thanks for filing this issue @xbonnamy-marklogic.
Tracking it here https://project.marklogic.com/jira/browse/DHFPROD-1746

**Comment by aebadirad** [comment]
This should be fixed in 4.x-develop (and develop), @xbonnamy-marklogic can you provide a few entities for us to test against on our develop to see if we're resolved the case for this issue pending the next version?

**Comment by xbonnamy-marklogic** [comment]
I have used Product and Order entities as described and used for the "Getting Started Tutorial for DHF 3.x - Data Hub Framework" available here: https://marklogic.github.io/marklogic-data-hub/tutorial/3x/

As a workaround for now to get proper related views generated for SQL, I have used the following QC code to generate a model descriptor encompassing all entities available and generate a TDE template from it:

'use strict';
const es = require('/MarkLogic/entity-services/entity-services');
const ARTIFACT_DIR = '<dhf-project-root-dir>/src/main/ml-schemas/tde/';

let schemaName = "MarkLogic";
let desc = {info: {title: schemaName, version: "0.0.1"}, definitions: {}};
for (const model of cts.search(cts.collectionQuery('http://marklogic.com/entity-services/models'))) {
  let name = model.root.info.title;
  let entity = model.root.definitions[name];
  desc.definitions[name] = entity;
}
xdmp.save(
  ARTIFACT_DIR + schemaName + '.tdex',
  es.extractionTemplateGenerate( xdmp.toJSON(desc) )
);

And then any adjustment can be made to the template before deploying it.

**Comment by bsrikan** [comment]
This is fixed now in 4.x-develop and develop.

**Comment by aebadirad** [comment]
Fixed in version 4.2.0
