### ISSUE TITLE
Create .gitignore when initiating hub project

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic/marklogic-data-hub#1772]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:
.war and other files get committed into git

What behavior are you expecting?
.gitignore should be created in the root of the project with some common sense things like bin/ , *.war etc,

#### Tech details

Which Operating System are you using?

Which version of MarkLogic are you using?

Which version of the Data Hub Framework are you using?
4.1.1

Is this a QuickStart UI bug? If so, which browser are you using?
No

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by rjrudin** [comment]
Closing as OBE.
