### ISSUE TITLE
Unable to create any flow on QuickStart UI using Firefox

### ISSUE THREAD

**Issue by eouthwaite** [marklogic/marklogic-data-hub#1775]
Short description of the problem:

Following the steps in the [QuickStart tutorial](https://marklogic.github.io/marklogic-data-hub/tutorial/3x/create-product-input-flow/), I am unable to create a new input flow when using Firefox.

It works with Chrome.

#### Tech details

CentOS7 linux

Which version of MarkLogic are you using?

MarkLogic 9.0-7

Which version of the Data Hub Framework are you using?

QuickStart 4.1.1

Is this a QuickStart UI bug? If so, which browser are you using?

Firefox ESR 45.6.0

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

[myoutput.txt](https://github.com/marklogic/marklogic-data-hub/files/2783037/myoutput.txt)

Attached - though no errors shown.

Create Input Flow and Create Harmonize Flow do not create anything when clicking on the Create button after filling in the form.

**Comment by akshaysonvane** [comment]
Hi @eouthwaite, can you try upgrading the Firefox version. I was able to create and run an input flow using Firefox 60.4.0esr (64-bit)

**Comment by eouthwaite** [comment]
Thanks - having an out of date system was at fault
