### ISSUE TITLE
Documentation for scaffolding tasks should mention the need to deploy

### ISSUE THREAD

**Issue by netdance** [marklogic/marklogic-data-hub#1783]
Short description of the problem:

Documentation for scaffolding tasks doesn't mention that the code needs to be deployed before it takes effect.

What behavior are you expecting?

Many users expect that when you run a scaffolding task, such as `hubCreateEntity`, you can then immediately run hubCreateInputFlow.  You can't - `mlLoadModules` needs to be run in addition (or `mlWatch` needs to be run in another window).  This should be mentioned in the documentation.

**Comment by damonfeldman** [comment]
Documenting the sequence is an option, and presumably cheaper, but being able to actually do the two in sequence would be ideal.

**Comment by akshaysonvane** [comment]
Thanks for filing, @netdance 
Tracking it here https://project.marklogic.com/jira/browse/DHFPROD-1761
