### ISSUE TITLE
Example :Single Step Ingest has error on DHF 4.1.x

### ISSUE THREAD

**Issue by Chunyu01** [marklogic/marklogic-data-hub#1810]
I am trying to set up the above example by DHF4.1.1(4.1.0)  from https://github.com/marklogic/marklogic-data-hub/tree/995d1822dbfdb9299ea83eb9d40d45c8d2745707/examples/single-step-ingest.
However, I am having the following error.
 
2019-01-29 10:20:03.945 Notice: XDMP-AS: (err:XPTY0004) $options as map:map -- Invalid coercion: xs:untypedAtomic("&#10;    10&#10;    380140431212&#10;    Shirt&#10;    promising...") as map:map
2019-01-29 10:20:03.945 Notice:+in /data-hub/4/impl/flow-lib.xqy, at 268:14,
 
Can anyone help this please?

**Comment by ayuwono** [comment]
hi @Chunyu01 , we're tracking this issue on JIRA: https://project.marklogic.com/jira/browse/DHFPROD-1772

**Comment by aebadirad** [comment]
There might be a delta between what is there written by @mhuang-ml and some minor changes we made to error handling in 4.1.1

**Comment by mhuang-ml** [comment]
@aebadirad,

I just submitted a pull request to resolve the issue

**Comment by mhuang-ml** [comment]
Issue is resolved in the 4.x-develop branch

**Comment by aebadirad** [comment]
correct, feel free to pick it up https://github.com/marklogic/marklogic-data-hub/tree/4.x-develop/examples/single-step-ingest

Will be part of the master examples on next release
