### ISSUE TITLE
Ability to override uri for input flows

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#182]
Options:
- add a writer
- add another step for uri changing
- add a magical hub function that sets it

**Comment by miguelrgonzalez** [comment]
what about a forth option:
 - Using options map to change the URI

options map is already passed along all the different plugins and it's defined on the context of the mlcp transform. So:

     map:put($options, "uri" , "new-fancy-uri")

and at the run-flow.xqy transform we could simply:

     map:put($context, "uri", map:get($params, "uri"))

Not particulary clean since you could modify this on any of the plugins and not just in the "writer", but easy enough to implement.

**Comment by tzejohn** [comment]
What are the latest thoughts on this? I think I will need to move items to a different URI in staging to facilitate a harmonization customization flow operating out of the staging db. My thought right now is to use CPF to move the content, but if a writer was available to the input flows, then I could use that.

**Comment by paxtonhare** [comment]
My current thought on this is to just use a custom REST extension to do this.

**Comment by paxtonhare** [comment]
Closing this bad boy. Use a REST extension.

**Comment by tzejohn** [comment]
FWIW, I ended up using CPF create a new document after ingest, deleting the old one. This is so that the move is automatic after ingest. Via the REST extension route, I would create a new endpoint used to ingest the document, is that correct?

**Comment by paxtonhare** [comment]
correct

**Comment by theflyinggriffin** [comment]
Creating a REST extension does not help when you are trying to ingest using MLCP, this issue should be reopened and addressed so we can have full control over the URIs going into STAGING just like we do for harmonization flows going into FINAL.

**Comment by mikerosiak** [comment]
What about a "uri_transform" option on MLCP that calls a specific module with the generated URI and content (as would be passed to main.sjs) and returns the new URI ... which then gets passed to main.sjs?

**Comment by theflyinggriffin** [comment]
What is passed to main.sjs does not change the URI that the document is written to. We need to change `content.uri` at the end of the transform function, similar to the way the end of the transform assigns the envelope to `content.value` in [Line 70](https://github.com/marklogic/marklogic-data-hub/blob/c6de592a5d0913a24330a482acbe272d07497a88/marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/transforms/mlcp-flow-transform.sjs#L70)

**Comment by theflyinggriffin** [comment]
I agree that either MLCP passing the URI of a module that will supply the new document URI could work, Another option is to give a new file 1 for each input flow (or possibly optional, 0 or 1 per input flow) named Uri.sjs that is used for all hub transforms (if it exists). This way no matter how you run the flow (MLCP/NiFi/REST/etc.) the URI is generated the same way.

**Comment by aebadirad** [comment]
Data hub 5.0 allows this to happen for MLCP. Will need another enhancement once CallBatcher comes out for DMSDK to allow for renaming the URI - REST tier transforms do not allow for it for current gen DMSDK, but this is on the roadmap.

So closing this out as it pertains to MLCP only.
