### ISSUE TITLE
Harmonize Using the REST API, harmonize flow has error with 4.1x

### ISSUE THREAD

**Issue by Chunyu01** [marklogic/marklogic-data-hub#1824]
I am trying to run the follow rest call with my own case.
POST /v1/resources/ml:flow?rs:identifiers=someIdentifier&rs:entity-name=EntityName&rs:flow-name=FlowName&rs:target-database=Documents&rs:options={"some":"json"}&rs:job-id=SomeJobID

There is an error, 
XDMP-ASerr:XPTY00041.0-mlInvalid coercionXDMP-AS: (err:XPTY0004) $qtext as xs:string+ -- Invalid coercion: () as xs:string+false$qtext as xs:string+()xs:string+/entities/Project/harmonize/ProjectHarmonizeJson/content.xqy7221plugin:extract-instance-Project((),

Also I tried to run my own Rest endpoint to call harmonize flow and follow the example here.
marklogic-data-hub/marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/extensions/flow.xqy
I ran and debug the function in 'Post' from QC, it is working fine.
However, I try by Postman vie http://localhost:9011/v1/resources/create-project?rs:identifiers=Users/cwilson/projects/PMPA_Git/PMPA/pmi/source/datahub-framework-4/input/project/project-middle.json&rs:entity-name=Project&rs:flow-name=ProjectHarmonizeJson&rs:job-id=1234
There is an error same as above.

Can you help please?

**Comment by sbayatpur** [comment]
Added this Jira item to include this info in docs: https://project.marklogic.com/jira/browse/DHFPROD-1793
