### ISSUE TITLE
Parallel processing in Flow Runner is weak

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic/marklogic-data-hub#1825]
Parallel processing in `FlowRunnerImpl` is weak. 

First, the current `awaitCompletion` contains a bug. Why do I pass a `unit` when `MILLISECONDS`is used? 

    @Override
    public void awaitCompletion(long timeout, TimeUnit unit) throws InterruptedException {
        if (runningThread != null) {
            runningThread.join(unit.convert(timeout, TimeUnit.MILLISECONDS));
        }
    }

Second, if I call `awaitCompletion` with a time-out, I do not get any information that it has been timed out or not. So this implementation need to change to something like:

    public void awaitCompletion(long timeout, TimeUnit unit) throws InterruptedException {
        if (runningThread != null) {
            runningThread.join(unit.convert(timeout, TimeUnit.MILLISECONDS));
            if ( runningThread.getState() != Thread.State.TERMINATED) {
                queryBatcher.stop();
                runningThread.interrupt();
                throw new InterruptedException("Time-out occurred.");
            }
        }
    }

Third, the `runningThread` cannot be managed from outside such as an `ExecutorService` eg obtained in an managed form from  an Application Server.  BTW: This is also the case from the MarkLogic Java API ThreadPool used by the `QueryBatcherImpl`.

**Comment by aebadirad** [comment]
As of Data Hub 5, parallel processing is now blocked in flow runner and all tasks are serial in a blockingqueue. 

For parallel execution please either execute multiple flowrunners or, preferably, use an external orchestrator that is more in line with handling massive scale parallel orchestration such as NiFi, Kafka, Kinesis, etc.
