### ISSUE TITLE
FlowRunner has no Load Balancer support

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic/marklogic-data-hub#1826]
The `FlowRunnerImpl` has no support for turning off cluster load distribution. In case Load balancer is used, ports of individual nodes are closed from external hosts (e.g. where the flowrunner is running). 

**Workaround:**

- Copy `FlowRunnerImpl`
- Pass in a `DatabaseClient` via `withSourceClient`pointing to the Load balancer
- Add the method listed below.
- Call this method in `FlowRunnerImpl` just before the `startJob` , just after constructing and configuring the `QueryBatcher`

```
private void turnOffClusterLoadDistribution(QueryBatcher qb) {
    String loadBalancerHost = stagingClient.getHost();
    ForestConfiguration forestConfig = qb.getForestConfig();
    FilteredForestConfiguration filteredForestConfig = new FilteredForestConfiguration(
    		forestConfig).withWhiteList(loadBalancerHost);
    for (String preferredHost : forestConfig.getPreferredHosts()) {
    	filteredForestConfig.withRenamedHost(preferredHost, loadBalancerHost);
    } 
    qb.withForestConfig(filteredForestConfig);
}   
```

**Comment by rjrudin** [comment]
Fixed in DHF 5
