### ISSUE TITLE
Add Swagger for REST API endpoints

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#183]
This swagger will expose all the REST endpoints to enable a user to be able to quickly understand how to get data out of MarkLogic.

**Comment by plemanach** [comment]
Any news on this ?

**Comment by paxtonhare** [comment]
It's not currently a priority.

On Tue, Apr 11, 2017 at 7:53 AM, Patrice Le Manach <notifications@github.com

**Comment by popzip** [comment]
@clockworked247 is this done or just for internal use?

**Comment by rjrudin** [comment]
Closing this as we intend to move to Data Services.

**Comment by jmakeig** [comment]
…which will soon publish Swagger/Open API descriptions themselves.
