### ISSUE TITLE
Quickstart Upgrade instructions link is malformed

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#1835]
#### The issue

Short description of the problem:

When I run quickstart on a hub project that needs to be updated I get a message with a link for info on how to upgrade. That link leads me to http://localhost:8080/null instead of a legit location.

What behavior are you expecting?

a legit link location.

Quickstart 4.1.1

![image](https://user-images.githubusercontent.com/630382/52126092-5506b500-25fc-11e9-8666-280eda665e0f.png)

**Comment by aebadirad** [comment]
Fixed in version 4.2.0

**Comment by kkanthet** [comment]
https://project.marklogic.com/jira/browse/DHFPROD-1726
