### ISSUE TITLE
gradle hubUpdate task is missing a description

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#1836]
When I run `gradle tasks` I get a list of tasks. There is no description for hubUpdate.

![image](https://user-images.githubusercontent.com/630382/52126221-bc246980-25fc-11e9-8254-4b4a99889617.png)

I would like to see a description.

**Comment by rahulvudutala** [comment]
Thanks for filing @paxtonhare. We will address this.

**Comment by rjrudin** [comment]
Tracking via DHFPROD-7021
