### ISSUE TITLE
writer not invoked in an xquery harmonisation flow (4.1.1

### ISSUE THREAD

**Issue by joecrean** [marklogic/marklogic-data-hub#1837]
### Welcome Hub enthusiast!

see closed ticket #998 for the detail

I believe this is related to the ticket #1669

**Comment by joecrean** [comment]
DHF 4.1.1 / ML 9.0-6.1

**Comment by rahulvudutala** [comment]
Thanks, @joecrean for filing the issue.
We are looking into this. I will get back to you regarding the issue.

**Comment by joecrean** [comment]
Every flow is executed in `extensions/flow.xqy` that is the REST extension (`ml:flow`) that is invoked via java/gradle/etc. In function `post`  it invokes the flow for each identifier (collector uri) which queues the writer requests. Then it explicitly uses those identifiers to read out and execute the contents of the map using function `flow:run-writers`.. hence if in main we call `run-writer` with a different id then it will not be executed. An alternative would be to read the map with `map:keys` and execute all the requests in there.. the complication here is that we would need to somehow create the `context-map`.

**Comment by mikrovvelle** [comment]
This mechanism seems to be responsible for #1892 as well.

**Comment by aebadirad** [comment]
The resolution to this is now a part of Data Hub 5.0 where the URI can be modified on each content object before being written.
