### ISSUE TITLE
QuickStart - mlcp transform_param shows the wrong entity when defining input flow

### ISSUE THREAD

**Issue by dbaldry** [marklogic/marklogic-data-hub#1858]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:   
mlcp transform_param shows previous entity name when you create an input flow immediately after creating another flow. 

What behavior are you expecting?
transform_param should match the entity type 

#### Tech details

Which Operating System are you using?
Centos 7
Which version of MarkLogic are you using?
9.08
Which version of the Data Hub Framework are you using?
4.11
Is this a QuickStart UI bug? If so, which browser are you using?
Chrome and Firefox
#### The devil is in the details...
Create an input flow for an entity, and do 'save' and 'run' (as per the tutorial). Then, following the tutorial and without navigating to a different page, create a new flow for a different entity. The top of the page then shows "Run Input Flow - <NewEntity> : <New Name>" but the rest of the page shows values from the old flow. 
For example, the input file path points to the previous flow directory and the mlcp command has -transform_param "entity-name=<previousEntity>,flow-name=<PreviousFlow>".  The input file path can be changed using the GUI but the transform_param cannot be changed. 
At this point, if you save/run the flow you will create documents, but because the tramsform_param was not correct the mappings page doesn't enable you to create mappings because it says there is no source data for the entity. 
The work around is to navigate to another page, then back to the input flows page. After doing this the transform_param will match the entity and you will be able to save/run.

**Comment by clockworked247** [comment]
Thanks for filing @dbaldry .  This seems like a pretty straight forward bug to address.

**Comment by sbayatpur** [comment]
Added a corresponding bug for this issue in Jira: https://project.marklogic.com/jira/browse/DHFPROD-1824

**Comment by clockworked247** [comment]
Thanks @sbayatpur I didn't realize we added JIRA tickets in Github.  I'll do that going forward.

**Comment by clockworked247** [comment]
Fixed in 4.2.1
