### ISSUE TITLE
DH UI: Action Dropdown does not flow left

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#1862]
#### The issue

The _Action_ dropdown menu flows right off the screen.
![image](https://user-images.githubusercontent.com/1315891/52568391-a113df80-2ddc-11e9-8ce5-499884ccaac3.png)

#### Tech details

Which Operating System are you using?
Mac OS 10.14.3

Which version of MarkLogic are you using?
9.0-8

Which version of the Data Hub Framework are you using?
4.1.1

Is this a QuickStart UI bug? If so, which browser are you using?
Yes, Chrome 71.0.3578.98

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

Just a minor UI issue.

**Comment by rahulvudutala** [comment]
Thanks for filing @prestonmcgowan. We will address this issue.

**Comment by clockworked247** [comment]
Filed:  https://project.marklogic.com/jira/browse/DHFPROD-1881

**Comment by rjrudin** [comment]
Closing as OBE.
