### ISSUE TITLE
Display Version in the Quick Start UI

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#1863]
#### The feature enhancement

What version of the DHF am I running? Can the DHF UI display that info? 
Can it be added:

- on a hover over of "Data Hub Framework"
- on the Settings page
- someplace else that makes sense?

#### Tech details
Which version of the Data Hub Framework are you using?
4.1.1, because I had to drop to terminal.

**Comment by rahulvudutala** [comment]
Thanks for filing @prestonmcgowan. We will address this issue.

**Comment by clockworked247** [comment]
Filed enhancement request here:  https://project.marklogic.com/jira/browse/DHFPROD-1880

**Comment by aebadirad** [comment]
Shipping with 5.0.0
