### ISSUE TITLE
mlDeploySecurity - Error Msg and Incomplete Docs

### ISSUE THREAD

**Issue by wpaven** [marklogic/marklogic-data-hub#1876]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:

Using MarkLogic 9.0-8 and DHF 4.1 - Going through 4.x tutorial - get to step https://marklogic.github.io/marklogic-data-hub/tutorial/4x/secure-pii-in-customer-data/ and it errors out.  

There is no documentation on mlDeploySecurity anywhere afaict.  It's not listed in the docs for the DHF gradle tasks

https://marklogic.github.io/marklogic-data-hub/refs/gradle-tasks/

What behavior are you expecting?

To not see an error message. I don't know what I should expect as there's  nothing in the tutorial or documentation to inform me what success looks like.   I added my username and pwd to gradle.properties and ran the command again and it worked.  But
1) There's nothing in the docs to advise people to do this
2) Having completed this step, what behavior should the users expect to see?

#### Tech details

Which Operating System are you using? Windows 10

Which version of MarkLogic are you using?

Which version of the Data Hub Framework are you using?

Is this a QuickStart UI bug? If so, which browser are you using? Firefox

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by clockworked247** [comment]
Thanks @wpaven for filing.  If you open in Developer tools in your browser before the issue happens and you look at:

- the Network tab, do you see either the server request failing with an error?
or
- the Console tab, do you see an error logged in the browser console?

That'd help us better understand the issue.

**Comment by wpaven** [comment]
I just needed to add my credentials to gradle.properties.  That was the error. I'm sorted. 

The issue i've logged here I believe is one more of documentation as 1) I had to figure out to update gradle.properties on my own (nothing in the qs tutorial mentions this and others reading may get stuck) and 2) I have no idea what mlDeploySecurity did or how it would affect the search/query experience based on this tutorial.  

I'd like to know more what mlDeploySecurity does and what it's intended behavior is and I think a demonstration in the qs tutorial could be useful.

Hope this helps @clockworked247 !

**Comment by clockworked247** [comment]
@wpaven Ah, yes.  Understood.  This should be in the docs.

**Comment by clockworked247** [comment]
Filed: https://project.marklogic.com/jira/browse/DHFPROD-1882

**Comment by aebadirad** [comment]
This has been completed and should have been released with DHF 4.2
