### ISSUE TITLE
Unable to delete harmonize flow with the "trash" icon

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#1877]
#### The issue

I have created a harmonize flow and I would like to delete it. I have tried to create a second flow and delete it also, both situations throw a JavaScript console error.

`ERROR ReferenceError: "event is not defined"

    deleteFlow http://localhost:8080/main.d7fe3d0d097511da7835.js:1 qq http://localhost:8080/main.d7fe3d0d097511da7835.js:1 handleEvent http://localhost:8080/main.d7fe3d0d097511da7835.js:1 handleEvent http://localhost:8080/main.d7fe3d0d097511da7835.js:1 Ki http://localhost:8080/main.d7fe3d0d097511da7835.js:1 kr http://localhost:8080/main.d7fe3d0d097511da7835.js:1 Ec http://localhost:8080/main.d7fe3d0d097511da7835.js:1 invokeTask http://localhost:8080/polyfills.0d0fa29fd286a1f569ee.js:1 onInvokeTask http://localhost:8080/main.d7fe3d0d097511da7835.js:1 invokeTask http://localhost:8080/polyfills.0d0fa29fd286a1f569ee.js:1 runTask http://localhost:8080/polyfills.0d0fa29fd286a1f569ee.js:1 invokeTask http://localhost:8080/polyfills.0d0fa29fd286a1f569ee.js:1 m http://localhost:8080/polyfills.0d0fa29fd286a1f569ee.js:1 b http://localhost:8080/polyfills.0d0fa29fd286a1f569ee.js:1 

main.d7fe3d0d097511da7835.js:1:82791

    St http://localhost:8080/main.d7fe3d0d097511da7835.js:1 handleError http://localhost:8080/main.d7fe3d0d097511da7835.js:1 Ki http://localhost:8080/main.d7fe3d0d097511da7835.js:1 kr http://localhost:8080/main.d7fe3d0d097511da7835.js:1 Ec http://localhost:8080/main.d7fe3d0d097511da7835.js:1 invokeTask http://localhost:8080/polyfills.0d0fa29fd286a1f569ee.js:1 onInvokeTask http://localhost:8080/main.d7fe3d0d097511da7835.js:1 invokeTask http://localhost:8080/polyfills.0d0fa29fd286a1f569ee.js:1 runTask http://localhost:8080/polyfills.0d0fa29fd286a1f569ee.js:1 invokeTask http://localhost:8080/polyfills.0d0fa29fd286a1f569ee.js:1 m http://localhost:8080/polyfills.0d0fa29fd286a1f569ee.js:1 b http://localhost:8080/polyfills.0d0fa29fd286a1f569ee.js:1 `

#### Tech details

Which Operating System are you using?
Mac OS

Which version of MarkLogic are you using?
9.0-8
Which version of the Data Hub Framework are you using?
4.1.1
Is this a QuickStart UI bug? If so, which browser are you using?
Yes, FireFox 65.0
Chrome 71 shows the confirmation dialog FireFox fails to show. Chrome however fails with a HTTP 400.

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:
[myoutput-firefox.txt](https://github.com/marklogic/marklogic-data-hub/files/2866176/myoutput-firefox.txt)
[myoutput-chrome.txt](https://github.com/marklogic/marklogic-data-hub/files/2866177/myoutput-chrome.txt)

**Comment by clockworked247** [comment]
Hi @prestonmcgowan thanks for the thorough details.  We'll look into the problem.

**Comment by joecrean** [comment]
I see this too.

**Comment by clockworked247** [comment]
@prestonmcgowan @joecrean https://project.marklogic.com/jira/browse/DHFPROD-1879 has been filed.

**Comment by clockworked247** [comment]
Fixed in 4.2.1
