### ISSUE TITLE
Ticket Template Update

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#1878]
The ticket template below looks like this...

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

#### Newer Quick Start Naming
Old naming:
$ java -jar quickstart.war -d > myoutput.txt

New naming:
$ java -jar quick-start-4.1.1.war > myoutput.txt

.. if it matters :-)

**Comment by clockworked247** [comment]
Seems more clear.  Thanks @prestonmcgowan Will pass this on to whoever has the powah to update the "issue" template for this repo.  

@aebadirad trying you first, if someone else should take this, pass it along.  :)
