### ISSUE TITLE
Input Flow Output Collections not resetting

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#1879]
#### The issue

When creating multiple input flows, the initial precomputed output collections are used for all input flows. I expected each flow to receive its own set of precomputed output collection names.

Steps to reproduce:
1.  Create "foo" entity
2. Create "bar" entity
3. Create "Foo Flow" input flow. Notice the collections are Foo,FooFlow,input
4. Create "Bar Flow" input flow. Notice the collections are Foo,FooFlow,input
Expected Bar,BarFlow,input

Workaround:
Manage the names of the collections by hand and do not trust the defaults.
If the user goes out of the flow screen after each input flow is created and back in, the flow collections will be generated correctly.

#### Tech details

Which Operating System are you using?
Mac OS

Which version of MarkLogic are you using?
9.0-8

Which version of the Data Hub Framework are you using?
4.1.1

Is this a QuickStart UI bug? If so, which browser are you using?
Yes. Firefox 65 and Chrome 74

**Comment by aebadirad** [comment]
Likely related to #1858

**Comment by rahulvudutala** [comment]
Corresponding bug for this issue in Jira: https://project.marklogic.com/jira/browse/DHFPROD-1821

**Comment by clockworked247** [comment]
Fixed in 4.2.1
