### ISSUE TITLE
Restrict hosts when running a flow

### ISSUE THREAD

**Issue by ltnd** [marklogic/marklogic-data-hub#1890]
we are using spring batch with the JAVA dhf snippet code available on the website to launch the harmonize : 

```java
FlowRunner flowRunner = flowManager.newFlowRunner()
  .withFlow(harmonizeFlow)
  .withBatchSize(10)
  .withThreadCount(4)
  .withOptions(options)
  .withSourceClient(srcClient)
  .withDestinationDatabase(destDb)
  .onItemComplete((String jobId, String itemId) -> {
      // do something with this completed item
  })
  .onItemFailed((String jobId, String itemId) -> {
      // do something with this failed item
  });
```
This is using DMSDK which first get the servers where the app-server DB forests are located in order to balance the workload on these servers.
But I have a process requiring heavy compute and I have e-nodes on my cluster I would like to use. 
Is there a specific params to put in the JAVA command in order to do that or a gradle property to add ? 
I am using DHF 2.0.6.

**Comment by jmakeig** [comment]
I’m not sure what you’re asking here, @ltnd. Are you seeing an actual performance problem? If so, can you describe your cluster topology and the performance you’re actually seeing?

**Comment by ltnd** [comment]
I have a cluster with 5 servers, 3 having a forest for the staging DB and 2 without.
My harmonize process does a lot of sjs compute and I want to be as fast as possible and spread the workload on the 5 servers and not only the 3 having the staging forests.

**Comment by jmakeig** [comment]
@ltnd, have you measured that 3+2 will actually be faster for your workload versus all five nodes hosting data?

**Comment by ltnd** [comment]
@jmakeig, we can't put the data on the "+2". Only 3 of the 5 nodes can host the data of the db.
So it's more 3+2 versus 3 only

**Comment by gduplantier** [comment]
Is there a plan to enable the data-hub to use e-nodes? I didn't see a ticket and this is marked as a question.

**Comment by gduplantier** [comment]
@rjrudin Yes, configuring a white list in gradle properties would work as long as it can contain nodes without forests, such as e-nodes.

**Comment by rjrudin** [comment]
@gduplantier So something along the lines of (these are really Data Hub properties, not Gradle properties; Gradle just provides a way to set them) - you'd set one of them:

```
hubHostWhiteList=host1,host2,host3
hubHostBlackList=host1,host2,host3
```

Pinging @yasht2010 and @DavidGorbet and @srinathgit  about this enhancement.
