### ISSUE TITLE
Long text allows facet numbers to exceed their container

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#1891]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:
![image](https://user-images.githubusercontent.com/1315891/53025091-51619380-342e-11e9-99d4-d3e79aeaf2e2.png)

The count pill is outside it's container with long text.
#### Tech details

Which Operating System are you using?
Mac OS
Which version of MarkLogic are you using?
ML 9.0-8
Which version of the Data Hub Framework are you using?
4.1.1
Is this a QuickStart UI bug? If so, which browser are you using?
Yes. Chrome 74

**Comment by clockworked247** [comment]
Thanks @prestonmcgowan https://project.marklogic.com/jira/browse/DHFPROD-1878 has been filed.

**Comment by aebadirad** [comment]
Resolved by the 5.0.1 release.
