### ISSUE TITLE
Create New Mapping Dialog does not close

### ISSUE THREAD

**Issue by stevenbrockman** [marklogic/marklogic-data-hub#1907]
For the QuickStart application, when clicking the + icon to add a new mapping.  The create new mapping dialog comes up.  But if you want to cancel it, it does not close.

This happens to me in Firefox.  I see an "event is not defined" error when clicking the "Cancel" button.

Only workaround now is to refresh the page.

**Comment by stevenbrockman** [comment]
should add - this works in Chrome

**Comment by clockworked247** [comment]
Hi @stevenbrockman Can you provide a screenshot?   Thanks.

**Comment by stevenbrockman** [comment]
screenshot doesn't help much... but here it is.  Basically, the cancel event or the "X" button (top right) do not work, and the model cannot be dismissed.
![screen shot 2019-02-27 at 1 14 01 pm](https://user-images.githubusercontent.com/2230186/53512820-c289f200-3a91-11e9-98ba-fc6c4a94dc75.png)

**Comment by rjrudin** [comment]
Closing as OBE.
