### ISSUE TITLE
Performance tracing

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#193]
We need a perf trace of every action in both marklogic and tomcat. This will tell us how long each task is taking, how much of that time is in tomcat, how much in ml.

To do this we need elapsed-time logging every time we cross a boundary 
- from the browser to QuickStart
- from QuickStart to the code in the core DataHub libraries 
- from QuickStart or core DataHub code to MarkLogic

That is, every REST call and also every call between QuickStart and the hub library will be logged.

Possible tech for each area:
- QuickStart may be able to use some Spring interceptor or annotation to log all reqeusts.
- core Data Hub library
   - get System.currentTimeMillis() before and after the operation, and log the difference to compute elapsed time.
- MarkLogic
   - have a standard function to compute elapsed time and log. (See code below in a comment)

The point of this is that when something takes a long time (pushing code, running a flow, etc) we will know which portion took how much time and can optimize as needed.

**Comment by damonfeldman** [comment]
Here is code for a utility function to wrap XQuery code in some logging:
```
declare function perflog:logit($what-is-it, $x)
{
 let $before := xdmp:elapsed-time()
 let $resp := $x()
 let $time := xdmp:elapsed-time() - $before
 let $_ := xdmp:log($what-is-it || " took " || $time)
 return
  $resp
};
```

To call this, import the common module and invoke like so:
```
perflog:logit("my code that does something", function() {
  let $x := 5
  return "hello"
   (: your stuff here :)
 })
 ```

**Comment by maeisabelle** [comment]
Hi @damonfeldman and @paxtonhare,

I think we cannot get the elapsed time from the browser to QuickStart as one resides in the client side while the other resides in the server side (also we are not guaranteed that the timestamp in the client side is the same as the server side). I also think it will just complicate things if we add it. What we can get is the total elapsed time when a post/get request is triggered in the browser and the result is returned.

For getting the elapsed time for the quick start to the code in Datahub libraries, I'm thinking of using AOP in spring (as doing the logging manually will make the codes too coupled). I'm still figuring out how it can be done but I need to confirm first if I can assume that we will only support one user using the application. If yes, I can declare and use an instance variable in the LoggingService (the Aspect) to track the timestamp when the user first enters QuickStart then compute the difference when s/he enters the data hub core libraries. Knowing where the code is actually at will be done via the annotation  @Before with the execution of the package of QuickStart API controller and the Data hub core libraries. 

For the logging the elapsed time from Data Hub core libraries to MarkLogic, I'm still checking it out. I'm focusing first on the first use cases.

Let me know your thoughts.

**Comment by damonfeldman** [comment]
When you say client and server do you mean the browser and tomcat? If so, we can just report the time taken inside Tomcat. The browser has good tools to show times for requests and processing time, so we can rely on those tools in the browser.

I think you may be thinking of something more complex that I was originally thinking when you say "getting the elapsed time for the quick start to the code in Datahub libraries" if you mean moving times across the wire between components.

Logging elapsed time data using the "simplest possible thing that can possibly work" as they say should do. That way when something is slow we can dig through the logs and see what took the time. Then we can profile that one call or function. 

So Java code would just use log.info(....) or similar. MarkLogic code would use xdmp:log(....). In that approach we would not need to subtract out or access hub core times. Also no annotations or new services (and likely no aspects) would be needed that way, vastly simplifying things.

**Comment by damonfeldman** [comment]
That may be more confusing than I intended. I suggest the following approach:

- go to every MarkLogic Service (everywhere that there is some .xqy that handles an incoming request) and call it via per:logit() above. 
   - as noted above, these are all in rc/main/resources/ml-modules/(services|transforms)
- go to every core hub Java method called from QuickStart and add a simple bit of code
```
long start = System.getCurrentTimeMillis();
[all the other code here]
long end = System.getCurrentTimeMillis();
log.info("Time for foobarbaz task was: " + (end-start) + " ms");
```
- Put that same simple elapsed time logging code in all Tomcat/Springboot entry points (or do that by config if one is available)
