### ISSUE TITLE
During install, list the artifacts being created

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#194]
To help train the user about what is going on, and illustrate the benefit of the hub framework / tool for those who are already familiar with MarkLogic, list the steps, actions and config item creation happening in the GUI during install.

Also, in an early test with a performance problem, it was not clear that the install was working without this feedback.

Maybe something like:

Creating staging database (DataHub-STAGING)
Creating and assigning forests to staging database (DataHub-STAGING-f1)
Creating App Server for staging ingest (Staging-Appserver / port=8010)
...
-- Install Complete! --

**Comment by divino** [comment]
Instead of just showing "Installing the Data Hub into MarkLogic..." ... we will replace it with the messages you mentioned above as it happen. Kindly confirm if you agree.
