### ISSUE TITLE
addNode(Sequence()) when MLCP runs with more than one thread

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#1953]
#### The issue
I receive the following in the app server's ErrorLog when my Flows MLCP **thread count** and **batch size** are greater than one.
`2019-03-04 14:33:38.553 Info: Exception caught while transforming/foo-dat--67.xml: XDMP-ARGTYPE: addNode(Sequence()) -- arg1 is not of type Node
2019-03-04 14:33:38.560 Info: Exception caught while transforming/foo-bar--33.xml: XDMP-ARGTYPE: addNode(Sequence()) -- arg1 is not of type Node
2019-03-04 14:33:38.562 Info: Exception caught while transforming/foo-bar--19.xml: XDMP-ARGTYPE: addNode(Sequence()) -- arg1 is not of type Node`

If I set the **thread count** and **batch size** to one, the code succeeds.

MLCP settings
`mlcp.sh import -mode "local" -host "localhost" -port "8030" -username -password "*****" -input_file_path "/Users/pmcgowan/Projects/DHF Bugs/xpath null node/sampleData" -input_file_type "documents" -output_collections "Foo,Bar,input" -output_permissions "rest-reader,read,rest-writer,update" -output_uri_replace "/Users/pmcgowan/Projects/DHF Bugs/xpath null node/sampleData,''" -document_type "xml" -thread_count "1" -batch_size "1" -transform_module "/data-hub/4/transforms/mlcp-flow-transform.sjs" -transform_namespace "http://marklogic.com/data-hub/mlcp-flow-transform" -transform_param "entity-name=Foo,flow-name=Bar"`

../entities/Foo/input/Bar/content.sjs
```
'use strict'

/*
* Create Content Plugin
*
* @param id         - the identifier returned by the collector
* @param options    - an object containing options. Options are sent from Java
*
* @return - your content
*/
function createContent(id, rawContent, options) {

  return rawContent;
}

module.exports = {
  createContent: createContent
};
```

../entities/Foo/input/Bar/headers.sjs
```
/*
 * Create Headers Plugin
 *
 * @param id       - the identifier returned by the collector
 * @param content  - the output of your content plugin
 * @param options  - an object containing options. Options are sent from Java
 *
 * @return - an object of headers
 */
function createHeaders(id, content, options) {
  const eventNode = fn.head(content.xpath("//*[1]"));
  const blah = fn.head(eventNode.xpath("//some/path/text()"));
  return {};
}

module.exports = {
  createHeaders: createHeaders
};
```

The eventNode seems to be the issue.
Why is the experience different when the thread and batch size change?

#### Tech details

Which Operating System are you using?
Mac 

Which version of MarkLogic are you using?
9.0-8

Which version of the Data Hub Framework are you using?
4.1.1

Is this a QuickStart UI bug? If so, which browser are you using?
??

**Comment by prestonmcgowan** [comment]
I have seen the code return addNode(null) before too, I cannot unfortunately reproduce it at this time.

**Comment by clockworked247** [comment]
Thanks for filing.  Created corresponding Jira issue:  https://project.marklogic.com/jira/browse/DHFPROD-1942

**Comment by rjrudin** [comment]
Closing as OBE.
