### ISSUE TITLE
Refactor to Auto deploy code

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#197]
Rather than updating the UI every time a file changes we want to start automatically deploying code changes.

- Update the FileWatcher to automatically deploy user modules when a file changes.
- Remove all the code that updates the UI with file change status
- Clean up the UI js code that updates the Icon state.
- Basically, clean up the code as much as possible
- Keep the UI button to deploy modules. But change it to always deploy when pressed. This means we should clear out the timestamp file (there is a function for that) and then deploy.

_After discussion with Damon (see below) I'm adding a few extras_
- when running flows we must wait until any current load is finished. could be a thread wait. could be whatever. just so long as when I poke the run flow button it won't run until after deploy is finished.
- For the Deploy modules button, also make it clear out the modules first. This means we need an undeployUserModules() method

**Comment by damonfeldman** [comment]
I'd like to do some more design/discussion on this one before it starts. Some initial thoughts:

- we should clear the old modules from the modules db if someone hits the deploy button. REST services and other config as well.
- how do we synchronize deploying and running flows?
   - one option is to transactionally update modules via a long-running TX, but I don't know if ml-app-deployer supports that. Then a flow will run against a consistent code set.
- how will the user know if the code they just changed is deployed or not
   - this is to test the common cycle of coding and running a flow to test it
   - related but slightly different issue is clearing the DBs. For non-idempotent transforms such as merging data records or using a random URI generator you have to clear old data before re-running a flow.

**Comment by damonfeldman** [comment]
Discussed wit Paxton. Suggest delaying/retrying flow runs if a deploy is in progress. This could be using thread wait() logic, or as simple as a check for a static boolean with a sleep until the deploy is done.

**Comment by divino** [comment]
> we should clear the old modules from the modules db if someone hits the deploy button. REST services and other config as well.

Are we implementing this also? I think the optimized approached need not undeploy the old modules. The updated files will overwrite the new ones.

**Comment by paxtonhare** [comment]
We are clearing the old modules only if the user has pressed the deploy modules button. We are treating this button as a clear and load.

For autodeploy we should not clear modules.
