### ISSUE TITLE
Add ability to clear the Staging or Final database

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#198]
For non-idempotent transforms such as merging data records or using a random URI generator you have to clear old data before re-running a flow so you can see just your new data.

e.g. if the URI is created by
```    $id || "-" || xdmp:random() || ".xml" ```
then multiple runs will add multiple copies, so we want to clear data before re-running a flow.

This will support a typical code/run cycle where you change a plugin, save it, then immediately want to run it to see the new behavior, or new logging that was added.

**Comment by divino** [comment]
This can be solved using the following solutions:

1. quickest to implement and execute is by adding a collection which follow this pattern <entity-nmae>-<flow-type>-<flow-name> so with this we can just delete based on the name of the default collection.

2. we already have default collection but it is <entity-name>, <flow-type> and <flow-name>. We can delete all docs which are part of all three default collections. This will require us to check each file so slower, execution.

**Comment by damonfeldman** [comment]
I think backing out the result of one job is also useful, but here I'm thinking of deleting ALL docs, regardless of collections. Custom code and custom writers can insert anything, and may not have collections associated.

If the data set is large, a database clear operation is fastest (which is actually done by clearing each forest):
```
xdmp:forest-clear(xdmp:database-forests(xdmp:database("My Database")))
```

**Comment by damonfeldman** [comment]
some code to eval to the modules db so the flags can be stored there

declare namespace trace="http://marklogic.com/data-hub/trace";

for $i in 1 to 1000
return
xdmp:eval('
declare namespace trace="http://marklogic.com/data-hub/trace";

cts:element-values(xs:QName("trace:is-tracing-enabled"))
')

**Comment by jmakeig** [comment]
> Custom code and custom writers can insert anything, and may not have collections associated.

That is a worst practice. We shouldn’t bend over backwards to support someone flying collection-free.
