### ISSUE TITLE
DHF gradle tasks should report which commands they run in info mode

### ISSUE THREAD

**Issue by crism** [marklogic/marklogic-data-hub#2105]
#### The issue

Running ml-gradle tasks with `-i` indicates which command is run for each task:
```
> Task :mlDeployApp
...
Executing command [com.marklogic.appdeployer.command.security.DeployPrivilegesCommand] with sort order [5]
...
Executing command [com.marklogic.appdeployer.command.security.DeployRolesCommand] with sort order [10]
...
Executing command [com.marklogic.appdeployer.command.security.DeployUsersCommand] with sort order [15]
...
```
The DHF gradle tasks do not do this, however:
```
> Task :hubDeployUserModules
...
Initializing ExecutorService
Initializing ExecutorService
Writing 203 files
...
```
The DHF output should be consistent with other ml-gradle tasks. This would aid when debugging problems with specific tasks.

#### Tech details

Which Operating System are you using? CentOS 7.6.1810.

Which version of MarkLogic are you using? 9.0-8

Which version of the Data Hub Framework are you using? 4.1.1

Is this a QuickStart UI bug? No.

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

**Comment by rjrudin** [comment]
hubDeployUserModules is only running a single command, so I don't think there's much value here.
