### ISSUE TITLE
Document Unit Testing Data Hub Framework (DHF) Flow

### ISSUE THREAD

**Issue by joecrean** [marklogic/marklogic-data-hub#2125]
Add some documentation and examples for including tests in DHF

related to the following [ticket](https://github.com/marklogic-community/marklogic-unit-test/issues/65) over on ml unit test.

**Comment by aebadirad** [comment]
We now have an example of this: https://github.com/marklogic/marklogic-data-hub/tree/master/examples/dhf4-with-tests

While we need more documentation, of course, especially for 5.0, this should resolve the related ticket and we can open new issues for better capture.

**Comment by joecrean** [comment]
@aebadirad 
my example is xquery and actually ready - i just have not created the PR for it yet.. actually has been ready for ages but was too busy to complete the merge. I would also like to complete this because it is am MBO and I have done the work on it.. it is very similar to the example you mention but with xquery and some patterns and libs that I like to use

**Comment by aebadirad** [comment]
Then PR it my friend! And refer to this issue!

**Comment by joecrean** [comment]
@aebadirad 
I shall.. this week.. thanks!!

**Comment by jamesagardner** [comment]
Any updates on this?  I'm going to close out the associated tickets at https://github.com/marklogic-community/marklogic-unit-test/issues/65 and https://github.com/marklogic-community/marklogic-unit-test/issues/36.  They have several comments that apply to this issue.

**Comment by rjrudin** [comment]
This is being addressed for DHF 5 in the 5.5 release
