### ISSUE TITLE
Enhancement Request: DHF/ml-gradle should ignore "hidden" files

### ISSUE THREAD

**Issue by danielholgate** [marklogic/marklogic-data-hub#2133]
Working on a DHF 4.2.1 project recently I was getting an error running the mlDeploy task against a new ML database for a project I had previously successfully deployed:

`Error occurred while loading REST modules: Error occurred while loading modules; host: dev-ml1; port: 8004; cause: Local message: /config/query write failed: Method not allowed. Server Message: REST-UNSUPPORTEDMETHOD: (err:FOER0000) Endpoint does not support method: PUT`

After deleting the app server and checking the project etc, rerunning the task a few times and trouble shooting with the exact same results, I finally used the  -debug flag and discovered the error:  **Some .DS_Store files (I'm working on Mac) had been saved by the machine under ml-modules/options etc. and ml-gradle was trying to load these files into ML. The error was being thrown directly after this** 
Deleting the files got the project working again. 

I think an enhancement request for DHF or ML-GRADLE (which ever appropriate) should be to ignore "hidden" files in directories, i.e those starting with a "."  
The Mac put them there for some reason but it then caused problems which I think we could easily prevent and make our load process more robust

**Comment by danielholgate** [comment]
An additional request would be for better error messages here as the error being displayed was quite distant from the root cause

**Comment by rjrudin** [comment]
No change to DHF needed, I added this - https://github.com/marklogic-community/ml-javaclient-util/issues/108 

The request though for a better error message would need to go against the marklogic-client-api project.

**Comment by danielholgate** [comment]
Thanks @rjrudin

**Comment by rjrudin** [comment]
@danielholgate  @aebadirad Any concerns about ignoring anything that doesn't end in ".xml" or ".json"? I can't think of any reason why anyone would have an options file that doesn't end in one of those extensions, and I believe it's fine for DHF.

**Comment by danielholgate** [comment]
that seems logical to me - I can't think of any situation where anything but .xml or .json files would need to be picked up

**Comment by aebadirad** [comment]
DataHub 5.0 now targets specific files on its pull during an ingestion step: eg: .json for json, .csv/tsv/psv/txt for csv, etc. as of 5.0.1.
