### ISSUE TITLE
Mapping page, problems with Source selection

### ISSUE THREAD

**Issue by MJMoody** [marklogic/marklogic-data-hub#2154]
I am following the DHF 4.x Tutorial, and having trouble with the [Harmonize Product by Mappings](https://marklogic.github.io/marklogic-data-hub/tutorial/4x/harmonize-product-data-by-mappings/) part.

On my system, the Source URI selection does not display the URI. When I click the URI pencil icon, it actually does display the expected valid URI. However, clicking the green check box at that point, the URI disappears again.

And through all of this, I am unable to select any Source fields.

I am using DHF 4.2.2 and MarkLogic 9.0-9, and have tested on both Chrome and Firefox.

![image](https://user-images.githubusercontent.com/15005529/55529384-e4a80d00-56ec-11e9-8431-258b61373e60.png)

![image](https://user-images.githubusercontent.com/15005529/55529399-f8537380-56ec-11e9-8d17-5adc5dbaed9f.png)

![image](https://user-images.githubusercontent.com/15005529/55529407-01dcdb80-56ed-11e9-864c-e598faacda59.png)

**Comment by MJMoody** [comment]
I am following the DHF 4.x Tutorial, and having trouble with the [Harmonize Product by Mappings](https://marklogic.github.io/marklogic-data-hub/tutorial/4x/harmonize-product-data-by-mappings/) part.

On my system, the Source URI selection does not display the URI. When I click the URI pencil icon, it actually does display the expected valid URI. However, clicking the green check box at that point, the URI disappears again.

And through all of this, I am unable to select any Source fields.

I am using DHF 4.2.2 and MarkLogic 9.0-9, and have tested on both Chrome and Firefox.

![image](https://user-images.githubusercontent.com/15005529/55529384-e4a80d00-56ec-11e9-8431-258b61373e60.png)

![image](https://user-images.githubusercontent.com/15005529/55529399-f8537380-56ec-11e9-8d17-5adc5dbaed9f.png)

![image](https://user-images.githubusercontent.com/15005529/55529407-01dcdb80-56ed-11e9-864c-e598faacda59.png)

**Comment by MJMoody** [comment]
Looking in Chrome DevTools, I see a bunch of these errors...

![image](https://user-images.githubusercontent.com/15005529/55607862-ee06a780-57c8-11e9-8317-3ada325b2b4e.png)

**Comment by ryanjdew** [comment]
Thanks for reporting this. We'll investigate.

**Comment by ryanjdew** [comment]
Tracking with internal ticket https://project.marklogic.com/jira/browse/DHFPROD-2119

@MJMoody Can you check the Job page and please share the results of the ingest step when following the tutorial? Thanks!

**Comment by MJMoody** [comment]
Here you go...

![image](https://user-images.githubusercontent.com/15005529/55934077-d5880880-5c72-11e9-8b73-6f06b4c53db1.png)

![image](https://user-images.githubusercontent.com/15005529/55934102-ec2e5f80-5c72-11e9-9f3c-6f974f99f118.png)

**Comment by aebadirad** [comment]
Interesting, what's the document look like from the URI supplied in the mapping options? Can we confirm we get a response that looks like an ES document?

**Comment by MJMoody** [comment]
I've since upgraded to the latest version of DHF, which fundamentally changes the Mapping process.

Apologies, but I won't be testing this issue on the previous version.

Thank you.
