### ISSUE TITLE
Add logging for ClearDHFModulesCommand class

### ISSUE THREAD

**Issue by danielholgate** [marklogic/marklogic-data-hub#2165]
When the mlClearModules command fails, console logging says onle "Failed to clear user modules" with no further detail. 
This task should include a stack trace and also be more granular in the exceptions it catches
 
This is a big problem in DHS because the only way users can understand what is happening when pushing projects to DHS service is via the errors logged out of these tasks

marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java

**Comment by danielholgate** [comment]
Comment from @rjrudin was:

"Unfortunately the exception is being caught and logged but without a stacktrace"

    catch (FailedRequestException e) {
                logger.error("Failed to clear user modules");
            }
And there's a lot of stuff that happens in the "try" block

**Comment by brucean52** [comment]
Internal JIRA ticket has been created to track this. https://project.marklogic.com/jira/browse/DHFPROD-2134

**Comment by rjrudin** [comment]
Closing as OBE; this command has been removed and ml-gradle's capability is used instead.
