### ISSUE TITLE
Cannot delete schemas from Final and Staging with OOTB mlDeleteUserSchemas

### ISSUE THREAD

**Issue by kosed** [marklogic/marklogic-data-hub#2186]
#### The issue

mlDeleteUserSchemas (and therefore mlReloadSchemas) just deletes schemas in final but not in staging. @rjrudin provided a tip : You can create another instance of mlDeleteUserSchemas in build.gradle and override the "database" property.

This helps but it should be natural to have a way to do that out of the box.

In 
#### Tech details
Which version of the Data Hub Framework are you using?
4.1.1

**Comment by kkanthet** [comment]
this will be anew enhancement  to override default mlgradle task, tracking it through internal jira ticket
https://project.marklogic.com/jira/browse/DHFPROD-2167

**Comment by rjrudin** [comment]
Tracking internally now via DHFPROD-7020. Will likely add a new task - e.g. hubClearUserSchemas - instead of trying to modify ml-gradle.
