### ISSUE TITLE
Can the "plugins" folder be parametirized (currently hardcoded in source) ?

### ISSUE THREAD

**Issue by kosed** [marklogic/marklogic-data-hub#2187]
We already have mlConfigPaths and mlModulePaths that are provided by ml-gradle.
The plugins folder certainly holds the most important files when it come to DHF so it feels natural to me to also have it configurable.

This will allow multiple team collaborates on the same DHF "base" project while each still keeping some level of control over their actual source (like different access permissions).
Or simply, allow relocation of the folder for X and Y reasons.

#### Tech details
Which version of the Data Hub Framework are you using?
4.1.1 but still the same in master as of this ticket's creation.

**Comment by kkanthet** [comment]
Will file an enhancement request in internal Jira to track this https://project.marklogic.com/jira/browse/DHFPROD-2165

**Comment by aebadirad** [comment]
Sorry. Not happening for 4.x plugins. This is not the intended design. Multiple teams can use git or svn protections if they aren't manage to not step on each other's toes.

A datahub is a single project. If the end user can't be trusted to protect their source code, I'm not sure what to say here. 5.0 we're dropping the idea of plugins, but will still have shared directories of information - trying to 'split up' a project for 'access' is the wrong way to go about it currently. A data hub is holistic.
