### ISSUE TITLE
Token replacement does not work for the plugins folder

### ISSUE THREAD

**Issue by kosed** [marklogic/marklogic-data-hub#2188]
#### The issue

[Module's token replacement](https://github.com/marklogic-community/ml-gradle/wiki/How-modules-are-loaded) does work for "ml-modules" folder (or as configured with mlModulePaths) but not for the "plugins" folder.

#### Tech details

Which version of the Data Hub Framework are you using?
4.1.1

**Comment by kkanthet** [comment]
Filed Internal jira ticket to track this bug https://project.marklogic.com/jira/projects/DHFPROD/issues/DHFPROD-2166

**Comment by aebadirad** [comment]
Sorry, this won't be fixed. We're dropping the idea of a plugins folder for 5.0 and only keeping it for legacy support. 


/plugins is protected and there can only be one, in the root of the project structure for 4.x
