### ISSUE TITLE
Flow descriptor files do not get permissions set in mlModulePermissions property

### ISSUE THREAD

**Issue by kosed** [marklogic/marklogic-data-hub#2190]
#### The issue

Flow descriptor files:
- /entities/*/input/*/*.xml
- /entities/*/harmonize/*/*.xml

do not get the permissions set with the mlModulePermissions property. They just get rest-reader/writer permissions which are "borderline" roles (being kind here) to use in a production environment, even more so if it is a shared one.
Arguably, they are not "modules" but the problem is that, once your actual users don't inherit from rest-reader/writer, the flows will no longer run

One workaround is to extend the mlLoadModules task in order to have those permissions set after modules are loaded.

#### Tech details
Which version of the Data Hub Framework are you using?
4.1.1

**Comment by kkanthet** [comment]
tracking this through internal ticket https://project.marklogic.com/jira/browse/DHFPROD-2169

**Comment by kkanthet** [comment]
Will not be Fixed in 4.x , Please re-open if this is still an issue in 5.4.0
