### ISSUE TITLE
Separate getting values from the rest of plugins (perhaps)

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#221]
It will be helpful in some ways to first get a set or map of values from inputs, and then format those into content, headers, triples or similar.

This may serve two purposes
- allow us to control debug/logging of the vars (have a var list that is "logged" to the traces, or conditions such as empty required vals that trigger tracing)
- align us with Entity Services in ML 9 where all fields in an "Entity" are first extracted to a map:map and then that map is used to build the envelope/final data.

**Comment by popzip** [comment]
@aebadirad how does 5.0 design align to this?

**Comment by aebadirad** [comment]
Closing out old issue that no longer applies to the latest major release. Latest version allows for universal access to all data objects and on-demand query capability within each step.
