### ISSUE TITLE
Loading GlobalCorp dataset results in deadlocks

### ISSUE THREAD

**Issue by aajacobs** [marklogic/marklogic-data-hub#225]
I also tried unloading and reloading the datahub, including deleting the config files that had been created with the same results.  I'm on ML 8.0-4.2.

<img width="1118" alt="screen shot 2016-05-02 at 3 55 16 pm" src="https://cloud.githubusercontent.com/assets/8723378/14965984/55d18cbc-107e-11e6-9794-5055f32016cc.png">

**Comment by paxtonhare** [comment]
did you check the "Generate URI" option in the Delimited text section?

**Comment by aajacobs** [comment]
Yes, I did. But strangely, running the generated mlcp command manually worked.

Sent from my iPhone

On May 3, 2016, at 3:32 PM, Paxton Hare <notifications@github.com<mailto:notifications@github.com>> wrote:


did you check the "Generate URI" option in the Delimited text section?

**Comment by paxtonhare** [comment]
Ah it's a bug in beta 4. Try the new beta 5 release.

Be sure to uninstall the hub from MarkLogic vi QuickStart before replacing
the jar.

**Comment by paxtonhare** [comment]
@aajacobs did updating fix this for you? If so I'll close this issue.
