### ISSUE TITLE
Unable to create Input Flow using gradlew hubCreateInputFlow

### ISSUE THREAD

**Issue by yosukew** [marklogic/marklogic-data-hub#2333]
Short description of the problem:

Following the steps in the hubCreateInputFlow in [Gradle Tasks in DHF](https://marklogic.github.io/marklogic-data-hub/refs/gradle-tasks/), I am unable to create the Input Flow.

What behavior are you expecting?

When I executed "gradlew hubCreateInputFlow", it will be succeeded with the following message.

BUILD SUCCESSFUL

#### Tech details

Which Operating System are you using?
CentOS7.4

Which version of MarkLogic are you using?
MarkLogic 9.0-8

Which version of the Data Hub Framework are you using?
'com.marklogic.ml-data-hub' version '4.3.1'

#### The devil is in the details...
* Reproduction procedure
1. execute "gradlew hubCreateEntity -PentityName=testEntity".
2. execute "gradlew hubCreateInputFlow -PentityName=testEntity -PflowName=testInputFlow -PdataFormat=json -PpluginFormat=sjs"

The Attached file is the result of executing step2 with --info option.

[output.txt](https://github.com/marklogic/marklogic-data-hub/files/3105564/output.txt)

**Comment by brucean52** [comment]
Internal JIRA ticket has been created for this issue. https://project.marklogic.com/jira/browse/DHFPROD-2319

**Comment by rahulvudutala** [comment]
@yosukew please run ./gradlew hubDeployUserArtifacts before creating an input flow ( before step2). The hubCreateInputFlow task expects the entity created to exist in your staging database.

**Comment by yosukew** [comment]
@rahulvudutala
Thank you very much for your answer. Before step2, I executed ./gradlew hubDeployUserArtifacts, and I succeeded.

**Comment by aebadirad** [comment]
Thank you very much @yosukew we'll make sure to update documentation in the future to make this easier to follow.

Thanks!
