### ISSUE TITLE
"Deploy to MarkLogic Data Hub Service" documentation: JOBS port

### ISSUE THREAD

**Issue by danielholgate** [marklogic/marklogic-data-hub#2335]
The documentation for deploying DHF to DHS ( https://marklogic.github.io/marklogic-data-hub/deploy/deploy-to-dhs/  )lists ports which no longer seem to be correct.

The page currently says under "Deploying a DHF Project to DHS" that the jobs port in DHS is 8007

```
App server | DHF | DHS* | DHS load balancers
staging | 8010 | 8006 | curation
final | 8011 | 8004 | operations
jobs | 8013 | **8007** | analytics

```
however the DHS documentation here https://cloudservices.marklogic.com/help?type=datahub&subtype=admin#different

say that the DHS JOBS endpoint is **8013**

**Comment by brucean52** [comment]
We have an internal JIRA ticket to update the deploy to DHS documentation.

https://project.marklogic.com/jira/browse/DHFPROD-2307

**Comment by aebadirad** [comment]
This has been completed.
