### ISSUE TITLE
content "sometimes" is fired twice for the same ID returned by collector

### ISSUE THREAD

**Issue by walaszcm** [marklogic/marklogic-data-hub#2354]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:
he behavior is following:
collector returns unique ids
content "sometimes"(it happen few times in different flows)  is fired twice for the same ID (from the same batch). 
We checked access logs one by one but POST call is one 
No errors also in the error log for app server.
Have someone reported similar issue?

What behavior are you expecting?
I am expecting content is fire only once for the same ID
#### Tech details

Which Operating System are you using?
LINUX
Which version of MarkLogic are you using?
ML 9.0.4 and 9.0-8.2
Which version of the Data Hub Framework are you using?
version '2.0.4'

**Comment by brucean52** [comment]
@walaszcm You are using an outdated version of the Data Hub. Is it possible to upgrade your Data Hub version to the latest version?

**Comment by walaszcm** [comment]
Yes we deliver big project for Roche company and we are almost on the end(last sprint)
Updating it to newest version would it be required code changes?
Can you advise if this was bug reported in 2.0.4 and was fixed in later versions?

**Comment by brucean52** [comment]
@aebadirad Could you take a look at this?

**Comment by aebadirad** [comment]
2.0.4 is before the productization, and I don't know what their content looks like to be able to determine why they're doubling up on their URIs. 

@walaszcm if the customer has a support contract with MarkLogic, please raise it through there, as 2.x is no longer maintained outside support cases. It'd also help to have the project and some sample data.

**Comment by aebadirad** [comment]
Since this has been dormant, and we've released Data Hub 5.0, going to close the issue and request that support handle this if there's a support contract just due to the fact we can't go back 3 versions to fix a publicly unsupported version that doesn't have a commercial support contract.
