### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by datapromike** [marklogic/marklogic-data-hub#2355]
https://marklogic.github.io/marklogic-data-hub/deploy/deploy-to-dhs/ says that port 8007 is used for Analytics.

https://cloudservices.marklogic.com/help?type=datahub&subtype=admin#endpoints says that 8008 is used for Analytics.  I think the github information is outdated.

**Comment by brucean52** [comment]
We have an internal JIRA ticket to update the deploy to DHS documentation. 

https://project.marklogic.com/jira/browse/DHFPROD-2307

**Comment by aebadirad** [comment]
This was completed.
