### ISSUE TITLE
mlNewUser creates user under hub-internal-config

### ISSUE THREAD

**Issue by dmcassel** [marklogic/marklogic-data-hub#2398]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem: I ran `./gradlew mlNewUser` and the JSON file was created under src/main/hub-internal-config/security/users. 

What behavior are you expecting?
I expected the file to be created under src/main/ml-config/security/users. 

#### Tech details

Which Operating System are you using?
Windows 10

Which version of MarkLogic are you using?
9.0-9.1

Which version of the Data Hub Framework are you using?
4.3.1

Is this a QuickStart UI bug? If so, which browser are you using?
No

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

[output.zip](https://github.com/marklogic/marklogic-data-hub/files/3137874/output.zip)

**Comment by rjrudin** [comment]
This isn't a DHF issue, as DHF has the config paths in the correct order. I'll open an ml-gradle ticket for using the last config dir.
