### ISSUE TITLE
Unable to run the harmonize flows

### ISSUE THREAD

**Issue by robpml** [marklogic/marklogic-data-hub#242]
having completed steps 1-9, I've changed the various data flow files as directed, but the 'run' and 'test' buttons are not selectable so I am unable to execute the harmonize flows

Chrome browser / OSX / ML 8.0-5.5

**Comment by paxtonhare** [comment]
Did you press the deploy button at the top? Modules need to be deployed to
the server befor you can run a flow.

**Comment by robpml** [comment]
yes that was it - I was being overly cautious as the docs didn't explicitly say to deploy (only in previous step 6)
