### ISSUE TITLE
Consider query expansion using an ontology (or a thesaurus)

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#245]
This task is to consider whether it is useful and worthwhile to add explicit support for ontology-based query expansion. It should be possible to code that feature by hand now using the hub with an ontology ingest flow and use of the ontology in a REST query service, but perhaps is should be easier still.

**Comment by popzip** [comment]
I'm not sure this is the right place for this request in today's architecture. Perhaps could still be valid but maybe in the context of: Data Services/endpoint capability, Entity Explorer...i'll add a label for future reference of the idea and close as not actionable for now. Feel free to re-open.
