### ISSUE TITLE
Missing code samples on the DHF4 tutorial

### ISSUE THREAD

**Issue by aajacobs** [marklogic/marklogic-data-hub#2450]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:  Missing code samples on the DHF4 tutorial

What behavior are you expecting?  Code samples to be there

#### Tech details

On the page https://marklogic.github.io/marklogic-data-hub/tutorial/4x/harmonize-order-data-by-custom-code/ anywhere it says "Replace the collector plugin code with the following:" the actual links go to the develop branch, but the code has been moved to the master branch, so the code doesn't render at all.  As a result, people can't complete the tutorial. 

This needs a long-term fix that will continue to show the code even as what's in master is moved to a different branch.

**Comment by aebadirad** [comment]
@eltesoro-ml need to change the link to the code to 4.x-develop

**Comment by aebadirad** [comment]
Fixed in 5.0.1

**Comment by eltesoro-ml** [comment]
Reopening because the link in the documentation still points to the old location. Fixing now.

**Comment by eltesoro-ml** [comment]
Fixed, pending [PR #2684](https://github.com/marklogic/marklogic-data-hub/pull/2684).
