### ISSUE TITLE
Mapper doesn't refresh sample URI when saved URI is invalid

### ISSUE THREAD

**Issue by aajacobs** [marklogic/marklogic-data-hub#2483]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:  
If the data in the staging DB is deleted, the previously instantiated mapper points to a now invalid URI.  

What behavior are you expecting?  
Since the selection of the sample URI is done automatically, have the mapper automatically choose a valid URI if the saved one is invalid.  Or if there is resistance to that idea in case the user has specified an invalid URI, you could prompt to ask if they want to select a valid one.

Also, an error that the URI is no longer valid does pop up but it does so when loading the flow (not the step), so it's unclear what that error is actually pointing to (see screenshot below that shows the error while looking at the ingest step).  The error should ideally show on the mapping page and ideally guide the user to fix it.

![image](https://user-images.githubusercontent.com/8723378/57531715-10c83680-7308-11e9-9bf2-740c8b394856.png)

#### Tech details

Which Operating System are you using?  CentOS

Which version of MarkLogic are you using?  9.0-9.1

Which version of the Data Hub Framework are you using? 5.0-rc1

Is this a QuickStart UI bug? If so, which browser are you using?  Chrome

**Comment by ayuwono** [comment]
Issue with UUID as the ingested doc is CSV:
https://project.marklogic.com/jira/browse/DHFPROD-2515

**Comment by kkanthet** [comment]
Issue Fixed in 5.1.0 release
