### ISSUE TITLE
Would like more control over URIs and loading CSV in DHF5

### ISSUE THREAD

**Issue by smazerml** [marklogic/marklogic-data-hub#2490]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:
What behavior are you expecting?
Enhancement request for DHF 5. 

I would like similar control features on the DMSDK-based ingest flows as MLCP. For example, I have a CSV and would like to set part of the URI path to the first column in my CSV. Using MLCP, it would be using delimited_text and uri_id. Additionally, documentation on all currently available ingest flow options settings and how they might correlate to known MLCP switches would be great.

#### Tech details

Which Operating System are you using?
MacOS
Which version of MarkLogic are you using?
ML 9.0-7
Which version of the Data Hub Framework are you using?
DHF5-RC1
Is this a QuickStart UI bug? If so, which browser are you using?
no
#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by ayuwono** [comment]
Thanks @smazerml, we had this issue on JIRA: https://project.marklogic.com/jira/browse/DHFPROD-2327

**Comment by aebadirad** [comment]
Currently, the interim workaround until we can get these added in is to use MLCP to hit the endpoint and then run the rest of the steps.

**Comment by rjrudin** [comment]
Closing, as this is being tracked internally.
