### ISSUE TITLE
DHF 5.0.0: Jobs throws 500

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#2493]
#### The issue
While running a flow, if I select the Jobs tab or if I navigate from the Flows tab by clicking the "running" link, the Jobs network call throws a 500 http error.

What behavior are you expecting?
I did not expect a 500.

#### Tech details

Which Operating System are you using?
MacOS 10.14.4 (18E226)

Which version of MarkLogic are you using?
9.0-9

Which version of the Data Hub Framework are you using?
5.0.0

Is this a QuickStart UI bug? If so, which browser are you using?
I don't think so

Adding HAR output for the network calls and a GIF of the issue

[BUG - jobs not loading_8053_ErrorLog.txt](https://github.com/marklogic/marklogic-data-hub/files/3174192/BUG.-.jobs.not.loading_8053_ErrorLog.txt)

[BUG - jobs not loading.har.txt](https://github.com/marklogic/marklogic-data-hub/files/3174193/BUG.-.jobs.not.loading.har.txt)

![BUG - jobs not loading](https://user-images.githubusercontent.com/1315891/57643445-c0f7a280-7587-11e9-9667-3372b6df7d7a.gif)

**Comment by ayuwono** [comment]
Tracking on JIRA: https://project.marklogic.com/jira/browse/DHFPROD-2523

**Comment by ayuwono** [comment]
Fixed on 5.0.1
