### ISSUE TITLE
DHF 5.0.0: Cannot select file to process

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#2494]
#### The issue
I want to select the file to process. Click the file does not indicate it has been selected.
Is the directory the only thing selected?

I expected to be able to select which file to process.

#### Tech details

Which Operating System are you using?
Mac 10.14.4 (18E226)

Which version of MarkLogic are you using?
9.0-9

Which version of the Data Hub Framework are you using?
5.0.0

Is this a QuickStart UI bug? If so, which browser are you using?
Likely is a QuickStart UI bug of UX expectation failure.

![BUG - cannot select file](https://user-images.githubusercontent.com/1315891/57643652-39f6fa00-7588-11e9-86d6-787a5977d8ac.gif)

**Comment by srinathgit** [comment]
The ingestion page is designed to select the directories and not files.

**Comment by ayuwono** [comment]
I think this is a UX labelling bug, as it should only select a folder. The label should say "Source Folder Path"

**Comment by ayuwono** [comment]
Thanks @prestonmcgowan , tracking this issue on JIRA: https://project.marklogic.com/jira/browse/DHFPROD-2522

**Comment by ayuwono** [comment]
Fixed in 5.0.1
