### ISSUE TITLE
DHF 5.0.0: Confusing Flow UI Status

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#2495]
#### The issue

I am not sure from the UI if something is running or not.
![image](https://user-images.githubusercontent.com/1315891/57644135-7545f880-7589-11e9-9e7d-c06ec2ee397a.png)

#### Tech details

Which Operating System are you using?
Mac 10.14.4 (18E226)

Which version of MarkLogic are you using?
9.0-9

Which version of the Data Hub Framework are you using?
5.0.0

Is this a QuickStart UI bug? If so, which browser are you using?
Likely

**Comment by prestonmcgowan** [comment]
Stop, Running, Ended
Stop button with Running status text makes sense.
What is "Ended" doing there?

**Comment by brucean52** [comment]
I think this is fixed on the latest develop branch.

**Comment by ayuwono** [comment]
Fixed in 5.0.1
