### ISSUE TITLE
DHF 5.0.0: Enforce URI prefixes that will not fail es.modelValidate()

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#2498]
#### The issue
Based on ticket 2496, the QuickStart UI allows me to enter a base URI that will not pass es.modelValidate(). If the DHF should allow for a no-code or low-code, this use case should not be encountered. The user should not have to jump to QConsole for a basic error.

`The reason why a valid 'targetEntityType' is not getting set in the mapping is because the entity is not a valid ES model. If you run es.modelValidate() on the entity you provided`

#### Tech details

Which Operating System are you using?
MacOS 10.14.4 (18E226)

Which version of MarkLogic are you using?
9.0-9

Which version of the Data Hub Framework are you using?
5.0.0

Is this a QuickStart UI bug? If so, which browser are you using?
Backend expectation that is not presented in the UI.

**Comment by brucean52** [comment]
JIRA ticket: https://project.marklogic.com/jira/browse/DHFPROD-2534

**Comment by kkanthet** [comment]
Done as part of 5.0.2 release.
