### ISSUE TITLE
QuickStart App data not loaded to correct collection

### ISSUE THREAD

**Issue by nizdobs** [marklogic/marklogic-data-hub#250]
When loading globalTech data in the QuickStart App the mlcp that the sample app creates to load the global corp data is: 
mlcp.bat -host localhost -port 8010 -username sbodzin -password ***** -import -mode local -input_file_path C:\Users\sbodzin\Dropbox\MarkLogic\DemoScripts\DataHub\marklogic-data-hub\input\GlobalCorp -output_uri_replace "C:\Users\sbodzin\Dropbox\MarkLogic\DemoScripts\DataHub\marklogic-data-hub\input\GlobalCorp,''" -input_file_type "delimited_text" **_-output_collections "Employee,input-global-flow,input"_** -output_permissions "rest-reader,read,rest-writer,update" -document_type "json" -generate_uri true -transform_module "/com.marklogic.hub/mlcp-flow-transform.xqy" -transform_namespace "http://marklogic.com/data-hub/mlcp-flow-transform" -transform_param "<params><entity-name>Employee</entity-name><flow-name>input-global-flow</flow-name><flow-type>input</flow-type></params>"

But the globalTech harmonize collector has the following line:
for (var x of fn.collection('**load-global-corp**')) {

The globalCorp data was not loaded to the load-global-corp collection so the collector doesn't actually apply to any documents

**Comment by nizdobs** [comment]
Last line of bug report should instead read
The globalCorp data was not loaded to the load-global-corp collection so the collector doesn't actually apply to any documents

**Comment by paxtonhare** [comment]
@nizdobs and I discussed this. It's a documentation issue. He was following along with the tutorial but deviated by using his own flow names. The tutorial should indicate that the names are important if you use the code as-is.

**Comment by paxtonhare** [comment]
I fixed the documentation to warn the user.
