### ISSUE TITLE
DHF 5.0: Minor UI missing space in the toolbar

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#2501]
#### The issue

All of the items in the toolbar have a space in front of them, except "Jobs".
![image](https://user-images.githubusercontent.com/1315891/57663181-e8b72c80-75c0-11e9-8a05-74687aaafb16.png)

![image](https://user-images.githubusercontent.com/1315891/57663193-f8367580-75c0-11e9-9b6a-b21772a4197d.png)

#### Tech details

Which version of the Data Hub Framework are you using?
5.0.0

Is this a QuickStart UI bug? If so, which browser are you using?
Yes. Very minor

**Comment by ayuwono** [comment]
Nice catch

**Comment by ayuwono** [comment]
https://project.marklogic.com/jira/browse/DHFPROD-2527

**Comment by ayuwono** [comment]
Fixed in 5.0.1
