### ISSUE TITLE
DHF 5.0.0: No Merge Strategies

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#2502]
#### The issue
No merge strategies are in the dropdown.

![image](https://user-images.githubusercontent.com/1315891/57663812-87dd2380-75c3-11e9-8936-1f895ea8cee8.png)

#### Tech details

Which version of MarkLogic are you using?
9.0-9

Which version of the Data Hub Framework are you using?
5.0.0

Is this a QuickStart UI bug? If so, which browser are you using?
Maybe?

**Comment by prestonmcgowan** [comment]
I had to create the merge strategy in the next section, Merge Strategies.

Maybe, if none exist, the UI should say none created?

Otherwise, this can be closed.

**Comment by ayuwono** [comment]
Tracking this here: https://project.marklogic.com/jira/browse/DHFPROD-2528

It's a good UX improvement

**Comment by aebadirad** [comment]
Fixed in 5.0.1
