### ISSUE TITLE
Unable to customize ingestion step

### ISSUE THREAD

**Issue by freeweel** [marklogic/marklogic-data-hub#2506]
#### The issue

An input flow with a custom ingestion step continues to run the "built-in" ingestion instead of the custom one.

What behavior are you expecting?
I expect it to run the method pointed to by modulePath in the step description instead of the built-in ingestion method.

Which Operating System are you using? Windows 10 Pro

Which version of MarkLogic are you using? 9.0-7

Which version of the Data Hub Framework are you using?  5.0.0

Is this a QuickStart UI bug? If so, which browser are you using? Chrome, but its not a UI issue

#### The devil is in the details...

Here are the steps I did:
1. Created custom step of type ingestion using ml-gradle as follows:
gradlew hubCreateStepDefinition -PstepDefName=Load_XML_Docs -PstepDefType=ingestion

2. Added customizations and a console.log statement to the SJS file at:
\src\main\ml-modules\root\custom-modules\ingestion\Load_XML_Docs\main.sjs

3. Added Load_XML_Docs step to the Load_XML flow

4. Ran gradlew mlLoadModules to upload the custom script

5. Verified that module got uploaded to the appropriate path in t he modules DB using Query console

6. Checked Step in QuickStart UI and Load_XML.flow.json to verify custom step was included
(see attachment)
[Load_XML.flow.json.zip](https://github.com/marklogic/marklogic-data-hub/files/3178835/Load_XML.flow.json.zip)

7. Went into modules DB and edited in Query console to add a console.log statement to built-in code at:
/data-hub/5/builtins/steps/ingestion/default/main.sjs

8. Ran flow

The customizations that I added did not get run, and my error log at 8110_ErrorLog.txt shows the logging statement that I added to the built-in step and it does not show the console.log for the custom step pointed to by the modulePath in the flow description

Log statement.
2019-05-14 10:05:38.675 Info: Running built-in ingestion...

This leads me to conclude that it is running the built-in ingestion code and ignoring the main.sjs pointed to in the modulePath.

**Comment by brucean52** [comment]
Ingestion steps will only use the default-ingestion configuration. Please try creating a Custom step for custom ingestion.

**Comment by freeweel** [comment]
If that's the case, then I have a couple  of questions:

Why is it that when you issue this command:
gradlew hubCreateStepDefinition -PstepDefName=StepName -PstepDefType=ingestion

That it does these things?
1. Creates a step definition with a dmodulePath pointing to a custom ingestion step
2. Creates a custom .sjs file as "custom_modules/ingestion/StepName/main.sjs"

If this is not the way to do a custom ingestion step, then is there an example of how a custom ingestion step would be done?

Paul Vanderveen

**Comment by brucean52** [comment]
You can specify PstepDefType=custom. I'm not the most familiar with using gradle commands, I'll see if someone else can answer your question better.

https://docs.marklogic.com/datahub/flows/create-step-using-gradle.html

**Comment by freeweel** [comment]
Here's a little more info.  The reason I went down the custom method with type=ingestion in the first place was because Rahul Vudutala told me on the HipChat room to do it that way.  I can make a pure custom method, but a plain old custom method won't know how to ingest data.  How, for example, would I specify the local file system folders to upload?   I ended up running an ingestion step followed by a custom step to modify the ingested data, but that seems inefficient to make two copies for a minor data change.  There seems to have been some intent to allow customizing specialized types of steps, but it doesn't seem to work.  It should either work, or it should be removed.

**Comment by brucean52** [comment]
@rahulvudutala I'll leave this to you.

**Comment by sbayatpur** [comment]
Hi Paul, we will be adding UI support for custom ingestion steps. I'll be reaching out to talk through our solution to this with you.

**Comment by kkanthet** [comment]
This feature is part of 5.1.0 release , planned in nov 2019

**Comment by rjrudin** [comment]
This has been straightened out in DHF 5.4, where "custom" means "a custom step". You can now have stepDefinitionType=ingestion on your step, and then a custom value for stepDefinitionName, and it will use that step definition's module.
