### ISSUE TITLE
DHF 5.0.0: Changing the name of an entity makes the mapping disappear?

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#2507]
#### The issue

I changed the name of my entity. When I go back to the MAPPING part of my flow, I am presented with this message, "Before configuring this mapping you must set a target entity. You can create new entities in the Entities view."

Can the modification of the entity name warn me of my mapping being removed?
Can the modification of the entity name update my mapping?
Is my mapping truly lost?

#### Tech details

Which Operating System are you using?
MacOS 10.14

Which version of MarkLogic are you using?
9.0-9

Which version of the Data Hub Framework are you using?
5.0.0

Is this a QuickStart UI bug? If so, which browser are you using?
Maybe?

**Comment by brucean52** [comment]
Created an improvement JIRA ticket: https://project.marklogic.com/jira/browse/DHFPROD-2533

**Comment by kkanthet** [comment]
This has been handled in HubCentral.
