### ISSUE TITLE
DHF 5.0.0: Mapping drop down flowing off the screen

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#2508]
#### The issue
When I get to the bottom of my entity in the mapping stage, the dropdown flows off the screen limiting what I can see.

![image](https://user-images.githubusercontent.com/1315891/57717853-1d22fb00-764a-11e9-9d62-8e7aac4537e3.png)

#### Tech details

Which Operating System are you using?
MacOS 10.14

Which version of MarkLogic are you using?
9.0-9

Which version of the Data Hub Framework are you using?
5.0.0

Is this a QuickStart UI bug? If so, which browser are you using?
Yes.

**Comment by brucean52** [comment]
Created JIRA ticket: https://project.marklogic.com/jira/secure/RapidBoard.jspa?rapidView=258&projectKey=DHFPROD&view=planning&selectedIssue=DHFPROD-2532

**Comment by wooldridge** [comment]
This was addressed previously to version 5 here, may involve a similar fix: https://github.com/marklogic/marklogic-data-hub/issues/1388

**Comment by aebadirad** [comment]
Fixed in 5.0.1
