### ISSUE TITLE
DHF 5.0.0: Mapping changes in the UI does not result in me knowing my changes were saved

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#2509]
#### The UX issue
Whenever I make updates in the Flow's Ingest, Mapping, or Merge components, I look for a "save" or similar button. I can see the changes are automatically persisted with the DevTools, but as a user I am left to wonder if my changes were saved. 

Can a "saved" status be placed on the screen or an animation on the flow diagram that shows my changes have been persisted?

#### Tech details

Which Operating System are you using?
MacOS 10.14

Which version of MarkLogic are you using?
9.0-9

Which version of the Data Hub Framework are you using?
5.0.0

Is this a QuickStart UI bug? If so, which browser are you using?
Yes.

**Comment by brucean52** [comment]
I created a more generic JIRA ticket that covers all steps (Ingestion, Mapping, Mastering, and Custom)

https://project.marklogic.com/jira/browse/DHFPROD-2531

**Comment by kkanthet** [comment]
Issue Fixed in 5.0.2 release
