### ISSUE TITLE
QuickStart App data loaded to incorrect directory?

### ISSUE THREAD

**Issue by nizdobs** [marklogic/marklogic-data-hub#251]
When loading globalTech data in the QuickStart App the mlcp that the sample app creates to load the global corp data is: 
mlcp.bat -host localhost -port 8010 -username sbodzin -password ****\* -import -mode local -input_file_path C:\Users\sbodzin\Dropbox\MarkLogic\DemoScripts\DataHub\marklogic-data-hub\input\GlobalCorp **-output_uri_replace "C:\Users\sbodzin\Dropbox\MarkLogic\DemoScripts\DataHub\marklogic-data-hub\input\GlobalCorp,''"** -input_file_type "delimited_text" -output_collections "Employee,input-global-flow,input" -output_permissions "rest-reader,read,rest-writer,update" -document_type "json" -generate_uri true -transform_module "/com.marklogic.hub/mlcp-flow-transform.xqy" -transform_namespace "http://marklogic.com/data-hub/mlcp-flow-transform" -transform_param "Employeeinput-global-flowinput"

The -output_uri_replace argument should mean that docs are loaded to the root directory, correct?

But after running the ingest plugin on my Windows machine my uris have the form:
/C:/Users/sbodzin/Dropbox/MarkLogic/DemoScripts/DataHub/marklogic-data-hub/input/GlobalCorp/EmployeeTable.csv-0-640

**Comment by paxtonhare** [comment]
This is a run from cygwin issue.

**Comment by garyrusso** [comment]
I'm having a similar problem when I run the data-hub java server from either cygwin or via DOS command prompt.

My problem is that the "Output URI Replace" setting on the load-acme-tech Run Input Flow is not sticky. It goes back to original setting whenever I navigate away even after pressing the "save options" button.

**Comment by paxtonhare** [comment]
Which version of the hub?
