### ISSUE TITLE
Binaries example readme download link gives a 404

### ISSUE THREAD

**Issue by tjchambers32** [marklogic/marklogic-data-hub#2513]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:
The first link in the TLDR is broken, it gives a 404. 
https://github.com/marklogic/marklogic-data-hub/tree/4.0.1/examples/load-binaries

**Comment by aebadirad** [comment]
This should be fixed for the most current supported versions (4.3.1 and 5.0.1). We won't be going back to address downloading of older binaries of the same version. Apologies if this causes some distress, but we advocate for upgrading to the latest minor version of the major version you're using for support.
