### ISSUE TITLE
DHF5.0.0 - Run a single step for a flow fires all steps

### ISSUE THREAD

**Issue by peetkes** [marklogic/marklogic-data-hub#2515]
I created a curation flow consisting two steps.
When I try to run only the first step via ml-gradle command it executes both steps . gradle command hubRunFlow seems to ignore the -Pstep commandline option

My command:
````
gradlew hubRunFlow -PflowName=AECleanFlow -PentityName=AdverseEvent -PshowOptions -Pstep=1
````

#### Tech details
Which Operating System are you using?
MacOS High Sierra

Which version of MarkLogic are you using?
MarkLogic 9.0-9.1

Which version of the Data Hub Framework are you using?
DHF 5.0.0

#### The outcome
The last part of the message is:
````
    "flowName": "AECleanFlow",
    "endTime": "2019-05-16T06:16:49.037351Z",
    "lastCompletedStep": "1",
    "lastAttemptedStep": "2",
    "jobStatus": "finished_with_errors",
    "startTime": "2019-05-16T06:15:26.842903Z"
}

````
So as you can see it tries to also execute the 2nd step of the flow

**Comment by srinathgit** [comment]
Can you try changing -Pstep to -Psteps ?

```
gradlew hubRunFlow -PflowName=AECleanFlow -PentityName=AdverseEvent -PshowOptions -Psteps=1
```

**Comment by peetkes** [comment]
Changed and it worked, should be changed in the docs!

**Comment by akshaysonvane** [comment]
> Changed and it worked, should be changed in the docs!
> […](#)
> Op 16 mei 2019 om 08:24 heeft Srinath S ***@***.***> het volgende geschreven: Can you try changing -Pstep to -Psteps ? gradlew hubRunFlow -PflowName=AECleanFlow -PentityName=AdverseEvent -PshowOptions -Psteps=1 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

We have a Jira ticket for the doc change here https://project.marklogic.com/jira/browse/DHFPROD-2535

**Comment by aebadirad** [comment]
Docs have been modified. Closing issue.
