### ISSUE TITLE
Add help info for Smart Mastering options to guide the user in QuickStart

### ISSUE THREAD

**Issue by aajacobs** [marklogic/marklogic-data-hub#2518]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:  New users aren't sure how to properly configure Mastering flows in QuickStart.  It would be nice for the UI to have hints and help info so users can click on each Smart Mastering option to read what it does, how to use it, examples, links for more detail, etc.

What behavior are you expecting?  New user can easily figure out how to configure a Mastering flow in QuickStart without having to understand the details.

#### Tech details

Which version of the Data Hub Framework are you using? 5.0

Is this a QuickStart UI bug? If so, which browser are you using?  Not a bug, but an enhancement.

**Comment by Scapadiver** [comment]
+1  it is not at all obvious what you should put where in the UI.

**Comment by xmlnovelist** [comment]
+1 There are a couple of places especially but the one I ran into was Merge Strategies:Data Source. The UI has a free text field where you're supposed to type... What?

**Comment by aajacobs** [comment]
@xmlnovelist You're supposed to type in the name of the source you want to prefer, which assumes your sources follow the schema for sources outlined at https://marklogic-community.github.io/smart-mastering-core/how-does-it-work/ in the Data Model section.  

But I agree that's asking **a lot** for new users to know and understand, and having better guidance in the UI would be very helpful.

**Comment by ayuwono** [comment]
Thanks all, we have this on our roadmap, should be fixed on v5.1.0

**Comment by sbayatpur** [comment]
I appreciate this feedback.

For the short term, have created an example project that utilizes all the SM options and demonstrates how to use them: https://github.com/marklogic/marklogic-data-hub/tree/master/examples/smart-mastering-complete

In 5.1, you'll see tooltips for configuring Smart Mastering (included as part of these stories):
-https://project.marklogic.com/jira/browse/DHFPROD-2383
- https://project.marklogic.com/jira/browse/DHFPROD-2384
-https://project.marklogic.com/jira/browse/DHFPROD-2381

In the longer term, we'll evaluating how to improve the overall design of Smart Mastering in Data Hub (which should include better help)

**Comment by kkanthet** [comment]
Issue Fixed in 5.1.0 release
