### ISSUE TITLE
DHF 5.0.0: Quickstart UI - Adding options to flow does not work

### ISSUE THREAD

**Issue by derms** [marklogic/marklogic-data-hub#2531]
#### The issue

Step a flow as per below -

![image](https://user-images.githubusercontent.com/1885934/58173280-3e639700-7c9b-11e9-9f05-a2b7ec743677.png)

Tried to add an option as per below -

![image](https://user-images.githubusercontent.com/1885934/58173313-520efd80-7c9b-11e9-8c9d-a67cdfd9d514.png)

The option did not save - 

![image](https://user-images.githubusercontent.com/1885934/58173341-6652fa80-7c9b-11e9-98d5-4e398e0f2f84.png)

#### Tech details

Which Operating System are you using? Mac

Which version of MarkLogic are you using? 9.0.9-1

Which version of the Data Hub Framework are you using? 5.0.0

Is this a QuickStart UI bug? If so, which browser are you using? Chrome

Added output from quickstart
[myoutput.txt](https://github.com/marklogic/marklogic-data-hub/files/3207251/myoutput.txt)

**Comment by ayuwono** [comment]
I can see the options are saved, both from manage flows and edit flow page. I'm using Chrome too

<img width="1354" alt="Screen Shot 2019-05-22 at 10 03 01 AM" src="https://user-images.githubusercontent.com/7096668/58193884-f16ec900-7c78-11e9-9ac9-86220fd7bced.png">

<img width="1279" alt="Screen Shot 2019-05-22 at 10 03 19 AM" src="https://user-images.githubusercontent.com/7096668/58193887-f3d12300-7c78-11e9-8be5-e80fbe602f89.png">

**Comment by aebadirad** [comment]
@derms what version of Chrome?

**Comment by derms** [comment]
attaching chrome version

![image](https://user-images.githubusercontent.com/1885934/58235270-c8b20680-7d40-11e9-9f2a-1eb21799458e.png)

**Comment by derms** [comment]
when i try to add an option -

![image](https://user-images.githubusercontent.com/1885934/58235506-3a8a5000-7d41-11e9-8f65-66ae518f24f4.png)

the put does not contain the option

![image](https://user-images.githubusercontent.com/1885934/58235545-52fa6a80-7d41-11e9-9c6d-fe6b002b13e2.png)

**Comment by ayuwono** [comment]
@derms , got it, I think I'm using dev env (port 4200). Error on bootrun:
ERROR 69546 --- [nio-8080-exec-3] s.e.ErrorMvcAutoConfiguration$StaticView : Cannot render error page for request [/websocket/982/hg3to50e/htmlfile] and exception [Broken pipe] as the response has already been committed. As a result, the response may have the wrong status code.
09:42:14.947 [http-nio-8080-exec-3] ERROR o.s.b.a.w.s.e.ErrorMvcAutoConfiguration$StaticView - Cannot render error page for request [/websocket/982/hg3to50e/htmlfile] and exception [Broken pipe] as the response has already been committed. As a result, the response may have the wrong status code.

**Comment by ayuwono** [comment]
Tracking this issue on JIRA: https://project.marklogic.com/jira/browse/DHFPROD-2572

**Comment by aebadirad** [comment]
Fixed in 5.0.1
