### ISSUE TITLE
DHF 5.0.0: Quickstart UI - "No job document found" error in the jobs app server log file after flow successfully run 

### ISSUE THREAD

**Issue by derms** [marklogic/marklogic-data-hub#2532]
#### The issue

Configured a flow as follows -

![image](https://user-images.githubusercontent.com/1885934/58173877-c8602f80-7c9c-11e9-8f25-8ca94f36b40b.png)

with the step defined as per below

![image](https://user-images.githubusercontent.com/1885934/58173914-df9f1d00-7c9c-11e9-8e53-a67561476518.png)

Ran the flow - it finished successfully

![image](https://user-images.githubusercontent.com/1885934/58173940-f776a100-7c9c-11e9-86f0-1608e80f04bf.png)

But see a "No job document found" error in the jobs app server (log file attached) 

[8023_ErrorLog.txt](https://github.com/marklogic/marklogic-data-hub/files/3207302/8023_ErrorLog.txt)

#### Tech details

Which Operating System are you using? Mac

Which version of MarkLogic are you using? 9.0.9-1

Which version of the Data Hub Framework are you using? 5.0.0

Is this a QuickStart UI bug? If so, which browser are you using? Chrome

output attached
[myoutput.txt](https://github.com/marklogic/marklogic-data-hub/files/3207305/myoutput.txt)

**Comment by aebadirad** [comment]
Can we get the access log of the jobs app server at the same time? Curious to see what the request was.

**Comment by ayuwono** [comment]
@derms , is the Test collection from an ingestion step? 

Did you modify the main.sjs under your-project-dir/src/main/ml-modules/root/custom-modules/custom/<your-customstep-name> ?

**Comment by derms** [comment]
adding the access logs for yesterday and today

[8023_AccessLog.txt](https://github.com/marklogic/marklogic-data-hub/files/3210926/8023_AccessLog.txt)
[8023_AccessLog_1.txt](https://github.com/marklogic/marklogic-data-hub/files/3210927/8023_AccessLog_1.txt)

**Comment by derms** [comment]
@ayuwono there is no ingestion step - just the custom step. Yes I modified the main.sjs

**Comment by kkanthet** [comment]
@derms  custom step creates a job document, can we close this issue ?

**Comment by rjrudin** [comment]
This was a timing issue in QS where it would check for the job doc before one is created. Closing as it's QS.
