### ISSUE TITLE
DHF 5.0.0:  Cannot use options in Source Query for a step

### ISSUE THREAD

**Issue by derms** [marklogic/marklogic-data-hub#2533]
#### The issue

In previous version of the DHF, we could use pass options into the collector.sjs in order to reduce the documents that were processed in a given job. E.g. by passing a 'date' option, we could construct a query that would limit the documents processed to that date.

We seem to have lost this ability in DHF 5.0.0. We cannot use the options in the "Source Query" for a step -

![image](https://user-images.githubusercontent.com/1885934/58175103-ae741c00-7c9f-11e9-96ea-eb607bf120fc.png)

#### Tech details

Which Operating System are you using? Mac

Which version of MarkLogic are you using? 9.0.9-1

Which version of the Data Hub Framework are you using? 5.0.0

Is this a QuickStart UI bug? If so, which browser are you using? Chrome

**Comment by derms** [comment]
I should also add that not having this capability is a blocker or a number of clients  to migrate to DHF 5

**Comment by aebadirad** [comment]
You can pass sourceQuery as an option at run time. This doesn't follow the old method where you wrote a module to do collection.

> "options": {
    "sourceQuery": "cts.collectionQuery(<insertDateHere>)"
  },

**Comment by aebadirad** [comment]
@eltesoro-ml let's make sure we document this

**Comment by derms** [comment]
@aebadirad @eltesoro-ml thanks for letting me know.

For reference, this is an example that works

`gradle hubRunFlow -PflowName=tryme -Poptions="{\"sourceQuery\":\"cts.collectionQuery('xml')\"}" -PshowOptions=true`

**Comment by derms** [comment]
@aebadirad can you also put back the -Pdhf.<oprtionName>=<oprtionValue> functionality too (i.e. support the -Poptions=   and -Pdhf.<oprtionName>)? 

It is much less cumbersome using the  -Pdhf.<oprtionName> approach from the command line.

**Comment by aebadirad** [comment]
We also have -PoptionsFile="path/to/options.json" implemented. But an RFE can be raised for adding flat options.

**Comment by aebadirad** [comment]
@derms can you raise an RFE issue for restoring the dhf.key=value setup (they'll just get added to options object by key/value pairs) so that can tracked and we can close this one
