### ISSUE TITLE
DHF 5.0.0: QuickStart Browser should be alphabetically ordered

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#2535]
#### The issue
The QuickStart "Browse for a Project Folder" should be alphabetized so I can quickly find my project directory.

![image](https://user-images.githubusercontent.com/1315891/58199178-eaa67d00-7c9d-11e9-9b30-a078fe9b14c4.png)

#### Tech details

Which Operating System are you using?
Mac 10.14

Which version of MarkLogic are you using?
9.0-9

Which version of the Data Hub Framework are you using?
5.0.0

Is this a QuickStart UI bug? If so, which browser are you using?
Yes

**Comment by ayuwono** [comment]
This is fixed on 5.0 for sure: https://project.marklogic.com/jira/browse/DHFPROD-2313

Looking at your screenshot, it seems that it's sorted correctly? d...e...m...r...s...

**Comment by prestonmcgowan** [comment]
Above this section was uppercase names with a T, so it threw me off.
I will close this ticket as it is 0-9A-Za-z sort order.
