### ISSUE TITLE
DHF 5.0.0: Deployed! ... now what?

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#2536]
#### The issue
When deploying a new data hub from an empty directory, the DataHub deploys and a user is presented with the following screen.

![image](https://user-images.githubusercontent.com/1315891/58199898-84baf500-7c9f-11e9-9860-797f3528585b.png)

Having a blank screen make me think I messed something up. The QuickStart should lead me on what to do next. Or even tell me where to read some documentation, a video or something. A rather blank screen is not a good UX.

#### Tech details

Which Operating System are you using?
Mac 10.14

Which version of MarkLogic are you using?
9.0-9

Which version of the Data Hub Framework are you using?
5.0.0

Is this a QuickStart UI bug? If so, which browser are you using?
Yes, UX

**Comment by prestonmcgowan** [comment]
I noticed in the URL bar, the QuickStart was trying to put me back into a entity flow for another DHF project that I was not in.
I had previously been in my sandbox project, logged out, browsed to the empty directory, created a data hub for it, deployed it, and was then shown the blank page. 
Therefore, I think it is a state management in the UI issue and not some bad UX.

**Comment by brucean52** [comment]
OK, this makes sense. I think we need to add a '404 Request Not Found' route to Quickstart.

**Comment by brucean52** [comment]
JIRA Ticket: https://project.marklogic.com/jira/browse/DHFPROD-2575

**Comment by aebadirad** [comment]
Released as part of 5.0.2.
