### ISSUE TITLE
DHF 5.0.0: Large index creates a slow response with Quick Start

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#2537]
#### The issue
The QuickStart UI tries to bring all values for an index back in the UI. This behavior becomes an issue when I have an entity index that has several thousand (or more) values. The UI will lock up and the browser will ask to close the tab. If I defer the browser enough times, I can minimize the facet and the QuickStart UI will function much more smoothly.

Why does the UI bring back all the values? Can the values be paginated in the facet? Can the values be type ahead suggested?

#### Tech details

Which Operating System are you using?
Mac 10.14

Which version of MarkLogic are you using?
9.0-9

Which version of the Data Hub Framework are you using?
5.0.0

Is this a QuickStart UI bug? If so, which browser are you using?
Yes

Browser?
Chrome 74.0.3729.169

**Comment by ayuwono** [comment]
Tracing this on JIRA: https://project.marklogic.com/jira/browse/DHFPROD-2580

**Comment by kkanthet** [comment]
Fixed as part of 5.0.2 release
