### ISSUE TITLE
DHF 5 doc has broken links to DHF 4 docs

### ISSUE THREAD

**Issue by crism** [marklogic/marklogic-data-hub#2546]
#### The issue

Short description of the problem:

The [upgrade instructions](https://docs.marklogic.com/datahub/upgrade.html) say to upgrade to 4.3 if not already there, and have a link to directions to do that. That link is http://mldocx.marklogic.com:8050/dh4/upgrade/ which is an unknown host; it should be https://marklogic.github.io/marklogic-data-hub/upgrade/

**Comment by eltesoro-ml** [comment]
Thank you for letting us know. The links to 4.3 are fixed.
