### ISSUE TITLE
DHF 5.0.0: Can't add new step after deleting a flow step

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#2553]
In Quickstart 5.0.0....

If you remove a step that isn't the last step, then any subsequently added steps will overwrite the last step.

**Steps to reproduce:**
1. Create a flow
2. Add a step
3. Add a second step
4. Remove the first step
5. Try adding a new step

When you remove the 1st step, the underlying json just has 1 step remaining, but the key is "2". So when you add the 3rd step it inserts it as "2" and overwrites the existing step. My guess is that the code is doing something like:

`let key = steps.length + 1`

**Comment by brucean52** [comment]
Yeah, this is due to Java -> JavaScript indexing

JIRA Ticket: https://project.marklogic.com/jira/browse/DHFPROD-2581

**Comment by aebadirad** [comment]
Fixed in 5.0.1
