### ISSUE TITLE
DHF 5.0.0 QuickStart: UI infinite loop with empty entity

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#2555]
#### The issue
I wanted to bring my data from staging to final with no real changes. Load As Is.
Since "ingest" will only put data into Staging, I created a Mapping stage, but noticed I needed an entity. I created an entity, but did not add any properties. I tied the mapping stage to my entity and then the UI went into an infinite loop and became unresponsive. I had to close the browser to regain control.

![image](https://user-images.githubusercontent.com/1315891/58335805-632d4b00-7e10-11e9-971f-a3aaa724580e.png)

#### Tech details

Which Operating System are you using?
Mac 10.14

Which version of MarkLogic are you using?
9.0-9

Which version of the Data Hub Framework are you using?
5.0.0

Is this a QuickStart UI bug? If so, which browser are you using?
Yes

**Comment by ayuwono** [comment]
This is a bug on mapping for sure. If you want to ingest docs to final DB, you can do that by selecting your final DB from the step's Advanced Settings

**Comment by rjrudin** [comment]
Closing as this is QS
