### ISSUE TITLE
DHF 5.0.0: Mapping suggestion using individual strings?

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#2556]
#### The issue

![image](https://user-images.githubusercontent.com/1315891/58336445-bbb11800-7e11-11e9-8c01-50ae2bcd295e.png)

#### Tech details

Which Operating System are you using?
Mac 10.14

Which version of MarkLogic are you using?
9.0.0

Which version of the Data Hub Framework are you using?
5.0.0
Is this a QuickStart UI bug? If so, which browser are you using?
Not sure

**Comment by ayuwono** [comment]
We have this issue on JIRA: https://project.marklogic.com/jira/browse/DHFPROD-2543. I believe we only support flat json for mapping, but will confirm

**Comment by ayuwono** [comment]
https://docs.marklogic.com/datahub//flows/requirements-default-mapping.html

Mapping is for flat json documents, but you can customize it to handle the xml transformation

**Comment by aebadirad** [comment]
Fixed in 5.0.1
