### ISSUE TITLE
DHF 5.0.0 QS: Hard to catch Edit Settings

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#2558]
#### The issue
![Hard_to_catch_edit_settings](https://user-images.githubusercontent.com/1315891/58345243-e4430d00-7e25-11e9-93ad-1589990b270e.gif)

"Why don't you want me to click you?!"

#### Tech details

Which Operating System are you using?
Mac 10.14

Which version of MarkLogic are you using?
9.0.0

Which version of the Data Hub Framework are you using?
5.0.0

Is this a QuickStart UI bug? If so, which browser are you using?
Yes. Chrome

**Comment by ayuwono** [comment]
What Chrome version do you use? 

On my browser, it's easy to catch them, the Edit Settings have that hover over and I can click it around the area:
https://drive.google.com/file/d/1XzItAH4cJQVJNXM7mBQeGpczfI-yWuR7/view

**Comment by prestonmcgowan** [comment]
Version 74.0.3729.169

**Comment by ayuwono** [comment]
Using chrome version 75 and its fine
