### ISSUE TITLE
DHF 5.0.0: Jobs Invalid Date

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#2559]
#### The issue
![image](https://user-images.githubusercontent.com/1315891/58345555-a4c8f080-7e26-11e9-9096-c85cb7cc6723.png)

GET http://localhost:8080/api/flows/GeoLocation
Response:
`{"id":"GeoLocation","name":"GeoLocation","description":"","batchSize":100,"threadCount":4,"stopOnError":false,"options":{},"steps":[{"id":"Ingest-GeoLocation-Data-ingestion","name":"Ingest-GeoLocation-Data","stepDefinitionType":"ingestion","targetEntity":""}],"jobs":["c5945a33-9b0e-4644-a714-d1523ec64ced","b344c266-1fd8-425b-a357-1cb0a2386afa","c0445e35-e305-4c1a-99cf-a95316e24907"],"latestJob":{"id":"b344c266-1fd8-425b-a357-1cb0a2386afa","startTime":"2019-05-24T13:10:04.897506-04:00","endTime":"","output":null,"stepId":"Ingest-GeoLocation-Data-ingestion","stepName":"Ingest-GeoLocation-Data","stepRunningPercent":0,"status":"completed step 1","successfulEvents":17,"failedEvents":0}}`

Jobs Database file:
/jobs/c5945a33-9b0e-4644-a714-d1523ec64ced.json
`{
"job": {
"jobId": "c5945a33-9b0e-4644-a714-d1523ec64ced", 
"flow": "GeoLocation", 
"user": "admin", 
"lastAttemptedStep": "1", 
"lastCompletedStep": "1", 
"jobStatus": "completed step 1", 
"timeStarted": "2019-05-24T07:04:26.289219-04:00", 
"timeEnded": "N/A", 
"stepResponses": {
"1": {
"flowName": "GeoLocation", 
"stepName": "Ingest-GeoLocation-Data", 
"stepDefinitionName": "default-ingestion", 
"stepDefinitionType": "ingestion", 
"stepOutput": null, 
"fullOutput": null, 
"status": "completed step 1", 
"totalEvents": 17, 
"successfulEvents": 17, 
"failedEvents": 0, 
"successfulBatches": 1, 
"failedBatches": 0, 
"success": true, 
"stepStartTime": "2019-05-24T07:04:26.330128-04:00", 
"stepEndTime": "2019-05-24T07:04:27.973958-04:00"
}
}
}
}
`

#### Tech details

Which Operating System are you using?
Mac 10.14

Which version of MarkLogic are you using?
9.0-9

Which version of the Data Hub Framework are you using?
5.0.0

Is this a QuickStart UI bug? If so, which browser are you using?
/shrug

**Comment by ayuwono** [comment]
@prestonmcgowan , can you provide us the steps to reproduce? The dataset too? Thanks

**Comment by prestonmcgowan** [comment]
1. Create a new Flow
2. Add Ingest Step
2.1. Add the directory (Unzip any.zip)
2.2. Select XML for Source and Target File Type
3. Run the Ingest Step
4. Click Jobs to see the job details

**Comment by prestonmcgowan** [comment]
Test data:
https://github.com/koopjs/koop-provider-marklogic/tree/master/data/test/GeoLocation
 - any.zip

**Comment by ayuwono** [comment]
I believe this issue fixed on develop branch. I can ingest xml docs and the jobs have valid values
<img width="1294" alt="Screen Shot 2019-05-31 at 10 17 04 AM" src="https://user-images.githubusercontent.com/7096668/58722836-54edaa80-838d-11e9-9247-4a9d33bd730a.png">
