### ISSUE TITLE
Job Output window stuck and not close-able

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#256]
When I navigate to Jobs and click show output, the output window is half off the (right) side of the screen and not moveable or closeable.

Some possible fixes: allow the window to be dragged around (I bet there is a close button in the upper right?)
allow ESC to close the window
force it to appear in the center of the screen.

WORKAROUND: refresh the page to get back to the overall Jobs view.

**Comment by paxtonhare** [comment]
@damonfeldman which version? also, which browser? mac or windows?

**Comment by damonfeldman** [comment]
mac: chrome Version 51.0.2704.103 (64-bit)

**Comment by damonfeldman** [comment]
moving to rc 2 tag

**Comment by damonfeldman** [comment]
testing this link:  5c50baeb9a5ba691c768d392ce71fb42780f05ef

**Comment by damonfeldman** [comment]
![image](https://cloud.githubusercontent.com/assets/700633/17715354/b32f4286-63d1-11e6-9b8a-297133b9c45e.png)
