### ISSUE TITLE
DHF 5.0.0: Lots of JOBS calls for all finished work

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#2560]
#### The issue

![image](https://user-images.githubusercontent.com/1315891/58345955-9d561700-7e27-11e9-90f5-2ade71df8825.png)
 
and ... it is still going!
![image](https://user-images.githubusercontent.com/1315891/58346056-e5753980-7e27-11e9-92af-f9d66508c7d4.png)

I respect it trying to continue until the JOB is done ... but it's all done.
![image](https://user-images.githubusercontent.com/1315891/58346008-c8d90180-7e27-11e9-956b-ee2eec6f769e.png)

#### Tech details

Which Operating System are you using?
Mac 10.14

Which version of MarkLogic are you using?
9.0-9

Which version of the Data Hub Framework are you using?
5.0.0

Is this a QuickStart UI bug? If so, which browser are you using?
Oh yeah.

**Comment by aebadirad** [comment]
@brucean52 i think you improved this already in develop?

**Comment by brucean52** [comment]
I added polling for live updating a job if it's in progress, but I'm not sure what's causing this loop. @prestonmcgowan  do you have a way to reproduce this?

**Comment by prestonmcgowan** [comment]
All I did was log into the Quick Start UI.

![image](https://user-images.githubusercontent.com/1315891/58494989-537d7180-8144-11e9-9f7a-304ddd03226a.png)

**Comment by prestonmcgowan** [comment]
Perhaps it is the /api/flows/GeoLocation endpoint not the jobs endpoint. I think I was on the JOBS screen when I saw it, which made me think JOBS had caused it.

**Comment by kkanthet** [comment]
@prestonmcgowan  can we close this issue ?

**Comment by rjrudin** [comment]
Closing as this is QS
