### ISSUE TITLE
Smart Mastering issue with json result for matches

### ISSUE THREAD

**Issue by debashissinha** [marklogic/marklogic-data-hub#2569]
Hi All,

I am using smart mastering framework based on Data Hub framework . I have ran into a issue.

My Steps are as follows

a) I insert any two json document in data-hub-STAGING.
b) I run Harmonization.
c) Then from data-hub-FINAL I run smart mastering . 

I use rest api to invoke smart mastering 
e.g Link :- 
http://localhost:8011/v1/resources/sm-match?rs:uri=/Cash/Source2/cash1.json&rs:options=cash-match-options&rs:includeMatches=true

I am using the sm-match option for finding matches between three document . The problem is it gives the desired result with score but does not show the matches . It only shows that two document is a match but doesn't show which fields are matching .

However if from qconsole I run the following command 
import module namespace matcher = "http://marklogic.com/smart-mastering/matcher"
  at "com.marklogic.smart-mastering/matcher.xqy";

matcher:find-document-matches-by-options-name(
  fn:doc("/Cash/Source2/cash2.json"),
  "cash-match-options",
  fn:true(),
  cts:collection-query("Cash")
)  

I get all the result in xml having the score , the uri for the document matched  and also the matched items.

[cash_unharmonized_2.txt](https://github.com/marklogic/marklogic-data-hub/files/3232293/cash_unharmonized_2.txt)
[cash_unharmonized_3.txt](https://github.com/marklogic/marklogic-data-hub/files/3232294/cash_unharmonized_3.txt)
[cash_unharmonized_1.txt](https://github.com/marklogic/marklogic-data-hub/files/3232295/cash_unharmonized_1.txt)

My observation is  that some how during json transformation it is giving some other results.

I would like to request some one to kindly help me with this .

**Comment by ryanjdew** [comment]
@debashissinha Hello, It sounds like you probably aren't using Mastering within Data Hub 5. Can you share more information about what version of the Data Hub and what version of Smart Mastering you are using?

Thanks!

**Comment by debashissinha** [comment]
Hi Rayan,
Many thanks for your input . I was actually using an older version of datahub . Let me use the latest version as suggested by You . If I encounter any problem I`ll seek your kind help.

Thanks again for your suggestion .

Thanks a Lot!
Debashis

**Comment by debashissinha** [comment]
Hi Rayan,
I tried with version 5.0 of DataHub as suggested by you . Here are  the steps that I followed.
a) I tried with gradle flow but some how that was not working.
b) SO to save some time and avoid the configuration I used the quickstart flow .
c) I deployed  All the required module and logged into marklogic data hub using my admin credential .
d) All the required modules were instantiated and loaded to db.
e) Next I created an entity called Cash. With attributes form the json file (attached).


[cash1.txt](https://github.com/marklogic/marklogic-data-hub/files/3248670/cash1.txt)
[cash2.txt](https://github.com/marklogic/marklogic-data-hub/files/3248671/cash2.txt)
[cash3.txt](https://github.com/marklogic/marklogic-data-hub/files/3248672/cash3.txt)

All the above files are json.

The Cash entity is as in the diagram
![image](https://user-images.githubusercontent.com/46902108/58820633-bdb87980-8650-11e9-8015-c025b67886dd.png)

Next I Created a Flow called "CashFlow".
f) Inside CashFlow" I created a ingestion step with following details
![image](https://user-images.githubusercontent.com/46902108/58820740-04a66f00-8651-11e9-9e53-e858e652ce01.png)

g) Next I created the matching step with the following details
![image](https://user-images.githubusercontent.com/46902108/58821759-623bbb00-8653-11e9-858e-73063f58cfd2.png)
![image](https://user-images.githubusercontent.com/46902108/58821792-78497b80-8653-11e9-81b8-b984a9c6aec4.png)


h) Next I created the mastering step as given below 
![image](https://user-images.githubusercontent.com/46902108/58821846-a038df00-8653-11e9-8d52-17df38e072e2.png)
![image](https://user-images.githubusercontent.com/46902108/58821883-b5157280-8653-11e9-9500-0278b489942b.png)
![image](https://user-images.githubusercontent.com/46902108/58822055-34a34180-8654-11e9-8794-8d984b78c546.png)


j)Following this i created the merging option as given below
![image](https://user-images.githubusercontent.com/46902108/58821972-f6a61d80-8653-11e9-83b3-d607385fd47d.png)
![image](https://user-images.githubusercontent.com/46902108/58821999-0c1b4780-8654-11e9-9c2c-b0f3c1b3a704.png)

k) My documents cash1 and cash2 have same values whereas cash3 have same values .
l) I have used collection to find match . So ideally I got the two document as match in merged document which is cash1 and cash2 .
j) However when I look at the json for merged document I dont see all the fields . That is I see 10 fields only instead of 15 fields. I have uniformly given 10 as weight for all 15 fields. 

For your reference I am attaching the matching documents after step 2 and the merged documents after step 3. in .txt format
[cash3.json_matched.txt](https://github.com/marklogic/marklogic-data-hub/files/3248780/cash3.json_matched.txt)
[cash1.json_matched.txt](https://github.com/marklogic/marklogic-data-hub/files/3248781/cash1.json_matched.txt)
[cash2.json_matched.txt](https://github.com/marklogic/marklogic-data-hub/files/3248782/cash2.json_matched.txt)

Also attached the mastering results below 

data-hub-FINAL (15 Documents)
| /com.marklogic.smart-mastering/auditing/merge/f664ffad-d814-4068-8975-a724c360d46d.xml
[com.marklogic.smart-masteringauditingmergef664ffad-d814-4068-8975-a724c360d46d.xml.txt](https://github.com/marklogic/marklogic-data-hub/files/3248801/com.marklogic.smart-masteringauditingmergef664ffad-d814-4068-8975-a724c360d46d.xml.txt)


data-hub-FINAL (15 Documents)
| /com.marklogic.smart-mastering/merged/3cd8643b2c0d326093da9de012efd3f7.json
[com.marklogic.smart-masteringmerged3cd8643b2c0d326093da9de012efd3f7.json.txt](https://github.com/marklogic/marklogic-data-hub/files/3248811/com.marklogic.smart-masteringmerged3cd8643b2c0d326093da9de012efd3f7.json.txt)

Can you kindly help me understand as what is the exact reason that for merged document I am getting 10 fields whereas it should be 15 fields. whereas the match result is ok in terms of two documents only matching viz cash1.json and cash2.json.

Your help in this regard will be of great help for me 

I followed this link
https://docs.marklogic.com/datahub/projects/create-project-using-quickstart.html

Thank you again.

Regards
Debashis

**Comment by debashissinha** [comment]
Hi Rayan,
I tried with version 5.0 of DataHub as suggested by you . Here are  the steps that I followed.
a) I tried with gradle flow but some how that was not working.
b) SO to save some time and avoid the configuration I used the quickstart flow .
c) I deployed  All the required module and logged into marklogic data hub using my admin credential .
d) All the required modules were instantiated and loaded to db.
e) Next I created an entity called Cash. With attributes form the json file (attached).


[cash1.txt](https://github.com/marklogic/marklogic-data-hub/files/3248670/cash1.txt)
[cash2.txt](https://github.com/marklogic/marklogic-data-hub/files/3248671/cash2.txt)
[cash3.txt](https://github.com/marklogic/marklogic-data-hub/files/3248672/cash3.txt)

All the above files are json.

The Cash entity is as in the diagram
![image](https://user-images.githubusercontent.com/46902108/58820633-bdb87980-8650-11e9-8015-c025b67886dd.png)

Next I Created a Flow called "CashFlow".
f) Inside CashFlow" I created a ingestion step with following details
![image](https://user-images.githubusercontent.com/46902108/58820740-04a66f00-8651-11e9-9e53-e858e652ce01.png)

g) Next I created the matching step with the following details
![image](https://user-images.githubusercontent.com/46902108/58821759-623bbb00-8653-11e9-858e-73063f58cfd2.png)
![image](https://user-images.githubusercontent.com/46902108/58821792-78497b80-8653-11e9-81b8-b984a9c6aec4.png)


h) Next I created the mastering step as given below 
![image](https://user-images.githubusercontent.com/46902108/58821846-a038df00-8653-11e9-8d52-17df38e072e2.png)
![image](https://user-images.githubusercontent.com/46902108/58821883-b5157280-8653-11e9-9500-0278b489942b.png)
![image](https://user-images.githubusercontent.com/46902108/58822055-34a34180-8654-11e9-8794-8d984b78c546.png)


j)Following this i created the merging option as given below
![image](https://user-images.githubusercontent.com/46902108/58821972-f6a61d80-8653-11e9-83b3-d607385fd47d.png)
![image](https://user-images.githubusercontent.com/46902108/58821999-0c1b4780-8654-11e9-9c2c-b0f3c1b3a704.png)

k) My documents cash1 and cash2 have same values whereas cash3 have same values .
l) I have used collection to find match . So ideally I got the two document as match in merged document which is cash1 and cash2 .
j) However when I look at the json for merged document I dont see all the fields . That is I see 10 fields only instead of 15 fields. I have uniformly given 10 as weight for all 15 fields. 

For your reference I am attaching the matching documents after step 2 and the merged documents after step 3. in .txt format
[cash3.json_matched.txt](https://github.com/marklogic/marklogic-data-hub/files/3248780/cash3.json_matched.txt)
[cash1.json_matched.txt](https://github.com/marklogic/marklogic-data-hub/files/3248781/cash1.json_matched.txt)
[cash2.json_matched.txt](https://github.com/marklogic/marklogic-data-hub/files/3248782/cash2.json_matched.txt)

Also attached the mastering results below 

data-hub-FINAL (15 Documents)
| /com.marklogic.smart-mastering/auditing/merge/f664ffad-d814-4068-8975-a724c360d46d.xml
[com.marklogic.smart-masteringauditingmergef664ffad-d814-4068-8975-a724c360d46d.xml.txt](https://github.com/marklogic/marklogic-data-hub/files/3248801/com.marklogic.smart-masteringauditingmergef664ffad-d814-4068-8975-a724c360d46d.xml.txt)


data-hub-FINAL (15 Documents)
| /com.marklogic.smart-mastering/merged/3cd8643b2c0d326093da9de012efd3f7.json
[com.marklogic.smart-masteringmerged3cd8643b2c0d326093da9de012efd3f7.json.txt](https://github.com/marklogic/marklogic-data-hub/files/3248811/com.marklogic.smart-masteringmerged3cd8643b2c0d326093da9de012efd3f7.json.txt)

Can you kindly help me understand as what is the exact reason that for merged document I am getting 10 fields whereas it should be 15 fields. whereas the match result is ok in terms of two documents only matching viz cash1.json and cash2.json.

Your help in this regard will be of great help for me 

I followed this link
https://docs.marklogic.com/datahub/projects/create-project-using-quickstart.html

Thank you again.

Regards
Debashis

**Comment by debashissinha** [comment]
Hi Rayan,
I have another observation. Many fields in my json has "_" in the json key . While working once I encountered such an error which stated that any json key which has "_" cannot be used in lexicon query index. Can that be the reason ?

Thanks & Regards
Debashis

**Comment by ryanjdew** [comment]
Hi @debashissinha,

I've been able to confirm that you are correct and it is the underscore (_) in the property names that are causing the issue. We're investigating how best to support the underscores in JSON keys. In the meantime, if you have the flexibility to avoid underscores in your entity models, that would solve your issue. Thanks!

**Comment by debashissinha** [comment]
Hi Ryan,
Man thanks for your confirmation ... I am working extensively to understand the functioning of Smart Mastering as I Like the framework very much . I would like to share few few issues which I encountered . Would it be prudent If I open new issues for you to track them individually or should I do it in this issue.

Your valued advice is keenly solicited.

Thank You Again.
Regards
Debashis

**Comment by ryanjdew** [comment]
Please create new issues. If you could reference my username (@ryanjdew) somewhere in the body of the issue or in an additional comment, that would be helpful to ensure that it hits my radar. Thanks!

**Comment by debashissinha** [comment]
Hi Ryan ,
Thanks for your input . I will create accordingly.
Thanks
Debashis
