### ISSUE TITLE
Run Flow buttons inconsistent b/c Harmonize runs immediately

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#257]
Run Flow for raw ingest leads to an options/confirm dialog, but Run Flow for Harmonize runs immediately. There is no clue or indicator that the operations are different.

**Comment by paxtonhare** [comment]
You are using an old build.

**Comment by damonfeldman** [comment]
This is in rc.2.

The button in question always looks the same:
![image](https://cloud.githubusercontent.com/assets/700633/17715448/181cdd20-63d2-11e6-838c-9578506c7f27.png)

**Comment by paxtonhare** [comment]
add options to run harmonize for batch size, etc
