### ISSUE TITLE
DHF 5.0.0: REST API transform broken - impacting Nifi Flows

### ISSUE THREAD

**Issue by derms** [marklogic/marklogic-data-hub#2570]
#### The issue

The REST API call for document transforms is not working in DHF 5 for custom transforms. This is impacting Nifi Flows (amongst other things) 

The cause is a bug on line 517 of extensions-util.xqy

https://github.com/marklogic/marklogic-data-hub/blob/master/marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/rest-api/lib/extensions-util.xqy#L517

`if (empty($system-module))`

The `$system-module` sequence will never be empty - it will always contain at least one value. The test should be

`if (fn:count($system-module) < 2)`

This is a critical regression bug - can this be fixed as a high priority?

#### The details

E.g. for the following POST restapi call -

http://localhost:8020/v1/documents?uri=/myuri.json&transform=anonym&trans:source=WorkersInProgress

The following error is shown - 

`<error-response xmlns="http://marklogic.com/xdmp/error">
<status-code>400</status-code>
<status>Bad Request</status>
<message-code>RESTAPI-INVALIDREQ</message-code>
<message>RESTAPI-INVALIDREQ: (err:FOER0000) Invalid request:  reason: Extension anonym or a dependency does not exist: XDMP-MODNOTFOUND: (err:XQST0059) Module /data-hub/5/transforms/.xqy not found</message>
</error-response> `

Note that the custom transform "anonym.sjs" is loaded correctly and it worked correctly in DHF 4

`019-05-29 12:24:01.967 Notice: RESTAPI-INVALIDREQ: (err:FOER0000) Invalid request:  reason: Extension anonym or a dependency does not exist: XDMP-MODNOTFOUND: (err:XQST0059) Module /data-hub/5/transforms/.xqy not found
2019-05-29 12:24:01.967 Notice:+in /data-hub/5/rest-api/lib/extensions-util.xqy, at 942:17,
2019-05-29 12:24:01.967 Notice:+in extut:invoke-service("anonym", "TRANSFORM", (), xdmp:function(fn:QName("http://marklogic.com/rest-api/transform/","transform"), "/data-hub/5/transforms/.xqy"), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), fn:doc("/COMPANY_HIERARCHY/CO_2922"), fn:false()) [1.0-ml]
2019-05-29 12:24:01.967 Notice:+  $extension-name = "anonym"
2019-05-29 12:24:01.967 Notice:+  $method = "TRANSFORM"
`

#### Tech details

Which Operating System are you using? Mac

Which version of MarkLogic are you using? 9.0-9.1

Which version of the Data Hub Framework are you using? 5.0.0

Is this a QuickStart UI bug? If so, which browser are you using?

**Comment by rjrudin** [comment]
@derms I'm taking a look at this.

**Comment by rjrudin** [comment]
Was able to reproduce (with just doing a GET) and the proposed fix makes sense. I'll get a PR and test together.

**Comment by derms** [comment]
thanks @rjrudin

**Comment by rjrudin** [comment]
Created - https://project.marklogic.com/jira/browse/DHFPROD-2588 

PR - https://github.com/marklogic/marklogic-data-hub/pull/2572

**Comment by aebadirad** [comment]
Fixed in 5.0.1
