### ISSUE TITLE
Have the ingest flow support the properties that mlcp also supports

### ISSUE THREAD

**Issue by peetkes** [marklogic/marklogic-data-hub#2586]
In an ingest flow I cannot specify properties like delimiter, delimited_root_name, uri_id, input_file_pattern etc.
It would be very convenient for flow users to be able to also specify these props on an ingest flow.
This request is for DHF5.0.0

**Comment by ayuwono** [comment]
We plan to address this on 5.1.0: https://project.marklogic.com/jira/browse/DHFPROD-2327

**Comment by rjrudin** [comment]
We have a variety of internal tickets to track various features for ingestion, though it's unlikely it will ever support everything that mlcp does.
