### ISSUE TITLE
Quickstart Initialization of 2nd Datahub installation

### ISSUE THREAD

**Issue by masyukun** [marklogic/marklogic-data-hub#2599]
#### The issue

If you install a 2nd instance of Datahub using Quickstart, but with a different datahub name, it will reuse the same port numbers and fail in its installation process. 

The UI fails in an ugly way, without any useful debugging information: just a blank, dark blue box. 

The output from the java console indicates a failure, but no root cause:

```
Checking MarkLogic Installation:
	AppServers:
		Staging: MISSING
		Final:   MISSING
		Jobs:     MISSING
	Databases:
		Staging: MISSING
		Final:   MISSING
		Jobs:     MISSING
	Databases Indexes:
		Staging Triples Index : MISSING
		Staging Collection Lexicon : MISSING
		Final Triples Index : MISSING
		Final Collection Lexicon : MISSING
	Forests
		Staging: MISSING
		Final:   MISSING
		Jobs:     MISSING
	Core Hub Databases:
		Modules: MISSING
		Staging Schemas: MISSING
		Staging Triggers: MISSING


OVERALL RESULT: NOT INSTALLED

19:16:18.219 [http-nio-8080-exec-7] INFO  com.marklogic.hub.impl.DataHubImpl - 
Checking MarkLogic Installation:
	AppServers:
		Staging: MISSING
		Final:   MISSING
		Jobs:     MISSING
	Databases:
		Staging: MISSING
		Final:   MISSING
		Jobs:     MISSING
	Databases Indexes:
		Staging Triples Index : MISSING
		Staging Collection Lexicon : MISSING
		Final Triples Index : MISSING
		Final Collection Lexicon : MISSING
	Forests
		Staging: MISSING
		Final:   MISSING
		Jobs:     MISSING
	Core Hub Databases:
		Modules: MISSING
		Staging Schemas: MISSING
		Staging Triggers: MISSING


OVERALL RESULT: NOT INSTALLED
```

####What behavior are you expecting?
Since I'm providing server connectivity and user/pass information, I expect Quickstart to use ports that are free on the server by default. 

This will likely require an eval query to enumerate the appservers that already exist and find the first free 3 contiguous ports.

#### Tech details

Which Operating System are you using? macOS Mojave 10.14.5

Which version of MarkLogic are you using? 9.0-9.1

Which version of the Data Hub Framework are you using? 5.0.0

Is this a QuickStart UI bug? If so, which browser are you using? Yes. Chrome

**Comment by ayuwono** [comment]
Agree that we should provide a better error, will log an issue.

For a workaround, I can spin up a 2nd data hub instance by changing the ports manually from QuickStart Advanced Settings:
1) On 2nd installation (browse to a new project folder), change the data hub name
2) Expand the Advanced Settings menu and change the ports for staging, final, and jobs dbs
3) Start the installation

**Comment by ayuwono** [comment]
JIRA: https://project.marklogic.com/jira/browse/DHFPROD-2613

**Comment by rjrudin** [comment]
@masyukun @ayuwono There are 2 different expectations in this ticket:

1. QS should provide a better error message when there's a port conflict
1. QS should scan for open ports when there's a port conflict

I think the first is reasonable to do, but I don't think it's necessary to invest in the second. Would that be sufficient for resolving this ticket?

**Comment by rjrudin** [comment]
Closing, as QS is not being enhanced to scan for open ports
