### ISSUE TITLE
MLCP Command for CSV files is generated incorrectly 

### ISSUE THREAD

**Issue by alan-johnson** [marklogic/marklogic-data-hub#261]
The MLCP command line is being generated incorrectly for Delimited Text. The command line has no command after "mlcp.sh" as the first argument. Instead, an "-import" command line option is generated which is incorrect and causes MLCP to fail.  Generated command line attached in text document.
[mlcp-bug.txt](https://github.com/marklogic/marklogic-data-hub/files/443349/mlcp-bug.txt)

**Comment by paxtonhare** [comment]
@alan-johnson are you using rc.3?

**Comment by alan-johnson** [comment]
Sure am, Paxton. I’m going to be rerunning some tests tonight so if there’s something you’d like me to verify, grab messages, etc., I’d be happy to do so.
