### ISSUE TITLE
Data hub admin needs xdmp:value privilege to run flow containing mapping step

### ISSUE THREAD

**Issue by brent-hartwig** [marklogic/marklogic-data-hub#2625]
#### The issue

A data hub admin is unable to run a flow that a flow operator is able to run.  Turns out the data-hub-admin-role needs the xdmp:value privilege.

#### Tech details

Which Operating System are you using?  Windows Pro 10.0.17763 Build 17763

Which version of MarkLogic are you using?  9.0-9

Which version of the Data Hub Framework are you using?  5.0.0

Is this a QuickStart UI bug? If so, which browser are you using?  Doubtful but just in case: FF 67.0.1, 64-bit.

```
bhartwig@here MINGW64 /c/workspaces/ws-data-hub-5-sandbox/take-1
$ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (Zulu 8.38.0.13-CA-win64) (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (Zulu 8.38.0.13-CA-win64) (build 25.212-b04, mixed mode)

bhartwig@here MINGW64 /c/workspaces/ws-data-hub-5-sandbox/take-1
$ ./gradlew -version

------------------------------------------------------------
Gradle 5.2.1
------------------------------------------------------------

Build time:   2019-02-08 19:00:10 UTC
Revision:     f02764e074c32ee8851a4e1877dd1fea8ffb7183

Kotlin DSL:   1.1.3
Kotlin:       1.3.20
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_212 (Azul Systems, Inc. 25.212-b04)
OS:           Windows 10 10.0 amd64
```

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

QuickStart output follows.  It includes the start up entries and two runs of the same flow.  The first run was performed by a flow operator and was successful.  The second run was performed by a data hub admin and failed.  9:35:01 separates the two runs.

[myoutput.txt](https://github.com/marklogic/marklogic-data-hub/files/3266144/myoutput.txt)

The error message:

```
{"stack":"Error: SEC-PRIV: Need privilege: http://marklogic.com/xdmp/privileges/xdmp-value\n at Error (native)\n at main (/data-hub/5/builtins/steps/mapping/default/main.sjs:88:11)\n at Flow.runMain (/data-hub/5/impl/flow.sjs:374:12)\n at Flow.runStep (/data-hub/5/impl/flow.sjs:319:60)\n at Flow.runFlow (/data-hub/5/impl/flow.sjs:202:12)\n at post (/data-hub/5/extensions/runFlow.sjs:69:25)\n at callExtension (/data-hub/5/rest-api/lib/extensions-util.sjs:94:30)\n at applyOnce (/data-hub/5/rest-api/lib/extensions-util.sjs:112:10)","message":"SEC-PRIV: Need privilege: http://marklogic.com/xdmp/privileges/xdmp-value","name":"Error"}
```

List of privileges granted to the two users...

[my-flow-operator-user-privileges.txt](https://github.com/marklogic/marklogic-data-hub/files/3266223/my-flow-operator-user-privileges.txt)
[my-data-hub-admin-user-privileges.txt](https://github.com/marklogic/marklogic-data-hub/files/3266224/my-data-hub-admin-user-privileges.txt)

[project-extract.zip](https://github.com/marklogic/marklogic-data-hub/files/3266264/project-extract.zip) contains most of my data hub project.  I excluded other entities, flows, and mappings.  Sample data may be found within input/employee.

**Comment by aebadirad** [comment]
Current workaround until a fix is to grant the user the flow operator role.

**Comment by rjrudin** [comment]
Closing as this role is deprecated
