### ISSUE TITLE
Smart mastering issue for mutplie document matches taking long time

### ISSUE THREAD

**Issue by debashissinha** [marklogic/marklogic-data-hub#2628]
Hi @ryanjdew
I would like to draw your kind attention to an issue occurring while doing smartmastering.

a) I have created five JSON document . For Understanding sake let me call them as Employee1.json, Employee2.json , Employee3.json, Employee4.json,Employee5.json .

b) Employee1 and Employee4 has all the value same 
c) Employee2 has values which does not matches with any five document
d) Employee3 and Employee5 have values which partially match . That is to say if There are five fields in the json three of them have similar values rest two are different and does not matches with those fields in any of the five document.
e) I have created two thesolds one for exact match and one for partial match.
f) After this when I run mastering it times out after 8 minute .
g) But if I work with only two document where all the properties matches it gives me the result in  3 to 4 sec.

Can you kindly help to advise if anything is going wrong here from my side.

Your valued advise would be of great help.

Thanks & Regards
Debashis Sinha

**Comment by ryanjdew** [comment]
Hi @debashissinha,

Can you check the MarkLogic Server Logs for any errors that may have been thrown? The most likely place you would find an error is in the final app server error log (assuming default ports haven't been changed and running from localhost, it can be found at http://localhost:8001/get-error-log.xqy?filename=8011_ErrorLog.txt). If you find nothing there, please check the staging app server error log (http://localhost:8001/get-error-log.xqy?filename=8010_ErrorLog.txt).

Thanks!

**Comment by debashissinha** [comment]
reference to https://github.com/marklogic-community/smart-mastering-core/issues/317  closes the issues
