### ISSUE TITLE
Demo Enhancement Request: Show triples being used to relate different entities

### ISSUE THREAD

**Issue by nizdobs** [marklogic/marklogic-data-hub#264]
The current demo does a good job showing how an individual entity can be harmonized across multiple data sources. But it doesn't yet show how different entities would be queried. In order to do that we'd need a new entity and some triples that express the relationship between the entities.

From a demo story perspective I propose that we tell the story about AcmeTech/GlobalCorp wanting to check their employee salaries against other public standards. So they relate their existing job titles to publicly available public sector titles/pay scales. I've updated the demo EmployeeTable.csv to show mocked up comparable public sector pay grades and created GS-Scale.csv which shows the salary range of each pay grade. 

Once these entities are related you could then query to find which employees make more than the GS scale would dictate and who makes less than the scale would dictate.

-- Github wouldn't let me attach a csv file as an attachment so I've renamed them txt to attach them
[EmployeeTable.txt](https://github.com/marklogic/marklogic-data-hub/files/457248/EmployeeTable.txt)
[GS-Scale.txt](https://github.com/marklogic/marklogic-data-hub/files/457249/GS-Scale.txt)

**Comment by sbayatpur** [comment]
Closing this ticket, as this request is specific to a DHF 4 demo, and we are now focused on enhancements to DH 5 only. We'll take this request into account for enhancements to the DH 5 examples.
