### ISSUE TITLE
QuickStart fails because of missing, empty directories

### ISSUE THREAD

**Issue by dmcassel** [marklogic/marklogic-data-hub#2659]
#### The issue

Short description of the problem:

The team upgraded a DHF 4.3.1 project to 5.0.0. I pulled origin master, tried to use 5.0.0 Quick Start to connect. It found my environment files; I selected dev and provided my credentials, but the login failed. The Java console has an error message about a missing directory. 

What behavior are you expecting?

Successful login. 

#### Tech details

Which Operating System are you using?

Windows 10 Enterprise

Which version of MarkLogic are you using?

9.0-9

Which version of the Data Hub Framework are you using?

4.3.1 -> 5.0.0

Is this a QuickStart UI bug? If so, which browser are you using?

Yes; Chrome. 

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

The missing directories were `flows`, `mappings`, and `step-definitions`. Once I'd created all three, QuickStart ran fine, but if any were missing, I'd get an error. 

[debug.txt](https://github.com/marklogic/marklogic-data-hub/files/3283221/debug.txt)

**Comment by brucean52** [comment]
JIRA ticket: https://project.marklogic.com/jira/browse/DHFPROD-3089

**Comment by srinathgit** [comment]
The upgrade from 4.3.1 to 5.0.0 should create all the 3 directories you had mentioned. Were these directories removed by any chance ?

**Comment by dmcassel** [comment]
I ran into this when I cloned a repo that a colleague had made and tried to deploy. Git doesn't like empty directories.

**Comment by kkanthet** [comment]
I don't see this issue happening with upgrade from 43.x to 5.1.0 or 5.2.0 as during upgrade, all the required directories (./flows, ./entities,./step-definitions) are all created. I tested in 4.3.x dir and the dirs are created fine and the project watch service gets initialized as expected when logging into QS.
