### ISSUE TITLE
hubUpdate didn't update the version number

### ISSUE THREAD

**Issue by s3-4v** [marklogic/marklogic-data-hub#2665]
After running the hubUpdate task, it was necessary to manually update the mlDHFVersion property in gradle.properties to "5.0.0" in order for QuickStart to recognize the deployed data hub as upgraded. This was an upgrade performed on a DHF 4.3.1 project on MarkLogic Server 9.0-9. Please let me know if I can provide any information that would be helpful, thanks.

**Comment by s3-4v** [comment]
The upgrade docs for 4.2.x or 4.1.x to 4.3 do specify this in the procedure, but I don't see any similar step in the 4.3.x to 5.0.0 upgrade docs.

**Comment by eltesoro-ml** [comment]
Fixed. 
Published in https://docs.marklogic.com/datahub/upgrade.html.
Thank you for reporting the issue.
