### ISSUE TITLE
Opening large xml or json files crashes quick-start on 5.0.0. 6.02 mb doc causes a crash ever time I attempt to open it.

### ISSUE THREAD

**Issue by ilan1rosenbaum** [marklogic/marklogic-data-hub#2694]
#### The issue

Short description of the problem: all of quick-start crash's when I open larger files.

What behavior are you expecting? = It to show me my json file

#### Tech details

Which Operating System are you using? mojave

Which version of MarkLogic are you using?

Which version of the Data Hub Framework are you using?

Is this a QuickStart UI bug? If so, which browser are you using?

**Comment by ayuwono** [comment]
@ilan1rosenbaum do you see any error on bootrun or browser console?

**Comment by ilan1rosenbaum** [comment]
@ayuwono no, quick-start just freezes and theres no record of an error in the console, page stops responding. If I close quick-start browser page and reopen it the page works fine as long as i don't try and open a large file again.

**Comment by aebadirad** [comment]
Can we get a copy of the xml/json files?

**Comment by ilan1rosenbaum** [comment]
[Meters_100102414.xml.zip](https://github.com/marklogic/marklogic-data-hub/files/3303244/Meters_100102414.xml.zip)


heres one of them

**Comment by srinathgit** [comment]
I am able to open the file but it takes a few seconds (approx 30-40 secs) for the page to load

**Comment by aebadirad** [comment]
There may be ways to enhance performance so those docs can be seen, or at least truncated in a way that lets the user view it reasonably well.

**Comment by sbayatpur** [comment]
Tracking with this Jira issue: https://project.marklogic.com/jira/browse/DHFPROD-2700

**Comment by aebadirad** [comment]
Released as part of 5.0.2.
