### ISSUE TITLE
DHF 5.0.0 and 5.0.1: Scroll to the top in directory lists

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#2696]
#### The issue
When I am navigating with QuickStart into a directory structure, the loaded list does not start at the top. I can reach the top of the list to orient myself by scrolling to the top, but I would have expected to start at the top and not somewhere in the middle.

![dhf-scrollToTheTop](https://user-images.githubusercontent.com/1315891/59682799-f2761600-91a4-11e9-920c-d629e97f601a.gif)

#### Tech details

Which Operating System are you using?
MacOS 10.14

Which version of MarkLogic are you using?
9.0.9

Which version of the Data Hub Framework are you using?
5.0.0 or 5.0.1

Is this a QuickStart UI bug? If so, which browser are you using?
Yes.

**Comment by ayuwono** [comment]
Tracking this on JIRA: https://project.marklogic.com/jira/browse/DHFPROD-2694

**Comment by aebadirad** [comment]
addressed in #2748

**Comment by aebadirad** [comment]
Released as part of 5.0.2.
