### ISSUE TITLE
RFE: No default "data-hub" naming

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#2698]
#### The issue
I support several "data-hub" projects.
It is easiest for development for me to pull down the git repo of the data-hub project and use QuickStart to check out the code.
With the default for a new data-hub project being "data-hub" everyone seems to be accepting the defaults and thereby making it much harder to run different data-hubs for development.

I would like to see the default data-hub name come from the directory the data-hub code comes from.
Therefore I would have the following data-hubs
```
/Users/me/code/zipCodeLookup     (data-hub name: zipCodeLookup)
/Users/me/code/healthCareDemo    (data-hub name: healthCareDemo)
/Users/me/code/dhs-501           (data-hub name: dhs-501)
```

Even if someone else pulled down the code into a different directory, at least the data-hub names would be more unique.

#### Tech details

Which Operating System are you using?
Mac/Linux/Windows

Which version of MarkLogic are you using?
9.0 and wishing for 10

Which version of the Data Hub Framework are you using?
5.0.1

Is this a QuickStart UI bug? If so, which browser are you using?
No.

**Comment by prestonmcgowan** [comment]
The name could still be changed during the creation process, just the default would be more dynamic.

**Comment by rjrudin** [comment]
Closing, it's not likely we'll support this based on folder name
