### ISSUE TITLE
DHF 5.0.1 - Ability to select a file or multiple files during ingestion

### ISSUE THREAD

**Issue by sundarbandepalli** [marklogic/marklogic-data-hub#2709]
I am using DHF 5.0.1. 

Need to have the ability to select a file during ingestion step. My suggestion is show all the files in the folder and a select option next to each file name. The user can click and select the file for processing.

If I have multiple files of different types in the folder structure, it's very confusing to understand which files will be selected for processing. I understand we select source file type as txt or csv. But if I have PDF also in the same directory and I do not want it to be selected for processing.

**Comment by srinathgit** [comment]
If you have a directory with xml, json, pdf files then
if source file type is xml , all xml files in that dir will be processed
if source file type is JSON , all JSON files in that dir will be processed
if source file type is binary , all pdf files (non xml/json/txt/csv)in that dir will be processed

**Comment by sundarbandepalli** [comment]
Fair enough. Here's a use case, I have different files like PDF, XML, TXT. I want to select only the TXT files for processing. There are any number of them. Ability to choose the file and adding to different collections will be intuitive and helpful.

**Comment by wpaven** [comment]
I want the ability to pick an individual file as well.  the reason for this is to demonstrate - where did my data come from?  we want to be able to refer back to the actual source document that was used.  Logging a separate issue to capture this in the provo as well.

**Comment by rjrudin** [comment]
Closing, MLCP should be used for more advanced file ingestion
