### ISSUE TITLE
Allow plugins to know then name of the entity

### ISSUE THREAD

**Issue by jkerr5** [marklogic/marklogic-data-hub#271]
Provide the ability for a plugin to know the name of the entity it is working on. This would allow generic plugins to be written that map the entity names to dynamic configurations that could be loaded from the database.

**Comment by paxtonhare** [comment]
@jkerr5 will this work? I can put the following key/value pairs into the $options map that gets passed to the plugins:

```xquery
    let $options := map:new((
      map:entry("entity", $flow/hub:entity/fn:data()),
      map:entry("flow", $flow/hub:name/fn:data()),
      map:entry("flowType", $flow/hub:type/fn:data())
    ))
```

Then in your plugin you can get them with xquery:

```xquery
map:get($options, "entity")
map:get($options, "flow")
map:get($options, "flowType")
```

or sjs:

```javascript
options.entity
options.flow
options.flowType
```

**Comment by jkerr5** [comment]
That looks great Paxton.
