### ISSUE TITLE
Ability to harmonize from multiple sources into a single entity

### ISSUE THREAD

**Issue by sundarbandepalli** [marklogic/marklogic-data-hub#2711]
#### The issue
As an example: I have 2 files: Patient and Admissions. I ingest the files, data is in staging and want to create a single entity called 'Patient' and expose all the fields. expose only 1 patient ID from Patient information from staging, all the other fields from Patient and only 3 out of 4 fields from Admission. 

- Patient contains the following fields ([PatientID] - a unique ID representing a patient.
[PatientGender] - Male/Female.
[PatientDateOfBirth] - Date Of Birth.
[PatientRace] - African American, Asian, White.
[PatientMaritalStatus] - Single, Married, Divorced, Separated, Widowed.
[PatientLanguage] - English, Icelandic, Spanish.
[PatientPopulationPercentageBelowPoverty] - given in %.)

- Admission contains the following field ([PatientID] - a unique ID representing a patient.
[AdmissionID] - an admission ID for the patient.
[AdmissionStartDate] - start date.
[AdmissionEndDate] - end date.)

What behavior are you expecting?
During mapping, I want to have a drop down of all the fields on the source side. I have already exposed the fields by defining them in the entity stage. 

What is happening currently - If I select patient as the ingested source and run the mapping all fields get mapped. But if I do a second mapping with admission (since I cannot see the admission fields) - some of the fields are having null values in them.

Which Operating System are you using? MacOS

Which version of MarkLogic are you using? ML 9

Which version of the Data Hub Framework are you using? DHF 5.0

Is this a QuickStart UI bug? If so, which browser are you using? Chrome.

**Comment by ayuwono** [comment]
As of right now, we can't do N to 1 mapping yet

You can ingest both datasets, map them onto two separate mapping collections, then run a mastering step (set the source collections from both mapping collections) with the match on PatientIDs (assuming both are exactly the same). You will get a new collection of merged documents that show all properties

**Comment by ayuwono** [comment]
As of right now, we can't do N to 1 mapping yet

You can ingest both datasets, map them onto two separate mapping collections, then run a mastering step (set the source collections from both mapping collections) with the match on PatientIDs (assuming both are exactly the same). You will get a new collection of merged documents that show all properties

**Comment by aebadirad** [comment]
Another way you could handle this is a custom step, where you anchor on one document via a search (say the patient collection), and then do a search for the matching ID, and then harmonize them together in one step.

It depends on what stage can the docs see each other and if there's a permission/security concern with that. If the same process cannot see both docs to make the merged document, then you will have to go with the above mentioned comment and perform two mappings, to create two incomplete entities, then master them based on an exact match to the patient ID.

It depends on your scenario and needs.

**Comment by sundarbandepalli** [comment]
I think we have to go the custom step way. mapping into intermediate entities is not as simple. I am working off a sample data set. patient has 100 records, admissions has 372 records. If I have a lot of records, this intermediate process will not be very appealing to customers. All I am doing is just repeating the ingestion step but saying its mapping step. Anyway, now I am stuck at match and merge. 

When will this feature be made available?

**Comment by sbayatpur** [comment]
To clarify, custom steps are available now, but you have to add the code yourself: https://docs.marklogic.com/datahub/flows/configure-custom-step-using-quickstart.html

In terms of product direction, the recommendation will be to map them into intermediate entities and then merge, but I understand your concern regarding transactions/performance, and we'll need to do more work to optimize that process.

In the interim, we can add an example that demonstrates how to 'harmonize from multiple sources into a single entity' through a custom step. Here's the Jira ticket associated with that example: https://project.marklogic.com/jira/browse/DHFPROD-2729

**Comment by kkanthet** [comment]
Closing this issue , Example available  as part of 5.0.2 release
