### ISSUE TITLE
Custom step scaffolding needs better comments on mutability/immutability

### ISSUE THREAD

**Issue by mariannemyers** [marklogic/marklogic-data-hub#2714]
The main.sjs that pops out when a custom step is created can be improved to help novices (and @mariannemyers) get started with making additions and modifications.  Comments should be added that explicitly explain how to make the instance mutable via toObject() along with a simple example that adds an attachment.  If time permits, a sample for headers and triples could be useful, too.

**Comment by wooldridge** [comment]
@mariannemyers thanks for the feedback, additional comments would be good. We're also going to be adding the following to the examples folder of the project which shows some of what you're describing:

https://wiki.marklogic.com/display/ENGINEERING/Data+Hub+MLW+2019+Session+Demo#DataHubMLW2019SessionDemo-AddCustomStep(GeospatialEnrichment)

**Comment by rjrudin** [comment]
Tracking internally via DHFPROD-7019
