### ISSUE TITLE
QuickStart 5: Use a more descriptive ascii art name

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#2715]
#### The issue
I am running Data Hub 5.0.0

```

  __  __            _    _                _
 |  \/  | __ _ _ __| | _| |    ___   __ _(_) ___
 | |\/| |/ _` | '__| |/ / |   / _ \ / _` | |/ __|
 | |  | | (_| | |  |   <| |__| (_) | (_| | | (__
 |_|  |_|\__,_|_|  |_|\_\_____\___/ \__, |_|\___|
  ____        _          _   _      |___/    ____
 |  _ \  __ _| |_ __ _  | | | |_   _| |__   | ___|
 | | | |/ _` | __/ _` | | |_| | | | | '_ \  |___ \
 | |_| | (_| | || (_| | |  _  | |_| | |_) |  ___) |
 |____/ \__,_|\__\__,_| |_| |_|\__,_|_.__/  |____/



Starting. Please wait...

```

So why does this say 5 instead of 5.0.0?

#### Tech details

Which Operating System are you using?
Mac OS

Which version of MarkLogic are you using?
9.0-9

Which version of the Data Hub Framework are you using?
5.0.0

Is this a QuickStart UI bug? If so, which browser are you using?
Bug, not as much as clarification request :-)

#### The devil is in the details...
Sugar isn't always bad for you

**Comment by prestonmcgowan** [comment]
https://en.wikipedia.org/wiki/FIGlet

**Comment by brucean52** [comment]
We accept PRs if you want to add some sugar :)

**Comment by rjrudin** [comment]
Closing as it's QS
