### ISSUE TITLE
Quick Start does not provide an option to specify "update" option for custom modules

### ISSUE THREAD

**Issue by gvaidees** [marklogic/marklogic-data-hub#2722]
**Short description of the problem:** 
Custom modules can do updates. Default is assumed to be query mode. Custom step definition supports an option to specify that a custom module will be doing updates via the "stepUpdate" property, set under "options". This option is not exposed via QuickStart. 

Custom module developer can "declareUpdate" in their SJS code. But, supporting this in QuickStart would be nice

**What behavior are you expecting?**
Support for options such as "stepUpdate" via QuickStart while defining a step 

**Which Operating System are you using?** Windows

**Which version of MarkLogic are you using?** 9.0-9.1

**Which version of the Data Hub Framework are you using?** 5.0.1

**Is this a QuickStart UI bug? If so, which browser are you using?**
Not a bug. RFE. Chrome/FF

**Comment by brucean52** [comment]
JIRA ticket: https://project.marklogic.com/jira/browse/DHFPROD-3091

**Comment by kkanthet** [comment]
Will not be Fixed.
