### ISSUE TITLE
DHF 5.0.1 - adding multiple steps and ability to reorder steps (numbering)

### ISSUE THREAD

**Issue by sundarbandepalli** [marklogic/marklogic-data-hub#2724]
When you add multiple steps to the same flow, the new step should be added to the end of the flow. Currently after 4 or 5 steps, any new step we add it gets moved to the 2nd spot. 

From a flow perspective this is confusing. There is a sequence as you are logically defining the steps.

- A new step should be added to the end

- Ability to change the order of steps by selecting numbers.

**Comment by sundarbandepalli** [comment]
Also, once you have 9 steps in a flow, you cannot rearrange steps 8 and 9. I can still switch 8 to 7. but 8 to 9 does not happen.

**Comment by aebadirad** [comment]
This should be resolved (as well as having more than 9 steps!) as part of 5.0.2.
