### ISSUE TITLE
Setting up on Mac causes an issue with .war file

### ISSUE THREAD

**Issue by tpiros** [marklogic/marklogic-data-hub#273]
Trying to setup the app following the instructions. Getting to this stage`$ java -jar quick-start-1.0.0-rc.4.war` would thrown the following error:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/marklogic/quickstart/Application : Unsupported major.minor version 52.0
```

Further info:

```
$ java -version
java version "1.7.0_75"
Java(TM) SE Runtime Environment (build 1.7.0_75-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.75-b04, mixed mode)
```

**Comment by grechaw** [comment]
I don't know whether it's official or not for this project, but Java 8 is becoming more and more the default for our projects.   This error means that the jar was compiled for Java 8 (which may be considered a bug depending on @paxtonhare intentions)

**Comment by tpiros** [comment]
Thanks @grechaw - I'll upgrade to Java 8 but if this is indeed a requirement please state that somewhere in the instructions. Let's see what @paxtonhare has to say :) 🌴

**Comment by tpiros** [comment]
confirmed that with Java 8 the setup works. Will wait for @paxtonhare to comment before closing issue.

**Comment by paxtonhare** [comment]
It requires Java 8. Let's leave this open as a ticket to update the requirements list.
