### ISSUE TITLE
No documentation for hubCreateFlow task

### ISSUE THREAD

**Issue by crism** [marklogic/marklogic-data-hub#2731]
#### The issue

[The list of Data Hub Gradle tasks](https://docs.marklogic.com/datahub/tools/gradle/gradle-tasks.html) does not include `hubCreateFlow`. I believe it is a new DHF 5 task, and if so, it should be documented; if not, it should be listed among the legacy tasks.

#### Tech details

Which version of the Data Hub Framework are you using? 5.0.1

**Comment by sbayatpur** [comment]
It is documented on this page: https://docs.marklogic.com/datahub/flows/create-flow-using-gradle.html

However, you make a good point that it should be listed on the Data Hub Gradle Tasks page as well. Created this Jira issue to add it: https://project.marklogic.com/jira/browse/DHFPROD-2733

**Comment by kkanthet** [comment]
Fixed.
