### ISSUE TITLE
Exception in Quick Start

### ISSUE THREAD

**Issue by tpiros** [marklogic/marklogic-data-hub#274]
After the project folder selection phase in the Quick Start screen clicking the 'next' button would render an Exception in the developer tools:

`EXCEPTION: Error in ./Login class Login - inline template:0:3077`

`ORIGINAL EXCEPTION: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'.`

This stops the application to work completely.

**Comment by paxtonhare** [comment]
@tpiros I believe this will be fixed in the next release.
