### ISSUE TITLE
Set a limit on the query used in a flow

### ISSUE THREAD

**Issue by mariannemyers** [marklogic/marklogic-data-hub#2740]
It would be helpful to have an easy way to set a limit to restrict the number of documents passing into (or through) a flow.  I am testing against a large staging database and I do not want to let it rip against the entire collection.  As a workaround, I added a cts.andQuery() with a cts.pathRangeQuery() directly to the flow file to limit to one known ID.

**Comment by brucean52** [comment]
Tracking this with JIRA ticket: https://project.marklogic.com/jira/browse/DHFPROD-3093

**Comment by RobertSzkutak** [comment]
+1 . 

I have used https://docs.marklogic.com/cts.documentQuery to limit to a known URI or set of known URIs.

Alternatively I'm told you can wrap your source queries in cts.uris and enforce a limit.

**Comment by mariannemyers** [comment]
@RobertSzkutak Great suggestions!  I'll keep that in mind in the meantime.

**Comment by brent-hartwig** [comment]
+1 for this.  I just had the need to test harmonization in an environment that had over 100,000 docs applicable to that step, but only wanted to harmonize 1,000.  Another entity in the same environment has over 2,300,000 docs of the same entity.  My workaround was to temporarily add my 1,000 docs to a new collection, harmonize that collection, then remove those docs from the temp collection.  Thanks.

**Comment by jmakeig** [comment]
How do you determine the 1,000 to run? Are they special from a business perspective (e.g. the worst Bad Guys or the highest value trades) or do you just want a handful to test?

**Comment by brent-hartwig** [comment]
Nothing fancy this time, @jmakeig.  Just had to get some to Clay who was seeing how well they worked with the UI.  Had the sampling not been adequate, I would have selected another range and possibly larger range.

**Comment by rjrudin** [comment]
Closing as it's tracked internally; planning on 5.5 support for this
