### ISSUE TITLE
DHF 5.0.1 RFE: deletion step type

### ISSUE THREAD

**Issue by crism** [marklogic/marklogic-data-hub#2750]
#### The issue

Short description of the problem: Deleting final data should be easier.

What behavior are you expecting? It would be nice to specify a `sourceQuery` and have the matching items be deleted (temporally, if a temporal collection is specified in the `collections` parameter). Code for the step might even be unnecessary, though some further refinement of the deletion candidates might be desirable in some cases.

#### Tech details

Which Operating System are you using? CentOS 7

Which version of MarkLogic are you using? 9.0-9

Which version of the Data Hub Framework are you using? 5.0.1

Is this a QuickStart UI bug? If so, which browser are you using? N/A

**Comment by brucean52** [comment]
JIRA ticket: https://project.marklogic.com/jira/browse/DHFPROD-3094

**Comment by rjrudin** [comment]
Closing since it's in JIRA.
