### ISSUE TITLE
Default Flow and Step Docs Unable to be Read

### ISSUE THREAD

**Issue by gregnist** [marklogic/marklogic-data-hub#2756]
**Short description of the problem:**

- This issue is experienced with MarkLogic 10.0.1 and Data Hub 5.0.1. It does not occur with MarkLogic 9.0.9 and Data Hub 5.0.1.
- When you install a hub, JSON documents are created that represent the default flows and steps.
- Those documents are not given any permissions, therefore they are only readable by users with the admin role.
- When implementing a project using more realistic users, such as a "developer" user who has the "data-hub-admin-role", "flow-developer-role", and "flow-operator-role", they are unable to read those documents and therefore unable to run a flow with an ingestion step.

**What behavior are you expecting?**

- I expect my developer user, as configured, to be able to create and run flows successfully.
- I expect consistent behavior between MarkLogic 9.0.9 and MarkLogic 10.0.1 when using Data Hub 5.0.1
- I have tested my steps using MarkLogic 9.0.9 and Data Hub 5.0.1 and everything works as expected.
- When I test using MarkLogic 10.0.1 and Data Hub 5.0.1 using the same steps is where I have an issue.

**Which Operating System are you using?**
- Centos 7

**Which version of MarkLogic are you using?**
- MarkLogic 10.0.1

**Which version of the Data Hub Framework are you using?**
- Data Hub 5.0.1

**Is this a QuickStart UI bug? If so, which browser are you using?**
- Not a QuickStart bug, but I am using Firefox.

#### The devil is in the details...

Here are the detailed steps I complete, which you can use to test / recreate:

1. Install MarkLogic 10.0.1, initialize the instance and create the admin user.
2. Launch the Data Hub Quick Start version 5.0.1
3. Initialize and install a new hub using the only user that I currently have available, the admin user.
4. Log out of QuickStart and close my session.
5. Use ml-gradle to deploy my desired project specific users and roles.
6. Log in to QuickStart using the new "developer" user (now I can see that the default JSON docs are no longer visible to me in the QuickStart Dashboard view).
7. Create an entity.
8. Create a flow with an ingestion step.
9. Run the flow and fail with this error:

![error](https://user-images.githubusercontent.com/1749707/60901150-71f28480-a23b-11e9-8f3f-c04b48bd9f2b.png)

Checking the permissions on the default flow and step JSON docs in Query Console shows that no permissions are being set on them, which explains why only the admin user is able to see and use them.

**Comment by rjrudin** [comment]
I'm taking a look at this.

**Comment by rjrudin** [comment]
@aebadirad The difference between ML 9 and 10 is that in 9, the flows and steps all get default permissions of rest-reader/read and rest-writer/update. In 10, they do not - they don't have any permissions on them. 

This doesn't seem consistent with the docs for the /v1/documents endpoint - http://docs.marklogic.com/REST/PUT/v1/documents - which state:

"If no permissions are explicitly set, documents you create with the MarkLogic REST API have a read permission for the rest-reader role and an update permission for the rest-writer role. When you explicitly set permissions, they are combined with the default permissions for the role of the current user."

I'm looking to see if there's an easy way to set permissions on flows/steps/entities.

**Comment by rjrudin** [comment]
Opened https://project.marklogic.com/jira/browse/DHFPROD-2772

**Comment by aebadirad** [comment]
Released as part of 5.0.2.
