### ISSUE TITLE
When using data-hub\5\transforms\mlcp-flow-transform the transform can not see the URI or the content running custom module code for Ingestion type

### ISSUE THREAD

**Issue by venuiyengar** [marklogic/marklogic-data-hub#2760]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue
mlcp flow transform fails to write the document ingested as it cannot find the URI or the content

#### Tech details

Which Operating System are you using?
Windows

Which version of MarkLogic are you using?
9.0-8.2
Which version of the Data Hub Framework are you using?
5.0.1
Is this a QuickStart UI bug? If so, which browser are you using?
NO
#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

[transform-issue.txt](https://github.com/marklogic/marklogic-data-hub/files/3374208/transform-issue.txt)

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`
[transform-issue.txt](https://github.com/marklogic/marklogic-data-hub/files/3374209/transform-issue.txt)

**Comment by venuiyengar** [comment]
Issue - Running flow with a step type as INGESTION and with basic code as part of module does not write the document. It says the first 2 argument for xdmp.documentInsert as null
Tech Details
I have a flow attached with 2 step, The first step invoked from gradle task using mlcp (attached snippet of task). The custom module code along with step definition attached.

[mlcp-flow-transform-issue.txt](https://github.com/marklogic/marklogic-data-hub/files/3374203/mlcp-flow-transform-issue.txt)

**Comment by rjrudin** [comment]
I'm taking a look at this.

**Comment by rjrudin** [comment]
Try running mlcp - either via MlcpTask or mlcp.sh - without the -modules_root argument. That seems to cause the error. I was able to get a basic mlcp ingest working with the DHF 5 transform, but once I included modules_root, I got the error that you received.

**Comment by bsrikan** [comment]
I was able to run the ingestion using mlcp with no issues. I ingested a csv doc and the command was:

`mlcp.sh import -mode "local" -host "localhost" -port "8010" -username "flow-developer" -password "flowdev" -input_file_path "/Users/sbalasub/Desktop/ML/DHF/QA/43_On_5/input/orders/" -input_file_type "delimited_text" -output_collections "MLCP" -output_permissions "rest-reader,read,rest-writer,update" -output_uri_replace ".*input,''" -document_type "json" -generate_uri true -transform_module "/data-hub/5/transforms/mlcp-flow-transform.sjs" -transform_namespace "http://marklogic.com/data-hub/mlcp-flow-transform" -transform_param 'options={"outputFormat": "json"},flow-name=LoadOrder,step=3'`

**Comment by venuiyengar** [comment]
The property "-modules_root", "/", as part of mlcp property was causing this issue. The ingestion works fine after removing this property. Having this in DHF 5.0 generates unintended behavior while writing the document.
