### ISSUE TITLE
DHF 5.0.1 - QS annoying alert for missing uri in mapping step

### ISSUE THREAD

**Issue by wpaven** [marklogic/marklogic-data-hub#2762]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:
create a mapping step
map a source doc to the target entity
run the step to harmonize
delete all the content from your databases and redeploy your flows
everytime you gointo the flow prompts with an alert that the URI is missing for the document that was previously used for mapping.  
If you select a new document, it whacks your previous mapping.  If you don't do anything, your cursed with the annoying message constantly popping up.  anything better we can do here?

What behavior are you expecting?

Not this

#### Tech details

Which Operating System are you using? Windows 10

Which version of MarkLogic are you using? 10-0.1

Which version of the Data Hub Framework are you using? 5.0-1

Is this a QuickStart UI bug? If so, which browser are you using? chrome, firefox

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by ayuwono** [comment]
This is a known issue:
https://project.marklogic.com/jira/browse/DHFPROD-2515

The workaround is to delete all mapping files associated with that mapping step

**Comment by kkanthet** [comment]
Issue Fixed in 5.1.0 release
