### ISSUE TITLE
DHF 5.0.1 - RFE QS list filename that document was sourced from in ingest step in provo triples in jobs db

### ISSUE THREAD

**Issue by wpaven** [marklogic/marklogic-data-hub#2763]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue
the source file name is lost in the provo.  IT shops struggle constantly with "where did this record get sourced from" . In QS we want to be able to specify a file in an ingest step, and have the filename reflected in the jobs db in provo so we can demonstrate how easy it is for marklogic to answer that question for them

Short description of the problem:

What behavior are you expecting?  see above

#### Tech details

Which Operating System are you using? windows 10

Which version of MarkLogic are you using? 10.0.1

Which version of the Data Hub Framework are you using? 5.0.1

Is this a QuickStart UI bug? If so, which browser are you using? chrome/firefox

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by brucean52** [comment]
JIRA ticket: https://project.marklogic.com/jira/browse/DHFPROD-3095

**Comment by rjrudin** [comment]
Closing since it's in JIRA.
