### ISSUE TITLE
If you add module_root for mlcp command while using DHF 5.0 you will get null, null error while writing the document

### ISSUE THREAD

**Issue by venuiyengar** [marklogic/marklogic-data-hub#2766]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue
Specifying module_root property as part of mlcp command
Causes null, null error while calling xdmp.documentInsert

What behavior are you expecting?
Ingestion should succeed without an error while writing document

#### Tech details

Which Operating System are you using?
Windows

Which version of MarkLogic are you using?
9.0.-8.2
Which version of the Data Hub Framework are you using?
5.0.1

Is this a QuickStart UI bug? If so, which browser are you using?

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

gradle command  causing this issue
mlcp.bat import -host "localhost" -port "8010" -username "admin" -password "xxxxx"  ^
-input_file_path "data/drugZip"  ^
-output_collections "Drug,loadzipDrug,input"  ^
-output_permissions "rest-reader,read,rest-writer,update"  ^
-output_uri_replace ".*data/drugZip,''"  ^
-document_type "json"  ^
-transform_module "/data-hub/5/transforms/mlcp-flow-transform.sjs"  ^
-transform_param "entity-name=Drug,flow-name=loadDrug,step=1,options={\"finalDbName\":\"data-hub-FINAL\"}" -modules_root "/"

**Comment by venuiyengar** [comment]
Remove module_root property from mlcp command to fix the issue

**Comment by rjrudin** [comment]
@venuiyengar I'm not sure if this ticket is needed - the previous ticket captured that "module_root" was a problem. Is the intent of this ticket that "module_root" not be a problem?

**Comment by venuiyengar** [comment]
Remove module_root property from mlcp command to fix the issue

**Comment by venuiyengar** [comment]
If module_root should not be used we need to deprecate that and update the documentation accordingly.

**Comment by rjrudin** [comment]
But module_root is an mlcp input, not a DHF input, so we can't deprecate it. If there's DHF documentation stating that module_root should be used (https://docs.marklogic.com/datahub/flows/ingest-using-mlcp.html does not mention it), then please identify it so that it can be updated.

**Comment by venuiyengar** [comment]
Agreed, there are no references in DHF, I am closing this issue.
