### ISSUE TITLE
DHF 4.3.1 Timeout

### ISSUE THREAD

**Issue by millerbill3** [marklogic/marklogic-data-hub#2768]
#### The issue

Short description of the problem:
**DHF timeout when inserting document during ingestion**

What behavior are you expecting?
**Ingestion to happen normally**

#### Tech details

Which Operating System are you using? 
**Windows**

Which version of MarkLogic are you using? 
**9.0-8.2**

Which version of the Data Hub Framework are you using? 
**4.3.1**

Is this a QuickStart UI bug? If so, which browser are you using? 
**Unknown, but  using Chrome**

#### The devil is in the details...
The specific scenario is using the UI to run an ingest of a large Excel file (~ 50MB or bigger). The ingestion flow runs document filter and returns the extracted content while also saving the original binary to the database. After a period of time, doc filter finished, the binary is saved, and the doc.json is also saved, but either the UI or MLCP is waiting for some other document to be inserted. Looking at the trace log and output from MLCP the attached image shows the document insertion attempting 14 times before failing. 

![image](https://user-images.githubusercontent.com/6152078/60997934-00433500-a326-11e9-92b5-a60ec36a6713.png)

What document is DHF trying to insert?
It's unknown if this also happens running MLCP directly as I wasn't able to test it.

If possible, rerun the command with -d for debugging output and attach the output: 

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by aebadirad** [comment]
Does this happen without using the DHF transform too?

**Comment by rjrudin** [comment]
Closing due to no response
