### ISSUE TITLE
Document what ml-gradle capabilities are not supported in DHF projects

### ISSUE THREAD

**Issue by aajacobs** [marklogic/marklogic-data-hub#2781]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:  
As a user, I want to understand not just what additional capabilities have been added to ml-gradle to support DHF (as is outlined on https://marklogic.github.io/marklogic-data-hub/refs/gradle-tasks/), but also what core ml-gradle capabilities I should expect to work in DHF projects, or to work differently.  The aformentioned page includes links to the ml-gradle documentation, but neither place specifies exactly what should and should not work.  e.g., mlRestPort is not supported in DHF5 projects.

**Comment by brucean52** [comment]
JIRA Ticket: https://project.marklogic.com/jira/browse/DHFPROD-3085

**Comment by rjrudin** [comment]
Tracking internally in JIRA
