### ISSUE TITLE
DHF 5.0.1 RFE: provide built-in merge strategy to drop null values

### ISSUE THREAD

**Issue by crism** [marklogic/marklogic-data-hub#2786]
#### The issue

Short description of the problem: Harmonizing entities from diverse sources, it’s often the case that different sources will contribute values for different properties. I would like to keep the values where specified, but drop nulls. Currently, I have to write a merge algorithm to do this.

What behavior are you expecting? I would like a built-in merge strategy that will drop null values but otherwise keep all distinct values in a merge.

#### Tech details

Which Operating System are you using? CentOS

Which version of MarkLogic are you using? 9.0-9

Which version of the Data Hub Framework are you using? 5.0.1

Is this a QuickStart UI bug? If so, which browser are you using? N/A

**Comment by brucean52** [comment]
Internal JIRA ticket: https://project.marklogic.com/jira/browse/DHFPROD-3086

**Comment by rjrudin** [comment]
Closing as it's being tracked internally via an open ticket
