### ISSUE TITLE
SmartMaster merge flow not working using Datahub 5.0.1

### ISSUE THREAD

**Issue by venuiyengar** [marklogic/marklogic-data-hub#2789]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Created smart master flow with 1 step. Attached flow. Smart master runs but throws errors while writing merged document. TDE is expecting one authorPreferredName, but multiple authorPreferredName (s) are returned from the merge process

What behavior are you expecting?

Should return maxValue=1 instead of multiple authorPreferredname

#### Tech details

Which Operating System are you using? Windows

Which version of MarkLogic are you using? 9.0.-8.2

Which version of the Data Hub Framework are you using? 5.0.1

Is this a QuickStart UI bug? If so, which browser are you using? NO
[SmartMasteringProcess.flow - Copy.json.txt](https://github.com/marklogic/marklogic-data-hub/files/3403834/SmartMasteringProcess.flow.-.Copy.json.txt)
[sm_out.txt](https://github.com/marklogic/marklogic-data-hub/files/3403839/sm_out.txt)

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by ryanjdew** [comment]
For more context, commonFacets which has the maxValues of 1 set against it is in the document's headers. At this point, it has been attempted to change the property definition in the merge options to use the path property instead of namespace/localname as that is the proper way to target items outside of the envelope instance.

**Comment by ryanjdew** [comment]
Tracking internally with https://project.marklogic.com/jira/browse/DHFPROD-2839

**Comment by venuiyengar** [comment]
I traced through the smart mastering code and it looks like it does read the options specified in the smart mastering flow and then converts that into XML. During the conversion process from JSON to XML it looses the path for commonFacets.

I feel it is good to support both XML and JSON format or allow specifying the merge and/or match files.

Any info on when we will ave a fix for this issue?

**Comment by venuiyengar** [comment]
The json options as part the flow has this path definition
              "property": [
                { "namespace": "", "localname": "personGivenName", "name": "personGivenName" },
                { "namespace": "", "localname": "personSurName", "name": "personSurName" },
                { "namespace": "", "localname": "personName", "name": "personName" },
                { "namespace": "", "localname": "lastestTimeStamp", "name": "lastestTimeStamp" },
                { "namespace": "", "localname": "personMiddleName", "name": "personMiddleName" },
                { "namespace": "", "localname": "topics", "name": "topics" },
                { "namespace": "", "localname": "affiliations", "name": "affiliations" },
                { "namespace": "", "localname": "sources", "name": "sources" },
                { "namespace": "", "localname": "coAuthors", "name": "coAuthors" },
                { "namespace": "", "localname": "institutionPreferredName", "name": "institutionPreferredName" },
                { "namespace": "", "localname": "authorPreferredName", "name": "authorPreferredName" },
                {
                  "path": "/envelope/headers/commonFacets",
                  "name": "commonFacets"
                },

The xml that gets generated in process.xqy has this

    <merge xmlns:merging="http://marklogic.com/smart-mastering/merging" property-name="lastestTimeStamp" max-values="1"/>
    <merge xmlns:merging="http://marklogic.com/smart-mastering/merging" property-name="sources" max-values="1"/>
    <merge xmlns:merging="http://marklogic.com/smart-mastering/merging" property-name="commonFacets" max-sources="1" max-values="1"/>
    <merge xmlns:merging="http://marklogic.com/smart-mastering/merging" property-name="affiliations" max-values="1"/>
    <merge xmlns:merging="http://marklogic.com/smart-mastering/merging" property-name="authorPreferredName" max-values="1"/>
    <merge xmlns:merging="http://marklogic.com/smart-mastering/merging" property-name="coAuthors" max-values="30">

**Comment by rjrudin** [comment]
Closing as this is being tracked internally via an open ticket
