### ISSUE TITLE
Smart Mastering not matching or merging document

### ISSUE THREAD

**Issue by kaaret** [marklogic/marklogic-data-hub#2793]
I setup up a smart mastering project but changed the defaults so the mapping step goes from staging to staging with the Smart Mastering then going from staging to final.

I had both the mapping and smart mastering steps save its results in the customer collection.

When I run the project I get no errors and final is populated but it has the same set of records that are in staging - no matching or merging occurs.  

I copied the original data source and imported it twice to guarantee matches and there are still no matches or merges.

Attached are the entity and flow files

[SmartMastering.flow.zip](https://github.com/marklogic/marklogic-data-hub/files/3407341/SmartMastering.flow.zip)

**Comment by rjrudin** [comment]
Try adding "mdm-content" as a target collection to your mapping steps.

**Comment by rjrudin** [comment]
Closing due to lack of response
