### ISSUE TITLE
Entity definition in data-hub-final/staging-SCHEMAS not found when using a non-admin user

### ISSUE THREAD

**Issue by ijovanov** [marklogic/marklogic-data-hub#2800]
**Short description of the problem:**

- Entity definition file gets in staging-schemas and final-schemas without any permissions
- If a .mapping.json refers to an entity via "targetEntityType" property it ends up in schemas database of FINAL/STAGING database looking for a given entity definition
- When a user gets changed from admin to flow-developer or flow-operator the entity definition cannot be found and running the flow results in an error

**What behavior are you expecting?**

- I expect that the flow runs to the completion also with non-admin users such as flow-developer or flow-operator

**Which Operating System are you using?**

Local development - MacOS Mojave

**Which version of MarkLogic are you using?**

MarkLogic 9.0-9.1

**Which version of the Data Hub Framework are you using?**

Data Hub 5.0.1

**Is this a QuickStart UI bug? If so, which browser are you using?**

I am using Chrome. It is not QS related.

**The devil is in the details...**

1. Create a flow that uses a default mapping that refers to an entity as follows.
    "targetEntityType": "http://igorpharm.com/Patient-0.0.2/Patient",
2. Try to run the flow as the admin user and check if it runs until the completion (gradle command gradle hubRunFlow -PflowName=ingestHarmonize -Psteps="8,9")
3. Edit your mlUsername and mlPassword to reflect flow-operator or flow-developer user
4. Re-run the flow and check if it runs successfully 

Error:
`"{\"stack\":\"Error: Could not find a target entity: http://igorpharm.com/Patient-0.0.2/Patient\\n    at Error (native)\\n    at main (/data-hub/5/builtins/steps/mapping/default/main.sjs:76:11)\\n    at Flow.runMain (/data-hub/5/impl/flow.sjs:374:12)\\n    at Flow.runStep (/data-hub/5/impl/flow.sjs:319:58)\\n    at Flow.runFlow (/data-hub/5/impl/flow.sjs:202:12)\\n    at post (/data-hub/5/extensions/runFlow.sjs:69:25)\\n    at callExtension (/data-hub/5/rest-api/lib/extensions-util.sjs:94:30)\\n    at applyOnce (/data-hub/5/rest-api/lib/extensions-util.sjs:112:10)\",\"message\":\"Could not find a target entity: http://igorpharm.com/Patient-0.0.2/Patient\",\"name\":\"Error\"}",`

**Comment by aebadirad** [comment]
I believe 5.0.2 should address this, though in general this is caused by an admin user modifying things as the admin user has no permissions associated with it (secure by default), so a good practice is never to actually use admin to modify data hub contents.

That being said, 5.0.2 should now apply default permissions on the entity artifacts.
