### ISSUE TITLE
DHF 5.0.1: smart mastering errors with multiple values

### ISSUE THREAD

**Issue by crism** [marklogic/marklogic-data-hub#2803]
#### The issue

Short description of the problem: Using the built-in ZIP algorithm with multiple values results in an error:
```
XDMP-ARGTYPE: (err:XPTY0004) cts:json-property-scope-query(xs:NCName("Vendor"), (cts:element-value-query(fn:QName("","zip"), "19175-*", ("lang=en"), 10), cts:element-value-query(fn:QName("","zip"), "02298", ("lang=en"), 5), cts:element-value-query(fn:QName("","zip"), "32690-*", ("lang=en"), 10))) -- arg2 is not of type cts:query
```

What behavior are you expecting? I expect the algorithm to succeed, giving stronger scores for more matches.

#### Tech details

Which Operating System are you using? CentOS 7

Which version of MarkLogic are you using? 9.0-9

Which version of the Data Hub Framework are you using? 5.0.1

Is this a QuickStart UI bug? If so, which browser are you using? N/A

**Comment by crism** [comment]
The development branch has changed a lot since 5.0.1 in this part of the code. I may not be able to send a valid pull request until 5.0.2 comes out, if the problem persists there.

**Comment by sbayatpur** [comment]
@ryanjdew  Is there a corresponding Jira issue for this? If not, can you create one?

**Comment by ryanjdew** [comment]
There isn't a corresponding Jira issue, but the issue has already been resolved in develop and 5.x-develop branches.
