### ISSUE TITLE
DHF 5.0.1: Built-in ZIP matching algorithm only works for XML sources

### ISSUE THREAD

**Issue by crism** [marklogic/marklogic-data-hub#2813]
#### The issue

Short description of the problem: The `zip-match` algorithm provided with Smart Mastering uses `cts:element-value-query()`, which does not work against JSON property values.

What behavior are you expecting? The `zip-match` algorithm should work agnostically against JSON or XML data.

#### Tech details

Which Operating System are you using? CentOS 7

Which version of MarkLogic are you using? 9.0-9

Which version of the Data Hub Framework are you using? 5.0.1

Is this a QuickStart UI bug? If so, which browser are you using? N/A

**Comment by crism** [comment]
This appears to be fixed in the `develop` branch.

**Comment by aebadirad** [comment]
Released as part of 5.0.2.
