### ISSUE TITLE
DHF 5.0 RFE: allow collections to be maintained on a custom step

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#2815]
#### The issue
The user/developer needs to know too much about collections to maintain them properly, and replacing all collections improperly couples custom steps with whatever prior work had taken place in other steps.

The "collections" section of a custom step configuration specifies the full set of collections, but there is no way to preserve existing collections. This means that the writer of a step needs to be aware of, and preserve, all collections added by prior steps. This is tight coupling of the steps.

In particular, if a custom step is run after a Mastering step, one needs to know the rather complex set of collections used in Mastering in order to preserve them.

What behavior are you expecting?
Simple ways to add metadata to documents as they move through steps, without needing to know all prior steps to have a step run properly.

Which version of MarkLogic are you using?
ML 9, DHF 5.0

**Comment by brucean52** [comment]
JIRA ticket: https://project.marklogic.com/jira/browse/DHFPROD-3097

**Comment by rjrudin** [comment]
Closing since it's in JIRA
