### ISSUE TITLE
DHF 5.0.1 - On-no-match action not firing as part of smart mastering options for merge

### ISSUE THREAD

**Issue by venuiyengar** [marklogic/marklogic-data-hub#2820]
### Welcome Hub enthusiast!

Smart mastering matching and merging process is ignoring on-no-match action specified in flow options file

Short description of the problem:
I have specified on-no-match action as below so that unmatched documents collection should be tagged as processed which is not happening.

What behavior are you expecting?

No action being fired to remove and add desired collection

#### Tech details

I have specified on-no-match action as below so that unmatched documents collection should be tagged as processed which is not happening.

                "onNoMatch": {
                 "remove": {
                  "collection": "authorUnprocessed"
                 },
                 "add": {
                  "collection": "authorProcessed"
                 }                 
                },
On this line of code 
let $on-no-match := $merge-options/merging:algorithms/merging:collections/merging:on-no-match
I do see the correct action being pulled from the options file as below:
<on-no-match xmlns="http://marklogic.com/smart-mastering/merging"><remove><collection>authorUnprocessed</collection></remove><add><collection>authorProcessed</collection></add></on-no-match>

However, the processed and unmatched documents remains in their original collection as authorUnprocessed.

Which Operating System are you using? Windows

Which version of MarkLogic are you using? 9.0.8-2

Which version of the Data Hub Framework are you using? 5.0.1

Is this a QuickStart UI bug? If so, which browser are you using? NO

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by venuiyengar** [comment]
<?xml version="1.0"?>
<on-no-match xmlns="http://marklogic.com/smart-mastering/merging">
  <remove>
    <collection>authorUnprocessed</collection>
  </remove>
  <add>
    <collection>authorProcessed</collection>
  </add>
</on-no-match>

**Comment by venuiyengar** [comment]
`<?xml version="1.0"?>
<on-no-match xmlns="http://marklogic.com/smart-mastering/merging">
  <remove>
    <collection>authorUnprocessed</collection>
  </remove>
  <add>
    <collection>authorProcessed</collection>
  </add>
</on-no-match>
`

**Comment by timmytva** [comment]
I think I'm seeing this issue in 5.0.4.  `onMerge` works fine. `onMatch` seems to be ignored.

**Comment by srinathgit** [comment]
This issue has been fixed in 5.1.0 (and 5.1.0-beta)
