### ISSUE TITLE
DHF 4.2.2/DHF 4.3.1 does not support ML 9.0-10

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic/marklogic-data-hub#2827]
Hi, DHF 4.2.2 (and most likely 4.3.1 as well) does not pass the version check.  9.0-10 gets translated into  ver=9010 which is smaler than 9050 (which is 9.0-5). 

I really need a hotfix (4.2.2.1 or 4.2.3 ASAP). 

Also I think it is important to make the version check a WARNING, instead of a showstopper. 

> PreInstall Check: [FAILED]
  ---------------------------------------
  {stagingPortInUseBy=null, finalPortInUseBy=null, stagingPortInUse=false, finalPortInUse=false, safeToInstall=false, serverVersion=9.0-10, jobPortInUseBy=null, jobPortInUse=false, serverVersionOk=false}- PROBLEM: Unsupported MarkLogic Server Version: 9.0-10

**Comment by srinathgit** [comment]
Tracking in https://project.marklogic.com/jira/browse/DHFPROD-2905

**Comment by chaitanya447** [comment]
We are not able to track the issue status from JIRA tool, do we require any special priviliges to access the account. As we are not able to track the issue, could you please share me the current status of the issue?

**Comment by kkanthet** [comment]
Able to run mlDeploy on 9.0-10 and 10.0-1.
