### ISSUE TITLE
Marklogic 9 Content Pump issue

### ISSUE THREAD

**Issue by debashissinha** [marklogic/marklogic-data-hub#2832]
Hi @ryanjdew,

I have been trying to do a MLCP on marklogic 9 installed on  a cluster. I am actually trying to copy data from one collection to another. Both of the collection are in seperate db.  When I am running the same on my local marklogic installation it works fine . But as soon as I try to connect to the clustered marklogic host it gives me an error. Please find attached the sample code.
[mlcpcode.txt](https://github.com/marklogic/marklogic-data-hub/files/3440712/mlcpcode.txt)

I have  also tried using the mlcp utility but it also encounters the same issue .
I used this command 
mlcp.bat copy -mode local -input_host ******* -input_port **** -input_username **** -input_password ***** -output_host ******** -output_port *** -output_username ******* -output_password *******

The issue that I get is  for both the cases is 

**19/07/29 12:59:51 ERROR contentpump.LocalJobRunner: Unable to query source information, no usable hostname found**

Can you kindly help to throw some insight into the issue

**Comment by ryanjdew** [comment]
Hi @debashissinha,

Thanks for filing. This issue would be better filed under the MLCP project at https://github.com/marklogic/marklogic-contentpump/issues.

If you could provide the answer to the following questions in a new ticket under the mlcp-contentpump project, it could help speed things along.

1. Is your cluster behind a VPN and if so, are all members of the cluster reachable from the client running MLCP?
1. Are the names for each of the hosts in the cluster valid DNS names that the MLCP client can use to find the hosts?
1. Is the cluster using SSL/TLS on the app server you're attempting to connect to?

Thanks!

**Comment by debashissinha** [comment]
Closing the issue to reopen in proper category https://github.com/marklogic/marklogic-contentpump/issues/107
