### ISSUE TITLE
Quickstart has outdated link for upgrading hub project

### ISSUE THREAD

**Issue by aajacobs** [marklogic/marklogic-data-hub#2841]
#### The issue

Short description of the problem:  QS 5.0.2's link for "How to update a Hub project" sends you to 4.x docs for upgrading a hub project (https://marklogic.github.io/marklogic-data-hub/upgrade/) instead of the 5.x docs (https://docs.marklogic.com/datahub/upgrade.html). 

What behavior are you expecting?.  QS should link to current documentation. 

<img width="1138" alt="Screen Shot 2019-07-30 at 9 52 04 AM" src="https://user-images.githubusercontent.com/8723378/62135225-d55a5a00-b2af-11e9-9ea8-1ede4e3ddbd5.png">

**Comment by brucean52** [comment]
Internal JIRA ticket created: https://project.marklogic.com/jira/browse/DHFPROD-3083
