### ISSUE TITLE
Include instructions for upgrading from 5.x projects to the current version

### ISSUE THREAD

**Issue by aajacobs** [marklogic/marklogic-data-hub#2842]
Short description of the problem:  Current docs at https://docs.marklogic.com/datahub/upgrade.html don't include instructions for how to upgrade an existing 5.x project to the current 5.x release.

**Comment by brucean52** [comment]
Internal JIRA Ticket: https://project.marklogic.com/jira/browse/DHFPROD-3084

**Comment by rjrudin** [comment]
Is addressed in DHF 5 docs
