### ISSUE TITLE
DHF v1/resources/ml:sjsFlow returns HTTP 200 even when there is a plugin error; impacts NiFi ML ExtensionCallMarkLogic flow file routing on errors

### ISSUE THREAD

**Issue by kmoralesml** [marklogic/marklogic-data-hub#2855]
#### The issue

DHF v1/resources/ml:sjsFlow returns HTTP 200 even when there is a plugin error; impacts NiFi ML ExtensionCallMarkLogic flow file routing on errors

##### What behavior are you expecting?

Given a harmonize flow in sjs
When a plugin error or exception is encountered, and 
When the flow is run via a POST to v1/resources/ml:sjsFlow, 
Then I expect an HTTP error code that is != 200.

#### Tech details

Which Operating System are you using? *ix

Which version of MarkLogic are you using? 9.0-8

Which version of the Data Hub Framework are you using? 3.0

Is this a QuickStart UI bug?  NOT quickstart UI specific.; Mode of automation : all headless gradle; not using QS.

##### Actual behavior

Given a harmonize flow in sjs
When a plugin error or exception is encountered, and 
When the flow is run via a POST to v1/resources/ml:sjsFlow, 
Then I see an HTTP 200 OK, and this has repercussions on *failure detection* because I would have to...
* check the log files
* parse the response body - examining the values "totalCount”, “errorCount", "completedItems", "failedItems" etc 
* when used by the ExtensionCallMarkLogic, failures are still routed to the success queue

##### Output when kicking off harmonize flow via ReST
`* About to connect() to localhost port 8210 (#0)
>*Trying ::1...
>*Connected to localhost (::1) port 8210 (#0)
> POST /v1/resources/ml:sjsFlow?rs:flow-name=harmonize-safety-report-log-only&rs:sup-22429-data-hubdata-hub-FINAL&rs:entity-name=safety-report&rs:identifiers=/safetyreport/maude/7466418.json HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8210
> Accept: */*
> Content-Length: 0
> Content-Type: application/x-www-form-urlencoded
>  ...
> *Server auth using Digest with user 'admin'
> POST /v1/resources/ml:sjsFlow?rs:flow-name=harmonize-safety-report-log-only&rs:sup-22429-data-hubdata-hub-FINAL&rs:entity-name=safety-report&rs:identifiers=/safetyreport/maude/7466418.json HTTP/1.1
> Authorization: Digest username="admin", realm="public", nonce="379688b25d16a6:1cQlmpMVFNx2FssJCf3/XQ==", uri="/v1/resources/ml:sjsFlow?rs:flow-name=harmonize-safety-report-log-only&rs:sup-22429-data-hubdata-hub-FINAL&rs:entity-name=safety-report&rs:identifiers=/safetyreport/maude/7466418.json", cnonce="ICAgICAgICAgICAgICAgICAgICAgICAgICAyNDQ4ODc=", nc=00000001, qop=auth, response="fffd91724f5ab43f0873cd0884e295bd", opaque="732c2280815f6954"
> User-Agent: curl/7.29.0
> Host: localhost:8210
> Accept: */*
> Content-Length: 0
> Content-Type: application/x-www-form-urlencoded
> 
< HTTP/1.1 200 OK
< Server: MarkLogic
< Content-Type: application/json; charset=UTF-8
< Content-Length: 15246
< Connection: Keep-Alive
< Keep-Alive: timeout=5
< 
{"totalCount":1, "errorCount":1, "completedItems":[], "failedItems":["/safetyreport/maude/7466418.json"], "errors":[{"stack":"DATAHUB-PLUGIN-ERROR: Error in a plugin : error in a plugin\nin /MarkLogic/data-hub-framework/impl/flow-lib.sjs, at 626:7
...
`
##### Logs

 The STAGING error log file output
 2019-07-31 09:48:53.346 Info: ["error in runFlow:", "DATAHUB-PLUGIN-ERROR: Error in a plugin : error in a plugin"]

#### References
See also support ticket 22429

**Comment by rjrudin** [comment]
DHF 4 won't be changed to address this and it would be a breaking change; the DHF 4/5 approach (for better or worse) is to store errors in the response and return a 200.
