### ISSUE TITLE
DHF 5.0.1 RFE: constant value mapping rule

### ISSUE THREAD

**Issue by crism** [marklogic/marklogic-data-hub#2858]
#### The issue

Short description of the problem: There’s no way to map a field to a single constant value without custom step code.

What behavior are you expecting? I would like to be able to specify a static value, like:
```json
"type" : {
  "constant" : "SUBCONTRACTOR"
},
```
instead of using the `sourcedFrom` key. This would be useful when ingesting data from multiple sources, where a default value makes sense for everything from one of those sources in its initial mapping step.

Additional enhancements come to mind, like
```json
"type" : {
  "sourcedFrom" : "vendor_type",
  "default" : "SUBCONTRACTOR"
},
```
where the default value is used if the `sourcedFrom` is absent or null.

#### Tech details

Which Operating System are you using? CentOS 7

Which version of MarkLogic are you using? 9.0-9

Which version of the Data Hub Framework are you using? 5.0.1

Is this a QuickStart UI bug? If so, which browser are you using? N/A

**Comment by rjrudin** [comment]
In the DHF 5.1 mapper, this can be done simply via 'SUBCONTRACTOR'.
