### ISSUE TITLE
Enhancement: support for creating REST endpoints

### ISSUE THREAD

**Issue by stuartMoorhouse** [marklogic/marklogic-data-hub#2859]
I would like to be able, using QuickStart or ml gradle, to be able to stub a uri rewriter.

This would be more efficient than hacking a rewritier XML document. It would also enable reuse of rewriter rules and support integration with tools like Swagger hub.

Ideally, the gradle task could take as input an Open API spec and as output produce a "rewriter module" containing the rewriter rules.

**Comment by stuartMoorhouse** [comment]
output: 

`<match-path matches="^/(v1|LATEST)/api/hdap/(patients)/(adverseevents|exposures|labtestresults)?$">
    <add-query-param name="rs:version">$0</add-query-param>
  </match-path>`

**Comment by rjrudin** [comment]
DHF definitely isn't going to support this, as it doesn't have anything to do with DHF. Data Services (created after this ticket was created) may support this eventually.
