### ISSUE TITLE
entities .xml files do not have permissions set

### ISSUE THREAD

**Issue by freshie** [marklogic/marklogic-data-hub#2869]
When deploying DHF 4 flows in DHF 5.0.1 on ML 10.0.1 the .xml files that get created be the server do not have permissions set on them. This means that the flow has to be ran as a user having the admin role. 

an example uri: IE: /entities /employee/inpute/ad-user/ad-user.xml
example content: 
<?xml version="1.0" encoding="UTF-8"?>

<flow xmlns="http://marklogic.com/data-hub">
<name>
ad-users
</name>
<entity>
employee
</entity>
<type>
input
</type>
<data-format>
json
</data-format>
<code-format>
sjs
</code-format>
<main code-format="sjs" module="/entities/employee/input/ad-users/main.sjs">
</main>
</flow>

**Comment by sbayatpur** [comment]
Tracking this here: https://project.marklogic.com/jira/browse/DHFPROD-2976

**Comment by ryanjdew** [comment]
This has been fixed in the 5.0.3 release.
