### ISSUE TITLE
Need a standard way to unit test SMT Default Mastering

### ISSUE THREAD

**Issue by venuiyengar** [marklogic/marklogic-data-hub#2874]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

There is no way to unit test SMT flow with matching and merging options

What behavior are you expecting?
I would like to test SMT and tweak configuration for matching and merging with a small set of data to make sure the functionality is working correctly. 

#### Tech details
In the prior release DHF 4, we were able to load options and call SMT logic. After moving to DHF 5, I can not seem to find a way to accomplish this as some of the SMT functions are not exposed.

Which Operating System are you using? Windows

Which version of MarkLogic are you using?

Which version of the Data Hub Framework are you using? DHF 5.0.1

Is this a QuickStart UI bug? If so, which browser are you using? NO

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by rjrudin** [comment]
We are internally tracking better testing support for OOTB DHF 5 steps.
