### ISSUE TITLE
Default Smart mastering with DHF 5.0.2 generates multiple info block titles

### ISSUE THREAD

**Issue by venuiyengar** [marklogic/marklogic-data-hub#2888]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Multiple Info block titles as part of instance after merge

Short description of the problem:
I am using DHF 5.0.2 and using default mastering. After merge the merge document contains multiple instance.info.title as below

"instance": {
"info": [
{
"title": "Author", 
"version": "0.0.3"
}
, 
{
"title": "Author", 
"version": "0.0.3"
}
]
, 

What behavior are you expecting?

#### Tech details

Which Operating System are you using? Windows

Which version of MarkLogic are you using? 9.0.-8.2

Which version of the Data Hub Framework are you using? 5.0.2
[smt-flowfile.txt](https://github.com/marklogic/marklogic-data-hub/files/3494430/smt-flowfile.txt)

Is this a QuickStart UI bug? If so, which browser are you using?

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by kkanthet** [comment]
@venuiyengar can you please attach complete doc before and after merge ,  If you still have this issue

**Comment by rjrudin** [comment]
Closing due to lack of response
