### ISSUE TITLE
DHF MLCP transform is referencing a role that doesn't exist in DHS

### ISSUE THREAD

**Issue by venuiyengar** [marklogic/marklogic-data-hub#2892]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:
DHF MLCP transform is referencing a role that doesn't exist in DHS

What behavior are you expecting?
Running mlcp to import uses DHF 5 transform and that complains about a role that does not exist in DHS environment

#### Tech details

Which Operating System are you using? Linux

Which version of MarkLogic are you using? 9.0-8.2

Which version of the Data Hub Framework are you using? DHF 5.0.2

Is this a QuickStart UI bug? If so, which browser are you using? NO

#### The devil is in the details...

/home/ec2-user/mlcp-9.0.10/bin/mlcp.sh import -host 10.1.5.154 -port 8010 -ssl true -username ##### -password #### -thread_count 32 -input_file_path 'data/drugZip' -output_collections "Drug,loadzipDrug,input" -output_permissions "rest-reader,read,rest-writer,update" -document_type "binary" -output_uri_replace ".*data/drugZip,''" -output_uri_prefix "/drug" -transform_module "/data-hub/5/transforms/mlcp-flow-transform.sjs" -transform_param "entity-name=Drug,flow-name=loadDrug,step=1,options={\"finalDbName\":\"data-hub-FINAL\"}"

When you execute this from the shell, you will see the issue with roles

19/08/12 17:56:19 WARN contentpump.TransformWriter: Failed document SEC-ROLEDNE: xdmp.permission("flow-developer-role", "update") -- Role does not exist: sec:role-name = flow-developer-role
19/08/12 17:56:20 WARN contentpump.TransformWriter: Failed document SEC-ROLEDNE: xdmp.permission("flow-developer-role", "update") -- Role does not exist: sec:role-name = flow-developer-role
19/08/12 17:56:20 INFO contentpump.LocalJobRunner: com.marklogic.mapreduce.MarkLogicCounter:
19/08/12 17:56:20 INFO contentpump.LocalJobRunner: INPUT_RECORDS: 80
19/08/12 17:56:20 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS: 80
19/08/12 17:56:20 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS_COMMITTED: 65
19/08/12 17:56:20 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS_FAILED: 20
19/08/12 17:56:20 INFO contentpump.LocalJobRunner: Total execution time: 4 sec

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by bsrikan** [comment]
We can close this issue. Venu had confirmed so in an email.
