### ISSUE TITLE
Percentage Match on  text field using Smart Mastering

### ISSUE THREAD

**Issue by debashissinha** [marklogic/marklogic-data-hub#2894]
Hi @ryanjdew 
I have been using smart mastering  for matching two json  documents. I have a particular requirement which calls for matching two fields based on percentage. E.g lets say we have a field called "firstName" in two documents and we intend to match both of them . In one document lets say we have the following text for "firstName" field -> "Frieda Robscheit" and in the second document we have the following text for "firstName" field ->  "Frieda Robscheit-Robbins JR"  .

I have to match both the fields in both the documents if say 30% or 40 % of the text matches . In  my case both the fields are text fields. 

I have searched through the documentation  of smart mastering and felt that may be am looking in the wrong direction . I request you to help me with some useful links or documentation or guide  for smart mastering where this kind of implementation can be found.

Soliciting your kind help here.

Thanks & Regards
Debashis SInha

**Comment by ryanjdew** [comment]
Hi @debashissinha,

Smart Mastering relies on the search indexes to create an initial list of merge candidates. We currently don't have anything out of the box for percentages, but one approach would be to attempt this with wildcards in a custom algorithm. In the given example, you could create a custom algorithm that calculates 40% of the string length and then truncates and appends a wildcard.

```javascript
let value = 'Frieda Robscheit-Robbins JR';
let reducedLength = fn.stringLength(value) * 0.4;
let reducedString = fn.substring(value, 1, fn.ceiling(reducedLength));
let wildcarded = `${reducedString}*`;
wildcarded; // => 'Frieda Robs*'
```

For more details on creating the custom matching algorithms see https://marklogic-community.github.io/smart-mastering-core/docs/custom-match-algorithms/ 

For your example where the starting text is all the same, it should be pretty straight forward. If you are looking for something that will match 40% of the text anywhere in the text, you need to create a series of wildcard queries for the different scenarios. You'll probably want to use the sliding window method. You can read more about that here: https://medium.com/outco/how-to-solve-sliding-window-problems-28d67601a66

This would definitely be a great request for future enhancement.

**Comment by rjrudin** [comment]
Closing as custom match provides a solution
