### ISSUE TITLE
Documentation bug on REST API extension's capability

### ISSUE THREAD

**Issue by aajacobs** [marklogic/marklogic-data-hub#2896]
#### The issue

Short description of the problem:

The docs at https://docs.marklogic.com/datahub/flows/run-flow-using-rest-client-api.html say 

```The REST Client API extension that runs a complete flow or a single step within the flow to process the specified records.```

However the REST Client API extension can not run a complete flow.  It can only run a single step.

Also, this preface on that page is out of place and introduces confusion, as it doesn't relate to the REST extension at all.  Consider moving it to the appropriate section (like QuickStart, which has that behavior, or remove it completely, as the Data Hub itself does not offer this level of orchestration:

```
When running a flow, Data Hub performs the following:

    Calls the collector to get the list of IDs of the records to process.
    Splits the list into batches.
    Calls a custom REST extension that invokes the main.[xqy|sjs] for your flow.
```

**Comment by kkanthet** [comment]
create jira issue and added to backlog for prioritization, https://project.marklogic.com/jira/browse/DHFPROD-3087

**Comment by rjrudin** [comment]
This was addressed by removing this endpoint from the public docs, as it indeed does not run a flow
