### ISSUE TITLE
QuickStart Enhancement: Additional info on preview

### ISSUE THREAD

**Issue by awanczowski** [marklogic/marklogic-data-hub#2908]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem: I would like the ability to see collections, permissions, and document properties about a document in the full preview view

What behavior are you expecting?

#### Tech details

Which Operating System are you using? All

Which version of MarkLogic are you using? 10.0-1

Which version of the Data Hub Framework are you using? 5.0.2

Is this a QuickStart UI bug? If so, which browser are you using? QuickStart Enhancement

**Comment by rjrudin** [comment]
This is being planned for HC
