### ISSUE TITLE
hubDeleteJobs doesn't delete batch docs

### ISSUE THREAD

**Issue by timmytva** [marklogic/marklogic-data-hub#2920]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:

Running ml-gradle task `hubDeleteJobs` with a list of jobIds deletes the jobs docs from the Jobs DB but does not delete the associated batch docs.

What behavior are you expecting?

To delete all artifacts associated with the JobIds from the Jobs database.

#### Tech details

Which Operating System are you using?

Which version of MarkLogic are you using?

10.0-1

Which version of the Data Hub Framework are you using?

5.0.1

Is this a QuickStart UI bug? If so, which browser are you using?

Nope, ran ml-gradle from command line.

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by ryanjdew** [comment]
Thank you for filing this issue. We're tracking it internally with the following JIRA ticket: https://project.marklogic.com/jira/browse/DHFPROD-3112

**Comment by kkanthet** [comment]
Issue Fixed in 5.2.0 release
