### ISSUE TITLE
Flow defs and custom modules go missing after flow runs

### ISSUE THREAD

**Issue by xmlnovelist** [marklogic/marklogic-data-hub#2929]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

I have seen both flow defs and custom modules go missing after flow runs. In my case I was firing hundreds of runFlow calls. The flow would run as called, but when the system had been quiet and I kicked off a new set of runFlow calls, the flow defs and the modules had been deleted (though I haven't yet confirmed by looking for DELETEs in the logs, as @rrudin suggested) I had to call mlDeploy to run the flows again.

Error:

Extension ml:runFlow or a dependency does not exist: XDMP-MODNOTFOUND: cachedModules[moduleLibraryURI] = require(moduleLibraryURI); -- Module /custom-modules/custom/jdeSalesOrderURIStep/main.sjs not found

What behavior are you expecting?

Flows run without redeploying.

#### Tech details

Which Operating System are you using?

CentOS

Which version of MarkLogic are you using?

10.0.1
Which version of the Data Hub Framework are you using?
5.0.2

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by brucean52** [comment]
JIRA ticket: https://project.marklogic.com/jira/browse/DHFPROD-3127

**Comment by srinathgit** [comment]
Are you seeing this issue again ? If so, can you provide 8010, 8011(staging, final server ports) server error and access logs

**Comment by kkanthet** [comment]
We cannot reproduce this issue, please re-open a new ticket of this is still an issue.
