### ISSUE TITLE
DHF2.0.6 does not support ML 9.0-10+

### ISSUE THREAD

**Issue by ltnd** [marklogic/marklogic-data-hub#2932]
When deploying DHF2.0.6 on ML 9.0-10.2, the task hubPreInstallCheck prevent from deploying with the message : 

PreInstall Check: [FAILED]
--
  PROBLEM: Unsupported MarkLogic Server Version: 9.0-10.2
        FIX: Update to a supported version of MarkLogic.
<img width="1047" alt="Screenshot 2019-09-10 at 18 15 24" src="https://user-images.githubusercontent.com/15875379/64632230-fe1a5700-d3f8-11e9-8c8f-04bb1dcf2345.png">

Can you fix it ?

**Comment by kkanthet** [comment]
@ltnd  2.0.6 is not supported any more , can you upgrade to 4.3.1 https://marklogic.github.io/marklogic-data-hub/upgrade/ ?

**Comment by ltnd** [comment]
> @ltnd 2.0.6 is not supported any more , can you upgrade to 4.3.1 https://marklogic.github.io/marklogic-data-hub/upgrade/ ?

Upgrading will be very expensive as we have a lot of customized flows and we will need to do regression testing. We would need a fix on the DHF2.

**Comment by inder** [comment]
Please refer to this version matrix of supported versions:
https://wiki.marklogic.com/display/PM/Support+Matrix+for+Data+Hub

At this point there is no plan to support 2.x release line.

**Comment by inder** [comment]
Also, version compatibility matrix is widely published on MarkLogic website - https://docs.marklogic.com/datahub/refs/version-compatibility.html

**Comment by rjrudin** [comment]
Closing based on above response
