### ISSUE TITLE
Job errors shows and empty message

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#2944]
#### The issue

I ran a flow with errors and when browsing errors got an empty result

What behavior are you expecting?
A description of the errors (which documents faile, what went wrong, etc)

#### Tech details

Which Operating System are you using? osx mojave

Which version of MarkLogic are you using?  9.0-9.1

Which version of the Data Hub Framework are you using?  5.0-2

Is this a QuickStart UI bug? If so, which browser are you using? yes. chrome . 76.0.3809.132

#### setup
test flow with an ingest and mapping step. 
batch size set to 5
run on default input dir (the hub dir itself)
custom step has an artificial error on all the amp files via:

```js
  function main(content, options) {

    //grab the doc id/uri
    let id = content.uri;

    if (id.includes("amp")) throw "ignoring amps";   // force an error for some files
```

#### result
There is no console output. GUI shows:
![image](https://user-images.githubusercontent.com/700633/64784526-53a94d80-d538-11e9-8af5-3281e5eee758.png)

job doc reads:

```json
{
"jobId": "321fc282-c1bd-406f-a585-c531f19e5c98", 
"flow": "test", 
"user": "admin", 
"lastAttemptedStep": "2", 
"lastCompletedStep": "1", 
"jobStatus": "finished_with_errors", 
"timeStarted": "2019-09-12T08:31:22.260471-04:00", 
"timeEnded": "2019-09-12T08:31:24.72689-04:00", 
"stepResponses": {
"1": {
"flowName": "test", 
"stepName": "test", 
"stepDefinitionName": "default-ingestion", 
"stepDefinitionType": "ingestion", 
"stepOutput": null, 
"fullOutput": null, 
"status": "completed step 1", 
"totalEvents": 98, 
"successfulEvents": 98, 
"failedEvents": 0, 
"successfulBatches": 20, 
"failedBatches": 0, 
"success": true, 
"stepStartTime": "2019-09-12T08:31:22.2783-04:00", 
"stepEndTime": "2019-09-12T08:31:23.773416-04:00"
}, 
"2": {
"flowName": "test", 
"stepName": "map", 
"stepDefinitionName": "map", 
"stepDefinitionType": "custom", 
"stepOutput": [
"{}", 
"{}", 
"{}", 
"{}", 
"{}", 
"{}", 
"{}", 
"{}", 
"{}", 
"{}"
], 
"fullOutput": null, 
"status": "completed with errors step 2", 
"totalEvents": 98, 
"successfulEvents": 32, 
"failedEvents": 66, 
"successfulBatches": 8, 
"failedBatches": 12, 
"success": false, 
"stepStartTime": "2019-09-12T08:31:23.793543-04:00", 
"stepEndTime": "2019-09-12T08:31:24.714057-04:00"
}
}
}
```

**Comment by rjrudin** [comment]
Closing as the response above seems correct and no response
