### ISSUE TITLE
DHF 4 upgrade page should link to DHF 5 upgrade

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#2954]
#### The issue

Searching for hub upgrade takes you here: https://marklogic.github.io/marklogic-data-hub/upgrade/ 

but it does not mention DHF 5. 

What behavior are you expecting?
Holistic info on upgrade, perhaps via a link to: https://docs.marklogic.com/datahub/upgrade.html

**Comment by kkanthet** [comment]
Tracking through internal bug https://project.marklogic.com/jira/browse/DHFPROD-3149

**Comment by rjrudin** [comment]
Closing, as DHF 4 docs do have a link to DHF 5 docs
