### ISSUE TITLE
Where is v5.0.2 designed to have triples defined?

### ISSUE THREAD

**Issue by russelltibballs** [marklogic/marklogic-data-hub#2956]
#### The issue

Short description of the problem:

In v4 and prior DH in there is a panel where we define triples for the harmonization process. This does not appear to exist in v5.0.2. The is a custom main.sjs script where I can't see a place to add triples definitions.

What behavior are you expecting?

I actually liked the way the custom java script panels worked in v4 and prior. It was obvious what the intended flow was. I am not a great programmer so I like things to be obvious and not have to think too hard. However if you are changing the way things are intended to work it would be nice to have a pointer as where are the logical points to do the things we did previously in the new world. I am sure I have missed something so please point me in the right direction. If not please update the doco to say where we create triples. 

#### Tech details

Which Operating System are you using? ML and DH on Centos 7

Which version of MarkLogic are you using? 9.1

Which version of the Data Hub Framework are you using? V5..2

Is this a QuickStart UI bug? If so, which browser are you using?

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

N?A

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by aebadirad** [comment]
In the triples section of the instance (when you create a custom step, you'll get a scaffolded module), and you do exactly what you did before in 4.x javascript - create a set of triple objects to stuff in the triples: []. Just here you have more flexibility, and you can add/remove triples at anytime during the execution of the module.

A bit about the envelope we use: https://docs.marklogic.com/datahub/about/envelope-pattern.html
Overview of editing a custom module: https://docs.marklogic.com/datahub/modules/editing-custom-step-module.html
 Quick code example:
` // Example code for using data that was sent to MarkLogic server for the document
  let instance = content.value; // <---- this is your 'instance' content
  let triples = []; //<--- add your triples to this array
//adds a triple object to the triples array
 triples.push({
"triple":{
  "subject": "http://example.org/ns/dir/js/",
  "predicate": "http://xmlns.com/foaf/0.1/firstname/",
  "object": {
    "datatype" : "http://www.w3.org/2001/XMLSchema#string",
      "value":"John"
    }
  };
}
  let headers = {}; // <--- attach your header stuff to this
  //form our envelope here now, specifying our output format
  let envelope = datahub.flow.flowUtils.makeEnvelope(instance, headers, triples, outputFormat);`

**Comment by rjrudin** [comment]
Closing based on above response
