### ISSUE TITLE
Ingestion Step - Does not load files without an extension

### ISSUE THREAD

**Issue by daveegrant** [marklogic/marklogic-data-hub#2958]
#### The issue

Short description of the problem:
Running QuickStart v5.0.2, created a new flow with a single ingestion step.  The input directory includes files that do not have extensions in their file names (e.g. - file1, file2).  When the ingestion step is run from QuickStart, none of the files are ingested.  After renaming one file in the directory to include an extension (e.g. - file1.xml), then running the step again from QuickStart, the 1 file is loaded.

What behavior are you expecting?

Expecting all of the files in the directory to be loaded.  I explicitly indicated that the input files were XML.

#### Tech details

Which Operating System are you using?
Unix (MacOS).

Which version of MarkLogic are you using?
MarkLogic 9.0-8.2

Which version of the Data Hub Framework are you using?
5.0.2

Is this a QuickStart UI bug? If so, which browser are you using?
Believe the issue is DHF rather than QuickStart but not sure.  Using Chrome.

#### The devil is in the details...

Ran QuickStart with the -d flag but there were no messages when the flow was executed.  Also, there were no messages in the MarkLogic ErrorLog files.

**Comment by brucean52** [comment]
JIRA ticket: https://project.marklogic.com/jira/browse/DHFPROD-3187

**Comment by xmlnovelist** [comment]
My ingestion step specified a directory full of files with .xhtml suffixes. The step committed 0 records, however when ran the mlcp command the step generated, it committed the records as expected. When I changed the extensions to xml, the step ran properly.

**Comment by kkanthet** [comment]
Issue Fixed in 5.2.0 release
