### ISSUE TITLE
ResponseHolder MismatchedInputException when Full Output Enabled

### ISSUE THREAD

**Issue by awanczowski** [marklogic/marklogic-data-hub#2963]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem: When setting fullOuput to true there is a deserialization issue with com.marklogic.hub.step.ResponseHolder

[out.txt](https://github.com/marklogic/marklogic-data-hub/files/3627553/out.txt)
 

What behavior are you expecting?

#### Tech details

Which Operating System are you using? Mac OS X

Which version of MarkLogic are you using? 10.0-1

Which version of the Data Hub Framework are you using? 5.0.2

**Comment by ryanjdew** [comment]
Thank you for filing this issue. Tracking internally with JIRA issue https://project.marklogic.com/jira/browse/DHFPROD-3176

**Comment by kkanthet** [comment]
Issue Fixed in 5.1.0 release
