### ISSUE TITLE
NPE from FlowRunnerImpl when multi-threading

### ISSUE THREAD

**Issue by awanczowski** [marklogic/marklogic-data-hub#2971]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:
When multi-threading flow calls we randomly get NPEs from the FlowRunnerImpl when trying to get the StepQueue. I believe it is because the StepQueue is not synchronized. If we synchronize our whole function invoking the call the error goes away. 

https://github.com/marklogic/marklogic-data-hub/blob/master/marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java#L437

What behavior are you expecting?

#### Tech details

Which Operating System are you using? Multiple, Mac OS X and CentOs 

Which version of MarkLogic are you using? 10.0-1

Which version of the Data Hub Framework are you using? 5.0.2

Is this a QuickStart UI bug? If so, which browser are you using? N/A

**Comment by srinathgit** [comment]
@awanczowski ,
Can you provide the code snippet that you are using to run the flows ?

**Comment by awanczowski** [comment]
Sure, I put together a quick example here (https://github.com/awanczowski/marklogic-dmsdk-dhf-combo). This has the 5.0.2 data hub config and a java app that generates records loading them with DMSDK then initializing the flow when the batch is successful. 

To mitigate the NPE I synchronized the function that uses the FlowRunner but it would be ideal to remove the need.
https://github.com/awanczowski/marklogic-dmsdk-dhf-combo/blob/master/demo-loader/src/main/java/com/marklogic/dhf/demo/DataHubFlowRunner.java#L50

**Comment by srinathgit** [comment]
In the first line of description, you mentioned "When multi-threading flow calls ..". What do you mean by that ? The current implementation of FlowRunner runs one flow at a time, if you start multiple flows , it adds it to queue and runs them one by one.

**Comment by awanczowski** [comment]
I believe the WriteBatcher is running on multiple threads. If I remove the on success call to the flow runner is not synchronized it results with an NPE on occasion.

**Comment by srinathgit** [comment]
1. Ok, even if you start flows on multiple threads, the current implementation of FlowRunner is designed to run one at a time. The other flows (apart from the one currently running) will be queued  and run one by one. 
2. We will look into this issue where you hit NPE when starting flows in multiple threads

**Comment by awanczowski** [comment]
Great thanks!

**Comment by rjrudin** [comment]
Closing as the better approach is to create a new FlowRunnerImpl per thread; this is much easier to do in 5.2.0 as FRI does not depend on Spring for usage.
