### ISSUE TITLE
DHF5 Help link takes you to DHF4 help info 

### ISSUE THREAD

**Issue by JackYoungblood** [marklogic/marklogic-data-hub#2973]
In the DHF5.0.2 Entity definition screen there is a question mark icon indicating that help is available (just to the right of the word "Properties"). However, when you click it you are taken to DHF4 help files (https://marklogic.github.io/marklogic-data-hub/refs/index-settings/).

**Comment by brucean52** [comment]
JIRA ticket: https://project.marklogic.com/jira/browse/DHFPROD-3186

**Comment by rjrudin** [comment]
Closing as this is QS
