### ISSUE TITLE
entities tab doesnt work 5.2

### ISSUE THREAD

**Issue by victobiz** [marklogic/marklogic-data-hub#2984]
#### The issue

Short description of the problem:
Going through the tutorials in Windows 10 for our enterprise which uses this in a win10/linux/and mac envioronments. In Hub 5.2 when trying to set a entity via the main tutorial I make the default entity 'company' in this case is set up fine. but when navigating to the 'flow' tab their is no side bar for entities setup. Retroverted to 4.3.2 which had the entity sidebar but when adding a input flow it does not add anything. I retroverted to 4.1.1 that is working as the tutorial describes. not sure if this is already stated in the issues here.

#### Tech details

Which Operating System are you using?
Windows10

Which version of MarkLogic are you using?
10.2 (sep 22 version)

Which version of the Data Hub Framework are you using?
5.2/4.3.2/4.1.1
Is this a QuickStart UI bug? If so, which browser are you using?
google Chrome
#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by kkanthet** [comment]
@victobiz  DHF-5.0.2 will not work on 10.0-2 server , We are working on DHF patch 5.0.3 which will fix the issue. The product team has communicated this known backward incompatibility with 10.0-2

**Comment by rjrudin** [comment]
Closing based on above response
