### ISSUE TITLE
Enhancement request (ability to browse staging data using column name filters)

### ISSUE THREAD

**Issue by sundarbandepalli** [marklogic/marklogic-data-hub#2988]
**Issue** - During ingestion, DHF understands the columns and data type of values that is being ingested i.e. the source file information. 

**Short description of the problem**:
Currently when we say browse in DHF, we can filter only by collection or search. The other options are harmonizing, developing an app etc.

It will be more user friendly 
1) if we can see all columns, datatypes (if its staging by ingested source information), 
2) ability to review a sample of data that are available by collection
3) ability to filter by the corresponding values.
4) Ideally random sampling of data will be very useful. 

As a business user or a power user, the objective is to have an ability to view all the information in a common place (with no dependency on IT) 

**What behavior are you expecting?**
Going back to the source file whether 'csv' or database or writing is not convenient. Need feature enhancement, better usability requests.

#### Tech details

Which Operating System are you using? MAC

Which version of MarkLogic are you using? 9

Which version of the Data Hub Framework are you using? 5.0.2

Is this a QuickStart UI bug? If so, which browser are you using?

**Comment by sbayatpur** [comment]
@yasht2010 I think this could be good context for you as you begin to think about displaying ingested data.

**Comment by rjrudin** [comment]
Being addressed via HC
