### ISSUE TITLE
Additional feedback from REDEPLOY button

### ISSUE THREAD

**Issue by mikeburl** [marklogic/marklogic-data-hub#2993]
#### The issue

After pressing the REDEPLOY button in the flows page users have no way of knowing when the process is complete and flows are ready to be run again.  This can be frustrating for users with slower laptops as they have to go over to query console and refresh the modules database until it's done.

#### Tech details
Datahub version 5.0
Issue occurs on all browsers

**Comment by brucean52** [comment]
JIRA ticket: https://project.marklogic.com/jira/browse/DHFPROD-3220

**Comment by rjrudin** [comment]
Closing since it's QS
