### ISSUE TITLE
Browsing data via DHF

### ISSUE THREAD

**Issue by sundarbandepalli** [marklogic/marklogic-data-hub#2994]
Ability to choose a default database for your project or application remembers last used or selected database.

Staging vs Final. It's a minor enhancement request but will greatly help from a usability and testing perspectives. I am in the process of enhancing a project with flows and steps and each time while testing for results, I have to repeat the same steps. Since, database always defaults to Staging when you click browse data.

**Comment by brucean52** [comment]
JIRA: https://project.marklogic.com/jira/browse/DHFPROD-3221

**Comment by kkanthet** [comment]
Please open a new ticket , if this is still an issue in Hub Central.
