### ISSUE TITLE
Allow MarkLogic NiFi processors to pass arbitrary JSON to data hub step custom hook

### ISSUE THREAD

**Issue by brent-hartwig** [marklogic/marklogic-data-hub#3001]
#### The issue

Short description of the problem:

Ability to pass additional data from NiFi to a data hub step's custom hook.

Pass provenance metadata known within NiFi into the same request to ingest the document, using `PutMarkLogic`.  A custom hook on the data hub ingestion step is already manipulating the headers.  We need to incorporate said provenance data as well.

Looking at `PutMarkLogic`'s source, I was hopeful setting NiFi processor / flowfile properties whose names began with trans:, meta:, and property: would work but did not see those included in the options provided to the custom hook.  **I don't know if the complete solution would require edits within data hub and the NiFi processor.**

Please also consider doing the same for `ExtensionCallMarkLogic` as future requirements for my project or those of another may require provenance or other data to reach a data hub custom step or a data hub custom hook.

I personally haven't thought whether passing arbitrary data to the other ML NiFi processors would make sense.

#### Workaround

As suggested by a colleague, at least for ingestion, one could modify the content of the NiFi flow file to include the additional data, then rearrange or otherwise use in the custom hook. 

#### Tech details

Which Operating System are you using? Amazon Linux AMI

Which version of MarkLogic are you using? 10.0-1 via AWS CFT

Which version of the Data Hub Framework are you using? 5.0.2

Which version of NiFi are you using? 1.9.2

Which version of the ML NiFi processors are you using? 1.8.0.3

Is this a QuickStart UI bug? If so, which browser are you using? N/A

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

N/A

**Comment by rjrudin** [comment]
The better approach is to use a custom ingestion step, or just use a custom REST transform, as an ingestion step is hardly doing anything other than wrapping the data in an envelope.
