### ISSUE TITLE
Batch document timestamp inconsistency 

### ISSUE THREAD

**Issue by awanczowski** [marklogic/marklogic-data-hub#3004]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem: Not sure if this a bug but may be something to investigate. Batch documents have the same start and end time for all flows I run. 

```
stepNumber: "1",
batchStatus: "finished",
timeStarted: "2019-09-27T17:20:26.467525Z",
timeEnded: "2019-09-27T17:20:26.467525Z",
hostName: "2bf6b6ecb0c9",
reqTimeStamp: "2019-09-27T17:20:09.137949",
reqTrnxID: "11867062885122220111",
writeTimeStamp: "2019-09-27T17:20:27.140193Z",
writeTrnxID: "1232685700730914945",
```

What behavior are you expecting? Timestamps to include processing time. 

#### Tech details

Which Operating System are you using? Mac OS X

Which version of MarkLogic are you using? 10.0-1

Which version of the Data Hub Framework are you using? 5.0.2

Is this a QuickStart UI bug? If so, which browser are you using? N/A

**Comment by akshaysonvane** [comment]
Tracking the bug here: https://project.marklogic.com/jira/browse/DHFPROD-3280

**Comment by rjrudin** [comment]
Closing since it's in JIRA
