### ISSUE TITLE
Limitation while browsing data using DHF (bug, enhancement request)

### ISSUE THREAD

**Issue by sundarbandepalli** [marklogic/marklogic-data-hub#3028]
#### The issue
While browsing data using URI using query console, I can see the complete output. However, when I use DHF, it truncates results. 

What behavior are you expecting?
A configurable parameter. As an example, if we want to limit say 5k lines of information or unlimited. It's a choice.

Which Operating System are you using? OS X

Which version of MarkLogic are you using? 9.0-10.3

Which version of the Data Hub Framework are you using? 5.0.3

Is this a QuickStart UI bug? If so, which browser are you using? Chrome.

**Comment by srinathgit** [comment]
There were issues loading the entire results in the browser, hence the decision to truncate them was made

**Comment by rjrudin** [comment]
Supported via HC
