### ISSUE TITLE
Documentation of Rest Extensions..

### ISSUE THREAD

**Issue by bgeorge11** [marklogic/marklogic-data-hub#3032]
https://docs.marklogic.com/datahub/refs/rest-extensions.html  is missing the extension ml:IngestFlow. To make a DHF5 ingest flow work from Nifi, this is the transform module that should be called. Adding this issue for documentation correction.

**Comment by srinathgit** [comment]
A doc bug https://project.marklogic.com/jira/browse/DHFPROD-3274 has been opened

**Comment by srinathgit** [comment]
@bgeorge11 ,
Did you mean ml:runIngest instead of ml:ingestFlow ?

**Comment by bgeorge11** [comment]
Yeah. ml:runIngest. Sorry for the typo

**Comment by eltesoro-ml** [comment]
Fixed and published: https://docs.marklogic.com/datahub/refs/rest-extensions.html.
