### ISSUE TITLE
Clean Target database directory ? is confusing not working

### ISSUE THREAD

**Issue by BharathaRavindra** [marklogic/marklogic-data-hub#305]
I expect when i select this option, I think my database forest is cleared- what ever the data is there earlier.
But its not clear any data in Forest.

**Comment by damonfeldman** [comment]
I'm working with Bharata. the wording does say clear "directory" but we can't figure out if this means some specific directory, or how  it is specified.

**Comment by damonfeldman** [comment]
I agree with removing clean target dir in the short term. 

Then perhaps we can create a new ticket or repurpose this one to add more options at that time. That is, all of:
- fastload
- clean output directory
- output directory

with appropriate disclaimers that fastload has to be used properly, or put it in an "advanced" section.
