### ISSUE TITLE
Ability to map child elements and attributes/ properties in XML and JSON documents, in themapping step

### ISSUE THREAD

**Issue by stuartMoorhouse** [marklogic/marklogic-data-hub#3077]
#### The issue

The mapping step in QuickStart seems to only support mapping from one flat structure to another. 

But typically documents have structures like this: 
```
<header>
    <messageId messageIdScheme="http://www.drkw.com/messageId/OTC">OTCCallorPutSpread_2019-10-15T21:28:57.371+01:00</messageId>
    <sentBy messageAddressScheme="http://www.MsgParty.com/partyId">drkw</sentBy>
    <creationTimestamp>2019-10-15T21:28:57.371+01:00</creationTimestamp>
  </header>
```

I would like to map messageId, sentBy and creationTimestamp to properties in an entity, but I can't see how to do that in the QuickStart UI.

**Comment by rjrudin** [comment]
@ryanjdew @sbayatpur Can we close this since I think 5.1.0 addresses it?

**Comment by rjrudin** [comment]
Supported in 5.1
