### ISSUE TITLE
Abilty to set properties to default values in mapping step

### ISSUE THREAD

**Issue by stuartMoorhouse** [marklogic/marklogic-data-hub#3078]
#### The issue
It would be useful if, using the QuickStart UI, instead of having to map values in a source document to a property, the property could be set to a default value based on collection.

For example, call documents in the collection "otcCallOrPutSpread" would have the *type* property set to "OTCCallOrPutSpread".

**Comment by rjrudin** [comment]
@ryanjdew  @sbayatpur I think this is coming in 5.1.0, correct? As an XPath expression can just be a static value? If so, I think we can close this.

**Comment by rjrudin** [comment]
Supported in 5.1
