### ISSUE TITLE
improve error message experience

### ISSUE THREAD

**Issue by stuartMoorhouse** [marklogic/marklogic-data-hub#3081]
Could error messages please be easier to use. For example:

```Local message: failed to apply resource at documents: Internal Server Error. Server Message: XDMP-JSONEOF: xdmp:multipart-decode("02b97d8c-eb9e-44d8-8f71-ab45330e43bc", binary{"2d2d30326239376438632d656239652d343464382d386637312d616234353333..."}) -- Unexpected end of file in JSON at line 25 char 2 . See the MarkLogic server error log for further detail.```

It would help in debugging if we knew which JSON file had caused the error. 
It would also help if the error message specified the log(s) to look in.

**Comment by sbayatpur** [comment]
Thanks @stuartMoorhouse , we are looking to improve the error experience. I've opened this story for your suggestion: https://project.marklogic.com/jira/browse/DHFPROD-3542

**Comment by rjrudin** [comment]
What action had you taken that led to this error occurring?

**Comment by rjrudin** [comment]
Pinging @stuartMoorhouse  on this, as we first need to know what action led to this error.

**Comment by stuartMoorhouse** [comment]
Hi, I was trying to load JSON documents using an ingest step. 

Some of the JSON documents were invalid. Please see https://github.com/marklogic/marklogic-data-hub/issues/3187 for more details.

**Comment by rjrudin** [comment]
@sbayatpur @stuartMoorhouse @ehennum This error is coming from the ML Java Client. We don't want DH to be in the business of trying to parse additional information out of the error. 

I think the main goal is that when a batch of documents is written (DH is using DMSDK) and one of them fails, then ideally the error message would include the URI of the document that failed to be inserted. But I think that would require a change to the ML server itself. 

@damonfeldman has mentioned before the concept of the client retrying each document one-by-one to see which one fails, but I think that's a feature we'd want implemented in DMSDK, not in DH. 

@ehennum If I'm on the right track here, then my recommendation is that we close this ticket and open a new one, either against the ML server or against the Java client, for trying to identify the URI of the document that failed to insert.

**Comment by kkanthet** [comment]
Closing based on above comments.
