### ISSUE TITLE
Post ml:runFlow fails unless given a list of URIs

### ISSUE THREAD

**Issue by stuartMoorhouse** [marklogic/marklogic-data-hub#3083]
Running
``
POST localhost:18010/v1/resources/ml:runFlow?rs:job-id=001&rs:flow-name=otc-call-or-put-spread-to-services-model&rs:step=1&database=data-hub-FINAL&rs:target-database=data-hub-FINAL
`` returns:

``
{
    "errorResponse": {
        "statusCode": 400,
        "status": "Bad Request",
        "messageCode": "XDMP-ARGTYPE",
        "message": "XDMP-ARGTYPE: cts.query(\"cts.collectionQuery([\\\"otc-call-or-put-spread-to-canonical-entit...\") -- arg1 is not of type Node"
    }
``

but adding a fake uri with 
``
POST localhost:18010/v1/resources/ml:runFlow?rs:job-id=001&rs:flow-name=otc-call-or-put-spread-to-services-model&rs:step=1&database=data-hub-FINAL&rs:target-database=data-hub-FINAL&rs:options={ "uris" : [ "test.xml" ] }
`` returns:

``
{
    "jobId": "001",
    "totalCount": 0,
    "errorCount": 0,
    "completedItems": [],
    "failedItems": [],
    "errors": []
}
``

## Expected behaviour
The REST call can be made without specifiying the uris and the step is run.

**Comment by srinathgit** [comment]
The current datahub architecture first runs the collection step which returns to the client a list of uris. ml:runFlow is meant to run a mapping or mastering step for a batch of uris obtained in collection step. A client side orchestrator batches the uris obtained from and hits the ml:runFlow endpoint continuously and gets the results.

**Comment by rjrudin** [comment]
Closing this, as while it's called "ml:runFlow", that's a misnomer - it's an endpoint for processing a batch of URIs for a particular step.
