### ISSUE TITLE
Smart Mastering: match property values are all cast to strings

### ISSUE THREAD

**Issue by crism** [marklogic/marklogic-data-hub#3087]
#### The issue

Short description of the problem: When matching on integer-valued properties, no match is ever found.

What behavior are you expecting? Matches should work on integers and other non-string types as well as on strings.

#### Tech details

Which Operating System are you using? CentOS 7.

Which version of MarkLogic are you using? 10.0-2

Which version of the Data Hub Framework are you using? 5.1-SNAPSHOT (from the `develop` branch)

Is this a QuickStart UI bug? If so, which browser are you using? N/A

#### The devil is in the details...

It looks like this arose with commit 9959a55; before that, the compiled query checked the castability of the value being compared. (Although I note this change is present in DHF 5.0.2, which seems to be working.) This could probably be corrected by putting the castability tests back into `match-impl:query-map-to-query()`.

**Comment by ryanjdew** [comment]
Tracking with https://project.marklogic.com/jira/browse/DHFPROD-3440
