### ISSUE TITLE
Smart Mastering: attachments are included in property values to match

### ISSUE THREAD

**Issue by crism** [marklogic/marklogic-data-hub#3090]
#### The issue

Short description of the problem: When the source for a match query is an envelope with attachments, the property values to match include all elements or fields of a given name, not just the values in the instance. This can be a problem if the source document is the result of a mapping step, and the attachment contains fields with the same name but different meanings or misleading values.

What behavior are you expecting? When match candidates follow the entity services envelope pattern, only the instance payloads should be considered for matching.

#### Tech details

Which Operating System are you using? CentOS 7

Which version of MarkLogic are you using? 10.0-2

Which version of the Data Hub Framework are you using? 5.1-SNAPSHOT (from the `develop` branch)

Is this a QuickStart UI bug? If so, which browser are you using? N/A

#### The devil is in the details...

The problem lies in this XPath in `match-impl:values-by-qname()`: `fn:distinct-values($document//*[fn:node-name(.) eq $qname] ! fn:normalize-space(fn:string(.))[.])`

**Comment by rjrudin** [comment]
Just curious - would you prefer that attachments weren't populated by default? I've never been a fan of the entire raw document being added to the final document, have never run into a need for that in an application.

**Comment by crism** [comment]
I don’t have an opinion about attachments being populated by default… it makes sense for a destructive merge to keep the history, and I can think of cases where it’s useful. But it really should not be regarded as first-class information when considering a possible merge.

**Comment by sbayatpur** [comment]
@jmakeig  and @ryanjdew, do you know if there is a product reason why Smart Mastering looks for matches in the attachments as well as the instance parts of the envelopes? I'm wondering if this was an intentional decision or not.

**Comment by ryanjdew** [comment]
@sbayatpur The query is scoped to inside the instance property or element. Due to the searches being unfiltered, if the element value positions index isn't turned on then false positive matches will occur on items outside the instance. 

Mastering does have the ability to leverage path range indexes now, which would be another way to not have false positives. We need to make an adjustment so we will dynamically use the path range indexes if one is defined in the Entity Model.

**Comment by rjrudin** [comment]
@fsnow  There's a ticket for mapping to not include attachments by default, which I think is the main problem here. Do you think anything should be done for mastering, or can we close this?

**Comment by ryanjdew** [comment]
The latest mastering code pulls values from the document using targeted XPath based on the Entity Model, so this is no longer an issue.
