### ISSUE TITLE
Add support for a single data hub step to have both a before and after custom hook

### ISSUE THREAD

**Issue by brent-hartwig** [marklogic/marklogic-data-hub#3099]
#### The issue

A project has the need to initially ingest content from the primary source but later merge 3rd party enrichment data from a secondary source.  The merging logic needs to occur before the hub's core logic for the ingestion step type.  However, since we are already using the custom hook for post-processing, we can't also use a custom hook configured for 'before'.  The post-processing custom hook is responsible for manipulating headers, including moving NiFi provenance from the instance section to the headers section (Related: https://github.com/marklogic/marklogic-data-hub/issues/3001).

#### Workarounds / Alternatives

1. See if the post-processing logic could be merged with the pre-processing logic, and still with a single custom hook.
2. Go with a custom step that utilizes up to one custom hook.
3. Employ a custom step that wraps one of the built-ins (suggested and previously implemented by @crism).

#### Tech details

Which Operating System are you using?  CentOS Linux release 7.6.1810

Which version of MarkLogic are you using?  10.0-2.1

Which version of the Data Hub Framework are you using?  5.0.2

Is this a QuickStart UI bug? If so, which browser are you using?  N/A

#### The devil is in the details...

N/A

**Comment by srinathgit** [comment]
Did you try running with property "runBefore" in customHook set to true ? I believe it is meant for pre processing hook

**Comment by brent-hartwig** [comment]
Hi, Srinath,

Thanks for the reply.  While I haven't tried that I wasn't questioning whether it would work; rather, this RFE is asking that the same step be able to configure different modules to a before _and_ after hook.  As is, we can only have one or the other.  Thank you.

-Brent

**Comment by jmakeig** [comment]
> The merging logic needs to occur before the hub's core logic for the ingestion step type. 

Why? Shouldn’t this be a mapping step?

**Comment by brent-hartwig** [comment]
I don't believe so.  While we're looking at two distinct sources, the data from one is to create entity docs and the data from the other is to add to those docs (as opposed to create additional entity docs).  Until the enrichment data comes in, the harmonized entities simply won't include that data.  Once the enrichment data arrives, we intend to add it to the existing staging entity docs then re-harmonize.

In the following illustration, `incoming.metadata` is purposely dropped as it's just clutter in this context.

Step 1. Initial raw input from our primary source (via NiFi):
```
{
    "incoming": {
        "raw": {
            "DESYNPUF_ID": "00196F0702489342",
            "FIRSTNAME": "KIMBERLY",
            "LASTNAME": "PEREZ",
            ...
        },
        "metadata": {
            "ingestSystem": "NiFi",
            ...
        }
    }
}
```

Step 2. ML doc immediately after ingestion:
```
{
   "envelope":{
      "headers":{
         "provenance":{
            "lineage":{
               "input":[
                  {
                     "entity":"AcmeMember",
                     "database":"data-hub-STAGING",
                     "flowName":"AcmeMemberFlow",
                     "stepNumber":"1",
                     "inputDateTime":"2019-10-23T15:31:02.261304Z",
                     "inputUser":"flow-operator"
                  }
               ]
            }
         }
      },
      "instance":{
         "DESYNPUF_ID":"00196F0702489342",
         "FIRSTNAME":"KIMBERLY",
         "LASTNAME":"PEREZ",
         ...
      }
   }
}
```

Step 4. Document is harmonized and reaches the final database.

Step 5. Portions of the harmonized document are added to a CSV file and sent to a 3rd-party enrichment service.

Step 6. At some point later we receive this raw input from our enrichment source:
```
{
    "incoming": {
        "raw": {
            "ID":"00196F0702489342",
            "exampleProp1":"some meaningful enrichment value",
            "exampleProp2":"another one",
            "exampleProp3":"and yet another one"
        },
        "metadata": {
            "ingestSystem": "NiFi",
            ...
        }
    }
}
```

Step 7. System to detect incoming data is enrichment data and therefore move incoming.raw to envelope.headers.enrichmentData, add to the provenance headers, but keep everything else as is:
{
   "envelope":{
      "headers":{
         "provenance":{
            "lineage":{
               "input":[
                  {
                     "entity":"AcmeMember",
                     "database":"data-hub-STAGING",
                     "flowName":"AcmeMemberFlow",
                     "stepNumber":"1",
                     "inputDateTime":"2019-10-23T15:31:02.261304Z",
                     "inputUser":"flow-operator"
                  }
               ],
               "enrichment":[
                  {
                     "todo":"likely similar info as input."
                  }
               ]
            }
         },
         "enrichmentData":{
            "exampleProp1":"some meaningful enrichment value",
            "exampleProp2":"another one",
            "exampleProp3":"and yet another one"
         }
      },
      "instance":{
         "DESYNPUF_ID":"00196F0702489342",
         "FIRSTNAME":"KIMBERLY",
         "LASTNAME":"PEREZ",
         ...
      }
   }
}
```

Step 8. Doc gets harmonized again, but will include enrichment data this time.

**Comment by jmakeig** [comment]
First, thanks for the detailed explanation. Getting concrete really helps. 

This still feels to me like two mapping steps and one mastering step:

Map 1: raw DESYNPUF to Person
Map 2: raw enrichment payload to _partial Person_
Master: Match and merge the partial Person to an existing (or new) Person instance.

Yes, this is more steps. However, breaking it down into discrete steps allows for specialization in who does the work and a better chance that we could build specific tooling. 

Where does this break down, @brent-hartwig?

**Comment by RobertSzkutak** [comment]
@jmakeig This is a high performance use case. Any chance it's on the roadmap to combine multiple steps into a single transaction?

**Comment by jmakeig** [comment]
I appreciate that, but “high performance” is relative. Yes, faster is better than slower, but that’s not the only criteria. Can we take this offline and get more specific with data and harmonization logic? Ideally, if we were to do something here, I’d like it to maintain the (independently testable, single concern, visualizable) step abstraction regardless of how we might optimize under the covers.

**Comment by DavidGorbet** [comment]
I'm also interested in a response to Justin's most recent comment. We all agree that for definition and management of steps, more granular is better. For execution of steps, more performant is better. There is a balance we need to strike. How to strike that balance requires actual data about what is performant enough and some business context to help us prioritize performance optimizations over ease of use and other capabilities we'd otherwise be working on.

**Comment by RobertSzkutak** [comment]
@DavidGorbet The users Im working with would like to have the ability to write a series of small, orthogonal custom steps and run those in succession. The primary purpose for this is to be able to reuse the custom steps and minimize the need to write new code. With the overhead of collecting URIs and processing them in a separate transaction for each step it's not a path I can recommend they head down today. 

There are limitations with custom hooks such as the inability to modify document collections or permissions which make adding a custom step rather than a hook after an ingest/mapping/mastering step necessary. The ability to only have one hook per step and not both a pre and post hook is also a factor that can require an additional custom step be implemented.

Users I've worked with have found the design pattern for hooks unorthodox when trying to move code from a custom step over to a hook or vice versa. Being able to combine multiple operations between steps into a single transaction would completely eliminate the need for custom hooks entirely and simplify development.

**Comment by rjrudin** [comment]
This can be accomplished via a step interceptor in 5.4, and we're unlikely to change how custom hooks work.
