### ISSUE TITLE
Doesn't like apostrophe in json property name

### ISSUE THREAD

**Issue by sjcrook** [marklogic/marklogic-data-hub#3101]
/data-hub/5/builtins/steps/mapping/default/lib.sjs, getPath function.

Change...

path = `${sourceContext}${connector}node('${propertyName}')[fn:not(. instance of array-node())]`;

...to...

path = `${sourceContext}${connector}node("${propertyName}")[fn:not(. instance of array-node())]`;

**Comment by akshaysonvane** [comment]
Tracking via https://project.marklogic.com/jira/browse/DHFPROD-3413

**Comment by rjrudin** [comment]
This can be accomplished via the 5.1 mapper
