### ISSUE TITLE
Not accurate matching & merging

### ISSUE THREAD

**Issue by hourdays** [marklogic/marklogic-data-hub#3110]
#### The issue

I used **DHF 5.0.1** to **master data** coming **from two CSV** sources: 427 rows from source one and 6865 rows from source two so a total of **7292** rows hence **documents** inside MarkLogic Data Hub.

**Matching** is done on a key which is common for several rows from source one and two.
So each CSV row has a key column and we want to match and merge all rows from both sources which have the same key.
For some given keys, which are used by many rows such as more than a hundred or more (I did not figure out the threshold), I ended up with more then one Golden Record.
I was able to work around the issue by raising the maxScan flow tuning setting to 10000.

As for **Merging** I noticed that all values were not all there in the resulting Golden Record.

#### Tech details

macOS Mojave 10.14.6
MarkLogic 9.0-9.1
DHF 5.0.1
It does not seem to be a QuickStart UI related bug.

#### The devil is in the details...
yes it is :-)

**Comment by akshaysonvane** [comment]
I was able to run the code but can't seem to find the missing values for the Merging step.
All properties tally up for the merged docs that I checked.

@hourdays has decided to provide an instance where properties are missing.
