### ISSUE TITLE
Matching with null values

### ISSUE THREAD

**Issue by sjcrook** [marklogic/marklogic-data-hub#3113]
DHF 5.0.3 (and possibly earlier versions) is matching on null.  For example, given two records...

firstName,lastName,postalCode,email
John,Smith,12345,jsmith@gmail.com
David,Smith,23456,null

...and a scoring of...

          "scoring" : {
            "add" : [ {
              "propertyName" : "email",
              "weight" : "20"
            },{
              "propertyName" : "lastName",
              "weight" : "12"
            },{
              "propertyName" : "firstName",
              "weight" : "5"
            },{
              "propertyName" : "postalCode",
              "weight" : "5"
            } ],
            "expand" : [ ],
            "reduce" : [ ]
          },
          "actions" : {
            "action" : [ ]
          },
          "thresholds" : {
            "threshold" : [ {
              "above" : "22",
              "label" : "DefiniteMatch",
              "action" : "merge"
            }, {
              "above" : "17",
              "label" : "PossibleMatch",
              "action" : "notify"
            } ]
          }

...the two records will match when they shouldn't.  See files at https://www.dropbox.com/sh/71wrw7tc9fcl8jx/AAB0OKlRPXlS3AsyORPsschIa?dl=0

**Comment by sjcrook** [comment]
Setup instructions.

Run mlcp to ingest the data.  Use the following options files (you'll need to tweak the location of the source).
  - mlcp-options-CRM-Contact-ThirdParty-CSV.txt
  - mlcp-options-non-CRM-ThirdParty-Discovery-BestRetail-CSV.txt

Run the following flows
  - CRM-Contact-ThirdParty
  - non-CRM-Thirdparty-Discovery-BestRetail
  - MergeContacts

Run the following script and looks for incorrect matches

xquery version "1.0-ml";
 
for $doc in cts:search(fn:collection(), cts:collection-query("mdm-merged"))[1 to 20]
  return
    (
      fn:base-uri($doc),
      fn:string-join(xdmp:document-get-collections(fn:base-uri($doc)), "|"),
      "======",
      fn:string-join(for $uri in $doc//merges/document-uri
        order by $uri
        return
          let $doc := fn:doc($uri)
          let $firstName := $doc//Contact/firstName
          let $lastName := $doc//Contact/lastName
          let $postalCode := if ($doc//Contact/postalCode instance of null-node()) then "null" else $doc//Contact/postalCode
          let $email := if ($doc//Contact/email instance of null-node()) then "null" else $doc//Contact/email
          return
            $firstName || "," || $lastName || "," || $postalCode || "," || $email || "," || $uri, "&#10;")
    )

**Comment by akshaysonvane** [comment]
Thanks, @sjcrook for adding the dataset and steps to repro.
Tracking via https://project.marklogic.com/jira/browse/DHFPROD-3437

**Comment by xmlnovelist** [comment]
I reproduced this using the dataset and steps, and updated DHFPROD-3437

**Comment by rjrudin** [comment]
Closing, as the resolution is to upgrade to 10.0-3 or 9.0-11, which addresses internal bug 53610.
