### ISSUE TITLE
Un-hide the temp files in .tmp

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#313]
People can easily miss the .tmp file when clearing out old config, re-installing or similar, because it's hidden by default. Should we move that file to a visible name? 

Not sure what is in there or what would be an appropriate name to communicate it's purpose.

**Comment by kosed** [comment]
+1

**Comment by aebadirad** [comment]
Will be eliminating the .tmp directory going forward. This should resolve this ticket by OBE'ing it.
