### ISSUE TITLE
ml:runFlow via REST without uris fails even with given sourceQuery

### ISSUE THREAD

**Issue by janmichaelyu** [marklogic/marklogic-data-hub#3132]
#### The issue

Short description of the problem:
I tried using no sourceQuery in the call 
```
http://localhost:8010/v1/resources/ml:runFlow?rs:flow-name=TestFlow&rs:step=1&rs:options={}
```
gets me
```
        "message": "XDMP-ARGTYPE: cts.query(\"cts.collectionQuery([\\\"ExtractedJSON\\\"])\") -- arg1 is not of type Node"
```

even if the flow runs correctly via quickstart.

What behavior are you expecting?

#### Tech details

Which Operating System are you using?
Mac

Which version of MarkLogic are you using?
10.0-1

Which version of the Data Hub Framework are you using?
5.0.2

Is this a QuickStart UI bug? If so, which browser are you using?
Nope. Using Chrome and NiFi HTTPInvoke.

#### The devil is in the details...

I also tried:
```
http://localhost:8010/v1/resources/ml:runFlow?rs:flow-name=TestFlow&rs:step=1&rs:options={"sourceQuery":"cts.collectionQuery([\"ExtractedJSON\"])"}
```
gets me
```
        "message": "XDMP-ARGTYPE: cts.query(\"cts.collectionQuery([\\\"ExtractedJSON\\\"])\") -- arg1 is not of type Node"
```

Also tried:
```
        "message": "XDMP-ARGTYPE: cts.query(\"<cts:collection-query xmlns:cts=\\\"http://marklogic.com/cts\\\"><ct...\") -- arg1 is not of type Node"
```
from a REST call.
```
http://localhost:8010/v1/resources/ml:runFlow?rs:flow-name=TestFlow&rs:step=1&rs:options={"sourceQuery":"<cts:collection-query xmlns:cts=\"http://marklogic.com/cts\"><cts:uri>ExtractedJSON</cts:uri></cts:collection-query>"}
```
Related to #3083

**Comment by srinathgit** [comment]
ml:runFlow requires uris to be provided. The collector runs the source query first (collector has a separate endpoint of its own)and the uris are persisted on the client side. It is batched and ml:runFlow is called on a batch of uris.
For example :

POST /v1/resources/ml:runFlow?rs:job-id=dad9b695-4175-4d48-92c9-b8d2681b6e1e&rs:flow-name=testabcd&rs:target-database=data-hub-FINAL&rs:options={
  "uris" : [ "/Users/ssambasu/Downloads/dhs-5-example/input/orders/json/10448.json", "/Users/ssambasu/Downloads/dhs-5-example/input/orders/json/10449.json", "/Users/ssambasu/Downloads/dhs-5-example/input/orders/json/10450.json", "/Users/ssambasu/Downloads/dhs-5-example/input/orders/json/10451.json" ]
}&rs:step=2&database=data-hub-STAGING

**Comment by rjrudin** [comment]
Closing this, as while it's called "ml:runFlow", that's a misnomer - it's an endpoint for processing a batch of URIs for a particular step.
