### ISSUE TITLE
Give steps the same context as step hooks

### ISSUE THREAD

**Issue by brent-hartwig** [marklogic/marklogic-data-hub#3133]
#### The issue

Upon reviewing `Flow#runStep()`, I see custom hooks are provided more information than the steps.  I would like steps to be provided the same information.  I could have used this in a custom ingestion step that a) performs some pre-processing of the inbound content, b) executes the data hub's default ingestion code, and c) performs some post-processing of the inbound content where that pre-processing is attempting to use information only provided to custom hooks.  _Business need described in https://github.com/marklogic/marklogic-data-hub/issues/3099._

Given the easy workaround listed below, we do not require this change to move forward.  Nonetheless, I thought it good to share as perhaps other use cases will emerge that the workaround wouldn't apply to or be as convenient.  Thank you for your consideration.

#### Workaround

Should we not want to give up use of the hook-provided information, we will need to configure the step definition with the custom hook and not have the custom step perform the post-processing.  

#### Tech details

Which Operating System are you using? CentOS Linux release 7.6.1810

Which version of MarkLogic are you using? 10.0-2.1

Which version of the Data Hub Framework are you using? 5.0.2

Is this a QuickStart UI bug? If so, which browser are you using? N/A

#### The devil is in the details...

As shown below, hooks are provided the flow name, step number, entire step definition, and the list of URIs.  Both are given the content.  The step's `main()` function is also given the options defined in the step definition, thereby doesn't have access to the step version or step number, which could be incorporated in the lineage metadata.

Related hook processing code within `Flow#runStep()`:
```
// Include all of the step context in the parameters for the custom hook to make use of
let parameters = Object.assign({uris, content, options, flowName, stepNumber, step}, hook.parameters);
hookOperation = function () {
  flowInstance.datahub.hubUtils.invoke(
    hook.module,
    parameters,
    hook.user || xdmp.getCurrentUser(),
    hook.database || (hook.runBefore ? flowInstance.globalContext.sourceDatabase : flowInstance.globalContext.targetDatabase)
  );
}
```

Related step (batch) processing code within `Flow#runStep()` --please also cover non-batch processing:
```
let results = normalizeToSequence(flowInstance.runMain(normalizeToSequence(content), options, processor.run));
```

And 'Flow#runMain()`:
```
runMain(content, options, func) {
  let resp;
  resp = func(content, options);
  return resp;
};
```

**Comment by rjrudin** [comment]
Should use a step interceptor in 5.4 instead, which does provide the same context
