### ISSUE TITLE
Status Details are hard to read

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#3135]
#### The issue

I have a bug in my matching code, my problem to fix.
When I click on "Failed step 3" i receive the following popup.
![image](https://user-images.githubusercontent.com/1315891/67431354-15309500-f5b2-11e9-9e24-66d7012e99a8.png)

Can this popup be displayed any better? Can the "\n" be converted to a new line at a minimum?

#### Tech details
Which Operating System are you using?
MacOS

Which version of MarkLogic are you using?
9.0-10

Which version of the Data Hub Framework are you using?
5.0.4

Is this a QuickStart UI bug? If so, which browser are you using?
Yes, Chrome

**Comment by srinathgit** [comment]
Issue https://project.marklogic.com/jira/browse/DHFPROD-3450 created

**Comment by kkanthet** [comment]
Issue Fixed in 5.1.0 release
