### ISSUE TITLE
Easier to navigate to "my data" from Dashboard

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#3140]
#### The issue
If I am on the dashboard and I see the "Staging" and "Final" databases, I should be able to click on the "Staging" or "Final" text and be taken to the "Browse Data" for that database.

I simply added a link on the text "Final" to see that this could work.

```<a href="/#/browse?p=1&d=FINAL&e=false">Final</a>```

This way, I was able to:
1. login to quickstart
2. see I had, data in FINAL
3. Click on Final
4. start to navigate the data

Currently, I must:
1. login to quickstart
2. see I had, data in FINAL
3. Click browse data
4. wait for STAGING to load
5. Change to Final
6. Navigate my data

It's the little things.

#### Tech details

Which version of the Data Hub Framework are you using?
5.0.4

Is this a QuickStart UI bug? If so, which browser are you using?
UX Enhancement

**Comment by rjrudin** [comment]
Closing since it's QS
