### ISSUE TITLE
Clicking the "trash can" should not remove DHF configuration (entities)

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#3141]
#### The issue
Clicking on the trash can on the Dashboard should not remove the data that is uploaded to the database when "Redeploy Modules" is executed.

If I click the "skull" then you can delete the DHF configuration data.

#### Tech details
Which version of the Data Hub Framework are you using?
5.0.4

Is this a QuickStart UI bug? If so, which browser are you using?
Yes.

**Comment by srinathgit** [comment]
I would assume you would also not want flows, step definitions to be removed when the "trash can" is clicked ?

**Comment by rjrudin** [comment]
Supported in HC
