### ISSUE TITLE
Bad wording in QS UI

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#3142]
## The issue
![image](https://user-images.githubusercontent.com/1315891/67507503-0226cf00-f65d-11e9-98e1-1d5e6870fb99.png)

"Additional Target Collections" makes me think I am targeting these collections for a query, not that I am adding them to my document.

Please change the wording to be more direct and less ambiguous.

#### Tech details

Which version of the Data Hub Framework are you using?
5.0.4

Is this a QuickStart UI bug? If so, which browser are you using?
QS UX

**Comment by rjrudin** [comment]
Closing since it's QS
