### ISSUE TITLE
Debug QuickStart logging

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#3143]
#### The issue
`java -jar quickstart.war -d ` doesn't seem to be doing any different data logging to the console

I notice both say they are using INFO logging.
```
-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
```

#### Tech details

Which Operating System are you using?
Mac OS

Which version of MarkLogic are you using?
9.0-10.4
Which version of the Data Hub Framework are you using?
5.0.4
Is this a QuickStart UI bug? If so, which browser are you using?
Yes

#### The devil is in the details...
[start-quickstart-debug.txt](https://github.com/marklogic/marklogic-data-hub/files/3769025/start-quickstart-debug.txt)
[start-quickstart.txt](https://github.com/marklogic/marklogic-data-hub/files/3769026/start-quickstart.txt)

**Comment by srinathgit** [comment]
Opened https://project.marklogic.com/jira/browse/DHFPROD-3463

**Comment by srinathgit** [comment]
@prestonmcgowan ,
You can just put a logback.xml like the one attached to the directory where you have qs and start the process as java -jar quickstart.war --logging.config=logback.xml (github doesn't allow attaching xml files, so it's called logback.txt in the attachment). You can have granular control on logging levels of different classes using this.
[logback.txt](https://github.com/marklogic/marklogic-data-hub/files/3838667/logback.txt)

**Comment by prestonmcgowan** [comment]
So, the documentation when we create a ticket says to add `-d` to provide better logging. Does the ticket template need to be updated?

**Comment by srinathgit** [comment]
It is actually ``` java -jar quickstart.war --debug ``` but it doesn't provide debug level log for the application, it provide debug level log for spring boot related classes. 
https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-logging-console-output
I don't think it is that useful for debugging the issues. I think the ticket template needs changing.

**Comment by prestonmcgowan** [comment]
The following is the template in github.


  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by srinathgit** [comment]
The template has been changed now. I will go ahead and close this issue

**Comment by prestonmcgowan** [comment]
Looks good.

Thank you.
