### ISSUE TITLE
QuickStart Jobs Commited "search" is being executed twice

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#3144]
#### The issue
Steps to reproduce:
1. Create an ingest flow
2. Load some data
3. Go to the Job details that loaded the data
4. Notice some documents were "committed"
5. Make sure Chrome Dev Tools is showing networking (or similar tool)
6. Click the number under "committed"
7. Notice the documents load
8. Notice in Chrome Dev Tools, the search executed twice

#### Tech details

Which Operating System are you using?
Mac OS

Which version of MarkLogic are you using?
9.0-10.4

Which version of the Data Hub Framework are you using?
5.0.4

Is this a QuickStart UI bug? If so, which browser are you using?
Yes

**Comment by srinathgit** [comment]
Opened https://project.marklogic.com/jira/browse/DHFPROD-3464

**Comment by kkanthet** [comment]
Issue Fixed in 5.1.0 release
