### ISSUE TITLE
Notify the user when the mapping steps become a passthru

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#3145]
#### The issue

In certain circumstances when the threshold for a merge cannot be met by the available match rules, the matchers are skipped and the mastering step becomes a pass thru. Often times this is a misconfiguration by the flow developer.

Please alert the flow developer in the QuickStart UI and in the ErrorLog that the matchers will not meet a threshold and the step becomes a pass thru.

#### Tech details

Which Operating System are you using?
Mac OS

Which version of MarkLogic are you using?
9.0-10.4

Which version of the Data Hub Framework are you using?
5.0.4

Is this a QuickStart UI bug? If so, which browser are you using?
No, but some UI notification would be helpful

**Comment by rjrudin** [comment]
Closing since it's QS, and separate matching/merging steps are now recommended
