### ISSUE TITLE
Geospatial Matcher

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#3155]
#### The issue
I have a latitude and longitude in my entity along with a business name.
I can make use of an exact matcher to match on the names.
I would like to make use of a compound matcher for my latitude and longitude. The geospatial matcher should make use of either a custom polygon region, circle with configurable radius, and/or box region.

#### Tech details
Which version of MarkLogic are you using?
10.0-2

Which version of the Data Hub Framework are you using?
5.0.2

Is this a QuickStart UI bug? If so, which browser are you using?
No

**Comment by prestonmcgowan** [comment]
Here is my workaround matcher for the time being:

![image](https://user-images.githubusercontent.com/1315891/67699767-0b78aa00-f983-11e9-8185-dcc009a2790d.png)


```
xquery version "1.0-ml";

module namespace alg = "http://data-hub-framework.marklogic.com/matcher";

declare namespace matcher = "http://marklogic.com/smart-mastering/matcher";

declare option xdmp:mapping "false";

declare function alg:close-enough-match(
  $expand-values as xs:string*,
  $expand-xml as element(matcher:expand),
  $options-xml as element(matcher:options)
) as cts:query* {
    let $_ := (
        xdmp:log("$expand-values"),
        xdmp:log($expand-values)
        (: xdmp:log("$expand-xml"),
        xdmp:log($expand-xml),
        xdmp:log("$options-xml"),
        xdmp:log($options-xml) :)
    )

    let $queries := cts:or-query((
        for $value in $expand-values
        let $lat    := xs:float(fn:tokenize($value, "_")[1])
        let $long   := xs:float(fn:tokenize($value, "_")[2])
        let $point  := cts:point($lat, $long)
        let $circle := cts:circle(1, $point)
        let $query  := cts:json-property-pair-geospatial-query(
            "Place",
            "latitude",
            "longitude",
            $circle
        )
        return $query
    ))

    let $_ := (
        xdmp:log("Queries"),
        xdmp:log($queries)
    )

    return $queries
};
```

**Comment by rjrudin** [comment]
@fsnow  Please open a JIRA ticket if this seems worth supporting in mastering
