### ISSUE TITLE
Compound Matcher

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#3156]
#### The issue
I have data with confidence levels associated with it.
I would only like to make use of specific data if the confidence associated with it is above a known threshold.

The current matchers do not allow me to provide an propert(y|ies) to match on and provide a threshold to make use of. I therefore must create everything as a custom match.

May we be provided a way to perform a match on multiple properties in a single matcher?
May we provide a way to link two or more properties in a single match?

#### Tech details

Which version of MarkLogic are you using?
10.0-2

Which version of the Data Hub Framework are you using?
5.0.4

Is this a QuickStart UI bug? If so, which browser are you using?
No.

**Comment by rjrudin** [comment]
@fsnow  Worth supporting?

**Comment by rjrudin** [comment]
This is supported in the backend of DHF 5.4.0, and will be supported in the HC GUI in 5.5.0.
