### ISSUE TITLE
Unique Schema Databases

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#3164]
#### The issue

I noticed the _STAGING_ and _JOBS_ database share a Schema database.
This DHF configuration does not follow the recommended standards from MarkLogic TDE documentation.

Statement:

> For best performance, it is recommended that you do not configure your content database to use the default Schemas database and instead create your own schemas database for your template documents. If you create multiple content databases to hold documents to be extracted by TDE, each content database must have its own schema database. Failure to do so may result in unexpected indexing behavior on the content databases.

Link: https://docs.marklogic.com/guide/app-dev/TDE#id_54035

#### Tech details

Which version of MarkLogic are you using?
10.0-2

Which version of the Data Hub Framework are you using?
5.0.4

Is this a QuickStart UI bug? If so, which browser are you using?
No

**Comment by rjrudin** [comment]
What would you want to see here - i.e. should the job database have its own e.g. "job-schemas" database? Or should the job database default to using Schemas and Triggers, as it's not likely that a user will need schemas/triggers in the job database? And if the user does need those, the job database can always be customized to have its own schemas/triggers databases.

**Comment by prestonmcgowan** [comment]
"job-schemas" makes sense based on the recommendation in the TDE Guide.

**Comment by rjrudin** [comment]
This seems valid, tracking internally via 7011
