### ISSUE TITLE
Add a Validation Plugin

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#317]
Validation can be run in any plugin, but there is no explicit validation plugin, or standard handling of "invalid" documents per some schema or rule set. The hub can likely provide a lot of support to guide developers to best practices and ease use of validation. Some ideas include:
1. Allowing users to drop in a standard schema document, such as XSD, Schematron or JSON Schema document, and have that automatically applied.
2. Provide standard ways to handle "invalid" documents, such as rejecting the document altogether, writing it to a special logical location to be reviewed and processed later, or accepting the document, but tracking the issue.
3. Both raw and harmonized validation are useful. Input Flow validation (of raw data inputs) helps catch the situation when an upstream system sends unexpected data. Harmonize Flow validation helps ensure that the completed data product is adequate and complete (also, Harmonized data will benefit from having a formal schema more than the various raw formats).

GUIs or reports on what is valid, invalid, overall counts may be useful.

**Comment by janmichaelyu** [comment]
Here's how I think the validation will work with the DHF:
<img width="898" alt="screenshot 2017-07-21 17 03 38" src="https://user-images.githubusercontent.com/12621739/28457050-2f77acf0-6e37-11e7-9978-ce5af5bdb687.png">

And here's a schema for the validation report:
<img width="1072" alt="screenshot 2017-07-21 17 09 01" src="https://user-images.githubusercontent.com/12621739/28457081-53cb053e-6e37-11e7-94a6-488c6b13ecda.png">

@damonfeldman Let me know how it looks.

**Comment by janmichaelyu** [comment]
Can't attach the xsd in github but I uploaded it in JIRA.

**Comment by sbayatpur** [comment]
Closing this ticket, as this request is specific to DHF 4, and we are now focused on enhancements to DH 5 only. In the future, we will be looking at adding declarative validation to DH 5, though.
