### ISSUE TITLE
XML documents ingested as Json via mlcp but failing with null node during mapping step.

### ISSUE THREAD

**Issue by sundarbandepalli** [marklogic/marklogic-data-hub#3173]
#### The issue

I am ingesting an xml document and during this step I am indicating that the output format is JSON. Ingesting works fine. During mapping, I am not sure why its failing? It's a straight forward step. When I resolve the path - /envelope/instance/Patients/firstname - JSON and txt documents are resolving however xml documents comes up with an output like this - fn:doc("140.json")/envelope/instance/Patients/null-node("firstname")

What behavior are you expecting?

Just like JSON documents, XML documents should get ingested and not have null values. Attachments/instance have the values correctly however the main instance everything is null. 

Which Operating System are you using?
Mac OS.

Which version of MarkLogic are you using?
9.x

Which version of the Data Hub Framework are you using?
5.0.3

Is this a QuickStart UI bug? If so, which browser are you using?
Yes, Chrome.

#### The devil is in the details...

Very easily reproducible. See below for a sample JSON document from staging collection.

{
  "envelope": {
    "headers": {
      "sources": [
        {
          "name": "newpatients"
        }
      ],
      "createdOn": "2019-10-30T15:42:12.993328-05:00",
      "createdBy": "admin"
    },
    "triples": [],
    "instance": {
      "Patients": {
        "PatientID": null,
        "gender": null,
        "dob": null,
        "race": null,
        "marital-status": null,
        "language": null,
        "percentagebelowpoverty": null,
        "admissions": [],
        "firstname": null,
        "lastname": null,
        "email": null,
        "pets": null,
        "ssn": null
      },
      "info": {
        "title": "Patients",
        "version": "0.0.1"
      }
    },
    "attachments": {
      "envelope": {
        "headers": {
          "sources": [
            {
              "name": "newpatients"
            }
          ],
          "createdOn": "2019-10-30T15:42:12.993328-05:00",
          "createdBy": "admin"
        },
        "triples": [],
        "instance": {
          "record": {
            "PatientID": "140",
            "gender": "Female",
            "email": "qrotherham3v@free.fr",
            "firstname": "Querida",
            "lastname": "Rotherham",
            "ssn": "576-70-1362"
          }
        },
        "attachments": null
      }
    }
  }
}

**Comment by srinathgit** [comment]
Hi ,
Can you provide a project with sample data so that we can reproduce the issue on our end ?

**Comment by sundarbandepalli** [comment]
This is the website I have been using for generating test data. https://mockaroo.com/
Attached are the files that I have used. 
[AdvocatePatients.xml.zip](https://github.com/marklogic/marklogic-data-hub/files/3806753/AdvocatePatients.xml.zip)
[AuroraPatients.json.zip](https://github.com/marklogic/marklogic-data-hub/files/3806756/AuroraPatients.json.zip)

I had some help and was able to fix it by making the change in the json file. Setting the source context. 

{
  "lang" : "zxx",
  "name" : "Advocate-patients-Advocate-patients-mapping",
  "description" : "",
  "version" : 2,
  "targetEntityType" : "http://example.org/Patients-0.0.1/Patients",
  "sourceContext" : "/record",
  "sourceURI" : "541.xml",
  "properties" : {
    "firstname" : {
      "sourcedFrom" : "firstname"
    },
    "gender" : {
      "sourcedFrom" : "gender"
    },
    "PatientID" : {
      "sourcedFrom" : "PatientID"
    },
    "email" : {
      "sourcedFrom" : "email"
    },
    "lastname" : {
      "sourcedFrom" : "lastname"
    },
    "ssn" : {
      "sourcedFrom" : "ssn"
    }
  }
}

**Comment by rjrudin** [comment]
Closing as it seems resolved
