### ISSUE TITLE
Redeploy button is wiping out hub modules

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#318]
#### The issue

__Short description of the problem:__

Pressing the reload modules button removes the hub's modules.

__What behavior are you expecting?__

Should not wipe out hub owned modules.

**Comment by damonfeldman** [comment]
Note: I am fairly sure this is the hubstats REST extension that was removed. Adding here in case someone searches for hubstats. Fixed in 1.0.1 as noted above.
