### ISSUE TITLE
SmartMastering RFE: add tracing statements

### ISSUE THREAD

**Issue by crism** [marklogic/marklogic-data-hub#3189]
#### The issue

Short description of the problem: Figuring out where something is going awry in Smart Mastering currently requires groveling through the SM source and adding log statements.

What behavior are you expecting? I would like to be able to turn on tracing and see what queries are being executed from which bits of code and what their results are.

#### Tech details

Which Operating System are you using? CentOS 7

Which version of MarkLogic are you using? 9.0-9

Which version of the Data Hub Framework are you using? 5.0.2

**Comment by rjrudin** [comment]
There's a fair amount of tracing available now via "SM-MATCH"; closing, please open JIRA ticket if more tracing is desired.
