### ISSUE TITLE
Mapping keeps throwing error: Could not find a target entity. But the entity is in the schema database

### ISSUE THREAD

**Issue by chenfiona** [marklogic/marklogic-data-hub#3194]
{"stack":"Error: Could not find a target entity: http://example.org/Labeler-0.0.1/Labeler\n at main (/data-hub/5/builtins/steps/mapping/default/main.sjs:76:11)\n at Flow.runMain (/data-hub/5/impl/flow.sjs:436:12)\n at Flow.runStep (/data-hub/5/impl/flow.sjs:337:58)\n at Flow.runFlow (/data-hub/5/impl/flow.sjs:206:12)\n at post (/marklogic.rest.resource/mlRunFlow/assets/resource.sjs:72:25)\n at callExtension (/MarkLogic/rest-api/lib/extensions-util.sjs:93:30)\n at applyOnce (/MarkLogic/rest-api/lib/extensions-util.sjs:111:10)","message":"Could not find a target entity: http://example.org/Labeler-0.0.1/Labeler","name":"Error"}

**Comment by aebadirad** [comment]
check if the permissions for the ES models is readable by the user running the flow - sometimes people deploy with admin or another super user, but don't have assigned permissions for the user running the flow to access them.

**Comment by chenfiona** [comment]
So deploy DH as admin and when I run the flow, I usually specify -PmlUsername=***, this user has the below roles granted:
"data-hub-admin-role","flow-developer-role","flow-operator-role","pii-reader"

**Comment by chenfiona** [comment]
I am wondering if I manually input the Entities definition under the /project-root/entities. Should I just re-run mlRedeploy or other ml-gradle command? When I ran the mlRedeploy, since I already set below in the gradle.properties and gradle-local.properties:
mlUsername=admin
mlPassword=admin
So mlRedeploy is actually ran by admin.  But that **** user has those roles granted, isn't it sufficient?

**Comment by aebadirad** [comment]
Admin user has no roles, however, so the entities being loaded are loaded as admin (following the marklogic least security permissions model).

Set your mlUser/pass to the user you are running the flow as (data-hub-admin-role is basically a slightly pared down admin) and do a mlReloadModules. It should now populate using the user you're using to run the flows and the permissions on the entity services models should now have the proper permissions (flow-operator-role: read, flow-developer-role: write etc) and be able to run the flow.

If you ever add anything manually, you can just do mlDeploy (index/topology changes/forest changes/etc) or mlReloadModules (entities/mappings/steps/flows/custom code) for a shorter, just artifact/module based redeploy.

**Comment by chenfiona** [comment]
Do you mean to say set the gradle-local.properties :
mlUsername=****

How about the gradle.properties ? 
mlUsername=

I always use mlDeploy whenever I made changes.

**Comment by aebadirad** [comment]
You can use mlDeploy, it's just the 'full reload' of the data hub.

And it depends on the environment you're using. Most people keep environment files for each (dev, test, local, prod, etc). So whichever you are using, set your username to the user that has the data-hub-admin-role and then run the flow as the same user (or another user that has flow-operator-role) and it should now find all of your models/mapping/steps.

**Comment by chenfiona** [comment]
Thanks! Let me confirm.  
1)  gradle-local.properties : (DEV)
mlUsername=**** ( the user who creates/runs the flow/creates entities)

2) gradle.properties: no changes are made in below lines, since I specify the mlUserName in local.properties. 
mlUsername=
mlPassword=

And going forward, everything is under *** user control in DEV.  Correct?

**Comment by aebadirad** [comment]
Yep.
Admin (literally the admin user) has no default permissions, so any documents/modules created by the user is not given any (and therefore only admin can access them).

You may have used admin back in MarkLogic 9 and this 'worked', but a small change was made in ML10 to not automatically tag documents inserted via the REST-tier with rest-reader/rest-writer that do not have the roles associated with the user to ensure stronger security out of the box. 

This is probably what you you ran into.

**Comment by chenfiona** [comment]
Thanks! Yes, I am using ML10. 
I will redeploy everything and see how it goes!

**Comment by aebadirad** [comment]
In general, as a company, we're trying to strongly discontinue the use of admin globally beyond the initial security admin user to setup other users with lesser privileges. I know it's a bit of a pain as a developer, and I sympathize, but to date MarkLogic has never had a security breach, and to keep that bar high we devote a lot of time/review to preventing possible incidents.

I can promise you: whatever pain you endure, we endure as we eat our own dogfood and we're working on improving the usability.

**Comment by chenfiona** [comment]
Thanks Alex !! 
Just one more question, besides admin, what user/role/privilege is required in order to run mapping?

**Comment by rjrudin** [comment]
For DHF 5.1, flow-operator-role would be used. In DHF 5.4, a new set of granular roles is available; please see the docs for info on those roles.
