### ISSUE TITLE
Detect when running upgraded hub

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#322]
#### The issue

**Short description of the problem:**

We should somehow detect when the hub has been updated to a newer version and handle updating the MarkLogic server xqy files and such.

**Comment by maachou** [comment]
### The issue
#### Short description of the problem:
After loading and harmonizing the "getting started tutorial" data, I'm unable to display the document counts per database in the dashboard page. 
In the error log it seems that the extension hubstat does not exist. The datahub framework is running on my mac and the datahub was installed on MarkLogic 8.0-6 in a Centos 7 VM.
Attached a screenshot of the dashboard page and the console error.
<img width="1440" alt="screen shot 2016-11-08 at 15 02 06" src="https://cloud.githubusercontent.com/assets/879083/20102553/cca5f5f2-a5c6-11e6-8bfc-810e6d7c1e4d.png">
<img width="1425" alt="screen shot 2016-11-08 at 15 01 42" src="https://cloud.githubusercontent.com/assets/879083/20102555/cca840c8-a5c6-11e6-9a4c-930ec47f1eb9.png">
