### ISSUE TITLE
Geo Index Configuration

### ISSUE THREAD

**Issue by awanczowski** [marklogic/marklogic-data-hub#3226]
#### The issue

Short description of the problem: I would like to put a Geo Index on a JSON property in my entity.  I am unsure where to place the configuration in the Entity Definition JSON, Quickstart does not have a checkbox for a geo index either. 

```
{
 "point": "40.7710077206132 -73.9724806580638" 
}
```

What behavior are you expecting?

#### Tech details

Which version of MarkLogic are you using? 10.0.2-1

Which version of the Data Hub Framework are you using? 5.0.4

**Comment by xmlnovelist** [comment]
This would be a feature requested by insurers, who have geo-location data for claims, and for banks, who have geo-location data for mortgages, etc.

**Comment by rjrudin** [comment]
Tracking internally
