### ISSUE TITLE
Enable/disable automatic TDE template creation in DHF 4.x up

### ISSUE THREAD

**Issue by taatuut** [marklogic/marklogic-data-hub#3230]
Would be nice to enable/disable automatic TDE template creation in DHF 4.x up, because it can result in unwanted results as large amounts of data end up in triple index by default with corresponding memory demand. Or is there such a configuration setting?

Some possible workarounds for avoiding the generation of TDE templates (courtesy @rjrudin ):

1) Delete the DH triggers that cause this - the ml-dh-*-entity.json files in src/main/hub-internal-config/triggers; and remove them from the triggers databases as well

2) Keep generating the TDEs, but then remove them from the “ml-data-hub-tde” collection.. This will cause them never to be modified but new ones will still be created.

3) Overwrite entity-model-trigger.xqy in ml-modules. Start with DH’s version, and then remove the one line of code that inserts the TDE template.

Option 1 & 3 might get in the way of upgrades since it involves tweaking the internal code so a more fundamental solution would be great.

**Comment by ryanjdew** [comment]
Another workaround option is to generate the TDEs into the project with `./gradlew hubGenerateTDETemplates` and then set enabled to false on each of those generated templates. See https://developer.marklogic.com/recipe/disable-tde-templates/
