### ISSUE TITLE
Bubble up server errors to UI layer

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#326]
rather than silently failing in the java console.

**Comment by janmichaelyu** [comment]
Hi @paxtonhare , apologies for not working on this earlier.

I skimmed a bit on the project and I think we can use a custom logger to append to a websocket and https://github.com/Reactive-Extensions/RxJS Observable to listen.

**Comment by paxtonhare** [comment]
We already have a service listening to web sockets. All you would need to
do is handle the error messages.

**Comment by janmichaelyu** [comment]
@paxtonhare Do you have a sample error or case that should be handled?

**Comment by janmichaelyu** [comment]
Anything that calls logger.error under the com.marklogic.quickstart packages should call a template.convertAndSend(new LogMessage(error.getStackTrace()) and a LogListenerService in the ui package will listen and make those messages available to a toast or component?

**Comment by janmichaelyu** [comment]
I was having problems making a logback appender work with spring so I had to resort to the ExceptionHandlerController calling SimpMessagingTemplate and sending to /topic/log.

Current implementation shows the latest log in the header as I figure out how to use snackbar.

**Comment by aebadirad** [comment]
Closing out old issue that no longer applies to the latest major release.
