### ISSUE TITLE
make .tmp non-portable

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#327]
store and check the system id that generated the dir. if it differs then trash it.

**Comment by paxtonhare** [comment]
consider putting the .tmp dir in the user's home dir or system dependent cache type dir.

**Comment by kosed** [comment]
Not sure for all the content inside but at least, I would advocate to keep the mlcp options in a more visible subdir of the DHF project folder for portability and reusability across team members.

**Comment by aebadirad** [comment]
In the future, going to eliminate .tmp entire, and 5.0 does not make heavy use of this outside a module-reload watch. So closing as this is almost OBE and will be entirely soon.
