### ISSUE TITLE
tutorial/4x/harmonize-order-data-by-custom-code/ missing code in 3b - Customize the Content Plugin

### ISSUE THREAD

**Issue by loutfim** [marklogic/marklogic-data-hub#3295]
Hello, 

3b - Customize the Content Plugin in the following page ("https://marklogic.github.io/marklogic-data-hub/tutorial/4x/harmonize-order-data-by-custom-code/") is not showing code required to complete the tutorial. 

![image](https://user-images.githubusercontent.com/57417569/69338857-f3cbd300-0c5b-11ea-94e1-2b5014a4931f.png)

Please can you provide the code in the location after 
`2. Replace the content plugin code with the following:` 
Thanks

**Comment by wooldridge** [comment]
@eltesoro-ml, FYI.

**Comment by rjrudin** [comment]
This appears to have been addressed at https://marklogic.github.io/marklogic-data-hub/tutorial/4x/harmonize-order-data-by-custom-code/ , and this ticket was never updated to reflect that.
