### ISSUE TITLE
Improve label on "Source Query" field in Mastering Step

### ISSUE THREAD

**Issue by danielholgate** [marklogic/marklogic-data-hub#3296]
The Mastering Step has a field called "Source Query", and the help explains that it takes a CTS query (see screen shot). However, this text alone does not make it clear if this expression is supposed to be Javascript or XQuery. 
Please add "javascript" to make it clearer to end users what is expected (even better also add a very simple example: _cts.collectionQuery(“SOMECOLLECTION”)_ etc )

<img width="895" alt="Mastering_Step" src="https://user-images.githubusercontent.com/13762269/69345482-7e6afd00-0c71-11ea-9fa1-fe472226121b.png">

**Comment by rjrudin** [comment]
Closing as it's QS
