### ISSUE TITLE
Add validation to Mastering Step "Source Query" field 

### ISSUE THREAD

**Issue by danielholgate** [marklogic/marklogic-data-hub#3297]
The "Source Query" field in the Mastering Step takes a CTS expression
<img width="895" alt="Mastering_Step" src="https://user-images.githubusercontent.com/13762269/69346350-ea019a00-0c72-11ea-8c0a-5a74080522e4.png">

however, there is no validation of this expression/query and the step can be saved with any text at all in here.
Time and potential problems can be saved for end users by adding validation to this field so they cannot enter incorrect expressions which are only discovered later when the step gets run.

**Comment by sbayatpur** [comment]
Thanks @danielholgate. I can see how this could be a helpful feature and have added it to our backlog.

**Comment by rjrudin** [comment]
Tracking internally via DHFPROD-7018
