### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by aneer84** [marklogic/marklogic-data-hub#3316]
**Is your feature request related to a problem? Please describe.**

**What is the user-facing scenario that prompted this gap in functionality?**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jmakeig** [comment]
@aneer84 did you submit this in error? If you have an issue, please update the description above with some specifics.

**Comment by rjrudin** [comment]
Closing
