### ISSUE TITLE
Include Xquery custom step in QuickStart 

### ISSUE THREAD

**Issue by rawalpuneet** [marklogic/marklogic-data-hub#3328]
Data Hub 5.0.4 is missing Xquery custom step. It is required for customers who are still on XML and wants to utilize Xquery for data wrangling. 
Here are the customers I support that are currently using Xquery:
1. NT
2. AbbVie
3. GAIC
4. Ensemble

**Comment by sbayatpur** [comment]
@rawalpuneet Thanks for this feedback! Are all the customers you listed using QuickStart today?

**Comment by rjrudin** [comment]
Closing as it's QS, and an XQY custom step can be generated via Gradle
