### ISSUE TITLE
Possible typo on wiki page

### ISSUE THREAD

**Issue by jgraham0325** [marklogic/marklogic-data-hub#333]
#### The issue

Short description of the problem: I think there may be a minor typo in the wiki regarding calling running input flows from Java

What behaviour are you expecting?

Able to take the Java code from the wiki to run an input flow and run it by replacing the variables. 

ACTUAL:
Page: https://github.com/marklogic/marklogic-data-hub/wiki/Advanced-Hub-Usage
Section:
Via the MarkLogic Java Client API. You must specify the appropriate transform for the flow to be run:
...
runFlow.addParameter("entity**-name**", entityName);
runFlow.addParameter("flow**-name**", flowName);
...

EXPECTED:
runFlow.addParameter("**entity**", entityName);
runFlow.addParameter("**flow**", flowName);

#### Tech details

Had a look in the transform and it appears it's looking for parameters called "entity" and "flow", not "enitity-name" and "flow-name"

**Comment by paxtonhare** [comment]
Thanks, @jgraham0325. Fixed!
