### ISSUE TITLE
[BUG] Quickstart "Searching.." forever on Entity search when none in database

### ISSUE THREAD

**Issue by danielholgate** [marklogic/marklogic-data-hub#3333]
DHF v5.0.4 Quick Start running on Mac. MarkLogic 10.0-2.1 running in guest Linux VM.

In Quick Start:  On the **Browse Data** tab, if you check  "**Entities only**" and click **Search** and there are currently no Entities in the selected db (Staging or Final) then instead of immediately reporting "No data" in the lower section of the screen, the words "**Searching...**" stay on screen and the spinner spins forever.

![Screen Shot 2019-11-27 at 16 21 19](https://user-images.githubusercontent.com/13762269/69736403-b28f6380-1132-11ea-9b68-825f99670ede.png)

Expecting: If you search for entities and there are none in DB (or none that match query) then "No data" should be immediately displayed

**Comment by wooldridge** [comment]
@danielholgate, thanks. I can reproduce. Start with an empty project folder in QuickStart and go to the **Browse Data** tab. For STAGING, I see the following browser network error:
```
{"code":500,"messasge":"Local message: search failed: Bad Request. Server Message: REST-INVALIDPARAM: (err:FOER0000) Invalid parameter: No configured options: staging-entity-options","timestamp":"2019-11-27T22:59:29.649+0000"}
```
For FINAL:
```
{"code":500,"messasge":"Local message: search failed: Bad Request. Server Message: REST-INVALIDPARAM: (err:FOER0000) Invalid parameter: No configured options: final-entity-options","timestamp":"2019-11-27T22:59:37.255+0000"}
```
Issue has been filed: https://project.marklogic.com/jira/browse/DHFPROD-3825

**Comment by rjrudin** [comment]
Closing as it's QS
