### ISSUE TITLE
[BUG] Delete/Trashcan icon for Staging database also deletes flows

### ISSUE THREAD

**Issue by danielholgate** [marklogic/marklogic-data-hub#3337]
DHF v5.0.4 Quick Start running on Mac. MarkLogic 10.0-2.1 running in guest Linux VM.

On the **Dashboard** tab there is a trash can icon to delete documents from Staging, Final, or Jobs. My example DHF project here has a few flows and steps but currently no data documents loaded, so even in an empty state Staging has 25 documents representing those flows/steps:
<img width="665" alt="Screen Shot 2019-11-27 at 23 01 55" src="https://user-images.githubusercontent.com/13762269/69762664-3d8c5000-116b-11ea-856c-4a3361ddf5bd.png">

Unfortunately after the trashcan button is clicked for Staging the count for documents goes to zero and this means also all the flows from staging are gone. 
<img width="674" alt="Screen Shot 2019-11-27 at 23 00 49" src="https://user-images.githubusercontent.com/13762269/69762550-e1293080-116a-11ea-9198-2fe36ed6f10e.png">

If you then trying to run any flow you will receive the following error appears saying that the flow cannot be found.
<img width="813" alt="Screen Shot 2019-11-27 at 22 59 45" src="https://user-images.githubusercontent.com/13762269/69762391-57796300-116a-11ea-936d-8f421ed2aab2.png">

The flows must at this point be re-deployed to the DB

Expected behaviour is that:

1. The trash can icons should delete data documents only and not touch any DHF configuration files in Staging or Final
2. Count of configuration documents shouldn't be included in the total here and users shouldn't be aware of them as it is confusing

**Comment by wooldridge** [comment]
@danielholgate, thanks. This is known behavior, e.g., deleting database document via the UI requires a redeploy of flows. I've filed a Jira ticket here to review this: https://project.marklogic.com/jira/browse/DHFPROD-3826

**Comment by rjrudin** [comment]
@danielholgate Let's use the JIRA ticket for the conversation on this.
