### ISSUE TITLE
Allow exernal data to be passed in to a flow's options-map

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#334]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

The flows have an options-map, but there is no way to set data into that map from an external REST or Java caller.

Specifically, it would be helpful to be able to set batch-identifiers on data ingested to staging, then run harmonize only for that batch of data (perhaps marked as collections on the staging documents). but this feature would also allow many other forms of communication or extension.

**Comment by jmakeig** [comment]
Related to marklogic/java-client-api#552
