### ISSUE TITLE
[FEATURE] Collision Detection on Primary Key

### ISSUE THREAD

**Issue by awanczowski** [marklogic/marklogic-data-hub#3341]
**Is your feature request related to a problem? Please describe.**

As a user I would like documents to fail if the Primary Key defined by the entity model is already in use. 

**What is the user-facing scenario that prompted this gap in functionality?**

There is risk of duplication of records coming from source systems. 

**Describe the solution you'd like**

During the mapping step a document should fail if the Primary Key is already in use. 

**Describe alternatives you've considered**

Do not fail the document and add a collection defining the record as a duplicate.

**Comment by hao1st** [comment]
@awanczowski I think the primary key should be used to avoid duplication whenever we insert a document (Ingestion may come from other applications rather than DataHub/GS or just a script from QConsole).

**Comment by awanczowski** [comment]
@hao1st totally agree, that would best case. Right now when loading multiple documents with the same ID I do not get any errors. It just creates the records. Is there a suggested approach for this?

**Comment by sbayatpur** [comment]
We recommend using Smart Mastering to identify the duplicate records and merge them after mapping.

**Comment by rjrudin** [comment]
We are tracking internally possible duplicate resolution on ingest
