### ISSUE TITLE
[FEATURE] Compound Primary Keys

### ISSUE THREAD

**Issue by awanczowski** [marklogic/marklogic-data-hub#3342]
**Is your feature request related to a problem? Please describe.**

As a user I would like to be able to select multiple fields in the Entity Model to be used as a primary key. 

**What is the user-facing scenario that prompted this gap in functionality?**

Within the QuickStart UI you are only able to select one field as a Primary Key.

**Describe the solution you'd like**

Ability to check off multiple fields to be utilized as a primary key. 

**Describe alternatives you've considered**

Workaround has been to crate a new field that is used as the ID and create a custom step to concatenate values from the model to produce the key. This will be easier once functions are a available in mapping

**Comment by hao1st** [comment]
@awanczowski I was wondering the reason we want to have a composite key as the primary key? Only check and remove duplication? I guess the smart master step is what we can achieve...

**Comment by awanczowski** [comment]
@hao1st The record is not always identifiable by a single item. Think of Episodic content form a Title Management System. You would have the Show, Season and Episode Number which all lead to a unique record. So, you would have something like GoT-S1-E1.

**Comment by sbayatpur** [comment]
@awanczowski this is just a request for QuickStart right? You are able to manipulate the Entity Services files outside of the UI to have multiple primary keys?

**Comment by awanczowski** [comment]
@sbayatpur I have not tried marking multiple items as the PK but the JSON definition for `primaryKey` is only a string field, not an array.

**Comment by awanczowski** [comment]
@sbayatpur Looks like it can not be an array.

https://docs.marklogic.com/guide/entity-services/models#id_88103

> You cannot use an entity property with array type as a primary key or for generating database configuration artifacts such as range index or word lexicon configuration.

**Comment by rjrudin** [comment]
@awanczowski This likely won't change in the near-term due to the limitation you pointed out in the ES docs. Note though that there aren't any DHF features (IIRC) that actually care about primaryKey - i.e. you're allowed to have multiple docs that have the same value for this property. It's more of an aspirational feature in ES. As such, if you have a real need for this,  just add your own metadata to the model. I can't speak for QS, but HC will not drop any of that metadata on the floor.
