### ISSUE TITLE
[FEATURE] Write installation logs to file in QuickStart

### ISSUE THREAD

**Issue by devinnicholson** [marklogic/marklogic-data-hub#3346]
I had a failed installation occur with a QS installation. Re-installation fixed the issue, but it still would've been helpful to look at the installation logs to figure out what caused a failure the first time. I didn't know the installation info wasn't written to file, but instead were written to console, so I wasn't able to send anyone debug info.

**Comment by hao1st** [comment]
@devinnicholson I believe that GS could improve with better user experience and trouble-shooting during installation and upgrade.

**Comment by rjrudin** [comment]
Closing as it's QS
