### ISSUE TITLE
[FEATURE] Ingest step with Source/Target format of "Binary" does not generate envelope

### ISSUE THREAD

**Issue by danielholgate** [marklogic/marklogic-data-hub#3375]
Quick start v5.1.0

When a document is loaded with an _ingest step that has target type of "Binary"_, the file gets inserted into MarkLogic without generating an envelope.

(You can actually use this to load XML, JSON etc without wrapping them in an envelope.. Not sure if this was the intention, but I can see it might actually some times be useful on projects)

However, this means there is no way through QuickStart to load PDFs and binary documents and associate them to a DHF envelope, and this doesn't fit the Envelope pattern..Questions like when was the binary loaded? etc. cannot be answered or tracked because no envelope = No metadata

The situation at the moment creates a lot of work for developers because even though the binary is now in MarkLogic they then need to manually process it, create their own DHF Envelope, linking it to the binary or extracted text from it etc.

**Expected Behaviour**
An envelope is created even when Target Type is "Binary"
In addition, it would be much better if the DHF framework/QuickStart the following for binary documents on ingest:

1) Insert the binary document at a URI (already happening at the moment)✅
2) Create a DHF envelope (at a different URI to #1) which contains an element/property pointing to the URI of the binary node in #1
3) Include an additional option in the Ingest Step when Source type is Binary (and file has certain extensions?) to run xdmp:document-filter on the document in 1 and insert the extracted content it into the envelope created in #2

Going as far as #3 would be the ideal, because 90% of the time the reason people load binaries into MarkLogic is to run document-filter and extract the content
However at the very least #2 is essential to bring binary ingest into line with the core DHF philosophy of Enveloping and make life much easier for developers/consultants

Sample PDF data file:
[example.pdf](https://github.com/marklogic/marklogic-data-hub/files/3954957/example.pdf)

**Comment by xnikhil08** [comment]
@danielholgate - Looking into this issue. Thanks for bringing this to our attention.

**Comment by xnikhil08** [comment]
@danielholgate - Could you please share a sample input document which you are trying to ingest and your expected output envelop pattern, along with any other input properties/parameters you might be using in the ingest step ?
This would help us to reproduce the issue.

**Comment by danielholgate** [comment]
Hi @xnikhil08 I added a sample PDF data file and updated the description in the ticket. 
Re-tested on 5.1 and this still occurs in latest version

**Comment by rjrudin** [comment]
Metadata is still added via document metadata keys. But the DHF ingestion step approach is to ingest the binary as a binary, so that means it's not wrapped in JSON or XML. If a different approach is desired, just use a custom ingestion step or REST transform.
