### ISSUE TITLE
[BUG] Entity versioning in QuickStart breaks Mapping steps to that entity

### ISSUE THREAD

**Issue by danielholgate** [marklogic/marklogic-data-hub#3385]
Quickstart version 5.1

**Problem:**
Changing the version of an entity in the UI breaks any Mapping steps which reference it. These steps can't be fixed through the QuickStart UI except by deleting and re-creating.

The error looks like this in Quickstart UI:

<img width="769" alt="Screen Shot 2019-12-11 at 15 03 20" src="https://user-images.githubusercontent.com/13762269/70628163-ed5fc400-1c27-11ea-97c0-f2b31ba19e89.png">

testing the mapping step shows this error as well
<img width="1405" alt="Screen Shot 2019-12-11 at 15 21 29" src="https://user-images.githubusercontent.com/13762269/70629229-f18ce100-1c29-11ea-9511-05c6c7cc007f.png">

**To Reproduce the problem**
Attached is a sample project (entity_version_bug_DHF.zip) with a simple flow called "test-flow" (ignore the "test-flow-2" flow) which ingests a few rows of a csv file, and then maps them to an entity called "Component". Note that the version of Component is **0.0.1.** Also attached is the data in a zip file (csv file. the data doesn't matter to this problem though, it's just to recreate). 
Set up this DHF project, change the location of the data file etc in the ingest step, and run it to test it works and that you can run the Mapping step to the Component entity. This should all work. 
Now, go to the entity and change the version number to **0.0.2** and save it. After this the mapping step no longer works because it is looking for Entity version 0.0.1.

At minimum I'd expect that either: 
A) Changing the version of an Entity (in Quickstart or directly on disk) shouldn't stop mapping steps from working. ie. that Mapping Steps don't really care which version of an entity they're trying to map to when they are run
or
B) a warning message is displayed in the UI to say "changing this entity version will require any mapping steps to be updated"

If the answer is B) there needs to be a way in QuickStart to identify and "fix" those Steps referencing the  Entity. 

**Fixing This**
I'm not sure what the design philosophy should be: Entities are a core MarkLogic concept, and Flows/Steps are a DHF concept - how do they relate together when Entities are versioned? Should DHF Mapping steps also be versioned? ie. When a new Entity version gets created, then new versions of all Mapping steps that map to it is also get automatically created to reflect the new entity version etc?  A part of the problem is also that QuickStart don't keep 0.0.1 on disk, it is now gone and overwritten by 0.0.2

Some design thinking required here

[entity_version_bug_DHF.zip](https://github.com/marklogic/marklogic-data-hub/files/3950796/entity_version_bug_DHF.zip)

[test_data.zip](https://github.com/marklogic/marklogic-data-hub/files/3950798/test_data.zip)

**Comment by rjrudin** [comment]
A mapping step cares about the entity version as it needs to be sure it's using the correct entity model when the mapping artifacts are created, and also when a mapping is validated. 

I don't think a mapping can be automatically updated to use a different entity model. A user really has to be in charge of the decision to say, "This mapping should use this version of an entity model". 

Currently, a user must modify the mapping manually to associate the mapping with a different entity version. 

So I think this is a feature request to say something along the lines of - when I'm modifying a mapping, give me the ability to pick the version of an entity model to associate with my mapping.

**Comment by danielholgate** [comment]
@rjrudin I agree: Another problem is that the Quickstart doesn't even keep version 0.0.1 of the entity anyway, it is gone and over-written by version 0.0.2.
So this is a sort of poor-mans versioning..looks like it but it's actually not doing anything like controlling multiple versions of the same entity. Note that adding/removing properties doesn't change the version number, you have to do it manually

**Comment by rjrudin** [comment]
Closing as HC intentionally does not expose version since changes to it are not yet supported throughout DHF
