### ISSUE TITLE
[FEATURE] Delete document based on context or collection

### ISSUE THREAD

**Issue by awanczowski** [marklogic/marklogic-data-hub#3389]
**Is your feature request related to a problem? Please describe.**

Under certain circumstances we have seen the need to delete a record from the data hub. For example, the origin system send messages to the data hub to remove records.

**What is the user-facing scenario that prompted this gap in functionality?**

We have been requested to do soft and hard deletes in cases such as CDC, duplicative record insertions, or just origin updates provided in batch.

**Describe the solution you'd like**

As a user I would like to mark items for deletion. The items marked should be removed from the database.

**Comment by jmakeig** [comment]
Temporal management does this for you. Is that a viable solution?

**Comment by awanczowski** [comment]
@jmakeig does this require bi-temporal indexes to be configured? Will this still retain the documents, just not make them visible?

**Comment by jmakeig** [comment]
Uni-temporal is also possible in recent releases of MarkLogic. Yes, temporal requires some bookkeeping metadata. (So will maintaining your own tombstones.)

**Comment by awanczowski** [comment]
Interesting, I'll take a look into this.

**Comment by jmakeig** [comment]
Please follow up on this thread with what you find or any other questions.

**Comment by rjrudin** [comment]
Closing due to lack of response
