### ISSUE TITLE
gradle commands for flow creation

### ISSUE THREAD

**Issue by miguelrgonzalez** [marklogic/marklogic-data-hub#339]
#### The issue

gradle hubCreateHarmonizeFlow -PentityName=EntityName -PflowName=FlowName -PpluginFormat=xqy

gradle hubCreateInputFlow -PentityName=EntityName -PflowName=FlowName -PpluginFormat=xqy

both commands create the folder structure and all necessary files with one small issue. The xml describing the flow has the incorrect data format:

<flow xmlns="http://marklogic.com/data-hub">
  <complexity>simple</complexity>
  <data-format>application/json</data-format>
  <plugins/>
</flow>
#### Tech details

Which Operating System are you using? OSX Sierra 10.12.1

Which version of MarkLogic are you using? 8.0-5.5

Which version of the Data Hub Framework are you using? 1.0.1

**Comment by paxtonhare** [comment]
You need to use the -PdataFormat=xml flag to specify
