### ISSUE TITLE
[BUG] DHF 5.1: ingestion step does not seem to follow symlinks

### ISSUE THREAD

**Issue by crism** [marklogic/marklogic-data-hub#3409]
#### The issue

Short description of the problem: When pointing an ingestion step to a directory full of symlinks, nothing is ingested.

What behavior are you expecting? Ingestion.

What are the steps to reproduce the issue:
1) Make a directory with some binary files in it.
1) Create an ingestion step that loads files from that directory.
1) Observe that files are ingested.
1) Create another directory. Create symbolic links to some or all of the files in the first directory.
1) Modify the ingestion step to load from the new directory.
1) Observe that no files are ingested.

#### Tech details

Which Operating System are you using? CentOS 7

Which version of MarkLogic are you using? 9.0-11

Which version of the Data Hub are you using? 5.1

Is this a QuickStart UI bug? If so, which browser are you using? N/A

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output: a debug-level log of attempted symlink ingestion is attached.
[dhf_ingestion_symlink.log](https://github.com/marklogic/marklogic-data-hub/files/3980960/dhf_ingestion_symlink.log)

**Comment by hao1st** [comment]
@crism I do not think DHF ingestion supports symbolic link now.

**Comment by rjrudin** [comment]
Closing, use MLCP for advanced file ingestion
