### ISSUE TITLE
[FEATURE] Ability to have variable source and target databases

### ISSUE THREAD

**Issue by awanczowski** [marklogic/marklogic-data-hub#3423]
**Is your feature request related to a problem? Please describe.**
As a developer I would like to have the ability to use dynamic variables, ideally coming from the gradle properties, to define the source and target database. 

This can help 

**What is the user-facing scenario that prompted this gap in functionality?**
Developers using multi-tenant dev machines use different database names to avoid conflicts. When elevating to QA/UAT/PROD there would be only a single set databases for the hub.

**Describe the solution you'd like**
The database names for staging and final from the gradle properties would be used to replace a dynamic variable in a Step definition for the source and target DB during deployment. 

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.f
Perhaps a sort of app config with variables that define the staging and final DBs  mapped to a MarkLogic database.

**Comment by rjrudin** [comment]
@sbayatpur @aroach337 This is a straightforward enhancement to the DHF commands for loading hub and user artifacts. I'd be fine with adding it to the "orchestration" bucket for 5.2.0.

**Comment by rjrudin** [comment]
This is supported in DHF 5.4.0 - artifact files support tokens
