### ISSUE TITLE
[BUG] DHF 5.1: Match queries are over-constrained and may never succeed

### ISSUE THREAD

**Issue by crism** [marklogic/marklogic-data-hub#3425]
#### The issue

Short description of the problem: Match queries began failing after upgrading to DHF 5.1.

What behavior are you expecting? Items with identical property values to match.

What are the steps to reproduce the issue:
1) Install DHF 5.1.
2) Run a mastering step with JSON data. Add a log message to serialize the match query.
3) Note that the query is something like this:
```json
{
  "jsonPropertyScopeQuery":{
    "property":["instance"],
    "query":{
      "andQuery":{
        "queries":[{
          "collectionQuery":{
            "uris":["collection-specified-in-step"]
          }
        }, {
          "andNotQuery":{
            "positiveQuery":{
              "andQuery":{
                "queries":[{
                  "jsonPropertyScopeQuery":{
                    "property":["instance"],
                    "query":{
                      "jsonPropertyScopeQuery":{
                        "property":["info"],
                        "query":{
                          "jsonPropertyValueQuery":{
                            "property":["title"],
                            "value":["entity-type"],
                            "options":["lang=en"],
                            "weight":0
                          }
                        }
                      }
                    }
                  }
                }]
              }
            },
            "negativeQuery":{ ... }
          }
        }]
      }
    }
  }
}
```
The outermost part of the query specifies a scope of `instance`; the inner check for `entity-type` also specifies a scope of `instance`, meaning that this is trying to match `instance/instance/info/title`, which will generally fail.

#### Tech details

Which Operating System are you using? CentOS 7

Which version of MarkLogic are you using? 9.0-11

Which version of the Data Hub are you using? 5.1

#### The devil is in the details...

This appears to come from the new `base-content-query` part of the compiled match options.

**Comment by rjrudin** [comment]
I am wondering if we need your project setup as well, as I don't see this happening with the projects in the ./examples directory - I use dh-5-example on a regular basis for testing, and I haven't had any problems there.

**Comment by crism** [comment]
I can’t see why this isn’t a problem with the examples; it only seems to depend on the `target-entity` being defined, which it is in `dh-5-example`. The only other difference I can see is separate matching and merging steps instead of a single mastering step, but I don’t think that would matter.

**Comment by rjrudin** [comment]
Can you try the dh-5-example out locally and see if you get the same problem? Also, if you have time - can you try using a mastering step in dh-5-example instead of separate matching/merging steps to see if you get the same problem?

**Comment by rjrudin** [comment]
Closing due to PR #3452
