### ISSUE TITLE
[BUG] Upgrade to DHF5 documentation not correct

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic/marklogic-data-hub#3435]
The documentation should be updated:

https://docs.marklogic.com/datahub//upgrade.html - is mentioning DHF 5.1.0 is running on 9.0-7 or later. This is incorrect. It should be 9.0-10.3 or 10.0.2 or later. You should only refer to the version compatibility page so that you only need to maintain versions on 1 page. 

https://docs.marklogic.com/datahub//upgrade.html - is giving as advice to run `mlDeploy`. This is not correct. This should be mlRedeploy, because else you keep the DHF 4 stuff in a already deployed application.

**Comment by rjrudin** [comment]
Thanks @josvanroosmalen - I opened https://project.marklogic.com/jira/browse/DHFPROD-4070 for internal tracking, that will likely be assigned to a sprint today. Going to close this as the fix will be tracked via JIRA.
