### ISSUE TITLE
[BUG] DHF 5.1: Inconsistent field index declaration and use for datahubCreatedByJob

### ISSUE THREAD

**Issue by crism** [marklogic/marklogic-data-hub#3440]
#### The issue

Short description of the problem: the `datahubCreatedByJob` field has an index defined with an English collation, but a field reference with root collation. This causes intermittent (and difficult to reproduce) errors when deploying.

What behavior are you expecting? Clean deployment.

What are the steps to reproduce the issue:
1) Install DHF 5.1.
2) Run `./gradlew mlDeploy`.

#### Tech details

Which Operating System are you using? CentOS

Which version of MarkLogic are you using? 9.0-11

Which version of the Data Hub are you using? 5.1.0

**Comment by crism** [comment]
This is already being tracked internally. but I’m patching it locally and may as well submit a PR.

**Comment by rjrudin** [comment]
@crism We've got the JIRA ticket to track this internally, so no need for another ticket. Thanks for submitting the PR though.
