### ISSUE TITLE
[FEATURE] input_file_path should support a single file

### ISSUE THREAD

**Issue by peetkes** [marklogic/marklogic-data-hub#3442]
If I overwrite the input_file_path option in the Ingest step so it points to a single file, the ingest fails when run inside Quickstart but when I copy the mlcp command and run it in a terminal it will execute fine and ingests the content of the input_file_path.
Find below the command copied from quickstart
````
mlcp.sh import -mode "local" -host "localhost" -port "8010" -username "admin" -password "admin" -input_file_path "/Users/pkester/Development/DIKW/SensingClues/Data/WildlifeWorks/arrestees/Arrestees.csv" -input_file_type "delimited_text" -generate_uri "true" -output_collections "TestIngest" -output_permissions "rest-reader,read,rest-writer,update" -output_uri_replace ".*/Data,''" -document_type "json" -transform_module "/data-hub/5/transforms/mlcp-flow-transform.sjs" -transform_namespace "http://marklogic.com/data-hub/mlcp-flow-transform" -transform_param "flow-name=Test,step=1"
````

This is tested on ML 10.0-2.1 and DHF 5.1.0 on CentOS 7

**Comment by rjrudin** [comment]
Thanks, I've opened a JIRA ticket internally - https://project.marklogic.com/jira/browse/DHFPROD-4084 - and thus will close this.

**Comment by rjrudin** [comment]
I re-titled this as a new feature, as for better or worse, the current design is that it must be a directory, so there was evidently a reason not to support a single file before.

**Comment by rjrudin** [comment]
Closing as this is specific to QS
