### ISSUE TITLE
[FEATURE] Add support for input_file_pattern on ingest step

### ISSUE THREAD

**Issue by peetkes** [marklogic/marklogic-data-hub#3443]
When you create an ingest step there is no way to specify an input file pattern. This is a supported option for MLCP so it would be very handy to add support for this option in quickstart as well.

**Comment by rjrudin** [comment]
Thanks, I've opened a JIRA ticket internally - https://project.marklogic.com/jira/browse/DHFPROD-4085 - and thus will close this.

**Comment by rjrudin** [comment]
Closing as it's specific to QS; should use MLCP for normal file ingestion
