### ISSUE TITLE
[DOC] DHF 5.1: Document REST transforms, their uses, and parameters

### ISSUE THREAD

**Issue by crism** [marklogic/marklogic-data-hub#3447]
Following up on #3032, the [current documentation](https://docs.marklogic.com/datahub/refs/rest-extensions.html) is not very useful for the uninitiated. It could be expanded to describe what those transforms do, and what parameters they take.

**Comment by timur-isangulov** [comment]
Internal Jira ticket created to track: https://project.marklogic.com/jira/browse/DHFPROD-4114.

**Comment by rjrudin** [comment]
Tracking internally
