### ISSUE TITLE
[BUG] Source document is not being displayed in mapping screen

### ISSUE THREAD

**Issue by Scapadiver** [marklogic/marklogic-data-hub#3448]
*### Welcome Hub enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

Short description of the problem:

entity mapping, not displaying source json document

What behavior are you expecting?

it to display the source document and allow mapping

What are the steps to reproduce the issue:
1) flow attached
2) source doc attached
3) piiEntity is in use

#### Tech details

Which Operating System are you using?

os x - current 10.14.6

Which version of MarkLogic are you using?

10.0-2.1

Which version of the Data Hub are you using?

5.1.0

Is this a QuickStart UI bug? If so, which browser are you using?

quickstart, chrome
[dhf-content.zip](https://github.com/marklogic/marklogic-data-hub/files/4042980/dhf-content.zip)
[message-to-be-mapped..txt](https://github.com/marklogic/marklogic-data-hub/files/4042987/message-to-be-mapped.txt)

the message-to-be-mapped is the result of the custom flow.  it is now a json document.

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar marklogic-datahub-<version>.war  --debug  > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -debug > myoutput.txt`

**Comment by rjrudin** [comment]
I'm taking a look at this now.

**Comment by rjrudin** [comment]
Correction - @timur-isangulov is going to wrangle this one first - @timur-isangulov let me know if you need a second pair of eyes.

**Comment by timur-isangulov** [comment]
Stan, the entities are missing in the attached project, mapping won't work without them. Can you please attach the relevant entity files.

**Comment by Scapadiver** [comment]
[main-dir.zip](https://github.com/marklogic/marklogic-data-hub/files/4054929/main-dir.zip)

updated entity info

**Comment by Scapadiver** [comment]
uploaded.

**Comment by Scapadiver** [comment]
[BSCA-DHF.zip](https://github.com/marklogic/marklogic-data-hub/files/4055295/BSCA-DHF.zip)

**Comment by timur-isangulov** [comment]
Internal ticked created https://project.marklogic.com/jira/browse/DHFPROD-4124. Thanks.

**Comment by srinathgit** [comment]
The source document's instance property is empty, that's why nothing shows up in mapping UI. It is expected.

**Comment by srinathgit** [comment]
I will go ahead and close this issue.
