### ISSUE TITLE
[BUG] DHF 5.1: Match query options get and-ed instead of or-ed

### ISSUE THREAD

**Issue by crism** [marklogic/marklogic-data-hub#3451]
#### The issue

Short description of the problem: After upgrading to DHF 5.1, matches that succeded previously began to fail.

What behavior are you expecting? Successful match.

What are the steps to reproduce the issue:
1) Create a match rule with both add and expand options.
2) Log the match query.
3) Observe that the add and expand sub-queries are joined in an `and-query()`; typically, they will not both be true, and so matching will fail.

#### Tech details

Which Operating System are you using? CentOS 7

Which version of MarkLogic are you using? 9.0-11

Which version of the Data Hub are you using? 5.1.0

#### The devil is in the details...

The problem appears to stem for the change to use `group-queries-by-scope()`, the results of which are then anded. This is a change from DHF 5.0.3, in which minimum threshold queries were grouped in an `or-query()`.

**Comment by ryanjdew** [comment]
Tracking internally with https://project.marklogic.com/jira/browse/DHFPROD-4160
