### ISSUE TITLE
Custom Step Error handling and collection tag

### ISSUE THREAD

**Issue by chenfiona** [marklogic/marklogic-data-hub#3456]
**Is your feature request related to a problem? Please describe.**
It is not a problem. 

**What is the user-facing scenario that prompted this gap in functionality?**
Data Hub Custom Step Error Handling and Collection Tag

**Describe the solution you'd like**
Need clarification about how to add a special collection tag to the document that failed:
https://docs.marklogic.com/datahub//modules/editing-custom-step-module.html

**Describe alternatives you've considered**
N/A

**Additional context**
Please provide details regarding below:
" Instead of throwing an error, You can add a special collection tag to the document that failed.
    In another step, you can search for documents with that collection tag and fix them accordingly."
My Request is how to add special collection tag to failed documents during the custom steps. This is a constant challenge for data hub custom step error handling. When custom step failed in the middle of flow-running, the error doesn't produce enough information as which document failed. It only gives a generic error.

**Comment by rjrudin** [comment]
While not stated, I believe the expectation is that a try/catch will be used in the custom step module. You can wrap everything in your custom step module function within a try/catch, and then in the catch block, you can set the collections or make any other changes you want to indicate that an error occurred. 

That's a short-term workaround. I think you're pointing at a potential broader solution - i.e. where a flow developer can configure options on a step to indicate changes to be made to a failed document - e.g. by setting errorCollections:["error1"], any document that fails a step would be added to the "error1" collection. Is that correct? 

Assigning @sbayatpur in anticipation of this being a potential new requirement.

**Comment by chenfiona** [comment]
Yes, That potential options in a step or other whatever build-in module is what I am asking for. 
The current error message is too vague. It will be great to implement a build-in try/catch mechanism so as to identify where/what exactly causes the failure quickly. 
It seems to me if the custom step failed just at one particular document, the subsequent documents can't be processed further.  So it will be difficult to use try/catch to add all the failed documents in that collection?

**Comment by rjrudin** [comment]
As long as your custom step doesn't have "acceptsBatch:true" in the step configuration, then each document will be processed one at a time by the step. If one fails, the others in the batch should still be processed. For example, if you have a batch of 100 and 5 of the documents fail, the other 95 should still be processed. The Batch document in the jobs database will then have the error messages for the 5 documents that failed. Are you seeing that data in your jobs database?

**Comment by chenfiona** [comment]
I did see some successfully custom data in the FINAL. The real questions are:
1. I am not sure if  95 out of 100 is still processed. It seems the opposite: the majority of data failed to be populated in FINAL. I think there is also difference if you set the failhard to TRUE. 
2. Again, the log didn't specify which doc and what part exactly failed.  I am not able to identify the bottleneck when the error message is massive and the same.

**Comment by rjrudin** [comment]
I was just mentioning 5 out of 100 failing as a theoretical example. For your case, try setting the batch size to 1 and also greatly limit the amount of data you're running through the step - it's much easier to debug processing a small amount of data. I'd start with batch size of 1 and a single document to process - you can modify your sourceQuery to be a cts.documentQuery on the URI of a document. Try debugging from there.

**Comment by chenfiona** [comment]
Okay.  May I know where I should add the try/catch? The supposition is that cts.search with which query on a JSON property value doesn't return any document and the subsequent custom process fails.  
Or do you have relevant documents?

**Comment by chenfiona** [comment]
I think one of the approach from DH design point of view is :  you can embed the try/catch in DH custom step module which return the uri and error message in the log.  
As a DH consumer, I use other method instead of try/catch. My goal is exception handling. The harmonisation process should be transparent to the end users.

**Comment by rjrudin** [comment]
Ultimately, what feature are you looking for here? I don't want to lose sight of that. Is it the ability to configure e.g. collections on documents that fail?

**Comment by chenfiona** [comment]
What I am looking at is: 
1. Embedded the try/catch in DH custom step module which returns URI and error message in the log
2. configure the failed documents into collection as you suggested

Option 1 is the practical solution in terms of troubleshooting.

**Comment by rjrudin** [comment]
@sbayatpur The feature request here is the ability to configure step options so that documents that fail in a batch are e.g. assigned to a particular collection.

**Comment by rjrudin** [comment]
Revisiting this - the Batch document captures the exact error, along with the URI of the document that failed. And as mentioned above, a developer writing a custom step is free to do whatever she wants for handling errors. 

Also note that DHF only writes documents outputted by a step; it doesn't modify documents that are inputted to a step. And as of 5.4, a user can input items that are not URIs. In that scenario, DHF wouldn't have anything to modify. So I don't think we're going to go down a road of DHF modifying input documents that fail, particularly since the Batch document captures that error. 

Finally, I just did a test on DHF 5.4.0 where I introduced an error into a mapping step module, and logging does show it:

```
{"message":"Error running step: TypeError: Cannot read property 'exist' of undefined. TypeError: Cannot read property 'exist' of undefined\n    at main (/data-hub/5/builtins/steps/mapping/entity-services/main.sjs:15:38)\n    at Flow.runMain (/data-hub/5/impl/flow.sjs:632:12)\n    at Flow.runStep (/data-hub/5/impl/flow.sjs:382:60)\n    at Flow.runFlow (/data-hub/5/impl/flow.sjs:268:12)\n    at /data-hub/5/data-services/stepRunner/processBatch.sjs:41:14","type":"error","currentDateTime":"2021-03-08T03:07:55.035375Z","user":"admin","serverID":"11598641433042032112","serverName":"data-hub-STAGING","dbID":"7917752692901693229","dbName":"data-hub-STAGING","modulesDbID":"11041026547942063338","modulesDbName":"data-hub-MODULES"}
```

So between logging and the Batch document capturing the error, I don't think we'll support having DHF modify an input document that fails, particularly when an input document may not exist.
