### ISSUE TITLE
Validate gradle run-flow inputs

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#346]
#### The issue
`gradle hubRunFlow -PentityName=Customer  -PflowName=load-activities`
is invalid (missing `-PflowType` per instructions here: https://github.com/marklogic/marklogic-data-hub/wiki/Advanced-Hub-Usage)

so it fails with:

  > Local message: Could not read resource at resources/flow. Server Message: The requested flow was not found
 
What behavior are you expecting?
That's reasonable, but it would be great if the inputs were checked and there was a readable message:

    > Usage: gradle parameter "flowType" is required, but not specified

**Comment by aebadirad** [comment]
Closing out old issue that no longer applies to the latest major release.
