### ISSUE TITLE
[FEATURE] Securing non-PII paths via Quickstart

### ISSUE THREAD

**Issue by awanczowski** [marklogic/marklogic-data-hub#3467]
**Is your feature request related to a problem? Please describe.**

There is a need to secure paths that are not PII data but require elevated permissions to see the data. I know this can be done solely with config. However, it would be nice for non-technical users to secure paths.

**What is the user-facing scenario that prompted this gap in functionality?**

As a user I would like QuickStart to allow for additional protected paths. It would be nice to select from a set of MarkLogic roles available. 

**Describe the solution you'd like**
It would be nice to have a new form field with a type-ahead that will list the roles and allow for multiples to be selected.

**Comment by rjrudin** [comment]
I'm closing this because I don't see us providing non-Pari-users with this ability. I think it's a fairly technical thing - it requires knowledge of a path and of ML roles. I don't see that generally being done by business analysts.
