### ISSUE TITLE
[BUG] Failed to run hubUpdate

### ISSUE THREAD

**Issue by frankietsang** [marklogic/marklogic-data-hub#3469]
[debug.txt](https://github.com/marklogic/marklogic-data-hub/files/4067282/debug.txt)
*### Welcome Hub enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

Short description of the problem:
Trying to upgrade from 5.0.2 to 5.1.0.  After updating the build.gradle and ran hubUpdate, I got the following error:

* What went wrong:
An exception occurred applying plugin request [id: 'com.marklogic.ml-data-hub', version: '5.1.0']
> Failed to apply plugin [id 'com.marklogic.ml-data-hub']
   > Could not set unknown property 'command' for task ':mlUpdateIndexes' of type com.marklogic.gradle.task.databases.UpdateIndexesTask.
What behavior are you expecting?

What are the steps to reproduce the issue:
1) gradlew hubUpdate -i

#### Tech details

Which Operating System are you using?
MacOS

Which version of MarkLogic are you using?
10.0-2

Which version of the Data Hub are you using?
Upgrade from 5.0.2 to 5.1.0

**Comment by rjrudin** [comment]
My guess is that in your build.gradle file, you are both importing the DHF Gradle plugin and the ml-gradle plugin. You don't want to do the latter. Odds are, you have an earlier version of ml-gradle that doesn't have the change to UpdateIndexesTask that DHF 5.1.0 is depending on. 

So check your build.gradle file for a line that applies or imports ml-gradle - remove that, and give it another try. If you still have a problem, please attach a sanitized copy of your build.gradle file to this ticket.

**Comment by frankietsang** [comment]
@rjrudin You are correct. There was a specific reference to ml-gradle. Before I saw your comment, I updated it to the latest version and the problem went away.  

I have since removed the ml-gradle from the plugins section and it works as well.  Thanks.
