### ISSUE TITLE
[BUG] DHF 5.1 - Smart Mastering:  proc-impl:expand-uris-for-merge in /com.marklogic.smart-mastering/impl/process.xqy has significant performance problem

### ISSUE THREAD

**Issue by derms** [marklogic/marklogic-data-hub#3471]
#### The issue

proc-impl:expand-uris-for-merge in /com.marklogic.smart-mastering/impl/process.xqy has a significant performance problem

Specificially this line -
Line 201

https://github.com/marklogic/marklogic-data-hub/blob/03017ccf955eab91c406dccde4f8d7ce14752821/marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/process.xqy#L201

#### Details

When performing a very simple match operation across 220 documents (140 of which are matched together), the matching step took 1 to 2 minutes. The CPU was maxed out at 100% during this time. Further exploration into the tasks being executed showed that almost all of the time was being spent in the '/com.marklogic.smart-mastering/impl/process.xqy' script - line 201. 

Replacing this line with '()' resulted in the execution taking only 8 seconds (and the results were the same for the use case tested).

Merge config below -
![image](https://user-images.githubusercontent.com/1885934/72534847-cffdc580-3877-11ea-9b82-6bf9718abd31.png)

#### Tech details

Which Operating System are you using? Mac

Which version of MarkLogic are you using? 10.0-2

Which version of the Data Hub are you using? 5.1

**Comment by jamesagardner** [comment]
Consider producing a map of all matching `/result/@action` and `/result/@uri` values.  Then use map:get to replace the XPath expression.

**Comment by rjrudin** [comment]
https://project.marklogic.com/jira/browse/DHFPROD-4150

**Comment by derms** [comment]
i think there may be a logic problem somewhere in the code, as for the small data set outlined in the code, this line is called 11,000 times

**Comment by rjrudin** [comment]
Closing because we're tracking this via DHFPROD-4150
