### ISSUE TITLE
inputFilePath and /envelope/headers/createdUsingFile is missing

### ISSUE THREAD

**Issue by chenfiona** [marklogic/marklogic-data-hub#3475]
*### Welcome Hub enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

Short description of the problem:

What behavior are you expecting?

/envelope/headers/createdUsingFile is missing when there are multiple files (JSON || XML) in the inputFilePath.

What are the steps to reproduce the issue:
1)   create an Ingestion step
2)   prepare multiple JSON || XML files in a dir
3)   inputFilePath points to that dir and run this Step
4)   When only a single file is in presence, /envelope/headers/createdUsingFile is generated

#### Tech details

Which Operating System are you using?
Windows

Which version of MarkLogic are you using?
10.0-2.1
Which version of the Data Hub are you using?
5.1.0
Is this a QuickStart UI bug? If so, which browser are you using?
No

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar marklogic-datahub-<version>.war  --debug  > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -debug > myoutput.txt`

**Comment by rjrudin** [comment]
The current approach for populating createdUsingFile is that it's only set when ingesting CSV files. The filename for JSON/XML files will be be present in the URI of each corresponding document. 

Note also that with mlcp, which is much more common to use for ingesting files (while still using the DHF transform for MLCP to reference an ingestion step), the filename will also be in the URI.
