### ISSUE TITLE
Better error Reporting on install

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#348]
Exceptions during the bootstrap process are difficult to debug.

For example, I just bootstrapped an invalid json payload because I had the same range index twice. Server threw MANAGE-INVALIDPAYLOAD and the install failed. Problem was that nothing logged out the actual payload that was sent to MarkLogic.

Add better try/catch support to return the actual payloads causing the error up to the user.

**Comment by aebadirad** [comment]
Unfortunately, this is what we have returned from the server.

We now spit out the payload that was attempted to use though, which I believe resolves this issue specifically.
