### ISSUE TITLE
[BUG] Cannot change the URI in custom ingest step 

### ISSUE THREAD

**Issue by jkerr5** [marklogic/marklogic-data-hub#3486]
#### The issue

Short description of the problem:
In a custom ingest step, if I set `content.uri` to a new value, the document does not get the new URI. It is inserted with the URI that is passed into the step. This is when running the step from QuickStart.

What behavior are you expecting?
To use the URI that I set when writing the document.

What are the steps to reproduce the issue:
1) Create a custom ingest step
2) Set content.uri = '/mytest.json'
3) Run the step against a directory containing a json file

#### Tech details

Which Operating System are you using?
Mac

Which version of MarkLogic are you using?
10.0-2

Which version of the Data Hub are you using?
5.1

Is this a QuickStart UI bug? If so, which browser are you using?
It seems to be related to the way QuickStart runs the step using DMSDK

**Comment by rjrudin** [comment]
This is a limitation of the REST API as documented at https://docs.marklogic.com/datahub/refs/troubleshooting.html .

**Comment by jkerr5** [comment]
Sure, that would be great @jmakeig This bug just came out of trying to get a simple custom ingestion step to work in QuickStart. Though this is documented in the troubleshooting guide now, I still think it is a bug in the generated code that has comments about what can be set and how but no indication of differing behavior between running the step with MLCP or via QuickStart.

**Comment by jmakeig** [comment]
Yes, there may be a bug in the current design. (We can re-focus this issue on that.) Looking much further out, I want to validate a potentially different, simpler design.
