### ISSUE TITLE
Easier changes to entity model after creation - perhaps regenerate one plugin

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#349]
#### The issue

During coding, it is not uncommon to find a gap or error in the model (the Entity model) after some code has been written. In that case, the only path is to manually update the code to be what the template code generation would have done, or regenerate the entire flow.

Instead it would be ideal if adding a new property or changing some would regenerate a minimal amount of code to make it easy to update the flows. 

A pop-up window with suggested (blank) plugin code may be enough. After updating the model, a developer could pop up the window and grab the new code bits needed, and manually merge to the real code.

Right now (quick-start-2.0.0-alpha-1) this is a "model first" tool, rather than supporting an agile process of modeling as-needed.

Hub version : quick-start-2.0.0-alpha-1

**Comment by aebadirad** [comment]
We've moving away from code generation based on entities. So closing this out due to the 5.0 release and future direction.
