### ISSUE TITLE
Unit testing with ml-data-hub:5.x 

### ISSUE THREAD

**Issue by rodgersandrew** [marklogic/marklogic-data-hub#3498]
marklogic-unit-test does not integrate with ml-data-hub:5.x

I have browsed numerous threads that are typically closed with no true solution. There was an attempt at doing so for DHF4 - https://github.com/marklogic-community/ml-unit-test/wiki/Integrating-with-DHF

However, mlRestApi has been deprecated and doesn't cover the real issue. The problem isn't just deploying test modules from the bundle. It is creating an app server and test content/module databases.

If this is not possible, what are alternatives outside of JUnit integration (which also has limited DHF integration docs). Using the Rest API and an external testing framework works for some cases of system testing, but still doesn't satisfy unit testing.

#### The issue

Short description of the problem:
Test App Server creation and relevant databases is not automated. Numerous test result output errors.

What behavior are you expecting?
I would expect I can integrate marklogic-unit-test with a data hub framework project and manage my tests just the same.

What are the steps to reproduce the issue:
1)Follow marklogic-unit-test install instructions
2)Run 'Gradle mlDeploy'

#### Tech details

Which Operating System are you using?
Windows 10 Enterprise

Which version of MarkLogic are you using?
10.0-3

Which version of the Data Hub are you using?
5.1.0

Is this a QuickStart UI bug? If so, which browser are you using?
N/A
#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar marklogic-datahub-<version>.war  --debug  > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -debug > myoutput.txt`

**Comment by rjrudin** [comment]
We've discussed providing configuration-based support, but it hasn't become a priority yet. In the meantime, try this gist - https://gist.github.com/rjrudin/0dd97eaee16b1f8dc75a35c7acf7b4e1 - I'll try it out today too to verify that it still works with DHF 5.1. 

As for importing marklogic-unit-test - mlRestApi was deprecated but still works, and it was only deprecated so it could be replaced by the better-named mlBundle, which operates in the same fashion. So you can definitely import marklogic-unit-test via this mechanism.

**Comment by rodgersandrew** [comment]
Thanks, that is all definitely helpful. We are getting an exception on DeployHubTestServerCommand.

We can see the database resources are successfully built but app servers are failing to be built:

Error at Super() within DeployHubTestServerCommand:
ArrayIndexOutOfBounds.

I have not defined any custom ports/names, just using the defaults defined in the gist.

**Comment by rjrudin** [comment]
Thanks - I think I wrote that gist for DHF 5.0.0, and gists tend not to age well. I'll kick the tires on it against DHF 5.1.0 hopefully later today, but may be early next week. 

We are tracking this requirement internally too, and a number of MarkLogicians are looking for this support as well. The ideal would be if you just have to set a single property - e.g. hubTestingEnabled=true - and all the additional resources are created and populated for you.

**Comment by dmcassel** [comment]
I'd be happy to see this feature implemented. Adding marklogic-unit-test is really easy for non-DHF projects; would be great to have it for those as well.

**Comment by rodgersandrew** [comment]
@rjrudin, Any updates with this? I see there was an update to your gist for 5.1 which was very helpful but there still seems to be a task missing for deploying modules to mlTestPort.

**Comment by rjrudin** [comment]
Assigning to @sbayatpur for prioritization.

**Comment by rjrudin** [comment]
We are planning support for this in 5.5 - however, we are not yet going to support creation/deletion of test appservers/databases. The recommended practice will be to use separate ML clusters for running automated tests and for running the application. 

The support will instead focus on ensuring that marklogic-unit-test and JUnit 5 tests can be written/run easily with DHF 5.5. Closing this as we're tracking this for 5.5.
