### ISSUE TITLE
"No message available" when following Quick Start

### ISSUE THREAD

**Issue by ken-tune** [marklogic/marklogic-data-hub#352]
#### The issue

When I follow the quick start instructions, at the 'login to the data hub' stage, I see the message 'no message available. Screenshot attached.

I'm expecting to get to the 'installation needed' stage.

#### Tech details

Experienced this on Windows 7. Then tried on AWS Linux, to see if error was windows related. Same behaviour seen on a clean VM.

8.0-6.1,

Which version of the Data Hub Framework are you using?

1.1.0

Is this a QuickStart UI bug? If so, which browser are you using?

Chrome

Java version  - 1.8.0_45-b14

#### The devil is in the details...

Error messages seen ...

08:49:31.089 [http-nio-8080-exec-5] ERROR o.s.w.s.s.s.DefaultHandshakeHandler -Handshake failed due to invalid Upgrade header: null
08:49:50.449 [http-nio-8080-exec-6] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

Nothing relevant in MarkLogic logs ( e.g. unauthenticated )

If possible, rerun the command with -d for debugging output and attach the output:

Attached.
[data-hub-debug-log-no-message-available.txt](https://github.com/marklogic/marklogic-data-hub/files/680582/data-hub-debug-log-no-message-available.txt)
![nomessageavailable](https://cloud.githubusercontent.com/assets/22936959/21586656/358621da-d0cb-11e6-9e26-6b6688590d1d.png)

**Comment by garyrusso** [comment]
I was getting the same error but it cleared up when I stopped and then restarted the java app.
