### ISSUE TITLE
[FEATURE] Support for variables is mapping

### ISSUE THREAD

**Issue by mhavey** [marklogic/marklogic-data-hub#3522]
Support for variables in the mapper would be useful. Allow the user to define his/her own variables by specifying for each variable:

- a variable name
- an expression that calculates the values of the variable. The value can be a simple type, an array, or even a node

Then in the main part of the mapping let the user reference this variable.

For example, I might define a variable v as /equipment[contains(name, "pump")]. This selects equipment nodes whose name contains the string "pump".  Then in the main part of the mapping:

- I map the "id" property to $v[1]/id. In other words, I map "id" to the ID of the first equipment whose name is "pump".
- I map the "distinctPumpNames" property to distinct-values($v/name).

The intent is to bring the power of XSLT variables to DHF mapping.

**Comment by rjrudin** [comment]
@sbayatpur I don't remember if there's a JIRA ticket for this already. Note this is different from system-defined variables like $URI and $DOC.

**Comment by rjrudin** [comment]
We're supporting this in 5.5 via "user parameters", which will allow a developer to perform pre-processing for a batch of items. That will include not only adding static variables, but e.g. performing queries to obtain values to use as variables.
