### ISSUE TITLE
[FEATURE] Allow vanilla ES models not built in QuickStart entity editor

### ISSUE THREAD

**Issue by mhavey** [marklogic/marklogic-data-hub#3523]
I should be able to use in DHF entities contained in a valid ES model that is built outside QuickStart. Currently DHF's requirements of a vanilla model are too strict, likely consequences of DHF's assumptions about ES. 

Here is the ask vs. DHF's restriction:

1. ASK: I should be able to use a big model with lots of primary entities (i.e., entities to be used as targets for mapping or mastering). RESTRICTION: DHF requires each primary entity to be in its own model (i.e., its own JSON descriptor file).

2. ASK: If my primary entity depends on a secondary entity, I shouldn't need to break out the secondary entity to its own model. For example, if A is a primary entity that refers to B as a sub-entity, it should be enough to bundle A and B into A's model. RESTRICTION: DHF requires two models: the model of A (with B included), and the model of B by itself.

**Comment by rjrudin** [comment]
Assigning to @sbayatpur , but I imagine that this will be addressed in the new GUI as opposed to in QuickStart.

**Comment by rjrudin** [comment]
This has been addressed in HC
