### ISSUE TITLE
DH5 api vs sjs

### ISSUE THREAD

**Issue by chenfiona** [marklogic/marklogic-data-hub#3524]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**What is the user-facing scenario that prompted this gap in functionality?**
Java API vs REST API to consume data 

**Describe the solution you'd like**
Is .api/module deprecated in DH5 ?  I understand DHF4 has API modules as DS end pints to consume data. It seems the DS via .api is not promoted in DH5?

**Describe alternatives you've considered**
I need to compare the DS via REST API vs (Java) API feasibility.
I also need the documentation regarding how to configure serviceDeclarationFile and task in DH5 in order to use Java API as service endpoints to consume data.

**Additional context**

**Comment by rjrudin** [comment]
I'm not sure what you're referring to when you say "I understand DHF4 has API modules as DS end pints to consume data. It seems the DS via .api is not promoted in DH5?"

Data Service endpoints can be used in both DHF 4 and 5. 

As for whether to use the REST API or Java API - note that the REST API and Data Services are two different things. REST endpoints are accessed via the REST API framework and require a specific URL rewriter, whereas Data Services endpoints are plain main modules with no framework. And the ML Java Client can be used to talk to both of these. 

As for documentation - this addresses how to create new Data Services - https://docs.marklogic.com/guide/java/DataServices . It does not differ for a DHF project.

**Comment by chenfiona** [comment]
The document is helpful, Thanks!  
What I try to confirm with you is this:
https://github.com/marklogic/marklogic-data-hub/tree/master/examples/dhf4/DHS-e2e

Is that DHS e2e applicable in both DHF4 and DH5?  Any change that I should be aware of?

**Comment by rjrudin** [comment]
Yes, you can construct similar DS endpoints like that in your DH5 application. Refer to the DS docs above though on the latest versions of the Java client and the development tools plugin.

**Comment by rjrudin** [comment]
Closing as this appears to be addressed
