### ISSUE TITLE
[BUG] Mapper complains duplicate templates when mapping to same subtype twice in the same mapping

### ISSUE THREAD

**Issue by mhavey** [marklogic/marklogic-data-hub#3526]
I'm getting the error  XSLT-DUPNAMEDTEMPLATE: (err:XTSE0660) in the following scenario. I have an entity called FactoryEquipment. Among the properties are this entity are plantRef and facilityRef. Each of these properties is a reference to the entity LocationRef. 

I built a mapping step that uses FactoryEquipment as its target ref. I map values for both plantRef and facilityRef. When I test the mapping using the mapper's built-in Test facility, I can see that the mapping is correct. But when I run this step, I get the following error:

 XSLT-DUPNAMEDTEMPLATE: (err:XTSE0660) Conflicting named template: <xsl:template name="LocationRef" mode="#default"><xsl:element name="LocationRef"> <xsl:variable name="n7040c85151371850"> <xsl:element name="name"> <xsl:value-of select="facility"/></xsl:element></xsl:variable><xsl:if test="exists($n7040c85151371850/node()/node())"> <xsl:copy-of select="$n7040c85151371850"/> </xsl:if></xsl:element> </xsl:template> and <xsl:template name="LocationRef" mode="#default"><xsl:element name="LocationRef"> <xsl:variable name="n2b004ddbbac2d705"> <xsl:element name="name"> <xsl:value-of select="plant_name"/></xsl:element></xsl:variable><xsl:if test="exists($n2b004ddbbac2d705/node()/node())"> <xsl:copy-of select="$n2b004ddbbac2d705"/> </xsl:if><xsl:for-each select="plant_categoryplant_name"> <xsl:element name="aliases"> <xsl:value-of select="."/></xsl:element></xsl:for-each></xsl:element> </xsl:template>

I am attaching the entity and mapping steps. 

My hunch is that the XSL transform that is generated under the covers creates two templates called LocationRef, one for the mapping to plantRef, the other for the mapping to facilityRef. If that's the design, then it's not possible to map to two instances of the same subtype in the same mapping. 

[dhfBug.zip](https://github.com/marklogic/marklogic-data-hub/files/4131307/dhfBug.zip)

**Comment by rjrudin** [comment]
Thanks, I'll take a look at this tomorrow.

**Comment by mhavey** [comment]
I can workaround by manually editing the generated XSLT template. I go into QC and edit /mappings/DHFBug-DupeTemplate/DHFBug-DupeTemplate-0.mapping.xml.xslt. There are two templates defined with name LocationRef. I give them different names, and that fixes it.

**Comment by rjrudin** [comment]
Thanks @mhavey , nice job with the example, I was able to reproduce it easily. Created https://project.marklogic.com/jira/browse/DHFPROD-4285, and will close this so it can be tracked internally.
