### ISSUE TITLE
Collection Filter wrong in case of custom step

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic/marklogic-data-hub#3540]
If you create a custom step, the source type (query/collection) is an optional radiobutton.

If you keep this empty, and go to settings you see that the Query is set to "cts.collectionQuery([])". This will return always 0 documents.

**Comment by aebadirad** [comment]
Is this in the 5.1 quickstart version?

**Comment by rjrudin** [comment]
Closing since it's QS
