### ISSUE TITLE
Best practice to deploy DH using existing data and harmonise/custom data

### ISSUE THREAD

**Issue by chenfiona** [marklogic/marklogic-data-hub#3541]
**Is your feature request related to a problem? Please describe.**
There are existing data in one DB which I need to harmonise and customise data using data hub.

**What is the user-facing scenario that prompted this gap in functionality?**
Existing data is in one DB, need the best practice to further harmonise and customise such data using data hub.

**Describe the solution you'd like**
A clear step to implement DH in such environment.
If the data needs to be re-ingested into the data hub, please suggest the best approach.
If the data stay untouched in this DB, please suggest the best approach to deploy DH. 

**Describe alternatives you've considered**
mlcp -> but not easily be incorporated into DH.

**Comment by aebadirad** [comment]
@sbayatpur I think this likely needs a deeper evaluation of what the requirement is driving the existing data use case, so looping you in

**Comment by chenfiona** [comment]
User case:  There are large amount of data in existing DBs. Is there a way of deploying DH upon those data/databases then proceed data harmonisation...etc ? For example: mlStagingAppserverName -> existing DB...

**Comment by rjrudin** [comment]
You can customize your gradle.properties file so that e.g. mlStagingDbName is that of your existing database. And you could do e.g. mlStagingHttpName to be that of an existing app server. 

I am wondering about configuration management here though, because once you start a DHF project, wouldn't you want the resources from your existing application to be in the project as well?

**Comment by chenfiona** [comment]
Can you explain the difference between using `mlStagingAppserverName`  and using `mlStagingHttpName`?  Can you demonstrate a working properties file containing `mlStagingDbName` and `mlStagingAppserverName`|`mlStagingHttpName` ?

**Comment by rjrudin** [comment]
Sorry that's a typo on my part - I meant mlStagingAppserverName. 

The list of DH properties is at https://docs.marklogic.com/datahub/5.4/refs/data-hub-properties.html ; you can add any number of those to a gradle.properties file to adjust values before you deploy your DHF application.

**Comment by rjrudin** [comment]
Closing as there's no action anticipated here other than responding to additional questions - please feel free to continue the conversation on this.
