### ISSUE TITLE
Need to update my forest location while setting up the datahub framework;

### ISSUE THREAD

**Issue by sudhirkr21** [marklogic/marklogic-data-hub#356]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:

Need to update my forest location while setting up the datahub framework;

What behavior are you expecting?

#### when i am trying to setup the framework by default forest are getting created in default location but i do not have enough space in that location,

Can you tell me how can i mount my forest location to specific location, as we already have that option from admin interface **data directory**	

Which Operating System are you using?
linux box

Which version of MarkLogic are you using?
8
Which version of the Data Hub Framework are you using?
1.0.2
Is this a QuickStart UI bug? If so, which browser are you using?
no
#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by paxtonhare** [comment]
Does this help?
https://github.com/marklogic/marklogic-data-hub/wiki/Advanced-Hub-Usage#changing-the-forest-data-path

**Comment by paxtonhare** [comment]
@sudhirkr21 is this still an issue?

**Comment by jeff-ml** [comment]
I believe this is what you are looking to achieve. 
https://github.com/marklogic-community/ml-gradle/tree/master/examples/custom-forests-and-replicas-project/src/main/ml-config/forests/custom-forest-example-content

Place your forests JSON files under user-config/forests . 

Example config with data directory specified:
	{
		"forest-name": "hub-FINAL-1",
		"host": "dev.server.com",
		"database": "edh-FINAL",
		"data-directory": "/mldata"
	}
