### ISSUE TITLE
Fail hard, does not work in case of a SVC-EXTIME

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic/marklogic-data-hub#3568]
In general there is a problem with timeouts. E.g. if you specify "fail hard" and you cause a SVC-EXTIME then this does not fail hard. 

Reproduction: create a harmonization which for all URI's work, but for 1 URI will end in an endless loop. Run this with "fail hard" After this produces a SVC-EXTIME, it does not stop the harmonization.

**Comment by rahulvudutala** [comment]
@josvanroosmalen Can you provide the datahub version to reproduce the issue

**Comment by rahulvudutala** [comment]
@josvanroosmalen I tried reproducing the issue. I have created an infinite loop. The server time out is 10mins. The mapping step completed its execution after 10 mins. 
I used the latest datahub 5.2 beta build on ML 10.0-2.1.

If you are still seeing this error on this version, can you provide a detailed steps to reproduce the issue.

**Comment by kkanthet** [comment]
Issue Fixed in 5.4.0 release
