### ISSUE TITLE
[BUG] QuickStart session management issues

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic/marklogic-data-hub#3569]
Assume I have:

- 1 project, with 2 environments, **local** and **remote**. 
- If you first start a session to **remote** -> login -> dashboard
- Then start a different session (new browser window, select project, local) to **local**. When you try to login it gives a red text "cannot login to remote.server.mycompany.com".  Obviously that is not working because they both use different passwords. 

So there seems to be something "hanging"/cached in the QuickStart backend.

**Comment by aebadirad** [comment]
QuickStart currently does not support multi-environment development simultaneously. Though you can request it be added as a feature.

**Comment by rjrudin** [comment]
Closing since it's QS
