### ISSUE TITLE
I need to load the data which in in .eml (email) format. Any suggestion how can i load it.

### ISSUE THREAD

**Issue by sudhirkr21** [marklogic/marklogic-data-hub#357]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

I need to load the data which are emails and are in .eml format
this there anyways i can make marklogic understand rfc2822

https://tools.ietf.org/html/rfc2822

What behavior are you expecting?

#### Tech details

Which Operating System are you using?
linux
Which version of MarkLogic are you using?
8
Which version of the Data Hub Framework are you using?
1.1.0
Is this a QuickStart UI bug? If so, which browser are you using?

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by jmakeig** [comment]
> I need to load the data which are emails and are in .eml format this there anyways i can make marklogic understand rfc2822

You could try MarkLogic’s built-in [document filters](https://docs.marklogic.com/guide/search-dev/binary-document-metadata). They can extract data and metadata from a variety of file formats. In general, though, you’re probably better off using something like Java to parse the `.eml` files, convert them to JSON or XML documents, and load those into MarkLogic. There are libraries in just about every popular language that can do this.
