### ISSUE TITLE
Custom Mapping function needs to access multiple document elements

### ISSUE THREAD

**Issue by venuiyengar** [marklogic/marklogic-data-hub#3585]
**Is your feature request related to a problem? Please describe.**
I would like to compute average based on a set of document elements ingested
For example: The ingested document contains 10 - 20 elements and I need to compute some average based on those element values. Currently I can pass all the elements to a custom function to compute average. It is good support array of elements that can be passed to custom function or pass the entire document to the custom function

**What is the user-facing scenario that prompted this gap in functionality?**
User would like to map an entity attribute based on some logic using multiple values from the document elements using a custom function
**Describe the solution you'd like**
The custom function for example may look like
1) get Average(value1,value2,value3,.......value10,.........,value24) or
2) getAverage(values) - An array of values
3) getAverage(doc) - pass the contents of entire ingested document

**Describe alternatives you've considered**
Currently here is how I am computing with a function by passing multiple element values
get Average(value1,value2,value3,.......value10,.........,value24)

**Additional context**
Most the mapping functions that I am using needs to pass multiple value codes to derive a single flag based on those values. This single derived flag will be set as part of the entity mapping

**Comment by rjrudin** [comment]
@venuiyengar  You can achieve this by something like this:

```
multipleArgs(/, Name)
```

And then the underlying function:

```
function multipleArgs(arg1, arg2) {
  console.log("arg1", arg1);
  console.log("arg2", arg2);
  return "it worked!";
}
```

If this doesn't work for you, please reopen this issue.
