### ISSUE TITLE
[BUG] JSON properties with beginning with @ cannot be mapped in QS

### ISSUE THREAD

**Issue by mariannemyers** [marklogic/marklogic-data-hub#3594]
#### The issue

I have an XML dataset I ingested via an Ingest step, and chose the output type to be JSON.  THe mlcp ingest causes any attribute values to be flattened into a property beginning with an @ 

For example...

`<row _id="row-h7in~5xmd_np47" ...>`

creates
`
{
  "row": {
              "@_id: "row-h7in~5xmd_np47",
               ...
  }
}
`

When I then move into a Mapping step, I cannot map that `@_id` using a drop-down value because `row/@_id` is actually not an attribute, so this XPath expression returns in the Mapper as "undefined, undefined". 

Manually changing the mapping to `row/node("@_id")` provides me the correct value.

It would make for a better user experience if this case was handled automatically and not require the user to understand the proper XPath expression to get to the value.  (And thanks to @aebadirad for pointing me in the right direction)

**Comment by rjrudin** [comment]
It seems that in order to automate this, the mapping system would need to check every single occurrence of "@" to determine if that's actually referring to a property/element name in the source document. I don't think that's really feasible. 

I think the solution here is that our docs should state that if you have a source property with a name starting with "@", then you need to use node("@_propName").

**Comment by jmakeig** [comment]
This is “as designed”. I agree that it’s not a great experience, but probably not something we’d change. I'd hypothesize that being actual XPath is more important than gracefully handling leading `@`s in property names. As @rjrudin indicates, we should think about better ways of informing users about this. What if the error message suggested the `node()` workaround, for example?

**Comment by mariannemyers** [comment]
I'd like to see a user cue or note in the documentation that `node()` is a workaround for this case, as @jmakeig suggests.  Of course I'd prefer this to be automatically handled, but I understand this is an edge case.

**Comment by aebadirad** [comment]
As a better user experience, one might consider the slight modification to validate xpath-compliant names on ingest and translate them to a policy-based configuration, but default system standard of compatibility for both xml and json documents.

This would include things like $, @, and spaces in names.

**Comment by jmakeig** [comment]
I don’t think we should rewrite source data. (Well, for this, at least.) Take JSON-LD, for example. Rewriting `@` property names would break things in lossy ways. I would be OK with changing the default XML to JSON translation that we provide, though.

**Comment by rjrudin** [comment]
Closing as we're tracking this internally and plan on addressing it via 5.5 - the property name will be properly escaped when selecting it from the property name list.
