### ISSUE TITLE
[BUG] When accepting and processing the request (even partially) an HTTP 2xx should be returned

### ISSUE THREAD

**Issue by mnuman** [marklogic/marklogic-data-hub#3596]
**Note**: _an attachment has been provided to detail this bug report_

#### The issue

Short description of the problem:
DHF 5.1.0 should NOT return an HTTP 400 and still partially process and persist the request, changed by https://github.com/marklogic/marklogic-data-hub/issues/2855

What behavior are you expecting?
Accepting a request and processing it should return an HTTP 200, status code of the actual processing should be communicated in the response object.

#### Tech details

Which Operating System are you using?
Windows 10
Which version of MarkLogic are you using?
ML 10.0-2
Which version of the Data Hub are you using?
DHF 5.1.0
Is this a QuickStart UI bug? If so, which browser are you using?
Nope

[DHF 5.1.0 - HTTP 400.docx](https://github.com/marklogic/marklogic-data-hub/files/4234708/DHF.5.1.0.-.HTTP.400.docx)

**Comment by aebadirad** [comment]
May want to decide on this more clearly @sbayatpur as we switched from one, to the other, but partial error states are a different beast than 'completed, no error' vs. 'failed, error'.

**Comment by rjrudin** [comment]
Ticket #2855 was never completed. To my knowledge, DHF 5.x continues to return a JSON response with a 200, and any errors that occurred are contained in that JSON response. The only exception is if an error occurred before any documents were processed, in which case the 4xx or 5xx that's returned would be correct.
