### ISSUE TITLE
custom step in QuickStart with customised document permission

### ISSUE THREAD

**Issue by chenfiona** [marklogic/marklogic-data-hub#3604]
**Is your feature request related to a problem? Please describe.**
The custom step in QuickStart doesn't have the "Target Permissions" setting as in the Ingestion step. 

**What is the user-facing scenario that prompted this gap in functionality?**
The document permissions @ Ingestion step are usually not the default "rest-reader,read,rest-writer,update" permission. However, I have to manually change the flow/step document permission to replace the default permission then redeploy.   

**Describe the solution you'd like**
A custom step in QuickStart should allow end user modify the document permission. 

**Describe alternatives you've considered**
Manually vi the step.json to modify the document permission.

**Additional context**
NOTE that the custom step usually promotes data to FINAL DB.  It is critical to make sure the  document permission is configured properly.

**Comment by rjrudin** [comment]
QuickStart won't be released in 5.5, but Hub Central is now available on-premise, and it will support editing a custom step in the 5.5 release.

**Comment by rjrudin** [comment]
Verified that custom steps in HC support editing target permissions; closing this ticket, as we are not going to release QS for 5.5.
