### ISSUE TITLE
Deprecated Gradle features were reported in DH 

### ISSUE THREAD

**Issue by chenfiona** [marklogic/marklogic-data-hub#3616]
*### Welcome Hub enthusiast!

Let's get the most out of this ticket, please fill out this template.
Whenever I run any gradle command: 
gradle mlRedeploy 
System throws error:
Deprecated Gradle features were used in this build, making it compatible with Gradle 6.0.

Short description of the problem:
Gradle 5.6.4 is installed for DH 5.0.4.

What behavior are you expecting?

What are the steps to reproduce the issue:
1) gradle mlRedeploy
2) gradle mlDeploy
3)

#### Tech details

Which Operating System are you using?
Window 7

Which version of MarkLogic are you using?
ML 10.0-3
Which version of the Data Hub are you using?
5.0.4
Is this a QuickStart UI bug? If so, which browser are you using?
No, Firefox

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar marklogic-datahub-<version>.war  --debug  > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -debug > myoutput.txt`

**Comment by rjrudin** [comment]
This has been resolved in DHF 5.1.0, which will not generate warnings in Gradle < 6 and will work correctly with Gradle 6.

**Comment by chenfiona** [comment]
Thanks!  Question is that in the build.gradle: ( this is what I use for Gradle 5.6.4 and DH 5.1.0 )
id 'net.saliman.properties' version '1.5.1'

Is "1.6.1" valid plugins if I do install Gradle 6+ ?

**Comment by rjrudin** [comment]
You have to check the plugins page for that plugin to see what versions are available - https://plugins.gradle.org/plugin/net.saliman.properties

**Comment by chenfiona** [comment]
Great! This helps!
