### ISSUE TITLE
URI during ingestion needs customisation: Custom-Ingestion or Custom-Other?

### ISSUE THREAD

**Issue by chenfiona** [marklogic/marklogic-data-hub#3619]
**Is your feature request related to a problem? Please describe.**

I need to define the URI during ingestion based on certain Property(Properties) instead of random /UUID.json

**What is the user-facing scenario that prompted this gap in functionality?**
Need a practical solution to customize ingested URI.

**Describe the solution you'd like**
 Can I achieve customized URI effect using Custom-Ingestion or Custom-Other or else? 
Will I customize URI in content.uri = *****  in the main.sjs or else? 

**Describe alternatives you've considered**
Before DH 5, I wrote the transformation module to customize URI. But I used MLCP transform the URI.  

**Additional context**
 URI customization step within DH needs clarification.

**Comment by rjrudin** [comment]
Are you trying to ingest data via MLCP, or via the REST API?

**Comment by chenfiona** [comment]
We plan to ingest data through DH flow/step. So I need to use some sort of custom step within DH to transform the URI. The Ingestion step wouldn't allow me to transform the URI (using specific Property value as part of the URI).
Due to the data volume, we also consider Java API.

**Comment by rjrudin** [comment]
The ML REST API won't allow a transform to modify the URI. An MLCP transform does.

**Comment by chenfiona** [comment]
MY question is : Can I use Custom-Ingestion or Custom-Other to transform URI instead of MLCP transform?
We are using DMSDK. So can you share the task setup in Gradle build in order to incorporate the transform modules?

**Comment by rjrudin** [comment]
If you use DMSDK, then you have to use a REST transform, and a REST transform does not allow for the URI to be manipulated. That is a REST limitation, not a DHF limitation. So it doesn't matter what kind of ingestion step you're using - you cannot modify the URI that is specified via DMSDK, or via whatever the client to /v1/documents is.

**Comment by chenfiona** [comment]
Thanks for the confirmation! 
I expect to run a flow/step to transform uri WITHIN data hub. The uri should be transformed during the ingestion step.  Is this doable?

**Comment by rjrudin** [comment]
It all depends on what client you're using to insert the document. If you're using MLCP, you can adjust the URI. If you're using the REST endpoint - /v1/documents - which is what the ML Java Client and DMSDK use, then you cannot transform the URI during ingestion. Again, this doesn't have anything to do with DHF, so the kind of step you're using does not matter.

**Comment by mikeberry** [comment]
I wanted to solve the problem within DHF so I added a cutom step after the ingestion that creates new documents with the desired URI based on attributes from my documents. Then I added a hook to that custom step to delete the original documents from the ingestion step. I agree it is a bit hacky but if you for some reason don't want to use MLCP (e.g. because you want to have the whole dataflow inside of DHF) then it is one solution I found. However I would appreciate if it were possible to transform the URI by configuring the ingestion step! I also tryed to write a custom ingestion step like so:
````
/**
 * This shows an example of a custom ingestion step, this is for when data comes into the data hub
 * We must construct an envelope wrapper about it and add any metadata or in-flight transforms here
 * so it is persisted once written to the database.
 *
 * Anytime data is sent to a step that is not from the database, it is mutable
 */


//If you'd like to construct triples using the semantics library, uncomment below
//const sem = require("/MarkLogic/semantics.xqy");
const DataHub = require("/data-hub/5/datahub.sjs");
const datahub = new DataHub();

function main(content, options) {

  //example of how to check options for an input format in case we wanted to do operations based on type
  //let inputFormat = options.inputFormat ? options.inputFormat.toLowerCase() : datahub.flow.consts.DEFAULT_FORMAT;

  //What output format do we want for the data?
  let outputFormat = options.outputFormat ? options.outputFormat.toLowerCase() : datahub.flow.consts.DEFAULT_FORMAT;

  //Example of error checking for data types
  if (outputFormat !== datahub.flow.consts.JSON && outputFormat !== datahub.flow.consts.XML && outputFormat !== datahub.flow.consts.BINARY && outputFormat !== datahub.flow.consts.TEXT) {
    let errMsg = 'The output format of type ' + outputFormat + ' is invalid. Valid options are '
      + datahub.flow.consts.XML + ' , ' + datahub.flow.consts.JSON + ', ' + datahub.flow.consts.TEXT + ' or' + datahub.flow.consts.BINARY + '.';
    datahub.debug.log({ message: errMsg, type: 'error' });
    throw Error(errMsg);
  }

  //we're going to grab the value of the content that was passed in, and use that to define our instance
  let instance = content.value.root || content.value;

  //If the type of data is binary OR the expected output was set to unstructured data (binary/text), let's return it as is.
  if (instance.nodeType === Node.BINARY_NODE || outputFormat === datahub.flow.consts.BINARY || outputFormat === datahub.flow.consts.TEXT) {
    return content;
  }
  else if (instance.nodeType === Node.TEXT_NODE) {
    //if it's text, and we want json or xml, let's try to parse it. If it can't, it'll throw an unchecked error.
    instance = datahub.flow.flowUtils.parseText(instance, outputFormat);
  }

  //let's create our triples array.
  let triples = [];

  //now our headers for any document level metadata
  let headers = datahub.flow.flowUtils.createHeaders(options);

  //And lastly we put it all together in an envelope structure
  //content.value = datahub.flow.flowUtils.makeEnvelope(instance, headers, triples, outputFormat);

  //Context changes are possible, here we show how to grab the context and example manipulate it
  //let context = content.context;
  //For example, we can get permissions, then manipulate them here
  //let permissions = context.permissions;

  //form our envelope here now, specifying our output format
  let envelope = datahub.flow.flowUtils.makeEnvelope(instance, headers, triples, outputFormat);

  //create our return content object, we have a handy helper function for creating a json scaffolding, but you
  //can also do a node-based one by using nodebuilder, especially if you're dealing with xml!
  let newContent = datahub.flow.flowUtils.createContentAsObject();

  //assign our envelope value
  newContent.value = envelope;

  //assign the uri
  newContent.uri = "path/" + instance["YourAttr1"] + "/" + instance["YourAttr2"] + "/" + instance["YourAttr3"] + ".json";

  //now let's return out our content to be written, it can be any combination of
  return newContent;
}

module.exports = {
  main: main
};
````

But this does not affect the URI either. I understand that somehow the REST api does not support things like that but from a user perspective it would help a lot if custom URI at ingestion were somehow possible.

**Comment by rjrudin** [comment]
DHF 5.4.0 introduces step interceptors for this exact use case - a way to adjust any part of a content object before it's persisted. See the following example project for more info - https://github.com/marklogic/marklogic-data-hub/tree/master/examples/step-interceptors
