### ISSUE TITLE
DH can't identify DAT file with ~|^ separator  

### ISSUE THREAD

**Issue by chenfiona** [marklogic/marklogic-data-hub#3621]
*### Welcome Hub enthusiast!
Let's get the most out of this ticket, please fill out this template.

Short description of the problem:
Need to ingest DAT file into DH. DAT file comes with ~|^ delimiter. I try other Field Separator with ~|^ but MLCP couldn't identify the content.
Try Binary or Text, didn't work.

What behavior are you expecting?
MLCP@DH should be able to ingest the DAT with ~|^ separator.

What are the steps to reproduce the issue:
1) -input_file_type "delimited_text" -generate_uri "true" -delimiter "~|^"
2)
3)

#### Tech details
Which Operating System are you using?
Windows 7
Which version of MarkLogic are you using?
ML 10.0-3
Which version of the Data Hub are you using?
5.1.0
Is this a QuickStart UI bug? If so, which browser are you using?
I don't believe it is UI bug.
#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar marklogic-datahub-<version>.war  --debug  > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -debug > myoutput.txt`

**Comment by rjrudin** [comment]
Since you're using MLCP, please submit this ticket to the MLCP project - https://github.com/marklogic/marklogic-contentpump .
