### ISSUE TITLE
Task or JAR in DH to ingest with DMSDK, run custom ( mapping or mastering ) steps with DH

### ISSUE THREAD

**Issue by chenfiona** [marklogic/marklogic-data-hub#3625]
**Is your feature request related to a problem? Please describe.**
DMSDK is already in-house for data ingestion. We plan to utilize DH for mapping and mastering.

**What is the user-facing scenario that prompted this gap in functionality?**
Data volume is huge and DMSDK is used to ingest and for some basic data transformation. We intend to test:
1. Incorporate DMSDK with DH
2. Use DH for mapping and mastering which requires some JAR or Task setup in Java API to kick off the steps 

**Describe the solution you'd like**
orchestration process for DMSDK ingestion, then DH mapping and mastering..etc

**Describe alternatives you've considered**

**Additional context**

**Comment by rjrudin** [comment]
The 5.4 docs (as well as 5.2) show how to do this:

- You can use the mlRunIngest transform for ingesting data via DMSDK and referencing a DHF ingestion step - https://docs.marklogic.com/datahub/5.4/flows/ingest-using-rest.html
- And the following docs explain how to programmatically run any steps in a flow - https://docs.marklogic.com/datahub/5.4/flows/run-flow-using-datahub-api.html 

If you have additional questions, please reopen this ticket or create a new one.
