### ISSUE TITLE
Conditional mapping? Doesn't work

### ISSUE THREAD

**Issue by chenfiona** [marklogic/marklogic-data-hub#3642]
*### Welcome Hub enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue
Short description of the problem:
Needs to map String to Date. It is conditional mapping: if the value is not "" or null, then parse date. But the system giving me below error:
                "{\"stack\":\"Error: XDMP-LEXVAL: xs:date(\\\"12/26/2012\\\") --
 Invalid lexical value \\\"12/26/2012\\\"\\n    at main (/data-hub/5/builtins/st
eps/mapping/entity-services/main.sjs:72:11)\\n    at Flow.runMain (/data-hub/5/i
What behavior are you expecting?

What are the steps to reproduce the issue:
1) the openDate is date type
2) mapping needs to map the string to date
3) Mapping step "sourcedFrom" :
"if (openDate !== "" || openDate !== null) then parseDate(openDate,'MM/DD/YYYY') else()"
then gradle throws the error

#### Tech details

Which Operating System are you using?
Windows7

Which version of MarkLogic are you using?
10.0-3
Which version of the Data Hub are you using?
5.1.0
Is this a QuickStart UI bug? If so, which browser are you using?
No
#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar marklogic-datahub-<version>.war  --debug  > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -debug > myoutput.txt`

**Comment by akshaysonvane** [comment]
The mapping step supports a valid XPath statement.
The following XPath worked for me.
```
if (Order/OrderDate != "") then parseDate(Order/OrderDate/text(),'MM-DD-YYYY') else "1999-07-04"
```

**Comment by chenfiona** [comment]
The difficulty lies if the Date does exist, it should be parsed and mapped. But the "else", it should be left as it is which is "". The entity can ONLY set it as either date or string which is catch 22.

**Comment by rjrudin** [comment]
DHF 5.4.0 no longer throws an error on an empty/null input. Please reopen this if you still get this behavior with DHF 5.4.0.
