### ISSUE TITLE
[BUG] DHF should not load artifacts into the backup cluster in a DR architecture

### ISSUE THREAD

**Issue by derms** [marklogic/marklogic-data-hub#3666]
Short description of the problem:

The standard approach when implementing a DR Architecture is to replicate the content databases (in the DHF case the STAGING and FINAL db's) and deploy the config and the modules code directly on the DR cluster. This approach does not work with the DHF as the gradle tasks

* mlDeploy
* mlLoadModules

put files into the STAGING and FINAL db's.

Would it be possible to have the gradle tasks take into account a flag like the following - 

mlIsDR=true

so that they do not deploy content to the STAGING and FINAL db's?

#### Tech details

Which Operating System are you using?
N/A

Which version of MarkLogic are you using?
N/A

Which version of the Data Hub are you using?
Impacts all versions.

**Comment by akshaysonvane** [comment]
Thanks for filing the issue, @derms.
Tracking it internally via https://project.marklogic.com/jira/browse/DHFPROD-4585

**Comment by rjrudin** [comment]
Closing as it's being tracked internally; we are planning on supporting this in 5.5
