### ISSUE TITLE
Make it easier to develop configuration artifacts in my IDE

### ISSUE THREAD

**Issue by jmakeig** [marklogic/marklogic-data-hub#3686]
As a developer, I want to leverage my IDE for things like type-ahead and validation when I’m working with public DHF configuration artifacts and API payloads. 

VS Code, for example, allows you to [associate a JSON Schema with a file extension](https://code.visualstudio.com/docs/languages/json#_json-schemas-and-settings). (It also supports the `$schema` property, but that requires changes to the source file.)

**Comment by jmakeig** [comment]
Related to mikrovvelle/mlxprs#16.

**Comment by ryanjdew** [comment]
Great suggestion. It would be good to get solid schemas for the artifacts published. We're doing that in part now by maintaining OpenAPI documentation for the middle-tier and starting the same process for our new Data Services. 

Thoughts on the scope for the Data Hub team on this? Would defining those schemas and making them easily accessible be sufficient? Or should there also be plugins/settings for specific editors that we'd maintain?

**Comment by jmakeig** [comment]
I think publishing schemas and Open API specs is sufficient. Way back in the olden days, the database had a requirement that every _public_ configuration artifact or type was required to have a schema for documentation and IDE/strong-typing purposes. The Data Hub should adopt this principle as well.

**Comment by rjrudin** [comment]
I think this is addressed for now, as JSON schemas are available under ./specs/models.
