### ISSUE TITLE
Upgrade v5.1 to v5.2 - Remove /src/main/hub-internal-config-5.1.0

### ISSUE THREAD

**Issue by chenfiona** [marklogic/marklogic-data-hub#3701]
*### Welcome Hub enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

Short description of the problem:

What behavior are you expecting?
Is it safe to remove /src/main/hub-internal-config-5.1.0 after upgrade?  

What are the steps to reproduce the issue:
1) gradle hubUpdate
2) gradle hubRedeploy
3) hub-internal-config-5.1.0 is generated ( so there are hub-internal-config & hub-internal-config-5.1.0)

#### Tech details

Which Operating System are you using?
Linux 
Which version of MarkLogic are you using?
10.0-3
Which version of the Data Hub are you using?
v5.1.0 -> Upgrade to v5.2.0
Is this a QuickStart UI bug? If so, which browser are you using?
No.

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar marklogic-datahub-<version>.war  --debug  > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -debug > myoutput.txt`

**Comment by rjrudin** [comment]
Yes.
