### ISSUE TITLE
TDE stops working after upgrade from 5.1.0 to 5.2.0

### ISSUE THREAD

**Issue by chenfiona** [marklogic/marklogic-data-hub#3702]
*### Welcome Hub enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

Short description of the problem:

What behavior are you expecting?
TDE stops functioning after upgrade to 5.2.0.

What are the steps to reproduce the issue:
1) Upgrade from 5.1.0 to 5.2.0
2) Run the same SQL or JS 
3) It throws error: ( the TDE views are in the schema DB)
TDE-NOSCHEMADB: tde.getView("DailyProduct", "DailyProduct") -- No schema database for TDE resource: view DailyProduct, no schema database configured for current database

#### Tech details

Which Operating System are you using?
Linux
Which version of MarkLogic are you using?
10.0-3
Which version of the Data Hub are you using?
5.2.0
Is this a QuickStart UI bug? If so, which browser are you using?
No
#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar marklogic-datahub-<version>.war  --debug  > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -debug > myoutput.txt`

**Comment by chenfiona** [comment]
So I grant the operator role to the TDE user and get TDE work. That said, this enables that user very powerful privileges. 
Can you please explain what role is required for the mapping/TDE in the new release?  Can I hardcode the required role(s) in gradle.properties? 
I see new security roles introduced in this major release.

Thank you!

**Comment by rjrudin** [comment]
What user are you testing with? If it's the admin user, you're likely running into this - http://docs.marklogic.com/guide/relnotes/chap4#id_45674 

Prior to 5.2.0, your TDE likely did not have any roles assigned. Starting in 5.2.0, the TDE gains data-hub-operator/read and data-hub-developer/update permissions, in addition to the default permissions of the user that inserts the TDE. If you're using the admin user (which you shouldn't use to test a TDE, as it's unlikely that you'd be doing that in production), you'll need to assign the data-hub-operator role to the admin user.

**Comment by chenfiona** [comment]
In DH5.1.0 , I created a role has below privileges:
  "role": ["data-hub-admin-role","flow-developer-role","flow-operator-role","pii-reader"].
I run all the flows except mapping( mapping ran by admin) with a user granted above role. If I don't run the mapping with admin, I can't retrieve any data from DH TDE ( through query console).
Then I upgrade to DH5.2.0, TDE doesn't work unless I grant admin with operator. 
My question is: Can I designate a user in gradle.properties||gradle-{env}.properties to run all the flows(including mapping)? If yes, what user is that? If not, what roles are required in /src/main/ml-config/security/roles? 

Also note below lines are not in the DH5.2.0 gradle.properties:

# The name of the role to create for hub deployment
mlDataHubAdminRole=data-hub-admin-role

**Comment by rjrudin** [comment]
Let's focus just on your mapping step when using 5.2.0. When you run it as a user with the roles you mentioned - let's call that user "flow-dev" - does the mapping step produce the expected output, including the correct permissions on the documents it creates?

**Comment by chenfiona** [comment]
I ran the TDE/Optic through Java API by "flow-dev" with ["data-hub-admin-role","flow-developer-role","flow-operator-role","pii-reader"] .  
It throws error:
Exception in thread "main" com.marklogic.client.FailedRequestException: Local message: failed to apply resource at rows: Internal Server Error. Server Message: SQL-TABLENOTFOUND: plan.view(...

If I use admin, of course, works.

**Comment by rjrudin** [comment]
What are the permissions on the TDE document that you're using for your query?

**Comment by chenfiona** [comment]
[Final Doc Permission.xlsx](https://github.com/marklogic/marklogic-data-hub/files/4350675/Final.Doc.Permission.xlsx)

Please see the detailed breakdown of the doc permission in the Final. 
The flows are ran by the "flow-dev" except the mapping ran by admin.

**Comment by rjrudin** [comment]
Can you share those in some other format than an Excel file? Sorry, I just don't want to download and run an Excel file from an untrusted location.

**Comment by chenfiona** [comment]
Here you go:

Role			            Read	Update
_______________________________________
temYoral-admin		Y	  Y
rest-writer			          Y
tde-view		                Y	
rest-reader		        Y	
rest-admin			          Y
curator-role			          Y
tde-admin		        Y	  Y
research-role		        Y	
harmonized-reader	        Y	
harmonized-uYdater		Y

**Comment by chenfiona** [comment]
Role	R	U
temporal-admin	P	P
rest-writer		P
tde-view	P	
rest-reader	P	
rest-admin		P
curator-role		P
tde-admin	P	P
research-role	P	
harmonized-reader	P	
harmonized-updater		P

**Comment by chenfiona** [comment]
Read:	
temporal-admin
tde-view
rest-reader
tde-admin
harmonized-reader

Update:
temporal-admin
rest-writer
rest-admin
tde-admin
harmonized-updater
flow-dev

**Comment by rjrudin** [comment]
I'm looking at your original error again:

```
TDE-NOSCHEMADB: tde.getView("DailyProduct", "DailyProduct") -- No schema database for TDE resource: view DailyProduct, no schema database configured for current database
```

I missed the "no schema database configured for current database" part. Are you trying this in qconsole? If so, are you pointing to data-hub-FINAL, or data-hub-final-SCHEMAS? That error sounds like you're pointing at a schemas database, but you need to point at the content database.

**Comment by chenfiona** [comment]
No, the error is from Java API which is nothing to do with QConsole. It throws error when ran by "flow-dev". It produces the correct result when ran by admin.
There is no error when I run TDE, Optic API, SQL queries in QConsole ( of course, because it is ran by admin). 
BTW, can you share an eval running TDE/Optic by different user?  This eval is sth similar with:
xdmp.eval(query,null,{ userId: xdmp.user('fiona')} );

**Comment by rjrudin** [comment]
Realizing this ticket was dropped - response to the above question is - try creating a user that has the desired role and also qconsole-user - you can then do whatever you'd like via qconsole.

**Comment by ryanjdew** [comment]
Closing as we haven't been able to reproduce and the issue is stale.
