### ISSUE TITLE
[BUG] TDE error during Smart Mapping

### ISSUE THREAD

**Issue by alan-johnson** [marklogic/marklogic-data-hub#3708]
*### Welcome Hub enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

We have a DH 5.1 project using smart mapping to identify duplicate employees. Upgrade to 5.2 and an error is thrown during the Smart Mapping step.

TDE-INDEX: xdmp:eval("\n const temporal = require(\"/MarkLogic/temporal.xqy\");\n\n...", {writeQueue:[{value:cts.doc("/employee/75c8c8d3-88ac-4395-98ce-3a4f67ccb7f3.json"), context:{permissions:[{capability:"update", roleId:"5126952842460325403"}, {capability:"read", roleId:"7089338530631756591"}, {capability:"read", roleId:"16742763111021671912"}, ...], metadata:{datahubCreatedBy:"dan", datahubCreatedByStep:"default-merging", datahubCreatedInFlow:"EmployeeMastering", ...}, collections:["Employee", "coastalMap", "sm-Employee-archived"]}, uri:"/employee/75c8c8d3-88ac-4395-98ce-3a4f67ccb7f3.json", ...}, {value:cts.doc("/employee/998.json"), context:{permissions:[{capability:"update", roleId:"16961529670784263631"}, {capability:"read", roleId:"6594007868299180050"}, {capability:"read", roleId:"17774220447394382090"}, ...], metadata:{datahubCreatedBy:"dan", datahubCreatedByStep:"default-merging", datahubCreatedOn:"2020-03-16T22:44:04.126808Z", ...}, collections:["Employee", "createTriples", "sm-Employee-archived"]}, uri:"/employee/998.json", ...}, {value:Element("<prov:document xmlns:xsd='http://www.w3.org/2001/XMLSchema' xmlns:sm='http://marklogic.com/smart-mastering/auditing#' .../>"), context:{permissions:[{capability:"update", roleId:"5126952842460325403"}, {capability:"read", roleId:"7089338530631756591"}, {capability:"read", roleId:"16742763111021671912"}, ...], collections:["sm-Employee-auditing"], metadata:{datahubCreatedOn:"2020-03-16T22:44:04.126808Z", datahubCreatedBy:"dan", datahubCreatedInFlow:"EmployeeMastering", ...}}, uri:"/com.marklogic.smart-mastering/auditing/merge/8d826dc8-4a41-4421...", ...}, ...], permissions:"xdmp.defaultPermissions()", baseCollections:["mergeDuplicates", "Employee", "mergeDuplicates", ...]}, {database:"7333219740875163667", commit:"auto", update:"true", ...}) -- Error applying template /tde/Employee-0.0.1.tdex to document /com.marklogic.smart-mastering/merged/a384ce37ce2a286fa7a4628831c00d48.json: TDE-EVALFAILED: Eval for $subject-iri='sem:iri(concat("http://example.org/Employee-0.0.1/Employee/", fn:encode-for-uri(./employeeID)))' returns TDE-BADVALEXPRESSION: Invalid val expression: XDMP-ARGTYPE: (err:XPTY0004) arg1 is not of type xs:string? in xdmp:eval("\n const temporal = require(\"/MarkLogic/temporal.xqy\");\n\n...", {writeQueue:[{value:cts.doc("/employee/75c8c8d3-88ac-4395-98ce-3a4f67ccb7f3.json"), context:{permissions:[{capability:"update", roleId:"5126952842460325403"}, {capability:"read", roleId:"7089338530631756591"}, {capability:"read", roleId:"16742763111021671912"}, ...], metadata:{datahubCreatedBy:"dan", datahubCreatedByStep:"default-merging", datahubCreatedInFlow:"EmployeeMastering", ...}, collections:["Employee", "coastalMap", "sm-Employee-archived"]}, uri:"/employee/75c8c8d3-88ac-4395-98ce-3a4f67ccb7f3.json", ...}, {value:cts.doc("/employee/998.json"), context:{permissions:[{capability:"update", roleId:"16961529670784263631"}, {capability:"read", roleId:"6594007868299180050"}, {capability:"read", roleId:"17774220447394382090"}, ...], metadata:{datahubCreatedBy:"dan", datahubCreatedByStep:"default-merging", datahubCreatedOn:"2020-03-16T22:44:04.126808Z", ...}, collections:["Employee", "createTriples", "sm-Employee-archived"]}, uri:"/employee/998.json", ...}, {value:Element("<prov:document xmlns:xsd='http://www.w3.org/2001/XMLSchema' xmlns:sm='http://marklogic.com/smart-mastering/auditing#' .../>"), context:{permissions:[{capability:"update", roleId:"5126952842460325403"}, {capability:"read", roleId:"7089338530631756591"}, {capability:"read", roleId:"16742763111021671912"}, ...], collections:["sm-Employee-auditing"], metadata:{datahubCreatedOn:"2020-03-16T22:44:04.126808Z", datahubCreatedBy:"dan", datahubCreatedInFlow:"EmployeeMastering", ...}}, uri:"/com.marklogic.smart-mastering/auditing/merge/8d826dc8-4a41-4421...", ...}, ...], permissions:"xdmp.defaultPermissions()", baseCollections:["mergeDuplicates", "Employee", "mergeDuplicates", ...]}, {database:"7333219740875163667", commit:"auto", update:"true", ...}) [javascript] in /MarkLogic/rest-api/lib/extensions-util.sjs [javascript] in /data-hub/5/impl/hub-utils.sjs, at 55:24, in writeDocuments() [javascript] in /data-hub/5/impl/flow.sjs, at 229:53, in runFlow() [javascript] in /marklogic.rest.resource/mlRunFlow/assets/resource.sjs, at 60:24, in post() [javascript] in /MarkLogic/rest-api/lib/extensions-util.sjs, at 93:29, in callExtension() [javascript] in /MarkLogic/rest-api/lib/extensions-util.sjs, at 111:9, in applyOnce() [javascript] in /MarkLogic/rest-api/lib/extensions-util.sjs, at 919:44, in xdmp:function(fn:QName("http://marklogic.com/rest-api/resource/mlRunFlow","post"), "/marklogic.rest.resource/mlRunFlow/assets/resource.xqy")(map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), document{object-node{}}) [javascript] in /data-hub/5/rest-api/lib/extensions-util.xqy, at 919:44, in extut:call-service("mlRunFlow", "POST", xdmp:function(fn:QName("http://marklogic.com/rest-api/resource/mlRunFlow","post"), "/marklogic.rest.resource/mlRunFlow/assets/resource.xqy"), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), document{object-node{}}) [1.0-ml] $extension-name = "mlRunFlow" $method = "POST" $service = xdmp:function(fn:QName("http://marklogic.com/rest-api/resource/mlRunFlow","post"), "/marklogic.rest.resource/mlRunFlow/assets/resource.xqy") $context = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>) $service-params = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>) $input = document{object-node{}} in /data-hub/5/rest-api/lib/extensions-util.xqy, at 872:20, in function() as item()*() [1.0-ml] in /data-hub/5/rest-api/lib/extensions-util.xqy, in xdmp:invoke(function() as item()*, <options xmlns="xdmp:eval"><isolation>same-statement</isolation><ignore-amps>...</ignore-amps></options>) [1.0-ml] in /data-hub/5/rest-api/lib/extensions-util.xqy, at 870:12, in extut:invoke-service("mlRunFlow", "POST", "query", xdmp:function(fn:QName("http://marklogic.com/rest-api/resource/mlRunFlow","post"), "/marklogic.rest.resource/mlRunFlow/assets/resource.xqy"), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), document{object-node{}}, fn:false()) [1.0-ml] $extension-name = "mlRunFlow" $method = "POST" $default-txn-mode = "query" $service = xdmp:function(fn:QName("http://marklogic.com/rest-api/resource/mlRunFlow","post"), "/marklogic.rest.resource/mlRunFlow/assets/resource.xqy") $context = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>) $service-params = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>) $input = document{object-node{}} $in-txn = fn:false() $txn-curr = "query" $txn-mode = "query" in /data-hub/5/rest-api/models/resource-model-query.xqy, at 270:20, in rsrcmodqry:resource-post("mlRunFlow", map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), document{object-node{}}, fn:false(), local:rsrcmod-callback#6) [1.0-ml] $resource-name = "mlRunFlow" $context = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>) $resource-params = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>) $input = document{object-node{}} $in-txn = fn:false() $responder = local:rsrcmod-callback#6 $service = xdmp:function(fn:QName("http://marklogic.com/rest-api/resource/mlRunFlow","post"), "/marklogic.rest.resource/mlRunFlow/assets/resource.xqy") in /data-hub/5/rest-api/models/resource-model-query.xqy, at 237:4, in rsrcmodqry:exec-post(map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), document{object-node{}}, local:rsrcmod-callback#6) [1.0-ml] $headers = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>) $endpoint-params = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>) $input = document{object-node{}} $responder = local:rsrcmod-callback#6 in /data-hub/5/rest-api/endpoints/resource-service-query.xqy, at 79:8 [1.0-ml] $headers = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>) $method = "POST" $body = document{object-node{}} $params = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>) $extra-names = ()

#### Tech details

MacOS Mojave 10.14.6

Which version of MarkLogic are you using?
ML 10.0.3

Which version of the Data Hub are you using?
DH 5.2

Is this a QuickStart UI bug? If so, which browser are you using?
No.

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar marklogic-datahub-<version>.war  --debug  > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -debug > myoutput.txt`

**Comment by rjrudin** [comment]
The actual error is this:

```
Error applying template /tde/Employee-0.0.1.tdex to document /com.marklogic.smart-mastering/merged/a384ce37ce2a286fa7a4628831c00d48.json: TDE-EVALFAILED: Eval for $subject-iri='sem:iri(concat("http://example.org/Employee-0.0.1/Employee/", fn:encode-for-uri(./employeeID)))' returns TDE-BADVALEXPRESSION: Invalid val expression: XDMP-ARGTYPE: (err:XPTY0004) arg1 is not of type xs:string?
```

It appears your TDE expects a single employeeID, which is in theory based on your entity model. But the result of merging two records is resulting in multiple employeeIDs. 

Try adjusting your entity model first to allow for an array of employeeIDs, just to see if the error goes away. Then check your merge options to see if they're allowing multiple employeeIDs to occur.

**Comment by alan-johnson** [comment]
Thanks Rob.. Any thoughts on why this works in 5.1 then? Perhaps TDEs are applied differently (or possibly not at all) by default for doc updates?

**Comment by rjrudin** [comment]
In 5.1, TDEs were inserted with only the default permissions of the user inserting them. If you inserted them with admin, then the TDE would have no permissions, and thus no one could use it except admin. In that scenario, that may mean that invalid data would not throw an error if the user running a step cannot see the TDE. 

In 5.2, TDEs have default permissions + permissions for data-hub-operator/developer. 

I am guessing the root cause is that your merge options are producing data that conflicts with your entity model, but 5.1 may not have complained because the user couldn't see the TDE.

**Comment by alan-johnson** [comment]
Looks like I was missing merge options in my step that merges the duplicate records. So.. this one is closed. Thanks Rob.. your comment helped greatly to narrow down the issue.
