### ISSUE TITLE
gradle plugin gets confused about users

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#371]
```ini
mlUsername=
mlPassword=
mlManageUsername=
mlManagePassword=
mlRestAdminUsername=
mlRestAdminPassword=
mlAdminUsername=
mlAdminPassword=
```

The logic that uses these users is flawed. Needs to be fixed.

**Comment by grechaw** [comment]
I think this issue goes back to ml-gradle and app-deployer.  There are assumptions about defaults which interact with these property names in confusing ways.

**Comment by jmakeig** [comment]
Can someone please file a bug against ml-gradle and/or ml-app-deployer to describe the issue and the expected outcome? (Ping @rjrudin)

**Comment by grechaw** [comment]
Wah wah but then we'd have to understand what's going on!

The issue would perhaps best be solved by ripping out all admin/admin defaults and requiring all above credentials.

**Comment by paxtonhare** [comment]
I think this is particular to data hub. I'm not using the default factories that Rob wrote for ml-grade/ml-app-deployer.

**Comment by rjrudin** [comment]
ml-gradle by default lets you "cheat" and user mlUsername/mlPassword for the following roles:

- Creating security resources like users/roles (requires admin access, overridden via mlAdminUsername/mlAdminPassword)
- Creating other Mgmt resources (requires manage-admin access, overridden via mlManageUsername/mlManagePassword)
- Loading modules via the REST API (requires rest-admin access, overridden via mlRestAdminUsername/mlRestAdminPassword)

So ml-gradle (really ml-app-deployer) looks for those various username/password combos, and if it can't find them, it defaults to mlUsername/mlPassword. So you can be bad and just do mlUsername=admin and mlPassword=admin, or you can use mlAdminUsername to create proper users with manage-admin and rest-admin and set the users/passwords appropriately.
