### ISSUE TITLE
Security implications of local file system access

### ISSUE THREAD

**Issue by jmakeig** [marklogic/marklogic-data-hub#372]
The Quick Start is basically a desktop application running in the browser. What are the implications of things like file system access, which aren’t typical for a browser app? What are our recommendations for OS user privileges running the Quick Start UI?

**Comment by grechaw** [comment]
We must really change quick-start not to use the filesystem.  It restricts quick-start to being a single-user application rather than a web application.  I think we'll want to defer recommendations until after we've made the switch away from filesystem access.
