### ISSUE TITLE
Single Collection in Final containing one copy of documents before/after the Mastering

### ISSUE THREAD

**Issue by chenfiona** [marklogic/marklogic-data-hub#3721]
*### Welcome Hub enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

Short description of the problem:

What behavior are you expecting?

What are the steps to reproduce the issue:
1) Day1: 1189 documents are harmonized into Final DB
2) Day2: 3 documents are harmonized into Final DB. 2 out of 3 Incremental documents are expected to be matched/merged in the Final. 
AFTER DAY2 Mastering flow ran in the Final, doc count is in excel. 
3) Day3: 3 documents are harmonized into Final DB. 2 out of 3 Incremental documents are expected to be matched/merged in the Final. 
Please see the number of documents in corresponding collection BEFORE Day3 Mastering flow in the Final.  
Here is the predicament: 
If I need to query the documents at this point-in-time, I will have to search the sm-Product-Mastered first, if not found, then search the Product collection.  As you can see, the sm-Product-Mastered only contains Day2 two mastered documents as soon as the Day3 documents harmonized into the Final (Day3 Mastering step is not ran yet).
The challenge is if querying against sm-Product-Mastered, there are only 2 documents. If querying against Product collection, you would see 4 documents returned:
One is the Day2 masterted doc, one is the Day1 doc, two are the Day2&Day3 incremental doc.

Is it possible that just one latest document returned by querying ONE collection?  Or did I do sth terrible wrong? Or this is what ML mastering is meant to be? 

#### Tech details

Which Operating System are you using?
Windows 7
Which version of MarkLogic are you using?
10.0-3
Which version of the Data Hub are you using?
5.1.0
Is this a QuickStart UI bug? If so, which browser are you using?
NO
#### The devil is in the details...
[Document count in between mastering.xlsx](https://github.com/marklogic/marklogic-data-hub/files/4350796/Document.count.in.between.mastering.xlsx)

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar marklogic-datahub-<version>.war  --debug  > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -debug > myoutput.txt`

**Comment by ryanjdew** [comment]
@chenfiona Thank you for opening an issue. The expected behavior is that after the matching/merging steps have completed the "sm-Product-mastered" collection will represent each distinct "Product" as determined by the settings of the matching step.

Would you be able to provide your flow/step configuration files? If necessary, please scrub them of any information that you don't wish to be publicly available.

**Comment by chenfiona** [comment]
Thanks for getting back to me, Ryan! We had a conference call with Puneet Rawal today. 
I don't think the problem is the matching/merge: the documents are matched/merged correctly.  The problem is that the documents are un-tagged from the "sm-Product-mastered" collection as soon as the newly harmonised doc pushed from Staging to Final but the Mastering flow is not ran yet. There is nothing wrong if the mastering step is ran. Just at that few seconds interim moment, "sm-Product-mastered" contains only the previous matched/merged doc. It seems to be a bug in that this behavior doesn't improve the un-tagged situation even additional collection is set:
            "onMerge" : {
                "add" : {
                  "collection" : [ "ProductFinal" ]
                },

Please let me know if you still need to see the flow config files.
