### ISSUE TITLE
Unable to login marklogic using hub frame work received  "500 Internal Server Error" 

### ISSUE THREAD

**Issue by sudhirkr21** [marklogic/marklogic-data-hub#374]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem: My data hub was working properly till yesterday but now suddenly i am getting "500 Internal Server Error" which i am not sure why i am getting this.

I did restart war file, but issue still remains

I tried creating another folder setup as well thinking it may be issue with my setup gone corrupted but then i get different error  "No message available"

There is some indexing happening in my database as well on a larger set of data( approx 1+tb, created some new fields) 

What behavior are you expecting?

should be able to access my dataset using hubframework

#### Tech details

Which Operating System are you using?

linux box

Which version of MarkLogic are you using?

8

Which version of the Data Hub Framework are you using?

1.1.0

Is this a QuickStart UI bug? If so, which browser are you using?
 chrome
#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by paxtonhare** [comment]
@sudhirkr21 do you have any stack traces from the java console or from ErrorLog.txt?
