### ISSUE TITLE
See if we can bail if the gradle version is too low

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#376]
the gradle plugin requires gradle 3.1 or greater. See if we can check the version at runtime and bail with an error message if the gradle version is too low.

**Comment by jmakeig** [comment]
Or just document the minimum version and recommend that users use `gradlew`?

**Comment by paxtonhare** [comment]
Yeah, that's what we have already done. But if someone has a problem I end up spending a lot of time tracking down a bug that turns out to be a bad gradle version. This would at least save me some time.

**Comment by paxtonhare** [comment]
![image](https://cloud.githubusercontent.com/assets/630382/23318781/d3db879e-faa1-11e6-883c-13b8483485fe.png)

It's totally possible.
