### ISSUE TITLE
Entities and custom modules fail to deploy - v1.1.0

### ISSUE THREAD

**Issue by gku11ava** [marklogic/marklogic-data-hub#377]
Issue:  Contents of the plugins folder do not get deployed using gradle mlDeploy or mlLoadModules.  

OS: CentOS 6 (2.6.32-642.6.1)
Gradle: 3.2.1
Data Hub: v1.1.0
MarkLogic: 8.0-6

Steps:
1. Run gradle hubInit to generate scaffolding
2. Place an XQuery module in the plugins folder.
3. Run gradle mlDeploy
4. Open browser to query console, explore data-hub-MODULES.  Search for the custom XQuery module.

**Comment by paxtonhare** [comment]
You have to use gradle mlloadmodules for those to get deployed.

**Comment by gku11ava** [comment]
gradle mlLoadModules does not seem to work either.   Prior to running, there are 70 modules in the modules DB.  After running there are 70.   Any custom entities or xquery modules are still not getting loaded.

**Comment by paxtonhare** [comment]
@gku11ava the Framework might think that you already deployed all of the modules. It keeps a file `.tmp/user-modules-deploy-timestamps.properties` with all of the timestamps of when it last deployed the files. 

try removing that file then run `gradle mlloadmodules`

If that works then we probably should update this issue to "Add ability to force User modules load from gradle."

**Comment by gku11ava** [comment]
Removing the file and using the mlLoadModules task works.   Does mlDeploy no longer call mlLoadModules or mlDeployCPF?  It seems I have to run those tasks manually after mlDeploy now.

**Comment by paxtonhare** [comment]
It does call DeployCpf. But maybe that fails if it isn't calling load modules. I'll add it in for grins.
