### ISSUE TITLE
Allow provenance tracking from one source to multiple destinations

### ISSUE THREAD

**Issue by dmcassel** [marklogic/marklogic-data-hub#3774]
**Is your feature request related to a problem? Please describe.**
The "Provenance in a Custom Step" section on the [Editing a Custom Step Module](https://docs.marklogic.com/datahub/modules/editing-custom-step-module.html) provides a structure that's used to record provenance when updating properties. That structure doesn't allow for arrays, which means that a property from one URI can only contribute to one property in the new document. This doesn't allow for when one property in a source contributes to multiple properties in the new document. For example, if a source has a "fullName" property, that could get split into "firstName" and "lastName" properties. 

**What is the user-facing scenario that prompted this gap in functionality?**

**Describe the solution you'd like**
Allow an array of values. 

```javascript
   {
    "/26451baa-fe14-471f-bd77-364ac3f64c82.json": {
      "fullName": [
        {
          "destination": "firstName",
          "value": "Bob"
        },
        {
          "destination": "lastName",
          "value": "Smith"
        }
      ]
    }
  }
```

**Describe alternatives you've considered**

**Additional context**

**Comment by Sanjeevani19** [comment]
Will be addressing this as a part of provenance feature
