### ISSUE TITLE
Geolocation mapping

### ISSUE THREAD

**Issue by chenfiona** [marklogic/marklogic-data-hub#3796]
**Is your feature request related to a problem? Please describe.**

**What is the user-facing scenario that prompted this gap in functionality?**
Data Hub capability to map Geolocation.

**Describe the solution you'd like**
I have a text file containing Geolocation column. The value looks like:
(33.57943283260, -86.7228323926)
How realistic is it to map such value into MarkLogic geospatial JSON format? 
The JSON format is supposed to be:
{"coords": {
  "lat": 1.0,
  "lon": 2.0
}}
OR
{"coords": "1.0 2.0" }
OR
{"coords": [1.0, 2.0] }

If no, can the ingested value (33.57943283260, -86.7228323926) be interpreted as valid ML geospatial format?

**Comment by srinathgit** [comment]
I am not aware of any built-in capabilities of mlcp or datahub ingestion step to convert the specific format to geospatial json format. You can however create a custom transformation to convert your format to Marklogic geospatial json format.

**Comment by chenfiona** [comment]
Thanks! So if I ingest the data as it is (33.57943283260, -86.7228323926), then it is NOT MarkLogic Geospatial compliant. Right?

**Comment by srinathgit** [comment]
Please look into this link https://docs.marklogic.com/guide/search-dev/geospatial#id_96147 for conversion to and from common geospatial formats

**Comment by chenfiona** [comment]
Thanks!  Here is the rub: 
     The original property value is:  
> "Geolocation": "(39.75685036680, -121.815983972)"
I can transform it to below for Geospatical search.  
> "geometry": [39.75685036680, -121.815983972]
      BUT TDE can't retrieve array value ( as soon as I modify "datatype" : "array", TDE returns null ). The entity of that property has to be string and the value is also be string. 
      So if I don't transform "Geolocation" into array or a conformed structure, Geospatial search doesn't work. If I transform it to array, mapping/TDE doesn't work. 
      Do you have any idea how the mapping@DH works for array ?  Or you can give me one line of code so as to make BOTH the format and TDE works at the same time?

**Comment by srinathgit** [comment]
It doesn't have to be array. Can you check the example in this link https://docs.marklogic.com/cts.jsonPropertyPairGeospatialQuery  ?

**Comment by rjrudin** [comment]
This is really outside the scope of DH. I think the simplest solution is to use a property/element index - https://docs.marklogic.com/guide/search-dev/geospatial#id_44359 . Based on your example, you can just change "(39.75685036680, -121.815983972)" into "39.75685036680 -121.815983972". Then add an element index to "geometry". You now have a single property with a geospatially-indexed value. No need to worry about an array, it'll work fine in your TDE since you have a single value. 

Please close this if that approach works out.

**Comment by chenfiona** [comment]
Thank you! I will test different approaches. I am sure one of them will work out.

**Comment by chenfiona** [comment]
I test the "39.75685036680 -121.815983972" format. Both the TDE and Geospatial search works!
