### ISSUE TITLE
Mastering is not working as expected

### ISSUE THREAD

**Issue by chenfiona** [marklogic/marklogic-data-hub#3804]
*### Welcome Hub enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

Short description of the problem:

What behavior are you expecting?
I have mastering flow which takes 3 property scoring. I expect the merged documents based on "Exact" match on all 3 properties. The first 2 properties are merged correctly but not the 3rd property. Even the 3rd property is different, the documents are still merged into one and the 3rd property are reduced to array.
What are the steps to reproduce the issue:
1) Below is the scoring factor:
          "scoring" : {
            "add" : [ {
              "propertyName" : "accountPersistentID",
              "weight" : "30"
            }, {
              "propertyName" : "assetPersistentID",
              "weight" : "30"
            }, {
              "propertyName" : "valueAsofDate",
              "weight" : "35"
            } ],
            "expand" : [ ],
            "reduce" : [ ]
          },
          "actions" : {
            "action" : [ ]
          },
          "thresholds" : {
            "threshold" : [ {
              "above" : "60",
              "label" : "HoldingMatch",
              "action" : "merge"
            } ]
2)
3)

#### Tech details

Which Operating System are you using?
Windows
Which version of MarkLogic are you using?
10.0-3
Which version of the Data Hub are you using?
V5.2.0
Is this a QuickStart UI bug? If so, which browser are you using?
No
#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar marklogic-datahub-<version>.war  --debug  > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -debug > myoutput.txt`

**Comment by srinathgit** [comment]
If possible, can you provide the project dir , data and instructions for reproducing the issue

**Comment by chenfiona** [comment]
Hi, I can't upload client data. What project structure would you need?

**Comment by srinathgit** [comment]
I would need the data hub project with the flow, entity and data (not client but sample data with 2 documents that would reproduce the issue). If you can zip up the datahub project with these, I will try debugging it at my end

**Comment by chenfiona** [comment]
Hi, I have sent 4 sample documents, entity definition and mastering step definition to Sundar Bandepalli .    Please do let me know if you need me upload here. Thanks!

**Comment by srinathgit** [comment]
I will work with Sundar to get the documents and reproduce the issue.

**Comment by srinathgit** [comment]
@chenfiona ,
In the "Match Options", can you adjust the weights of accountPersistentID, assetPersistentID and valueAsofDate to 20 (so that their sum is equal to merge threshold 60 so as to get an AND operation) and then try running the flow ?

**Comment by chenfiona** [comment]
Hi, it behaves differently but not what I expected. I replied back to Sundar and Chris. And I have uploaded the entire DH project and the data which is sufficient to reproduce the scenario and find the root cause.  Thanks!

**Comment by srinathgit** [comment]
I tried with the 4 documents you provided with weights set to 20 each for accountPersistentID, assetPersistentID, valueAsofDate and saw that only 2 documents which have the exact same values for these 3 properties got merged. I will try with the project you have provided. Is the issue same there as well (as in you see merges even in cases when  only 2 properties are same )  ?

**Comment by chenfiona** [comment]
Hi, My test results are: 
1. 
> 30/30/35 + 60 threshold -> either assetPersistentID or valueAsofDate is merged with the same accountPersistentID   
2. 
> 20/20/20 + 60 threshold (30/30/35 + 94 threshold) -> none of the document is matched/merged

I hope you understand what that really means.

**Comment by chenfiona** [comment]
Good news:  MarkLogic successfully matches and merges the expected documents after refactoring the Date format.  Thanks!
