### ISSUE TITLE
[BUG] Flow with multiple mapping steps overwrites documents in Final database for every mapping step

### ISSUE THREAD

**Issue by taatuut** [marklogic/marklogic-data-hub#3819]
#### The issue

Short description of the problem:

A flow with multiple mapping steps overwrites the resulting documents in Final database for every mapping step executed.

We have an input doc X, and we want to map out Entity A and Entity B (and Entity C,D,E,F,G). We setup multiple mapping steps A to G. However when we run the mapping of A followed by the mapping of B, the resulting document of mapping of A is overwritten because it outputs to the same URI. Same happens then when running mapping C to G (C overwrites B etc.).

What behavior are you expecting?

Being able to run a flow with multiple mapping steps without resulting documents overwriting themselves.

What are the steps to reproduce the issue:

Create a flow with multiple mapping steps that run on the same input collection but are supposed to output different documents.

Source:

<doc>
<some></some>
<thing></thing>
</doc>

Mapping A maps property <some> to a document in Final, mapping B maps property <thing> to a document in Final.

Running any mapping step first, then the other will overwrite previous results.

#### Tech details

Which Operating System are you using?
Windows 2016

Which version of MarkLogic are you using?
MarkLogic 10.0-3

Which version of the Data Hub are you using?
5.1

Is this a QuickStart UI bug? If so, which browser are you using?
No

**Comment by srinathgit** [comment]
The OOTB steps write the mapped document to the same uri as source doc(it modifies the extension if xml is transformed to json or vice versa in mapping process). You can use custom steps to modify the uris of the documents.
https://docs.marklogic.com/datahub/flows/configure-custom-step-using-quickstart.html
