### ISSUE TITLE
Can't run harmonize on 2.0.0-alpha.2

### ISSUE THREAD

**Issue by ryanjdew** [marklogic/marklogic-data-hub#382]
#### The issue

Short description of the problem:

If I run a harmonize task with the 2.0-alpha.2 war I get an error "Could not read resource at forestinfo. Server Message: Request failed. Error body not received from server". It appears it is using the now deprecated Data Movement SDK (moved into Java Client).

#### Tech details

Which Operating System are you using?

RHEL7 VM / Mac Client

Which version of MarkLogic are you using?

ML 9 Nightly (2017-03-22)

Which version of the Data Hub Framework are you using?

2.0.0-alpha.2

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for gradle:**  
  `gradle hubRunFlow -PentityName=MDM -PflowName=MDMHarmonize -PflowType=harmonize --stacktrace -d > output.txt`
[output.txt](https://github.com/marklogic/marklogic-data-hub/files/876663/output.txt)

**Comment by paxtonhare** [comment]
This is a mismatch of java-client-api and MarkLogic.

Install the latest nightly. Then use 4.0-SNAPSHOT.

**Comment by ryanjdew** [comment]
I get the same thing with the latest nightly installed and my gradle.build adjusted with the following:
`    compile group: "com.marklogic", name: "java-client-api", version:"4.0.0-SNAPSHOT"`
`    compile 'com.marklogic:marklogic-data-hub:2.0.0-alpha.2'`

Do I need the latest from 2.0.0-develop? If so, is there a '2.0.0-SNAPSHOT' or equivalent that I can point to or do I need to manually build for now?

**Comment by paxtonhare** [comment]
I think you will need to build manually for now.

**Comment by ryanjdew** [comment]
Just leaving here what I did for posterity. 

1. Clone the latest from the 2.0-develop branch
2. Adjust the marklogic-data-hub root gradle.properties to `version=2.0-SNAPSHOT`
3. Run `gradle publishToMavenLocal -x test -x javadoc` from the root of the project.
4. Adjust the build script for my project that is dependent on data hub to look like the following:

```groovy
buildscript {
  repositories {
    mavenLocal() // Important for local latest version of data hub. 
    jcenter()
    mavenCentral()
    maven {url 'http://developer.marklogic.com/maven2/'}
  }
  dependencies {
    classpath "com.marklogic:ml-data-hub:2.0-SNAPSHOT"
  }
}
apply plugin: "com.marklogic.ml-data-hub"
...
dependencies {
    ...
    compile 'com.marklogic:marklogic-data-hub:2.0-SNAPSHOT'
    ...
}
```

**Comment by paxtonhare** [comment]
closing this because 9.0 is out and this should be resolved
