### ISSUE TITLE
[BUG] DHF 5.2.1 plugin not published

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic/marklogic-data-hub#3825]
DHF 5.2.1 is released 12 days ago, but the plugin is not published:

This works: https://plugins.gradle.org/m2/gradle/plugin/com/marklogic/ml-data-hub/5.2.0/  but this does not: https://plugins.gradle.org/m2/gradle/plugin/com/marklogic/ml-data-hub/5.2.1/

If I run the `HubUpdate` I get:

```
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find gradle.plugin.com.marklogic:ml-data-hub:5.2.1.
     Searched in the following locations:
       - https://jcenter.bintray.com/gradle/plugin/com/marklogic/ml-data-hub/5.2.1/ml-data-hub-5.2.1.pom
       - https://repo.maven.apache.org/maven2/gradle/plugin/com/marklogic/ml-data-hub/5.2.1/ml-data-hub-5.2.1.pom
       - http://developer.marklogic.com/maven2/gradle/plugin/com/marklogic/ml-data-hub/5.2.1/ml-data-hub-5.2.1.pom
       - https://plugins.gradle.org/m2/gradle/plugin/com/marklogic/ml-data-hub/5.2.1/ml-data-hub-5.2.1.pom
```

**Comment by rjrudin** [comment]
What's in your build.gradle file? As shown in https://plugins.gradle.org/plugin/com.marklogic.ml-data-hub , if you're using "classpath" and "apply", then you must have the following:

```
repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
```

I just did a test with the following, and 5.2.1 worked fine, so closing this. If you still have an issue, please reopen with your build.gradle file included, as there must be a problem in there.

```
buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "com.marklogic:ml-data-hub:5.2.1"
    }
}

apply plugin: "com.marklogic.ml-data-hub"
```
