### ISSUE TITLE
[BUG] Problem with admin-group-scheduled-task-Default privilege when upgrading

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic/marklogic-data-hub#3826]
Multiple people are reporting this issue in #datahub slack channel:

If you:

- Install ML 9.0-x (I used 9.0-10.2)
- Create a empty DHF 4.3.1 project
- Deploy this project
- Upgrade to ML 10.0-4
- Run the upgrade procedure to 5.2.0 for the project.
- Run `mlDeploy`

This result in:

```
> Task :mlDeployApp FAILED
Logging HTTP response body to assist with debugging: {"errorResponse":{"statusCode":"400", "status":"Bad Request", "messageCode":"MANAGE-INVALIDPAYLOAD", "message":"MANAGE-INVALIDPAYLOAD: (err:FOER0000) Payload has errors in structure, content-type or values. Privilege action cannot be changed."}}
Error occurred while sending PUT request to /manage/v2/privileges/admin-group-scheduled-task-Default/properties?kind=execute; logging request body to assist with debugging: {
  "privilege-name" : "admin-group-scheduled-task-Default",
  "action" : "http://marklogic.com/xdmp/privileges/admin/group/scheduled-task/$$group-id(Default)",
  "kind" : "execute",
  "role" : [ "data-hub-developer" ]
}
````
However: This is not coming from the source tree, so most likely from the DHF plugin. Why does DHF need scheduled task priv?  Also http://localhost:8002/manage/v2/privileges/admin-group-scheduled-task-Default/properties?kind=execute&format=json already returns the same. So the action is not going to change:

```
{"privilege-name":"admin-group-scheduled-task-Default", "action":"http://marklogic.com/xdmp/privileges/admin/group/scheduled-task/$$group-id(Default)", "kind":"execute"}
````
I temporary walked around this issue by removing this priv, so that it get reinserted, but I am curious about the root cause.

**Comment by rjrudin** [comment]
I'm looking into this.

**Comment by rjrudin** [comment]
I can't install 4.3.1 on ML 9.0-12 - I get the following:

```
{stagingPortInUseBy=null, finalPortInUseBy=null, stagingPortInUse=false, finalPortInUse=false, safeToInstall=false, serverVersion=9.0-12, jobPortInUseBy=null, jobPortInUse=false, serverVersionOk=false}- PROBLEM: Unsupported MarkLogic Server Version: 9.0-12
        FIX: Update to a supported version of MarkLogic.
```

I'll try a different version of ML, I'll see if it can install on 10.0-2.1 as I have the native installer for that.

FWIW, I installed 4.3.1 on 10.0-4, then ugpraded to 5.2.0, and didn't have any problem with mlDeploy.

**Comment by rjrudin** [comment]
I followed the instructions, but used ML 10.0-2.1 as I DH 4.3.1 didn't let me install on 9.0-12. 

After upgrading to 10.0-4 and then 5.2.0, I ran mlDeploy, and the call to create the granular privilege succeeded:

```
Sending XML GET request as user 'admin' (who must have the 'manage-admin' and 'security' roles) to path: /manage/v2/privileges
Creating privilege: admin-group-scheduled-task-Default
Sending JSON POST request as user 'admin' (who must have the 'manage-admin' and 'security' roles) to path: /manage/v2/privileges
Created privilege: admin-group-scheduled-task-Default
Finished executing command [com.marklogic.hub.deploy.commands.CreateGranularPrivilegesCommand] in 12215ms
```

I wouldn't expect that to fail though, as the privilege doesn't exist, so DH is just creating a new privilege. 

Are you sure you have the right instructions to reproduce? I thought that someone else who reported something like this mentioned that they already had DH 5.2.0 installed, and they upgraded ML instead.

**Comment by rjrudin** [comment]
Closing based on inability to reproduce above and lack of response
