### ISSUE TITLE
content.provenance in Custom step module

### ISSUE THREAD

**Issue by chenfiona** [marklogic/marklogic-data-hub#3829]
**Is your feature request related to a problem? Please describe.**
I need to setup property-level provenance tracking in the Custom main.sjs. 

**What is the user-facing scenario that prompted this gap in functionality?**
I am not clear about : 
> content.provenance must contain the properties that you want to track and their values.

In the example:
`   {
    "/26451baa-fe14-471f-bd77-364ac3f64c82.json": {
      "lastName": {
       "destination": "surName",
       "value": "Smith"
      }
    }
  }
`
I don't expect manually hardcode URI in main.sjs.  During the custom step, there are new properties be harmonised. 

**Describe the solution you'd like**
Please describe the blocks of code in the main.sjs so as to achieve property-level provenance tracking. 

**Describe alternatives you've considered**
The block is something like:
`  
  newContent.value = envelope;
  newContent.uri = id;
  newContent.context = context;
  **newContent.provenance =**  
  return newContent;
`
**Additional context**

**Comment by Sanjeevani19** [comment]
- You can set provenance like this
   newContent.provenance = { [newContent.uri]: provenance };

- Define your provenance json object as shown in the example in this page in Provenance in a 
   Custom Step section : 
   [https://docs.marklogic.com/datahub/modules/editing-custom-step-module.html](url)

- This is how you define provenance granularity to enable property level provenance :
   [https://docs.marklogic.com/datahub/logs/set-provenance-granularity-manually.html](url)

Please try them and let me know if you have any questions.

**Comment by chenfiona** [comment]
Hello:  
Both the links shows

> No results matched your search.

**Comment by Sanjeevani19** [comment]
Sorry about that, for some reason the links are being redirected to github. If you copy and paste in manually in the browser the links seems to work.

**Comment by chenfiona** [comment]
Thanks! 
Since there are lots of JOBS documents, how can I pinpoint the difference between coarse and fine and from what type of documents/files?

**Comment by chenfiona** [comment]
My Auditing report seems to show more complicated/duplicated properties/values changes back and forth in one URI if I enable "fine" provenance tracking during mastering.  If I remove the "fine" option during mastering, the audit reports give me consistent single property/value in one URI.

**Comment by Sanjeevani19** [comment]
For now, you can figure out with type “dhf:EntityProperty”.

`cts.uris("", null, cts.andQuery([cts.collectionQuery("http://marklogic.com/provenance-services/record"), cts.wordQuery("dhf:EntityProperty")]))
`
I used the above query to get the uri’s of the provenance documents with granularity set as fine

**Comment by chenfiona** [comment]
Hello:  The auditing I developed is:
1). document-level ( through JOBS db)  
2). property-level ( through FINAL mastering auditing collection ) 
3). 360audit  ( capture URI, property, value changes during mastering )

Example of 1) is:
`<DocumentAudit>
<Audit URI="/account/1231f394-c4ad-4e56-962e-30b8e1a59626.json">
<DHF_Step>dhf:IngestionStep
</DHF_Step>
<DHF_Type>dhf:DocCreated
</DHF_Type>
<TimeStamp>2020-04-19T13:10:34.882236-04:00
</TimeStamp>
<User>admin
</User>
</Audit>
<Audit URI="/account/1231f394-c4ad-4e56-962e-30b8e1a59626.json">
<DHF_Step>dhf:MappingStep
</DHF_Step>
<DHF_Type>dhf:DocUpdated
</DHF_Type>
<TimeStamp>2020-04-19T13:10:35.5677984-04:00
</TimeStamp>
<User>admin
</User>
</Audit>
</DocumentAudit>`

My question is: 
A)  If I enable "fine", what will be the difference as regards above result? 

B)  The 360audit result I produced is sth like this:
`<_360Audit_>
<AuditUser>admin</AuditUser>
<Provenance uri="/account/1231f394-c4ad-4e56-962e-30b8e1a59626.json">
<property>
<name>id
</name>
<value>007
</value>
</property>
<property>
<name>lastname
</name>
<value>Jane
</value>
</property>
<property>
<name>email
</name>
<value>mary.jane@whodunit.com
</value>
</property>
<property>
<name>firstname
</name>
<value>Mary
</value>
</property>
</Provenance>`

But If I enable "fine" in the mastering, I may see some duplicated property/value. For example below property/value may appear twice in the mastering auditing document:
<property>
<name>lastname
</name>
<value>Jane
</value>
</property>

**Comment by Sanjeevani19** [comment]
A) The below links explains the difference between coarse and fine granularities in mastering step.
https://docs.marklogic.com/datahub/logs/about-provenance-lineage.html
https://docs.marklogic.com/datahub/logs/provenance-for-mastering.html

B) There could be values that look like duplicates if they were the same in the 2 documents that merged. It depends on the algorithm used for matching the documents. It would be helpful if you could provide an example data-set and steps to reproduce.

**Comment by chenfiona** [comment]
Thanks! I clearup the data and re-mastered. It doesn't appear giving me duplicated property/value in one URI for some reasons.  
I will contact you if I see such duplication in one URI again.
