### ISSUE TITLE
[BUG] Mastering step fails for documents in temporal collection

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic/marklogic-data-hub#3840]
*### Welcome Hub enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

Short description of the problem:
Mastering step fails to work with documents in temporal collection - it throws a bug

What behavior are you expecting?
That the documents are properly updated and new versions are created

What are the steps to reproduce the issue:
1) Add documents to a temporal collection
2) Try to master them 
3) Same error (see below) happens with or without the temporal collection specified as additional target collection in the step definition

#### Tech details

Which Operating System are you using?
MacOS 10.15.4 (19E266)

Which version of MarkLogic are you using?
10.0-3 on Docker

Which version of the Data Hub are you using?
5.2.1

Is this a QuickStart UI bug? If so, which browser are you using?
Nope.

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar marklogic-datahub-<version>.war  --debug  > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -debug > myoutput.txt`

Error:

```Cannot use "latest" as a temporal collection or in collection parameter in /data-hub/5/impl/hub-utils.sjs, at 55:24, in writeDocuments() [javascript] in /data-hub/5/impl/flow.sjs, at 229:53, in runFlow() [javascript] in /marklogic.rest.resource/mlRunFlow/assets/resource.sjs, at 60:24, in post() [javascript] in /MarkLogic/rest-api/lib/extensions-util.sjs, at 93:29, in callExtension() [javascript] in /MarkLogic/rest-api/lib/extensions-util.sjs, at 111:9, in applyOnce() [javascript] in /MarkLogic/rest-api/lib/extensions-util.sjs, at 919:44, in xdmp:function(fn:QName("http://marklogic.com/rest-api/resource/mlRunFlow","post"),```

<img width="1061" alt="Screenshot 2020-04-20 at 15 26 18" src="https://user-images.githubusercontent.com/15609655/79756740-5d3f3300-831b-11ea-8e18-c013bdb5875e.png">

**Comment by ryanjdew** [comment]
A workaround for this issue would be to use separate match/merge steps instead of the single mastering step. Beyond the benefit of preventing locking, the separate steps are able to use the core Data Hub method for writing documents that already accounts for writing temporal documents.

**Comment by sashamitrovich** [comment]
The workaround doesn't work for me, matching step fails, although with another error. I will log a separate bug for this.

**Comment by sashamitrovich** [comment]
I will try. Was blocked with the issue where the Merging step was finishing with errors (#3859 )

**Comment by sbayatpur** [comment]
We recommend that users use match and merge steps instead of mastering steps for performance reasons. Closing this since this is not an issue for match and merge steps. @sashamitrovich my understanding is you got match and merge steps working. Let me know if that wasn't resolved.
