### ISSUE TITLE
Upgrade to latest ML Java Client

### ISSUE THREAD

**Issue by daveegrant** [marklogic/marklogic-data-hub#3841]
The latest version of the marklogic-client-api (currently 5.2.0) includes a newer version of the <okhttp> library which offers more debugging options.  Recommend upgrading the data hub dependency to the latest version.

Having the new debugging options for <okhttp> would have been helpful to diagnose an SSL issue the customer (DTIC) encountered while attempting to deploy code updates to their MarkLogic cluster.

**Comment by srinathgit** [comment]
Thanks @daveegrant . We will look into the possibility of upgrading to java client api 5.2.0 and will post updates on it

**Comment by rjrudin** [comment]
DHF 5.4.0 is using Java Client 5.3.2
