### ISSUE TITLE
Custom step boilerplate code should reference instance[$type] not instance[$title]

### ISSUE THREAD

**Issue by mariannemyers** [marklogic/marklogic-data-hub#3842]
The boilerplate code to generate a custom step incorrectly references `instance[$title]` when the code in the impl `flow-utils.sjs` is looking for `instance[$type`].

Here the code indicates changing the `instance[$title]` should help create the instance:
https://github.com/marklogic/marklogic-data-hub/blob/develop/marklogic-data-hub/src/main/resources/scaffolding/custom-module/sjs/main-custom.sjs#L88

But over where it's created in the internal hub code, it's looking for for `content.hasOwnProperty("$type")` in order to properly generate the instance:
https://github.com/marklogic/marklogic-data-hub/blob/develop/marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow-utils.sjs#L92

Can the boilerplate code be updated to reference `instance[$type]`?

**Comment by srinathgit** [comment]
Thanks @mariannemyers . https://project.marklogic.com/jira/browse/DHFPROD-4807 has been created for fixing this issue

**Comment by kkanthet** [comment]
Issue Fixed in 5.4.0 release
