### ISSUE TITLE
[BUG] Merging step finishes with errors: "Message: Cannot read property 'toObject' of undefined"

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic/marklogic-data-hub#3859]
*### Welcome Hub enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

Short description of the problem:
Merging step fails with "Message: Cannot read property 'toObject' of undefined"

Detailed error (from the UI):
```TypeError: Cannot read property 'toObject' of undefined at cts.search.toArray.map (/data-hub/5/builtins/steps/mastering/default/merging.sjs:61:72) at Array.map (<anonymous>) at main (/data-hub/5/builtins/steps/mastering/default/merging.sjs:59:17) at Flow.runMain (/data-hub/5/impl/flow.sjs:485:12) at Flow.runStep (/data-hub/5/impl/flow.sjs:343:58) at Flow.runFlow (/data-hub/5/impl/flow.sjs:211:12) at post (/marklogic.rest.resource/mlRunFlow/assets/resource.sjs:60:25) at callExtension (/MarkLogic/rest-api/lib/extensions-util.sjs:93:30) at applyOnce (/MarkLogic/rest-api/lib/extensions-util.sjs:111:10)```

What behaviour are you expecting?
Runs successfully.

What are the steps to reproduce the issue:
1) Run Matching, it succeeds.
2) Run Merging on the matched documents.
3)

#### Tech details

Which Operating System are you using?
MacOS 10.15.4 (19E266)

Which version of MarkLogic are you using?
10.0-3 on Docker

Which version of the Data Hub are you using?
5.2.1

Is this a QuickStart UI bug? If so, which browser are you using?

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar marklogic-datahub-<version>.war  --debug  > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -debug > myoutput.txt`

ML log:
```2020-04-22 10:01:12.103 Info: {"message":"Error running step: TypeError: Cannot read property 'toObject' of undefined. TypeError: Cannot read property 'toObject' of undefined\n    at cts.search.toArray.map (/data-hub/5/builtins/steps/mastering/default/merging.sjs:61:72)\n    at Array.map (<anonymous>)\n    at main (/data-hub/5/builtins/steps/mastering/default/merging.sjs:59:17)\n    at Flow.runMain (/data-hub/5/impl/flow.sjs:485:12)\n    at Flow.runStep (/data-hub/5/impl/flow.sjs:343:58)\n    at Flow.runFlow (/data-hub/5/impl/flow.sjs:211:12)\n    at post (/marklogic.rest.resource/mlRunFlow/assets/resource.sjs:60:25)\n    at callExtension (/MarkLogic/rest-api/lib/extensions-util.sjs:93:30)\n    at applyOnce (/MarkLogic/rest-api/lib/extensions-util.sjs:111:10)","type":"error","currentDateTime":"2020-04-22T10:01:05.077586Z","user":"flow-developer","serverID":"11854719945948116211","serverName":"funds-data-hub-STAGING","dbID":"14757146973405796850","dbName":"funds-data-hub-FINAL","modulesDbID":"18365296999434134823","modulesDbName":"funds-data-hub-MODULES"}```

**Comment by sashamitrovich** [comment]
Note: some of the documents do get merged and some fail.

**Comment by srinathgit** [comment]
Thanks @sashamitrovich . https://project.marklogic.com/jira/browse/DHFPROD-4830 has been created to track this issue. It would be helpful if you can attach a datahub project to the jira issue using which we can reproduce the issue

**Comment by ryanjdew** [comment]
@sashamitrovich I was able to reproduce the issue. Can you try placing the file at the following link into your project at the location `src/main/ml-modules/root/data-hub/5/builtins/steps/mastering/default/merging.sjs` and verify it resolves the issue?

https://raw.githubusercontent.com/marklogic/marklogic-data-hub/a045e403e60ed5fc70fdd5a929995cfa16d14e57/marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/merging.sjs

**Comment by sashamitrovich** [comment]
This resolves the issue. Thanks, @ryanjdew .

**Comment by bsrikan** [comment]
@sashamitrovich can we close this issue if its resolved. Also pls let us know if this fixes #3840 as well.

**Comment by sashamitrovich** [comment]
@bsrikan , it can be resolved if this fix is going into the source code and I don't have to apply this workaround for every project :)

#3840 is a different issue, has to do with temporal and recognising that a temporal collection is used.

**Comment by bsrikan** [comment]
@sashamitrovich the fix for this issue is in source code now 👍
