### ISSUE TITLE
Request String utility functions in Mapping

### ISSUE THREAD

**Issue by chenfiona** [marklogic/marklogic-data-hub#3875]
**Is your feature request related to a problem? Please describe.**
String utility functions: `padStart()  padEnd()  trimStart()  trimEnd() `
are not found in the mapping function list. 

**What is the user-facing scenario that prompted this gap in functionality?**
Mapping functions should include above 4 useful String utilities.

**Comment by srinathgit** [comment]
Thanks @chenfiona  for opening the ticket. We will look into adding the functions you have mentioned in the feature request. FYI, You can create custom functions and use them in mappings https://docs.marklogic.com/datahub/flows/create-custom-mapping-functions.html

**Comment by chenfiona** [comment]
I have tried using the custom mapping before but failed.

**Comment by srinathgit** [comment]
Please follow the steps specified in the document , it provides an example , other functions can be implemented likewise, deployed and used in mapping.
