### ISSUE TITLE
Example: Watch a directory to initiate a flow

### ISSUE THREAD

**Issue by paul-hoehne** [marklogic/marklogic-data-hub#388]
Initiate a load and harmonize flow by watching for a new file in a directory.

When the new file arrives, the data is loaded by the data hub and then the harmonization flow is run.  I'll have a better idea of what it should do once I'm done with it.

**Comment by paxtonhare** [comment]
@paul-hoehne are you asking for an example in the examples dir on how to do this?

**Comment by paul-hoehne** [comment]
It's a little client related and I haven't had time to work on it.  If we can ever get to software construction I'll have something concrete.  But the idea is to start the DH quickstart and till it to monitor /foo/bar/baz and when new file shows up, make the magic happen.

**Comment by paxtonhare** [comment]
@paul-hoehne So you aren't looking for a stand-alone java app that uses the DHF and watches a dir. You are wanting an enhancement to Quick-start to do this, right?

**Comment by paul-hoehne** [comment]
Yep.  Willing to do it when I have time.

On May 24, 2017 9:15 AM, Paxton Hare <notifications@github.com> wrote:

@paul-hoehne<https://github.com/paul-hoehne> So you aren't looking for a stand-alone java app that uses the DHF and watches a dir. You are wanting an enhancement to Quick-start to do this, right?

**Comment by damonfeldman** [comment]
Can/should we use Spring Batch for this? Either with an integration to QuickStart in the same approach as embedding mlcp, or with a combined approach where you download them both and connect them. 

I believe MLSB or SB core already has a directory watcher (or we should add one if not).

**Comment by tcfenstermaker** [comment]
@damonfeldman @paxtonhare So is this an enhancement or an example? Or, does this mean you want an enhancement and an example along with it?

**Comment by paxtonhare** [comment]
I intended it to be an example with some custom Java code that watched a
dir. That way it would also demonstrate how to invoke a flow from Java.

But I'm ok with using spring batch if it has a watcher already.

**Comment by aebadirad** [comment]
Data Hub 5.0 allows for this to be triggered, or allows for an off the shelf product to orchestrate a data hub flow based on a file watch.

Closing.
