### ISSUE TITLE
[BUG] Invalid Schema Generation for Type Array

### ISSUE THREAD

**Issue by awanczowski** [marklogic/marklogic-data-hub#3888]
#### The issue

Short description of the problem: When creating a String entity property with a cardinality of 1:∞ the JSON Schema generated produces the following 

```
"symptoms": {
	"items": {
		"collation": "http://marklogic.com/collation/codepoint",
		"type": "array"
	},
	"type": "array"
}
```

What behavior are you expecting?

The items type should be "string"

What are the steps to reproduce the issue:
1) Create a new entity with a string field with cardinality 1:∞
2) View the schema generated in the Schema Database

#### Tech details

Which Operating System are you using?  Mac OS

Which version of MarkLogic are you using? 10.0.3

Which version of the Data Hub are you using? 5.2.0

**Comment by rjrudin** [comment]
Are you creating the entity manually or via QS? You need to share your entity model in order for this to be reproducible, just so that the entity model can be verified as being correct (i.e. if you're using QS, the bug may be in QS).

**Comment by awanczowski** [comment]
Hi @rjrudin ,

Sure, this happens either by QS or Gradle. I believe it may be part of the bundling but not sure. 

 Here is the entity and the JSON Schema generated.
```
{
  "info" : {
    "title" : "MyEntity",
    "version" : "0.0.1",
    "baseUri" : "http://example.org/"
  },
  "definitions" : {
    "MyEntity" : {
      "required" : [ ],
      "pii" : [ ],
      "elementRangeIndex" : [ ],
      "rangeIndex" : [ ],
      "wordLexicon" : [ ],
      "properties" : {
        "id" : {
          "datatype" : "string",
          "collation" : "http://marklogic.com/collation/codepoint"
        },
        "tags" : {
          "datatype" : "array",
          "items" : {
            "datatype" : "string",
            "collation" : "http://marklogic.com/collation/codepoint"
          }
        }
      }
    }
  }
}
```

```
{
	"lang": "zxx",
	"definitions": {
		"MyEntity": {
			"required": [],
			"pii": [],
			"elementRangeIndex": [],
			"rangeIndex": [],
			"wordLexicon": [],
			"properties": {
				"id": {
					"collation": "http://marklogic.com/collation/codepoint",
					"type": "string"
				},
				"tags": {
					"items": {
						"collation": "http://marklogic.com/collation/codepoint",
						"type": "array"
					},
					"type": "array"
				}
			}
		}
	},
	"required": ["MyEntity"],
	"$id": "http://example.org/",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"properties": {
		"MyEntity": {
			"$ref": "#/definitions/MyEntity"
		}
	},
	"info": {
		"title": "MyEntity",
		"version": "0.0.1",
		"baseUri": "http://example.org/"
	}
}
```

**Comment by Sanjeevani19** [comment]
Thanks @awanczowski , I was able to reproduce this with both QS and gradle. https://project.marklogic.com/jira/browse/DHFPROD-4903 has been created to track this issue.

**Comment by kkanthet** [comment]
Issue is no longer reproducible, Please re-open if its still an issue  in 5.4.0 release.
