### ISSUE TITLE
[BUG] Encrypted password property added in ext block not found by hubDeploy subtasks

### ISSUE THREAD

**Issue by xmlnovelist** [marklogic/marklogic-data-hub#3896]
*### Welcome Hub enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

Short description of the problem:
When using encrypted passwords as in https://github.com/marklogic-community/ml-gradle/wiki/Encrypting-passwords, gradle hubDeploy fails with missing password error.

What behavior are you expecting?
hubDeploy runs without error using encrypted password

What are the steps to reproduce the issue:
1)Create a 5.2 datahub
2)Go to https://github.com/marklogic-community/ml-gradle/wiki/Encrypting-passwords
3)Edit build.gradle per instructions, adding statements to ext block.
4)Remove password properties from gradle properties files.
5)use gradle addCredentials to encrypt password
6)Run hubDeploy
7)Several hubDeploy subtasks report no password

#### Tech details

Which Operating System are you using?
MacOS

Which version of MarkLogic are you using?

10.0-3
Which version of the Data Hub are you using?
5.2

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar marklogic-datahub-<version>.war  --debug  > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -debug > myoutput.txt`

**Comment by xmlnovelist** [comment]
This also effects mlcp tasks. I want it to work with mlcp tasks so I can do gradle automation on ingestion servers.

**Comment by srinathgit** [comment]
Thanks for filing the issue. https://project.marklogic.com/jira/browse/DHFPROD-4911 has been created to track it internally

**Comment by rjrudin** [comment]
Doing duplicate data entry here - looks like just one more line is needed in that ext block:

    hubConfig.mlPassword = credentials.myPassword

Closing this, DHFPROD-4911 will be used for any further conversation.

**Comment by dmcassel** [comment]
@rjrudin I've encountered this error, too. I added the following lines to my build.gradle ext block, but no change 

```
  hubConfig.mlUsername = credentials["myProject/${environmentName}/adminUsername"]
  hubConfig.mlPassword = credentials["myProject/${environmentName}/adminPassword"]
```

I can't see the JIRA issue where this is being tracked internally. Any updates on this? (It would be helpful if updates were public.) 

I'm using DHS; DHF 5.1.0.

**Comment by rjrudin** [comment]
@dmcassel  This was the full config I used for testing:

```
ext {
    // Configure properties based on encrypted credentials
    mlManageConfig.password = credentials.myPassword
    mlManageConfig.securityPassword = credentials.myPassword // only needed if setting mlSecurityUsername
    mlAdminConfig.password = credentials.myPassword
    mlAppConfig.restAdminPassword = credentials.myPassword
    mlAppConfig.appServicesPassword = credentials.myPassword

    // Re-initialize the connections to the Admin and Manage servers
    mlManageClient.manageConfig = mlManageConfig
    mlAdminManager.adminConfig = mlAdminConfig

    // This sets the password that DH uses for loading modules, loading user artifacts, etc. 
    hubConfig.mlPassword = credentials.myPassword
}
```

That was only tested on 5.2.0, I don't know if it works on 5.1.x.

**Comment by dmcassel** [comment]
@rjrudin That's pretty much what I have, except specifying the usernames too. If the credentials manager just doesn't work with DHF 5.1.0, it would be good to get that documented somewhere.

**Comment by grtjn** [comment]
I don't have access to DHFPROJ, so posting this here. This seems to work for DHF 5.5, and probably for older as well:

https://gist.github.com/grtjn/00541dc76b941342c41f96fe810dd104
