### ISSUE TITLE
Mapping fails for JSON Object

### ISSUE THREAD

**Issue by chenfiona** [marklogic/marklogic-data-hub#3904]
*### Welcome Hub enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

Short description of the problem:
1) Account entity is updated as:  
```
        "accountBalance": {
          "datatype" : "string",
          "collation" : "http://marklogic.com/collation/codepoint"
        }
```
2) accountBalance module is updated:
```
let accountBalance = {marketDate, sumValue};
instance.Account["accountBalance"] = accountBalance;
```
3)  Account TDE returns null for below object: 

> accountBalance

4) I would expect TDE reflect Object string:
`{ "marketDate": "2020-01-18", "sumValue": 21318784.35926 }`

#### Tech details
Which version of MarkLogic are you using?
10.0-3
Which version of the Data Hub are you using?
V5.2.0

**Comment by bsrikan** [comment]
@chenfiona can you pls clarify if the issue is about mapping step failing to run or TDE returning null? If its both, can you pls share the stacktrace of the error you get when running the mapping step. Thanks!

**Comment by chenfiona** [comment]
The issue is TDE.  
I need you to provide 2 lines of syntax regarding Object | Array mapping in DH V5.2.0. 
The syntax is sth like below:
```
    "accountBalance" : {
      "sourcedFrom" : "accountBalance/object-node()"
    }
```
I am not clear which ML XPath expression works. But outside ML, my Jsonpath/XPath always works.

**Comment by bsrikan** [comment]
For an entity property of type array
```
"email": {
          "datatype": "array",
          "items": {
            "datatype": "string",
            "collation": "http://marklogic.com/collation/codepoint"
          }
        }
```
the mapping would look like 
```
"email": {
"sourcedFrom": "email"
}
```

For an object its the same as well
```
"accountBalance": {
"sourcedFrom": "accountBalance"
}
``` 

Find screenshot below from QS where a string property "name" is being mapped to Address object:
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/16124406/81024485-6a364900-8e28-11ea-9197-879f1dedd34b.png">

Find screenshot from QConsole for a sql query:
<img width="1468" alt="image" src="https://user-images.githubusercontent.com/16124406/81025051-3a884080-8e2a-11ea-9379-5a102e0c2f85.png">

**Comment by chenfiona** [comment]
Are you suggesting that "accountBalance" needs be mapped **after** the custom step is ran?  The mapping@Account is before this custom step which has a dependency on the Holding mastering.

**Comment by chenfiona** [comment]
@bsrikan:  Can you double check if the Entity looks right ? It is Object. Will `string` work?
` "accountBalance": {`
         ` "datatype" : "string",`
         ` "collation" : "http://marklogic.com/collation/codepoint"`
       ` }`

**Comment by chenfiona** [comment]
If the Entity model is changed to below:  
`        "accountBalance" : {
          "datatype" : "array",
          "items" : {
            "datatype" : "string",
            "collation" : "http://marklogic.com/collation/codepoint"
          }`

I simply can't see `accountBalance` after the mapping:
`[SQL] SQL-NOCOLUMN: Column not found: accountBalance`
`Stack Trace`
`At line 2 column 7:`
`In xdmp:sql("-- query&#10;select accountBalance from Account.Account;", ())`
`1. -- query`
`2. select accountBalance from Account.Account;`

**Comment by bsrikan** [comment]
Are you using admin user. admin user cant use the TDE’s written by flow-developer/data-hub-developer due to the permissions set on them.

**Comment by chenfiona** [comment]
Myself and admin already have all the listed roles. If it is permission issue, I simply can't see other properties. 
How do you explain below returns perfect result ?
`select accountNumber from Account.Account;`
That particular property issue only happens when it is changed to 
`{ "datatype" : "array", "items" : { "datatype" : "string", "collation" : "http://marklogic.com/collation/codepoint" }`. 
If it is `string`, TDE returns `null`. 

Can you shed some light on this?

**Comment by chenfiona** [comment]
FYI, my previous solution is to, manually, transform the array and get the TDE work.  This may sound silly. But that always works for me.

**Comment by bsrikan** [comment]
With the custom step run after mapping, do you see the entity instance in the FINAL database to be as expected, ie it includes `"accountBalance":"{ \"marketDate\": \"2020-01-18\", \"sumValue\": 21318784.35926 }"`

**Comment by chenfiona** [comment]
It is:
`"accountBalance": {
 "marketDate": "2020-01-18", 
 "sumValue": 21318784.35926 
}`

**Comment by bsrikan** [comment]
Can you manually update it to be string serialized, since the property has datatype string.

**Comment by chenfiona** [comment]
I can transform any Object/array to get TDE going.
I merely suggest that TDE module definition should be looked into. A simple object property shouldn't be manually transformed for mapping, really.   
I appreciate your patience!
