### ISSUE TITLE
Ingest csv; outputFormat: xml -> xmlns=""

### ISSUE THREAD

**Issue by chenfiona** [marklogic/marklogic-data-hub#3906]
**Is your feature request related to a problem? Please describe.**
When data is ingested from csv and output is xml, the namespace becomes:
****************
`<envelope xmlns="http://marklogic.com/entity-services">`
  `<headers>`
    `<sources xmlns="">`
***************
`  <instance>`
      `<Abbr xmlns="">MA</Abbr>`
      `<City xmlns="">Quincy</City>`

**What is the user-facing scenario that prompted this gap in functionality?**
`xmlns=""` doesn't look right.  If I need to add attributes to elements, it becomes difficult.

**Describe the solution you'd like**
1) If `xmlns` must exist, `baseUri` in the entity.json should be the namespace not the `http://marklogic.com/entity-services` 
2) Since the original CSV doesn't contain namespace, `xmln`  is, preferably,  not presented in the document

**Describe alternatives you've considered**

**Comment by bsrikan** [comment]
Thanks for filing the bug @chenfiona . This is an issue with any document written as xml when they dont have namespace. I agree that adding an empty namespace is not a good idea. 
Filed a JIRA(https://project.marklogic.com/jira/browse/DHFPROD-4938) to track and fix internally.

**Comment by bsrikan** [comment]
@chenfiona `xmlns=""` is necessary to indicate that the elements don't belong to namespace of the root element and hence this is expected. We will be closing the JIRA ticket.

**Comment by chenfiona** [comment]
If I use mlcp outside of DH, I can specify below 2 options so as to create a root element with my custom namespace.  It means that DH can certainly allow user to custom a root element and corresponding namespace during the Ingestion. 

**`-delimited_root_name`**
**`-namespace`**

**Comment by kkanthet** [comment]
Issue is no longer reproducible, Please re-open if its still an issue  in 5.4.0 release.
