### ISSUE TITLE
Need to run many harmonization flows and do many writes from one task id

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#391]
#### The issue

Sometimes you want to take many actions based on one input. E.g. the collector may return a customerID (rather than a URI) and the desired flow would find all customer documents, harmonize them all, then write many harmonized documents + update a summary document.

#### Tech details

This may be somehow implemented with a splitter and joiner plugin. The splitter may convert the single task string (e.g. a customerID in this example) to a number of strings or URIs which can all run through a harmonization flow.

Each harmonization flow may then write their own data via a writer plugin. Alternatively or in addition, a "joiner" plugin may gather all results from all the split flows, and do a single operation.

### Caveats
It is not at all clear that this is a common use case, or easy to implement. Comments from others below will be useful to clarify how often this is needed, and for what use cases.

**Comment by mikrovvelle** [comment]
This was very common use case in projects I've worked on. We 'split' the collector output in the content module and looped through that output in subsequent modules, as described in #1892. It was so easy I thought it was the intended way to do it, and didn't realize this was an open design consideration.

**Comment by aebadirad** [comment]
Data Hub 5 now supports multiple output and to batch feed collector results into a step.
