### ISSUE TITLE
[BUG] Empty String or missing Date shows "undefined, undefined" on mapping screen

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#3953]
Short description of the problem:
See title

What behavior are you expecting?
At a minimum, list "undefined" once. Ideally, indicate that the field is being removed because it is an empty string in a more intelligible way. ("empty/removed" may be good. or "no value")

What are the steps to reproduce the issue:
1) map any record with an empty string in the mapper
2) hit the "test" button in the mapper

Which version of MarkLogic are you using?
9.0-11

Which version of the Data Hub are you using?
5.2.1

Is this a QuickStart UI bug? If so, which browser are you using?
Yes. Chrome.

This is a broader case for existing bug https://github.com/marklogic/marklogic-data-hub/issues/3553

**Comment by rahulvudutala** [comment]
Assigning it to @sbayatpur

**Comment by rjrudin** [comment]
Tracking this via DHFPROD-7012
