### ISSUE TITLE
/ml-config/ not deploying to DHS

### ISSUE THREAD

**Issue by rodgersandrew** [marklogic/marklogic-data-hub#3959]
*### Welcome Hub enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

When:
- Creating a configuration for temporal collections in src/main/ml-config/temporal or src/main/ml-config/databases/data-hub-FINAL/temporal/...
- Creating indexes in database-fields configuration...

The corresponding gradle tasks appear to "complete" successfully but none of the configuration is actually deployed to DHS. No errors are returned, mlDeployTemporal shows as successfully sending PUT request to manage endpoint for the temporal collection.

What are the steps to reproduce the issue:
1) Add temporal configuration from https://github.com/marklogic/marklogic-data-hub/tree/master/examples/dhs-example/src/main/ml-config/databases/data-hub-FINAL to local project
2) Attempt to run either hubDeploy or mlDeployTemporal against a DHS instance
3) Run temporal.axes(), temporal.collections() against the data-hub-FINAL database to see nothing is returned or see that no axes/collection configurations exist in data-hub-FINAL-SCHEMAS

#### Tech details

Which Operating System are you using?
This was through a VM during a training sessions for DHS

Which version of MarkLogic are you using?
Unsure how ML versioning works with DHS instances

Which version of the Data Hub are you using?
5.2.0

**Comment by rjrudin** [comment]
Check the schemas database to see if the temporal config is present in there. I'm wondering too if the user you're using to verify the config doesn't have permission to see them. 

If something went wrong during deployment, I'm 99.9% sure that the Manage API would have thrown an error - it's very particular about validating input (which is good). So my hunch is the config is there.

**Comment by rodgersandrew** [comment]
I had checked it and nothing was there, the user I am using has all available data-hub permissions for DHS.

That being said, I pointed the flow to the collection from my config and the temporal collections do exist so it must be working as expected.

I will have to figure out which permissions I am missing to not be able to view temporal config docs.

Thanks!

**Comment by rjrudin** [comment]
I can't recall right now, but I am guessing it's a matter of the fact that we use ML granular privileges to allow the user to deploy these resources, but then reading them likely requires a role that your user does not have.
