### ISSUE TITLE
[BUG] mlLoadModules failing when enabling SSL

### ISSUE THREAD

**Issue by mikeburl** [marklogic/marklogic-data-hub#3989]
#### The issue

Short description of the problem:
After enabling SSL on the DHF application servers, we are no longer able to run mlLoadModules.  We have verified that SSL is working as expected by hitting the application servers via curl and were also able to insert an example document via the custom task detailed here: https://github.com/marklogic-community/ml-gradle/wiki/Debugging-module-loading

We also sanity checked ourselves by again disabling SSL and re-running mlLoadModules and found that it worked again.  

What behavior are you expecting?
We are able to enable SSL on the application server, configure the gradle.properties to specify that connections are to happen via SSL, and mlLoadModules loads modules as expected.

What are the steps to reproduce the issue:
1) Install DHF using all default configurations
2) Enable SSL on all application servers, admin, manage, app-services, and the DHF app servers
3) Configure gradle to use SSL on all application servers
4) Run mlLoadModules

#### Tech details

Which Operating System are you using?
Client: Windows 10
Server: RHEL 7
Which version of MarkLogic are you using?
10.0-3
Which version of the Data Hub are you using?
5.2.0

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:
[output.txt](https://github.com/marklogic/marklogic-data-hub/files/4669088/output.txt)

[gradle.properties.txt](https://github.com/marklogic/marklogic-data-hub/files/4669096/gradle.properties.txt)
[gradle-tst.properties.txt](https://github.com/marklogic/marklogic-data-hub/files/4669097/gradle-tst.properties.txt)

**Comment by mikeburl** [comment]
Here's the output when we run mlLoadModules -i
[output.txt](https://github.com/marklogic/marklogic-data-hub/files/4669225/output.txt)

**Comment by rjrudin** [comment]
Closing this, as there's a Support ticket instead.
