### ISSUE TITLE
Mapping Need means to select json path with numeric property name

### ISSUE THREAD

**Issue by mchiarelli** [marklogic/marklogic-data-hub#3995]
*### Welcome Hub enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

Need a means to select json property that is numeric value in Mapping. For example the path steps/1/stepDefintionType will failed with error 1 is not a node.

to repo see attached project in DHFPROD-5054 the flow "testStopMapping" see mapping for "name"

#### Tech details

Which Operating System are you using? Mac OS

Which version of MarkLogic are you using?  10.0-4

Which version of the Data Hub are you using? 5.2.1

**Comment by ryanjdew** [comment]
The workaround is to use XPath like `steps/node("1")/stepDefintionType`. Was that XPath produced via the QuickStart UI?

**Comment by bsrikan** [comment]
Here is a link to the example project for this use case:
https://github.com/marklogic/marklogic-data-hub/blob/develop/examples/mapping-example/mappings/application_member-applicationMemberMapping/application_member-applicationMemberMapping-0.mapping.json

**Comment by rjrudin** [comment]
We are planning on enhancing the property selector in the mapping tool in 5.5 to automatically convert e.g. "1" to node("1"). 

In the meantime, please use the above workaround.
