### ISSUE TITLE
Listed Mapping functions are undefined

### ISSUE THREAD

**Issue by mchiarelli** [marklogic/marklogic-data-hub#3996]
*### Welcome Hub enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

Short description of the problem:

What behavior are you expecting?

QS mapping functions list has functions that when tested show error of undefined.

Non-exhaustive list is uparsed-text(), nilled(), doc(), error().

 

To Reproduce:   enter mapping UI select one of the list functions here and test. should see error undefined function. 
#### Tech details

Which Operating System are you using? Mac OS, Windows

Which version of MarkLogic are you using? 10.0-4

Which version of the Data Hub are you using? 5.2.1 

<img width="1457" alt="DHF-unparsed-text-function-undefined" src="https://user-images.githubusercontent.com/29524733/82953987-b0328880-9f60-11ea-80a4-095c8b33844e.png">
<img width="1456" alt="DHF-nilled-function-undefined" src="https://user-images.githubusercontent.com/29524733/82954002-b58fd300-9f60-11ea-81c2-30498da3b5fe.png">
<img width="1442" alt="DHF-error-function-undefined" src="https://user-images.githubusercontent.com/29524733/82954015-bc1e4a80-9f60-11ea-826d-2dd574789427.png">
<img width="1451" alt="DHF-doc-function-undefined" src="https://user-images.githubusercontent.com/29524733/82954028-c2142b80-9f60-11ea-941e-7477b4391e25.png">

**Comment by rahulvudutala** [comment]
@mchiarelli I was able to reproduce the issue. I created an internal Jira ticket to track
https://project.marklogic.com/jira/browse/DHFPROD-5084

**Comment by kkanthet** [comment]
Issue Fixed in 5.4.0 release
