### ISSUE TITLE
[BUG] Smart Mastering REST API Extensions.. 

### ISSUE THREAD

**Issue by bgeorge11** [marklogic/marklogic-data-hub#3998]
1. mlSmNotifications (GET) --> This REST API does not return any notification documents from the Entity collections (sm-<Entity>-notification). Instead, it is looking in legacy collection (mdm-notification) which is not the default value. 

For more details, pls contact biju.george@marklogic.com

**Comment by rahulvudutala** [comment]
@bgeorge11 Thanks for ticket. I have created an internal jira ticket for this issue. https://project.marklogic.com/jira/browse/DHFPROD-5089

**Comment by kkanthet** [comment]
Issue Fixed in 5.4.0 release
