### ISSUE TITLE
[BUG] Smart Mastering - Merge Extension not returning merged document.

### ISSUE THREAD

**Issue by bgeorge11** [marklogic/marklogic-data-hub#4000]
https://docs.marklogic.com/datahub/tools/rest/rest-extensions.html 

POST /v1/resources/mlSmMerge?rs:uri=URI1&rs:uri=URI2&rs:uri=URIn&rs:flowName=YourFlowName&rs:step=1&rs:preview=[true|false] 

rs:preview
If true, no changes are made to the database and a simulated merged record is returned; otherwise, the merged record is saved to the database. Default is false

But preview=true is NOT returning the simulated merged record, instead audit record is returned. Without the merged record being returned, preview cannot be used.

**Comment by bsrikan** [comment]
Ack. Will try to reproduce and get back to you.

**Comment by sbayatpur** [comment]
https://project.marklogic.com/jira/browse/DHFPROD-5160

**Comment by kkanthet** [comment]
Issue Fixed in 5.4.0 release
