### ISSUE TITLE
[BUG] Smart Mastering - Collection incorrect for REST Extensions..

### ISSUE THREAD

**Issue by bgeorge11** [marklogic/marklogic-data-hub#4001]
https://docs.marklogic.com/datahub/tools/rest/rest-extensions.html
 
mlSmHistoryDocument (GET) --> This REST extension is looking into the legacy collections mdm-* and not the new entity level collections. Hence, the API does not return the history document. 

For details of the issue, pls contact biju.george@marklogic.com

**Comment by paxtonhare** [comment]
I just ran into this same issue

**Comment by sbayatpur** [comment]
https://project.marklogic.com/jira/browse/DHFPROD-5159

**Comment by kkanthet** [comment]
Issue Fixed in 5.4.0 release
