### ISSUE TITLE
[BUG] Smart Mastering Merge step fails..

### ISSUE THREAD

**Issue by bgeorge11** [marklogic/marklogic-data-hub#4002]
https://developer.marklogic.com/learn/data-hub-quickstart/#curate-mastering 

When this tutorial is followed, running the entire flow together fails on Merge step with the below error. 
XDMP-DOCNOTFOUND: xdmp.documentDelete("/datahub/5/mastering/match-summary/c8742ac5-28f1-4475-8a9b-d2f83...") -- Document not found in [anonymous], at
Then the Merge step is run independently, there is no error.

**Comment by bsrikan** [comment]
Ack. Will run through the tutorial and let you know.

**Comment by sbayatpur** [comment]
https://project.marklogic.com/jira/browse/DHFPROD-5158

**Comment by kkanthet** [comment]
Issue Fixed in 5.4.0 release
