### ISSUE TITLE
[BUG] Smart Mastering - Match/Merge not deterministic in document count.. 

### ISSUE THREAD

**Issue by bgeorge11** [marklogic/marklogic-data-hub#4003]
Follow this tutorial..
https://developer.marklogic.com/learn/data-hub-quickstart/#curate-mastering 

Everything works fine the first time. Without changing anything (documents or match/merge rules), run the match and merge steps again. The number of documents in sm-<Entity>-mastered collection changes. The audit/provenance documents are having the sm-<Entity>-collection also which is incorrect.

**Comment by bgeorge11** [comment]
Pls contact biju.george@marklogic.com for recreating the issue

**Comment by bsrikan** [comment]
@bgeorge11 this is expected. Can you pls try adjusting the collections of the mapped document considered for mastering, so they are separate than the collections a mastered document would get.

**Comment by bgeorge11** [comment]
Why wouldn’t the default collections would not work ?

**Comment by bsrikan** [comment]
When you rerun the mastering step, if the document already mastered has the collection which mastering step would process again, then the document count might change.

**Comment by bgeorge11** [comment]
That is not what I observe.

1.      Follow this tutorial https://developer.marklogic.com/learn/data-hub-quickstart/#curate-mastering

2.      When the mergeDuplicates step run, there will be 198 documents in the sm-Customer-mastered collection.

3.      Now run findDuplicates and mergeDuplicates again without making any other change.

4.      Check sm-Customer-mastered collection. There are 200 documents.

5.      The additional two documents are NOT any more mastered documents, but two xml documents which are provenance records.

6.      Now, run again findDuplicates and mergeDuplicates. There are 202 documents – This time four xml documents.



Regards
Biju

**Comment by ryanjdew** [comment]
@bsrikan The bug stems from the auditing documents being added to the collection used for the sourceQuery. On the second run, it is trying to find matches for the auditing documents and when it doesn't find matches it is adding those auditing documents to the "sm-<Entity>-mastered" collection. 

I believe it stems from a bug in QuickStart adding the targetEntity as a default collection on teh output of the merge step.

**Comment by sbayatpur** [comment]
https://project.marklogic.com/jira/browse/DHFPROD-5157

**Comment by kkanthet** [comment]
Issue Fixed in 5.4.0 release
