### ISSUE TITLE
[FEATURE] : Support of embedded objects for matching rules in Quick start.

### ISSUE THREAD

**Issue by bgeorge11** [marklogic/marklogic-data-hub#4004]
When configuring the matching options using Quick start, only the root elements in an entity are coming up. It is common to have fields in embedded objects to have match rules. There should be a way to configure them too.. 

Example: If the entity is 
Customer 
    fname
    lname
    email
    address
          line1
          city
          state
          zip

It is not possible to configure the match rules on any of the address fields, but only on fname, lname & email.

**Comment by bsrikan** [comment]
Thanks for the feature request. Nested/Embedded objects arent supported for mastering in Quick Start and it is unlikely in the near future as well. Data Hub Central at some point will include the requested feature.
@sbayatpur pinging you for comments and to correct me if I am wrong.

**Comment by sbayatpur** [comment]
As part of supporting Smart Mastering configuration in Hub Central, we'll be adding support for nested objects. @bgeorge11 Thank you for filing this ticket, as it helps to know there's interest in this

**Comment by rjrudin** [comment]
Closing this, as we're tracking it in HC for 5.5
