### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by lsheth** [marklogic/marklogic-data-hub#4018]
*### Welcome Hub enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

Short description of the problem: 
I am using DHF 5.2.1 and MarkLogic Server 10.4.  DHF 5.2.1 - Smart Mastering - OOTB - REDUCE Match Option is NOT working. Getting “Invalid argument Type” error as attached

What behavior are you expecting? Expecting OOTB Reduce Match option to reduce the weight score if firstName and lastName of matched records are same. Details of Match Step config in attached file

What are the steps to reproduce the issue:
1) Clone the project from MarkLogic BitBucket repo at: https://project.marklogic.com/repo/scm/civs/dc-dhcf-mmis.git
2) Modify the flow to include "Reduce" Match option 
3) Run the Flow - Match Step to reproduce the error

#### Tech details

Which Operating System are you using? MacOS

Which version of MarkLogic are you using? ML 10.4

Which version of the Data Hub are you using? DHF 5.2.1

Is this a QuickStart UI bug? If so, which browser are you using?No, using FireFox

#### The devil is in the details...
[dc-dhcf-Match-Reduce-Error.txt](https://github.com/marklogic/marklogic-data-hub/files/4697652/dc-dhcf-Match-Reduce-Error.txt)

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar marklogic-datahub-<version>.war  --debug  > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -debug > myoutput.txt`

**Comment by bsrikan** [comment]
@lsheth, is the bug reproducible if run via QuickStart and gradle as well?

**Comment by ryanjdew** [comment]
@lsheth I commented on the data-hub slack channel that the error appeared to be in the property definitions, rather than the reduce function. 

Were those match options produced by the UI or were they altered in a manual way?

**Comment by rjrudin** [comment]
Closing due to lack of response. Please reopen if this is still an issue with DHF 5.4.0.
