### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by s3-4v** [marklogic/marklogic-data-hub#4020]
A standard mapping step in a flow finishes with errors in the jobs report; out of ~179K commits, 140 failed with this error:

`XSLT-UNBPRFX: (err:XTSE0280) Prefix fn has no namespace binding`

Error details:

> Error: XSLT-UNBPRFX: (err:XTSE0280) Prefix fn has no namespace binding at main (/data-hub/5/builtins/steps/mapping/entity-services/main.sjs:72:11) at Flow.runMain (/data-hub/5/impl/flow.sjs:485:12) at Flow.runStep (/data-hub/5/impl/flow.sjs:343:58) at Flow.runFlow (/data-hub/5/impl/flow.sjs:211:12) at post (/marklogic.rest.resource/mlRunFlow/assets/resource.sjs:60:25) at callExtension (/MarkLogic/rest-api/lib/extensions-util.sjs:93:30) at applyOnce (/MarkLogic/rest-api/lib/extensions-util.sjs:111:10)

Simply re-running the step resulted in 0 failures. Both times I used the UI. 

But this has happened before, so I wanted to enter it into the tracker and try to determine if anyone has possibly encountered this before--and what the fix might be. The flow has been run multiple times using both the UI and Gradle, with inconsistent results, so I understand it's difficult to reproduce.

This occurs on Windows 10 Pro, build 18363.836, using Data Hub 5.2.1, MarkLogic 10.0-4 on CentOS Linux release 7.7.1908, and Gradle (6.2.2 in the Wrapper; 6.4.1 native).

Thanks.

**Comment by rahulvudutala** [comment]
@s3-4v Can you share your project. I tried reproducing the issue with some data I have. It will be helpful if you can share the flow and input data.

**Comment by rjrudin** [comment]
I have not seen this particular error before. We've seen some issues where the module cache expires and that can cause mapping steps to break. But we'd see a different error if that were the case - e.g. ML would be saying that it cannot find a module, as opposed to a namespace binding. 

One thing to consider is that you should not need "fn:" on your function calls in a mapping expression. 

If you're still experiencing this error, please reopen this ticket with a minimal example of your project that causes the problem.
