### ISSUE TITLE
Screen resolution doesn't let me create a flow

### ISSUE THREAD

**Issue by dmcassel** [marklogic/marklogic-data-hub#405]
#### The issue

Short description of the problem: I can't see the Create button while making a flow

What behavior are you expecting? I'd like to be able to resize or move the window, or be able to hit enter. 

#### Tech details

Which Operating System are you using?

Which version of MarkLogic are you using? 9.0-1.1

Which version of the Data Hub Framework are you using? v2.0.0-alpha.4

Is this a QuickStart UI bug? If so, which browser are you using? Firefox

┆Status: To Do

**Comment by sashamitrovich** [comment]
I've been working with a customer (Credit Suisse Zurich) lately and they run into the same issue (Beta 1). In their view, this is a bug.

**Comment by clockworked247** [comment]
@dmcassel @sashamitrovich Does this issue still exist?  Looking at the latest 3.x version of DHF, the only time when this is an issue is when the height of your screen resolution is less than 442px, which is typically an unsupported screen height (1024px x 768px being the normal min dimensions).

Screen height at 442px height:
![image](https://user-images.githubusercontent.com/1016149/40006409-309993d0-574f-11e8-90b7-87d6462054a7.png)

Screen height at 730px height (just under the standard supported height, seems fine):
![image](https://user-images.githubusercontent.com/1016149/40006551-8adedcce-574f-11e8-820a-23da966e6ad1.png)

**Comment by sashamitrovich** [comment]
I haven’t seen that issue come up again. Thanks.


Mit freundlichen Grüßen / Best Regards,

Saša Mitrović
Principal Sales Engineer
MarkLogic Corporation
Sasha.Mitrovich@marklogic.com
Cell:  +49 173 314 0053
Phone: +49 69 667 787058
www.marklogic.com<http://www.marklogic.com/>
[signature_1517663795]<http://www.marklogic.com/social/>
This e-mail and any accompanying attachments are confidential. The information is intended solely for the use of the individual to whom it is addressed. Any review, disclosure, copying, distribution, or use of this e-mail communication by others is strictly prohibited. If you are not the intended recipient, please notify us immediately by returning this message to the sender and delete all copies. Thank you for your cooperation.

**Comment by dmcassel** [comment]
Old issue, so if you're not seeing it, feel free to close

**Comment by clockworked247** [comment]
Since all appears to be well, I'm closing.
