### ISSUE TITLE
[BUG] stopOnError Flag Overwritten to 'false' by QuickStart

### ISSUE THREAD

**Issue by mikerosiak** [marklogic/marklogic-data-hub#4119]
The stopOnError flag is not exposed in the QuickStart UI.  Changing it manually in the flow.json file works as expected when a flow is run, but if a change is made to the flow in QS, it overwrites this flag with "false".  It should retain the setting that's in the flow file, so that it can be set to "true" permanently.  A customer (Republic Services) is using QS to run flows and does not want a flow to continue if there is an error in any step.

DHF 5.2.2

**Comment by rjrudin** [comment]
Closing due to this being a QS bug, which we will not be releasing in 5.5. HC does not have this bug.
