### ISSUE TITLE
[FEATURE] Create an example of a custom hook updating a URI

### ISSUE THREAD

**Issue by awanczowski** [marklogic/marklogic-data-hub#4121]
**Is your feature request related to a problem? Please describe.**
On occasion there is a need to update the URI of a document. I would like to create an example in the DHF5-custom-hook to illustrate a URI change after mapping content.

**What is the user-facing scenario that prompted this gap in functionality?**
There is a need for deterministic URIs in certain cases. 

**Describe the solution you'd like**
I would like to have an example that updates the content.uri with a URI that the user would like.

**Comment by rjrudin** [comment]
Use a step interceptor in DHF 5.4.0, which is designed exactly for this purpose. A custom hook may or may not be able to update the URI based on the type of step it's applied to.
