### ISSUE TITLE
MLCP options: Output URI Replace is not working as expected

### ISSUE THREAD

**Issue by lsheth** [marklogic/marklogic-data-hub#414]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:
MLCP options: Output URI Replace is not working as expected. I am trying to replace input folder path with null but document gets ingested with URI having the folder path.

What behavior are you expecting? Expecting URI not to have input folder path 

My Input folder path is: C:\ML_DHF_Employee360\input\Salary

MY MLCP - Output URI Replace option is : C:\\ML_DHF_Employee360\\input\\Salary,''
(Please note there are two '\\' with escape sequence)

I get document ingested with URI as: /C:/ML_DHF_Employee360/input/Salary/SalaryTable.csv-0-800
Vs. I am expecting URI to be: /SalaryTable.csv-0-800

#### Tech details

Which Operating System are you using? Windows 7

Which version of MarkLogic are you using? ML9.0-1.1

Which version of the Data Hub Framework are you using? 1.1.2

Is this a QuickStart UI bug? If so, which browser are you using? Yes, Chrome

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by paxtonhare** [comment]
@lsheth are you running inside cygwin?

**Comment by lsheth** [comment]
No. I am running it using quick-start application.

**Comment by damonfeldman** [comment]
To determine if it is related to quick start or the mlcp config, please copy the mlcp command line which is provided on the quick start GUI and run that from the command line to see if it works, and post it here.

**Comment by paxtonhare** [comment]
I found the issue.

**Comment by lsheth** [comment]
Damon/ Paxton,

option from quick-start application generates the command line for MLCP correctly but document URI gets the folder path as prefix which is unexpected. MLCP command which gets generated is pasted below:
mlcp.bat import -mode local -host localhost -port 8019 -username admin -password ***** -input_file_path C:\ML_DHF_Employee360\input\Salary -input_file_type "delimited_text" -output_collections "salary,input" -output_permissions "rest-reader,read,rest-writer,update" -output_uri_replace "C:\\ML_DHF_Employee360\\input\\Salary,''" -document_type "json" -generate_uri true -transform_module "/com.marklogic.hub/mlcp-flow-transform.xqy" -transform_namespace "http://marklogic.com/data-hub/mlcp-flow-transform" -transform_param "entity=Employee,flow=salary,flowType=input"
