### ISSUE TITLE
hubInit should not overwrite gradle wrapper properties

### ISSUE THREAD

**Issue by jkerr5** [marklogic/marklogic-data-hub#4157]
*### Welcome Hub enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

Short description of the problem:

The `hubInit` task overwrites `gradle/wrapper/gradle-wrapper.properties` which may have been configured specifically for the project already.

What behavior are you expecting?

To not overwrite the gradle wrapper configuration if it exists already.

What are the steps to reproduce the issue:
1) Create a new empty project directory
2) Run `gradle wrapper`
3) Edit `gradle/wrapper/gradle-wrapper.properties` and add a comment
4) Add the data hub plugin to `build.gradle`
    ```
    id 'com.marklogic.ml-data-hub' version '5.2.2'
    ```
5) Run `./gradlew hubInit`
6) Observe changes made to `gradle/wrapper/gradle-wrapper.properties` 

#### Tech details

Which Operating System are you using?

macOS

Which version of MarkLogic are you using?

10.0-3

Which version of the Data Hub are you using?

5.2.2

Is this a QuickStart UI bug? If so, which browser are you using?

No

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

```
13:35:21.363 [INFO] [com.marklogic.hub.impl.HubProjectImpl] Getting file: scaffolding/gradle/wrapper/gradle-wrapper.jar
13:35:21.364 [INFO] [com.marklogic.hub.impl.HubProjectImpl] Getting file: scaffolding/gradle/wrapper/gradle-wrapper.properties
```

**Comment by rjrudin** [comment]
Do you think it would be reasonable to do the following:

- hubInit does not touch the existing Gradle wrapper
- hubUpdate does touch an existing Gradle wrapper, changing its version to the DHF version associated with the upgrade

**Comment by jkerr5** [comment]
After some offline discussion, I think I have determined that this issue is not valid. I was trying to force a developer workflow that really didn't make sense. I am ok with `hubInit` setting up the version of gradlew that the data hub wants to use. Developers should use that instead of using `gradle wrapper` to setup the version of gradlew for their project. They of course need to have gradle installed and connectivity to the outside internet to be able to do that.
