### ISSUE TITLE
Expose the ability to pass custom properties via gradle

### ISSUE THREAD

**Issue by kmoralesml** [marklogic/marklogic-data-hub#416]
#### The issue

Short description of the problem:
Expose the ability to pass custom properties via gradle such that flows, harmonize flows, in particular, can avail of the property(ies).

What behavior are you expecting?
When I run
gradle hubRunFlow -PentityName=someEntity -PflowName=harmonize-some-entity -PflowType=harmonize -PpluginFormat=xqy -PdataFormat=xml -PsomeProp=someVal

I expect
someProp to be available to my harmonize plugins.

#### Tech details

Which Operating System are you using? Windows, Linux, etc.

Which version of MarkLogic are you using? 8.0-6

Which version of the Data Hub Framework are you using? 1.1.2

Is this a QuickStart UI bug? If so, which browser are you using? No

**Comment by paxtonhare** [comment]
I'm testing this out right now. One potential issue I see is that there is no great way to differentiate between properties you pass in via the command line and other properties that are already available to gradle. 

Let's say you run this cmd line:
`gradle hubrunflow -PentityName=stuff -PflowName=harmonizeme -PflowType=harmonize -PshowOptions=true -Pstuff=junk -Phi=there`

You would want stuff=junk and hi=there to get passed to your flow.

But, without excluding other properties I end up passing in everything:
```
      mlFinalPort = 8011
      hi = there
      mlAdminPort = 9001
      showOptions = true
      mlTraceDbName = data-hub-TRACING
      mlFinalForestsPerHost = 4
      propertiesPluginEnvironmentNameProperty = environmentName
      mlPassword = admin
      mlTraceForestsPerHost = 1
      mlStagingDbName = data-hub-STAGING
      mlTraceAppserverName = data-hub-TRACING
      mlFinalAppserverName = data-hub-FINAL
      environmentName = local
      mlAppServicesPort = 9000
      mlStagingPort = 8010
      mlJobDbName = data-hub-JOBS
      mlJobPort = 8013
      mlJobForestsPerHost = 1
      mlStagingAppserverName = data-hub-STAGING
      mlSchemasDbName = data-hub-SCHEMAS
      mlTraceAuth = digest
      mlManagePort = 9002
      mlHubUserRole = data-hub-ROLE
      environmentFileDir = .
```

Does this sound reasonable? Or would we want to require some sort of prefix for custom properties?

Maybe something like:
`dhf*`

so

`gradle hubrunflow -PentityName=stuff -PflowName=harmonizeme -PflowType=harmonize -PshowOptions=true -PdhfStuff=junk -PdhfHi=there`

Any opinions on this?

It's easy enough to just pass everything in. Not sure if there is a downside other than a slightly larger payload at launch time.

**Comment by kmoralesml** [comment]
I vote for the prefix approach, that is, -PdhfSomeProp.  

Unsure if folks want a different prefix depending on the target plugin, headers/triples/content/writer/collector though.

**Comment by damonfeldman** [comment]
Is a delimiter acceptable to ml-gradle? if so, maybe use -Pdhf.stuff=junk -Pdhf.hi=there .

**Comment by paxtonhare** [comment]
Ok. I second the delimiter:

`-Pdhf.key=value`

@kmoralesml any key,value pair you provide will be sent to all of the plugins.

**Comment by kmoralesml** [comment]
Awesome.  Thank you for quickly accommodating this request, Paxton.
