### ISSUE TITLE
[BUG] Entity mapping tables missing from Quickstart GUI

### ISSUE THREAD

**Issue by xmlnovelist** [marklogic/marklogic-data-hub#4173]
*### Welcome Hub enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

Short description of the problem:

Version: DHF & Quickstart 5.2.2 << This bug affect low code customers 

When I click on most mapping steps in my flows, I do NOT see the entity mapping table.
I also see the following error most of the time "Unable to find source documents using the specified collection or query." When I know we have ingested the data that matches the query e.g. cts.collectionQuery(["Ingest-Locations"]) and can see the data in the Browse data tab as well as query console.
The mapping step does run successfully even with the GUI problems. 
I'd be happy to get on a call and debug this directly.
#### Tech details

Which Operating System are you using?
MacOS
Which version of MarkLogic are you using?
10.0+

Which version of the Data Hub are you using?
5.2.1, 5.2.2
Is this a QuickStart UI bug? If so, which browser are you using?
various

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar marklogic-datahub-<version>.war  --debug  > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -debug > myoutput.txt`

**Comment by xmlnovelist** [comment]
Initially filed in DHFPROD.

**Comment by wooldridge** [comment]
Corresponding Jira ticket is here: https://project.marklogic.com/jira/browse/DHFPROD-5221

**Comment by xmlnovelist** [comment]
Here are the entities.

[entities.zip](https://github.com/marklogic/marklogic-data-hub/files/4892375/entities.zip)

**Comment by rjrudin** [comment]
Closing due to this being a QS bug, which we will not be releasing in 5.5. HC does not have this bug.
