### ISSUE TITLE
[BUG] Kerberos ticket auth not supported

### ISSUE THREAD

**Issue by crism** [marklogic/marklogic-data-hub#4179]
#### The issue

Short description of the problem:

When a server is set to authenticate with kerberos-ticket, an error is received:
```
> No enum constant
com.marklogic.client.ext.SecurityContextType.KERBEROS-TICKET
```

What behavior are you expecting?

Deployment of a server with Kerberos ticket authentication.

What are the steps to reproduce the issue:
1. Set up a server definition using macros: `"authentication": "%%mlStagingAuth%%"`
1. In the gradle properties, define authentication as Kerberos ticket: `mlStagingAuth=kerberos-ticket`
1. Deploy the server definitions.
1. Receive error above.

#### Tech details

Which Operating System are you using? Windows

Which version of MarkLogic are you using? 9.0-12.2

Which version of the Data Hub are you using? 2.0.4

Is this a QuickStart UI bug? If so, which browser are you using? N/A

#### The devil is in the details...

The problem is that the deployment configuration looks for the gradle-based authorization setting, _e.g._ in `newStagingClient()` in `hubConfigImpl`, and tries to set the security context type based on the literal:
```java
config.setSecurityContextType(SecurityContextType.valueOf(stagingAuthMethod.toUpperCase()));
```
The enum for Kerberos-based security is `KERBEROS`, so `kerberos-ticket` fails to match and gives the error above. Using a value of `kerberos` in the gradle properties is fine. However, using the authentication macro from gradle properties as the value of `authentication` in the JSON server definition then fails, as the management REST API rejects a value of `kerberos`; only `kerberos-ticket` is accepted.

The discrepancy between the JSON token and the enum names seems to only apply to Kerberos. It should be special-cased, or a synonym added. The `SecurityContextType.valueOf(stagingAuthMethod.toUpperCase())` pattern is too ubiquitous to fix it there.

Splitting the method and payload could work too, but DHF ships with built-in `hub-internal-config` settings that use the macros in this way.

**Comment by wooldridge** [comment]
Thanks for filing this, @crism. 

@rjrudin had the following suggestion: We’ll need to add a new property - one property is being used for two different things (client auth and server auth), and turns out that the values for the two can differ. So e.g., instead of just mlStagingAuth, we’ll need something like mlStagingAuth and mlStagingServerAuth. And if the latter is not set, it should default to the former, and we’ll need that for mlJobAuth and mlFinalAuth as well.

**Comment by kkanthet** [comment]
We don't support Kerberos auth yet. Will open a ticket when we choose to.
