### ISSUE TITLE
DHF 5.2.2: Flow does not work

### ISSUE THREAD

**Issue by ls2013** [marklogic/marklogic-data-hub#4180]
![BudgetFlowMissing2](https://user-images.githubusercontent.com/5590907/86398166-2bc7d980-bc73-11ea-935b-40ac0db843b8.png)

**Comment by akshaysonvane** [comment]
This generally means that the flow is not deployed to the server. Try redeploying flows.
Using QS: https://docs.marklogic.com/datahub/flows/redeploy-flow-using-quickstart.html
Using Gradle: https://docs.marklogic.com/datahub/flows/redeploy-flow-using-gradle.html

**Comment by rjrudin** [comment]
Closing based on above recommendation and lack of response
