### ISSUE TITLE
Harmonization interface on top of staging?

### ISSUE THREAD

**Issue by tzejohn** [marklogic/marklogic-data-hub#422]
#### The issue

This is more of a usage question. I am looking to build an interface to facilitate the creation of the harmonization rules. i.e. we ingest into staging a bunch of records from multiple systems, where each system has different names for the same fields, and possibly varying formats of the same values. Then I create a UI which operates on staging to allow users to inspect the data, and identify which fields to move to headers, and how to map those values consistently. This will generate the harmonize plugins behind the scenes.

To facilitate this I was looking to move content to specific URI hierarchies based on ingest values. But this does not seem to be something that is meant for the ingest plugins. Could this be an instance where I have two different final databases? The first harmonize puts everything into the proper hierarchy and does other things to facilitate the interactive mapping, which then generates harmonize rules into a final final db.

On a side note what is a good use for the ingest plugins. In all examples I have seen so far, they don't really do anything, and most processing is in the harmonization flows.

#### Tech details
**Which version of MarkLogic are you using?**
8, moving to 9 when AWS image is ready.

**Which version of the Data Hub Framework are you using?**
Latest 1.*

**Comment by paxtonhare** [comment]
@tzejohn 2 harmonize flows sounds legit here. You would run the 1st one with sourceDb=staging and destDB=staging.

Then run the 2nd flow as normal.

A good use of the ingest plugins is to put provenance data into the envelope. Where did this data come from. what time was it loaded, etc.
