### ISSUE TITLE
[BUG] turning on advanced stemmed-searches breaks step execution for that database

### ISSUE THREAD

**Issue by mikrovvelle** [marklogic/marklogic-data-hub#4226]
#### The issue

If you set `"stemmed-searches": "advanced"` for the Staging or Final database, you will no longer be able to run flows with that database as a source. The step lookup fails, and DHF thinks the flow is missing even when it's present in the DB.

This is caused by the `cts.search` call in `getStepByNameAndType()`, in `/data-hub/5/impl/step.sjs`. It uses a `cts.jsonPropertyValueQuery()` to look up the step by its name and type listed in the JSON properties.

Around line 86 of `step.sjs` (split across lines for readability):

```js
let query = [cts.collectionQuery('http://marklogic.com/data-hub/step-definition'),
  cts.jsonPropertyValueQuery('name', name, 'case-insensitive'),
  cts.jsonPropertyValueQuery('type', type, 'case-insensitive')];
```

For the search to work (IFF advanced stemmed-searches are enabled), the options in those `jsonPropertyValueQuery`s needs to be set to `['case-insensitive', 'unstemmed']`.

#### What behavior are you expecting?

I would expect flows to still work even if I turned on advanced stemmed-searches.

#### What are the steps to reproduce the issue:

1. DHF project, with one or both of the content databases using 'advanced' stemmed-searches.
2. Define a flow and a custom step for it. Call it 'dummyStep'
3. Try to run that flow, in Gradle or from QS

In the QS logs or Gradle output, you'll see a message:

```
Logging HTTP response body to assist with debugging: {"errorResponse":{"statusCode":404, "status":"Not Found", "messageCode":"RESTAPI-SRVEXERR", "message":"A step with name \"dummyStep\" and type of \"CUSTOM\" was not found"}}
```

#### Tech details

- OS: CentOS in Docker and macOS
- ML version 10.0-4.2
- DH version 5.1.0 through 5.2.3, at least

#### Is this a QuickStart UI bug? If so, which browser are you using?

It's not specific to QuickStart

#### The devil is in the details...

I agree

**Comment by rjrudin** [comment]
Can you look at https://bugtrack.marklogic.com/53532 and determine if that's the cause here? 

@paxtonhare Any thoughts here - does this seem like the same ML issue that resulted in 53532?

**Comment by paxtonhare** [comment]
@rjrudin it's the same bug. DHF could issue a fix by adding unstemmed to the cts:search that gets the flows

**Comment by rjrudin** [comment]
This was addressed via a fix in ML - bug 54003. 

We then added a test to DHF to verify that if a flow can be run when advanced stemming is enabled - https://github.com/marklogic/marklogic-data-hub/pull/4589 . 

Note that the bugtrack ticket has instructions on how to apply the fix:

"The fix for the bug can be enabled through the trace event "Reindex JSON language property”.
Note: the trace event does not trigger a reindex. It applies the fix next time there is a reindex."
