### ISSUE TITLE
[BUG] Remove logback.xml from the marklogic-data-hub jar as it conflicts with the logback configuration in the application that uses this jar.

### ISSUE THREAD

**Issue by derms** [marklogic/marklogic-data-hub#4237]
#### The issue

Remove logback.xml from the marklogic-data-hub jar as it conflicts with the logback configuration in the application that uses this jar.

#### Tech details

Which version of the Data Hub are you using? 5.2.1

**Comment by akshaysonvane** [comment]
Thanks for filing this @derms. 
Here's the associated Jira link: https://project.marklogic.com/jira/browse/DHFPROD-5516

**Comment by kkanthet** [comment]
Issue Fixed in 5.4.0 release
