### ISSUE TITLE
Should there be a special Job status for when the collector returns 0 results?

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#425]
Right now, by virtue of a quasi-bug, the status for when a collector returns [] is FAILED.

Is this correct? Should the status be something else?

I can see it causing some confusion to have to try and figure out that the collector returned 0 results. Might be nice to somehow flag that in the jobs page of QuickStart.

@damonfeldman @jmakeig looking for feedback.

**Comment by damonfeldman** [comment]
I think it will sometimes be wanted or needed, where query conditions from options (or squirreled away in the DB) don't match any docs. E.g. a job to harmonize the docs in the last 5 minutes may often return zero items.

Agreed that it is nice to see this easily - perhaps via a job size in the jobs page. Job metadata should include things like the size, then how to show a job has 0 items becomes a GUI issue.

**Comment by grechaw** [comment]
Would you know by any chance whether this has changed in recent versions, @paxtonhare   I'll make a story out of this issue too if it should be addressed.

**Comment by popzip** [comment]
bump, any thoughts from the watchers?

**Comment by popzip** [comment]
assigning to Shannon to add as acceptance criteria for DH5.0 - we should have defined behavior (i don't have specific requirements for what behavior) when scope results in 0.

**Comment by aebadirad** [comment]
Data hub 5 now results in reporting back that it did not attempt a batch or operate on any documents but does not 'fail'. We can discuss adding a visual indicator or support for throwing an alert to a user that nothing was obtained in another RFE if that's desired.
