### ISSUE TITLE
[BUG] The java collector implementations don't pick up system properties (e.g. http.proxyHost)

### ISSUE THREAD

**Issue by derms** [marklogic/marklogic-data-hub#4252]
#### The issue

The com.marklogic.hub.collector.impl.CollectorImpl and com.marklogic.hub.legacy.collector.impl.LegacyCollectorImpl do not support the use of system properties (e.g. http.proxyHost). The standard DatabaseClient does. This has caused issues when using MarkLogic with the DHF through a proxy.

The solution is to call useSystemProperties() prior to calling build() on the httpClientBuilder

e.g.

`httpClientBuilder.useSystemProperties().build()`

instead of

`httpClientBuilder.build()`

#### Tech details

Which version of the Data Hub are you using? 5.2.x

**Comment by rjrudin** [comment]
In 5.3.0, CollectorImpl now uses a DatabaseClient. We did not modify LegacyCollectorImpl; perhaps we should?

@jmakeig Thoughts on this? I don't think we want to address them in any fashion other than replacing usage of RestTemplate with DatabaseClient. Just a matter if we want to modify LegacyCollectorImpl too.

**Comment by rjrudin** [comment]
@derms DHF 5.4.0 is using a DatabaseClient now, and thus this should work fine now. 

If you have a need for LegacyCollectorImpl to be fixed as well, please open a JIRA ticket for it internally.
