### ISSUE TITLE
[BUG] makeEnvelope breaks on upgrade to DH 5.2.3

### ISSUE THREAD

**Issue by eaolson** [marklogic/marklogic-data-hub#4322]
I have a harmonization procedure that runs fine on DH 5.0.2, but breaks in my development VM running 5.2.3. The problem centers around makeEnvelope() and what form the parameters are in. There is so little documentation around this function, I can't tell what the parameters are _supposed_ to be, so I can't tell if this is an intended change or not.

This snippet works as expected in DH 5.0.2:

```
'use strict';
const DataHub = require("/data-hub/5/datahub.sjs");
const datahub = new DataHub();
let instance = fn.head(xdmp.unquote('<html xmlns="http://www.w3.org/1999/xhtml"><head></head><body><p>Apple</p></body></html>')).root;
let headers = fn.head(xdmp.unquote('<headers xmlns="http://marklogic.com/entity-services"><foo>bar</foo></headers>')).root;
let triples = {};
let envelope = datahub.flow.flowUtils.makeEnvelope(instance, headers.xpath("/*").toArray(), triples, datahub.flow.consts.XML);
envelope;
```

In DH 5.2.3, this raises "XDMP-INVALIDTRIPLEMAP: sem.triple() -- The JavaScript object or map:map does not represent a valid triple." If I change that to `let triples = null;`, the error goes away (I always thought that empty object was odd and this project isn't using triples anyway). But then the headers in the resulting envelope are empty. I would have expected there to be a `<foo>` element.

```
<envelope xmlns="http://marklogic.com/entity-services">
  <headers>
  </headers>
  [...]
```

Remove the `toArray()` from the headers and it works as expected.

**Comment by xnikhil08** [comment]
Thanks @eaolson for filing this. 
We are looking into it and will get back to you if we need more information.

**Comment by xnikhil08** [comment]
@eaolson - Here's the associated JIRA ticket.
https://project.marklogic.com/jira/browse/DHFPROD-5667

**Comment by srinathgit** [comment]
The changes are intended . The instance and headers should be objects and triples should be an array. The following will work correctly

```
'use strict';
const DataHub = require("/data-hub/5/datahub.sjs");
const datahub = new DataHub();
let instance = fn.head(xdmp.unquote('<html xmlns="http://www.w3.org/1999/xhtml"><head></head><body><p>Apple</p></body></html>')).root;
let headers = fn.head(xdmp.unquote('<headers xmlns="http://marklogic.com/entity-services"><foo>bar</foo></headers>')).root;
let triples = [];
let envelope = datahub.flow.flowUtils.makeEnvelope(instance, headers.xpath("/*"), triples, datahub.flow.consts.XML);
envelope;
```

**Comment by rjrudin** [comment]
This is being addressed via DHFPROD-7114, where makeEnvelope is being made a public API in the new /data-hub/public/flow/flow-api.sjs module. This includes docs to clearly define the inputs and outputs as shown below:

```
/**
 * Returns an envelope based on the given arguments.
 * 
 * @param {object} instance the data to add to the "instance" section of the envelope
 * @param {object} headers the data to add to the "headers" section of the envelope
 * @param {array} triples the data to add to the "triples" section of the envelope
 * @param {string} outputFormat the format of the returned enveloped; either "json" or "xml"
 * @returns {object} the envelope object
 */
function makeEnvelope(instance, headers, triples, outputFormat = "json") {
  ...
}
```
