### ISSUE TITLE
Smart Mastering documentation  Improvement 

### ISSUE THREAD

**Issue by iowusu** [marklogic/marklogic-data-hub#4398]
1. The maximum for weight is 64 for any single field for matching in SMT. Can we document this or have Quickstart error out if a user put a value higher that 64? Or more explanation on how weight higher that 64 affect SMT. 

2. I observed that the info session for an entity is needed for SMT. Can this also be documented. 
"info": {
        "title": "member",
        "version": "0.0.1",
        "baseUri": "http://org./member/"
    }

**Comment by ryanjdew** [comment]
There is no longer a max value of 64 as the scoring is no longer dependent on cts:score.

The current expectation is that mastering in the Data Hub is working with entity instances that have that document structure.
