### ISSUE TITLE
[BUG] Documentation needed for Smart Mastering custom merge functions

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#4408]
docs.marklogic.com is missing info on the function signature and inputs for a custom merge function. The information can be found here on github:

https://marklogic-community.github.io/smart-mastering-core/docs/custom-merge-algorithms/

Assuming that is still up to date, because it is a somewhat older page, it should be incorporated into docs.marklogic.com as well.

**Comment by damonfeldman** [comment]
Note the input structure is somwhat complex, with two levels of sub-objects. From the github.io page:

"The propertyName is simply the name of the JSON property that holds the instance property being merged. The properties parameter is a sequence of JavaScript objects that provide information about property values from the source documents, along with lineage information. Each object has three keys: sources, values, and name. The value for sources is itself an object, with keys name (an identifier) extracted from the source; dateTime (an xs:dateTime) extracted from the source, if available; and documentUri (identifying this particular source document). The values key connects to the property value or values from this particular source document. The name key is the name of the property value.

The propertySpec parameter is the JSON obejct from the merging properties that corresponds to the property for which the algorithm is being used."

**Comment by rjrudin** [comment]
We're tracking this internally for 5.5 mastering improvements; we're looking to get detailed docs in place for every match and merge feature.
