### ISSUE TITLE
Inconsistant step hook behavior. Content objects are in string format (not object) when hook is in custom step [BUG] 

### ISSUE THREAD

**Issue by mikeberry** [marklogic/marklogic-data-hub#4530]
#### The issue

Short description of the problem:
When adding a hook to a custom step the content objects are Strings. I get the content objects by iterating over the content like so:
```
for (const contentObject of content) {
  const newContentObject= contentObject.value;
  ....
```
If I afterwards try:
`const instance = newContentObject.envelope.instance`
I get the error message: "cannot read instance of undefined"

However if I try:
`const instance = JSON.parse(newContentObject).envelope.instance`
It works

What behavior are you expecting?
I would expect the input to the hook to be the same for all step types.

What are the steps to reproduce the issue:
1) Create a new flow
2) Ingest some data
3) Create a custom step with some function (before or after)
4) Add a hook to this custom step
5) In the hook add the following code
```
for (const contentObject of content) {
  const newContentObject= contentObject.value;
  const instance = newContentObject.envelope.instance;
}
```

#### Tech details

Which Operating System are you using?
Centos 7
Which version of MarkLogic are you using?
10
Which version of the Data Hub are you using?
5.2.3
Is this a QuickStart UI bug? If so, which browser are you using?
Firefox 68.10.0esr (64-bit)

**Comment by rjrudin** [comment]
@mikeberry Apologize for the delay here. The dhf5-custom-hook example project shows a custom hook being used on an ingestion step. In that context, the ingestion step is being invoked by a REST transform, and "contentObject.value" is an object. 

But in a non-ingestion step, "content.value" is a document node, and thus "toObject()" must be called on contentObject.value first.

I don't believe we can make content.value the same thing for all steps, as at this point for DHF 5.x, that would be a breaking change, particularly for users with custom steps. 

I think we instead need to update the docs for a custom hook and also include a note in the example project of when to use "toObject()" and when not to use it.

**Comment by rjrudin** [comment]
Tracking internally via DHFPROD-7017
