### ISSUE TITLE
DHS Azure <-> On-prem Cloud

### ISSUE THREAD

**Issue by chenfiona** [marklogic/marklogic-data-hub#4704]
**What is the user-facing scenario that prompted this gap in functionality?**
Streamline existing MarkLogic data transformation@On-prem cloud.

**Describe the solution you'd like**
We have On-prem cloud MarkLogic Java framework. 
I need to understand if the DHS@Azure can interact and integrate with On-prem Cloud smoothly.
If such migration happens, what is the technical requirements?

**Comment by rjrudin** [comment]
@chenfiona Apologize for the delay in response here - for DHS on Azure questions, please see https://docs.marklogic.com/cloudservices/azure/ . That includes a link for contacting support.
