### ISSUE TITLE
[BUG] Merge step appears not to merge

### ISSUE THREAD

**Issue by mikrovvelle** [marklogic/marklogic-data-hub#4709]
#### Merge step appears not to merge

Despite a merge step successfully identifying lots of matches, output from a (mapping) -> (match) -> (merge) flow results in the same data as if matching and merging had been skipped.

The mapper outputs about 400k documents prior to matching. The matcher identifies about 3k sets of matches, with about ~100 URIs each. I would expect the merger to output the same number ~3k of merged docs.

This could have something to do with the target entity having a nested entity.

What are the steps to reproduce the issue:
1. Create an entity with a nested entity, and an ID one of the fields. Ingest some source data for it.
2. Create a three-step harmonization flow:
    1. Mapping some source data into the entity
    2. Matching based on an Exact match for the ID field Weight 20, Match Threshold 5
    3. Merging with no options, or configure each property to merge with "Max Values" at 1. (It doesn't seem to matter how this is configured) 
4. Run the flow

#### Tech details

> Which Operating System are you using?

ML Docker image, macOS as Docker host

> Which version of MarkLogic are you using?

10.0-5

> Which version of the Data Hub are you using?

5.2.4

> Is this a QuickStart UI bug? If so, which browser are you using?

#### The devil is in the details...

relevant [config-files](https://github.com/marklogic/marklogic-data-hub/files/5367659/config-files.zip) including flow definition, mapping and entity definition.

[harmonization-debug-20201012.txt](https://github.com/marklogic/marklogic-data-hub/files/5367672/harmonization-debug-20201012.txt) cut off early, after the bug was already manifest.

**Comment by ryanjdew** [comment]
This appears to be an issue with JSON queries and encoding entity and property names that have underscores. This issue is fixed for the 5.3 release. The internal ticket is https://project.marklogic.com/jira/browse/DHFPROD-5700.

**Comment by kkanthet** [comment]
Issue Fixed in 5.4.0 release
