### ISSUE TITLE
Consider making a public xquery interface for running flows that doesn’t change

### ISSUE THREAD

**Issue by luisjmart** [marklogic/marklogic-data-hub#471]
There are scenarios where is needed to invoke flows from xquery code like triggers and other functions. These functions are in the flow-lib.xqy.

Separating the functions to get and run flows into a public xquery interface, from other more lower lever functions should improve maintainability.

**Comment by aebadirad** [comment]
Due to age of the ticket and the shift away from the older style of flows, closing issue.
