### ISSUE TITLE
[FEATURE] Show URI count and progress of flow on command line

### ISSUE THREAD

**Issue by mikeburl** [marklogic/marklogic-data-hub#4733]
**Is your feature request related to a problem? Please describe.**
When running a flow it would be nice if a message was printed telling us how many URIs were collected by the collector.  This would be a small sanity check that would allow the user to know for sure that their collector is running as expected, and could also be an early indicator that something is wrong if someone misconfigured something.  

Additionally it would be nice if a message was printed occasionally showing how many documents have been processed so far.  At the moment the user has to go into qconsole or find some other means of manually observing the progress of the flow, rather than having the information presented to them.  I imagine this would include something like: timestamp : # of documents processed / total # of documents in flow : percentage complete : estimated time remaining

**What is the user-facing scenario that prompted this gap in functionality?**
A small error in boolean logic in the collector resulted in a much larger group of documents being grabbed than intended.  This error wasn't detected until over 14 hours later when the flow finally completed- and we saw the end state of the data.  If a message had shown us the number of URIs that were being processed at the beginning, we would have realized something was wrong much more quickly.

**Describe the solution you'd like**
After the collector finishes processing, print a message detailing how many documents are going to be processed.

While processing, occasionally print a message detailing the progress of the flow.

**Describe alternatives you've considered**
It's possible to manually go into qconsole and build an estimate over a query which searches for documents that have been processed by your flow.  It's possible but inconvenient.

**Comment by rjrudin** [comment]
Good suggestion; tracking internally via DHFPROD-7014. Will add info logging for counts of items and batches, and debug logging for each individual batch.
