### ISSUE TITLE
Consider Separating QuickStart releases from DHF releases

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#483]
Right now the Quickstart releases are in sync with DHF releases. There are a few disadvantages to this:

* People perceive that the code isn't production worthy. The core DHF is solid. The code has few, if any bugs logged against it. The QuickStart is where all of the bugs and enhancements are located
* Making a release involves testing a lot of parts. If we can update the 2 separately then we can be more agile with releases.

@damonfeldman I know you are somewhat in agreement.

@jmakeig any opinions on this?

**Comment by paxtonhare** [comment]
I'd also like to standardize the DHF Core between 1.x and 2.x. There are only a handful of diffs that need to be resolved:

- content vs instance in the envelope
- hub ns vs ES ns in the envelope
- 1.x requires "Monkey Patching" of the /v1/forestinfo so that DMSDK works on ML 8

If we elect to go instance and ES namespace then this is trivial. Otherwise I need to check the ML version and do something different for each one.

I really want to simplify the branch management. It's an epic pain right now to keep merging changes between all these branches.

Come to think of it, I could also merge the QuickStarts. Only show the entity modeling if you are on ML 9.

**Comment by damonfeldman** [comment]
Sounds good to me. The ML 8 upgrade path is somewhat of an issue, but if a breaking change is worthwhile, it is better early than late. What would existing production installations do, though? Is it just a case of editing their newly-generated code, and the old code will continue to run as-is?

**Comment by paxtonhare** [comment]
@damonfeldman the code internal to the hub flow-lib.xqy does write envelopes as es:envelope with es:instance. since that is "black box" then it might cause issues for existing installs.

I'd rather not break anything. 

I see two options here:

1. conditionally write es:envelope/es:instance vs hub:envelope/hub:content depending on server version.
1. revisit the main.xqy to expose the enveloping function from flow-lib so that the user can pick one.
