### ISSUE TITLE
How does one create a nested XML structure using ES?

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#486]
```xquery
let $model := json:object()
  let $_ := (
    map:put($model, '$attachments', $attachments),
    map:put($model, '$type', 'Patient'),
    map:put($model, '$version', '0.0.1'),
    map:put($model, "procedure_occurrences",
      for $i in 1 to 3
        return
          element procedure_occurrence { $i }
    )
```

Intended output:

```xml
<Patient xmlns="">
  <procedure_occurrences>
    <procedure_occurrence>1</procedure_occurrence>
    <procedure_occurrence>2</procedure_occurrence>
    <procedure_occurrence>3</procedure_occurrence>
  </procedure_occurrences>
</Patient>

```

actual output:
```xml
<Patient xmlns="">
  <procedure_occurrences>
    <procedure_occurrence>1</procedure_occurrence>
  </procedure_occurrences>
  <procedure_occurrences>
    <procedure_occurrence>2</procedure_occurrence>
  </procedure_occurrences>
  <procedure_occurrences>
    <procedure_occurrence>3</procedure_occurrence>
  </procedure_occurrences>
</Patient>
```

@grechaw should this work as intended above? I tried several code variations with returning json:array and such and it always wants to make many procedure_occurrences. My guess is that your intent was to keep it 1 level deep. Is that correct?

How gross would it be for me to modify the DHF code to do the intended above? Would it be an abomination that goes against everything ES holds dear?

**Comment by grechaw** [comment]
you don't want to do what you think you want to do, ive been down that road.  and it's probably moot now anyway, i think the next ES/DHF will just choose JSON structures.
