### ISSUE TITLE
Performance issues with Search, traces, and jobs tabs

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#506]
All 3 of these screens in quickstart are slow to load. Seems to be an issue in the Spring Boot layer

**Comment by sashamitrovich** [comment]
Almost all parts of the UI feel slow - the search page especially does a disservice to the otherwise very fast ML search core functionality. For some audiences this is a first encounter with MarkLogic search and it makes for a really bad first impression :(
