### ISSUE TITLE
Data from "options" in MLCP is not populating inside document

### ISSUE THREAD

**Issue by sourabhpal92** [marklogic/marklogic-data-hub#5092]
### Welcome Hub enthusiast!

After upgrading framework to 5.2.2 we found out that options (JSON) that we were passing via MLCP were not processing inside the document. 

#### The issue

After doing some digging we found out that , Marklogic library was losing double quotes from JSON formatted options during processing. 

What behavior are you expecting?
IN MLCP command:
example:
Expected:
options = {"job-id" : "datahub", "version": "2.0.2"}
MLCP options getting in error logs during processing:
options = {job-id : datahub, version: 2.0.2}
workaround that we did:
options = {\"job-id\" : \"datahub\", \"version\": \"2.0.2\"}

#### Tech details

Which Operating System are you using?
Windows 10
Which version of MarkLogic are you using?
Marklogic 10-4.4
Which version of Data Hub are you using?
Marklogic Datahub Framework 5.2.2
Is this a QuickStart UI bug? If so, which browser are you using?
No
#### The devil is in the details...
suspected lib that might have caused this issue:- 
/datahub/5/transforms/mlcp-flow-transform.sjs

#5091 #

**Comment by rahulvudutala** [comment]
@sourabhpal92 Thank you for reaching out to us. Can you share the MLCP command you are trying to use? 
Did you also try to use the MLCP optionsFile instead of providing the options in the command line?

**Comment by rjrudin** [comment]
I tried this via an instance of MlcpTask in the build.gradle file for examples/reference-entity-model:

```
transform_param = 'flow-name=CurateCustomerJSON,step=1,options={"hello":"world"}'
```

And I verified that options was correctly constructed in mlcp-flow-transform.sjs and that options.hello as accessible as well. 

If you're running MLCP via the command line, the quotes may be getting dropped by your command line interface. As mentioned above, the best practice with MLCP is to move MLCP inputs to an options file - https://docs.marklogic.com/guide/mlcp/import#id_24824 . 

Closing as I believe that will solve the problem, but if you're still getting the error, first try DHF 5.4.0, and then please reopen this with the MLCP command you're using.
