### ISSUE TITLE
Make job failure more prominent

### ISSUE THREAD

**Issue by dmcassel** [marklogic/marklogic-data-hub#531]
#### The issue

After running one of the flows, I currently need to switch over to the Jobs view and refresh to see that an error occurred in the flow. When an error occurs, make it more clearly visible by putting a sticky visual indicator on the screen. For instance, put a red-circled X or ! next to the Jobs tab. 

#### Tech details

Which Operating System are you using? Docker (Mac OS X)

Which version of MarkLogic are you using? 9.0-2

Which version of the Data Hub Framework are you using? 2.0.0

**Comment by aebadirad** [comment]
This is now more prominent and can be viewed from the flows screen in data hub 5.0
