### ISSUE TITLE
Enable test run for harmonize flow Content plugin

### ISSUE THREAD

**Issue by dmcassel** [marklogic/marklogic-data-hub#533]
#### The issue

Running a harmonize flow may take awhile, especially if I have a lot of data. Give me a way to run a quick test by running on a single document. Would be helpful to let me specify the input string, which should default to the first item returned by the collector. Display the output and any errors, but do not insert into the database. 

#### Tech details

Which version of the Data Hub Framework are you using? 2.0.0

**Comment by aebadirad** [comment]
Data Hub 5.0.0 and later supports option "noWrite: true" to allow for a 'test run' without writing anything.
