### ISSUE TITLE
[BUG] HC Run tab - Add Step does nothing

### ISSUE THREAD

**Issue by wpaven** [marklogic/marklogic-data-hub#5358]
*### Welcome Hub enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

See attached. On Run Tab, in HC I 
![HubCentralAddStep](https://user-images.githubusercontent.com/345873/110984258-e2b74180-8338-11eb-93c6-e5c6b8236bf9.png)
 have a menu to add a step. I click and nothing happens. Shouldn't this add the selected step?

Short description of the problem:

What behavior are you expecting?

What are the steps to reproduce the issue:
1)
2)
3)

#### Tech details

Which Operating System are you using?
Windows 19
Which version of MarkLogic are you using? 10.0-6.1

Which version of the Data Hub are you using? 5.4

Is this a QuickStart UI bug? If so, which browser are you using?

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar marklogic-datahub-<version>.war  --debug  > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -debug > myoutput.txt`

**Comment by wpaven** [comment]
Ah. Ok.  I thought I'd be able to add it from here. I'm sure I'm the only one who'll be confused.  Thanks!

**Comment by kkanthet** [comment]
@wpaven  closing this issue as resolved, please open new one if you still see any issue.
