### ISSUE TITLE
Provide stop-on-failure option

### ISSUE THREAD

**Issue by dmcassel** [marklogic/marklogic-data-hub#536]
#### The issue

If I'm running a harmonization flow and it doesn't work, I'll want to fix the problem and re-run. There may not be much value in having the job run to completion, hitting the same failure on more documents. Provide an option to have the flow stop execution the first time it fails (FAILURE) or hits an error (FINISHED_WITH_ERRORS). 

#### Tech details

Which version of the Data Hub Framework are you using? 2.0.0

**Comment by aebadirad** [comment]
Supported. Flows and steps in data hub 5 can specify "-PfailHard=true" to stop the data hub from continuing if it encounters an error.
