### ISSUE TITLE
Example: Create LDAP Project

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#546]
We need an example project showcasing how to use external security.

**Comment by grechaw** [comment]
+1

I found it mighty tricky to do in samplestack days.

**Comment by gku11ava** [comment]
What do you need in the example project?  I've got some example files that show how to configure external-security for LDAP, associate the data-hub-role  to an LDAP group and enable ldap authorization and authentication for the data hub app-servers.   Is that all that's needed or is there also a need to walk through setting up LDAP as well?  I also have notes on how to setup OpenLDAP with the memberOf plugin and LDIFs to create a bare bones example.

**Comment by aebadirad** [comment]
Being able to set it all up from Gradle (including a remove) to create a barebones example would be great.

You don't have to walk through the setting up of the LDAP, just the process of how to configure security & connect the DHF to the LDAP that's created in the barebones example.

We do have support both windows and linux environments, so please consider the cross-platform compatibility of the example as well.
