### ISSUE TITLE
Support XCC or HTTP invocation of flows

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#554]
#### The issue
only mlcp and REST transforms are currently supported. However, for maximum performance together with flexibility, a custom XCC loader is sometimes needed.

Short description of the problem:
The REST API has some overhead, which while low may not be acceptable when performance is critical. mlcp is likely the fastest approach, but cannot perform all the tasks of a custom program or SpringBatch loader, therefore a fast, non-REST-API approach is needed.

What behavior are you expecting?
Performance-optimized HTTP or XCC insert for input flows, that invokes the transform, with batching.

**Comment by paxtonhare** [comment]
@damonfeldman are you talking about input flows?

I'm curious to hear about what prompted this ticket.

**Comment by aebadirad** [comment]
Data Hub 5 now comes bundled with an http orchestrator, as well as can be invoked from the REST tier.

Data Services support will soon follow.
