### ISSUE TITLE
Documentation: document migration path when adding ml-data-hub to an existing ml-gradle project

### ISSUE THREAD

**Issue by sparnell** [marklogic/marklogic-data-hub#563]
Adding the ml-data-hub plugin to an existing ml-gradle based project breaks the project. There are conflicts between the two plugins which require removal of the ml-gradle plugin. The default directories used by ml-data-hub are different that the default directories used by ml-gradle, which means that application modules in src/main/ml-modules will no longer be deployed.

Since they are both gradle plugins for MarkLogic applications, and ml-data-hub builds on ml-gradle, I expected that ml-data-hub would be compatible with, and conform to the behavior and project organization of ml-gradle.

ml-data-hub version 2.0.0

**Comment by grechaw** [comment]
The 4.0.0 plugin sticks much more closely to the ml-gradle project structure and defaults.  That was one of the primary goals of the 4.0 timeframe.  It's not yet perfectly aligned but hopefully you'll find the experience simpler.

If im misconstruing our successes then please do have a chat with PM for more improvements and also maybe contribute back what you ran into when adding dhf to an existing ml-gradle project.
