### ISSUE TITLE
[BUG] Internal Server error when accessing some collections on DH Central

### ISSUE THREAD

**Issue by radaniba** [marklogic/marklogic-data-hub#5655]
### The issue

I am trying to access some data on DHC either on staging or mapped collections, but I am having an "internal server error" trying to see the json documents on the UI, the document is there and downloadable, but not loading on the UI and causing this issue, there is only one collection so far that is causing this.

The error that I have in the logs is 

```
2021-05-13 13:49:54.985 [http-nio-8090-exec-2] ERROR c.m.h.c.e.CustomExceptionHandler - Local message: failed to POST at /data-hub/5/data-services/entitySearch/getRecord.sjs: Internal Server Error. Server Message: JS-JAVASCRIPT: const flowStepNames = Object.keys(flow["steps"]).map(step => flow["steps"][step].name); -- Error running JavaScript request: TypeError: Cannot read property 'steps' of undefined . See the MarkLogic server error log for further detail.
com.marklogic.client.FailedRequestException: Local message: failed to POST at /data-hub/5/data-services/entitySearch/getRecord.sjs: Internal Server Error. Server Message: JS-JAVASCRIPT: const flowStepNames = Object.keys(flow["steps"]).map(step => flow["steps"][step].name); -- Error running JavaScript request: TypeError: Cannot read property 'steps' of undefined . See the MarkLogic server error log for further detail.
```

### Technical details

Please provide the following version information:

- Operating System = CentOS 
- MarkLogic = 10.0-4.2
- Data Hub =  5.4.1
-  Browser = Firefox 88.0

**Comment by rjrudin** [comment]
Thanks for the writeup - I am almost certain this was fixed in 5.4.2 via internal ticket 6985. The issue is that the provenance for the document references a flow that no longer exists; 5.4.2 ensures an error is not thrown in that scenario. 

Can you try 5.4.2? If it's resolved there, let us know and we'll close this.

**Comment by radaniba** [comment]
Hi @rjrudin you are right. DH upgraded and problem fixed, working on a test environment, so no big deal but I wanted to let you know that the upgraded deleted all my data following the documentation here https://docs.marklogic.com/datahub/5.4/upgrade.html

**Comment by rjrudin** [comment]
Hmm - by "deleted my data", do you mean data in an ML database? I don't know of anything in the upgrade process that would do that. The upgrade process does overwrite (after first making a copy of) the src/main/hub-internal-config directory, so if you made mods in there, you'd have to reapply them.

**Comment by radaniba** [comment]
Yes I was actually not able to find any documents in the staging and final area. Not able to rerun any mapping step as the system doesn’t look like finding path to the data. It might be a config issue, didnt really change anything in there. Checked the monitoring and it seems like the data is still there but not viewable in Central. Looking into it
