### ISSUE TITLE
[BUG] Inconsistency DHC Entity and Entity json file

### ISSUE THREAD

**Issue by radaniba** [marklogic/marklogic-data-hub#5665]
Hi everyone,

I have a server running DH that I upgraded since DH4 and I kept the service running while watching new releases and updates.

Now I am running DH 5.4.3 and DH Central 5.4.3 with DH server 10

I noticed when I update entities in DHC by adding or removing properties, the entities under `root/entities/Xxxx.entity.json` is not consistent with the change done from DHC (not updating) is this directory deprecated in 5.4.3 ?

Thanks

**Comment by rjrudin** [comment]
HC is designed for being used by many people at once, typically on a remote computer. Thus, it does not maintain a project on a filesystem; it writes everything to MarkLogic. When you want to get all the project files that it can modify out, you can use the Download button (available from the info icon in the header), or better yet, use the Gradle "hubPullChanges" task in your project, which will download the files and add them to your project.
