### ISSUE TITLE
[BUG] Matching step on a property of type "Related Entity"

### ISSUE THREAD

**Issue by radaniba** [marklogic/marklogic-data-hub#5674]
- Operating System = Centos
- MarkLogic = 10
- Data Hub = 5.4.3
- Central : 5.4.3

Hi there,

I am wondering if we use the attributes in a given entity that are configured as 'Related entity' in the matching step, currently I have it showing as "Multiple" but there is no way of me selecting what attribute in particular I want to match against

Any idea ?

"is_structured_for" here refers to an entity in my "Client" entity that is referring to an "Appointment" entity and I would like to match against one of its attributes to build the score for matching

![Screen Shot 2021-05-17 at 3 36 09 pm](https://user-images.githubusercontent.com/1666443/118521912-0dc17580-b76e-11eb-9eda-070b68dfccb5.png)

and I noticed that in the documentation the add Ruleset has a dropdown menu to add mutiple properties, where as in my 5.4.3 installation I have only one button for without that option so I can only map a single property at a time

## From the Documentation

![Screen Shot 2021-05-17 at 3 56 09 pm](https://user-images.githubusercontent.com/1666443/118452388-aaf9bb00-b728-11eb-87f5-c52dc4fba5c6.png)

## From my 5.4.3 instance

![Screen Shot 2021-05-17 at 3 58 54 pm](https://user-images.githubusercontent.com/1666443/118452579-e1373a80-b728-11eb-8094-8993f79dd119.png)

**Comment by ryanjdew** [comment]
@radaniba The documentation published functionality that is slated for the DH 5.5 release and subject to changes from what was inadvertently released. We will be updating the documentation shortly.

In DH 5.5 we will provide the ability to match on structured properties (or nested properties stored in the same document).  As for using related entity properties (stored in external documents) for matching, that is not yet available with our out-of-the-box matching functionality. There are a couple of ways you could potentially accomplish that with a custom match function. Any details on your use case would be helpful in our planning of that feature.

**Comment by radaniba** [comment]
Thank you so much @ryanjdew that make sense now. Any idea on the release date for 5.5 ?

The use case is constantly changing, I am trying several approaches, using complex entities with embedded properties, or using properties of type related entity, the matching/merging step will determine my final choice.

Thanks

**Comment by xnikhil08** [comment]
@radaniba - You can expect 5.5 HC to be available on-prem and on DHS, somewhere around mid-june.
