### ISSUE TITLE
[BUG] Merge step fails with this URIsToProcess error

### ISSUE THREAD

**Issue by radaniba** [marklogic/marklogic-data-hub#5704]
Hi everyone,

I am trying to merge some records in DH 5.4 but I am running through an issue that I am trying to understand 

![image](https://user-images.githubusercontent.com/1666443/119369864-3a820980-bce7-11eb-8bab-096718ec3d7e.png)

This is only happening with a collection in particular for now strangely but nothing looks wrong with it

**Comment by akshaysonvane** [comment]
Hi @radaniba ,
It seems like the `sourceQuery` is picking up documents that aren't matchSummary docs and thus do not contain the required keys (`matchSummary.URIsToProcess`) in them. 
Can you share the `sourceQuery` that you are using?

**Comment by radaniba** [comment]
Thank you @akshaysonvane you're right, I adjusted this but now I got this error message regarding time limit exceeded for the merge step

Message:  com.marklogic.client.FailedRequestException: Local message: failed to POST at /data-hub/5/data-services/stepRunner/processBatch.sjs: Internal Server Error. Server Message: XDMP-EXTIME: Time limit exceeded . See the MarkLogic server error log for further detail.
