### ISSUE TITLE
Detect and report missing parameters to input flows.

### ISSUE THREAD

**Issue by ODMResonance** [marklogic/marklogic-data-hub#572]
#### Paxton Edits
We need to detect when input flow parameters are missing and report them back to the user. Right now they get a cryptic error message.

### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:

Input flows into data hub is failing. I am setting up a datahub environment and slush generator Web-app through a repo that a ML Sales Engineer has kindly set up:
https://github.com/MJMoody/cg-ef-datahub
https://github.com/MJMoody/cg-ef-slushapp

What behavior are you expecting?

I am expecting the csv file to be ingested properly. Note that the input file used is the same file that the ML Sales Engineer/Developers used in building the entity plugins, etc. Given that the input flow never had a problem until ~2 months ago, I am assuming the error is not caused by anything to do with the structure of the input file. Rather, I have a suspicion that this error is coming from using old (~4 months old) code from the /plugin/entity folder - perhaps some incompatibilities with the newly updated data hub 2.0.

I have spent many hours trying to diagnose the issue, but to no avail - I am quite new to Marklogic.

#### Tech details

Which Operating System are you using?

Windows Server 2012 R2 (64 bit). However this issue was also occurring in my local machine (Windows 7 64 Bit)

Which version of MarkLogic are you using?

9 (MarkLogic-9.0-3.1-amd64.msi)
Also mlcp9.0.3, FYI

Which version of the Data Hub Framework are you using?

quick-start-2.0.0.war

Is this a QuickStart UI bug? If so, which browser are you using?

Not sure. Using Chrome 62.0.3202.89 (Official Build) (64-bit)

#### The devil is in the details...

The entity set up is as per cg-ef-datahub repo. I git clone that repo, then run the quickstart.war file, the move onto running the input flows. A few months ago, this went smoothly, and encountered no errors - but recently I have been encountering the following error:
`23:59:19.272 [main] INFO  c.m.contentpump.LocalJobRunner - Content type: XML
23:59:20.772 [main] INFO  c.marklogic.contentpump.ContentPump - Job name: local_100719205_1
23:59:20.834 [main] INFO  c.m.c.FileAndDirectoryInputFormat - Total input paths to process : 1
23:59:24.835 [Thread-4] INFO  c.m.contentpump.LocalJobRunner -  completed 100%
23:43:01.604 [pool-1-thread-2] WARN  c.m.contentpump.TransformWriter - Failed document /silhouette/consultants/consultant-anon-final.csv-0-2
23:43:01.604 [pool-1-thread-2] WARN  c.m.contentpump.TransformWriter - <error:format-string xmlns:error="http://marklogic.com/xdmp/error" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">XDMP-AS: (err:XPTY0004) $entity-name as xs:string -- Invalid coercion: () as xs:string</error:format-string>`
...
`23:59:25.038 [main] INFO  c.m.contentpump.LocalJobRunner - com.marklogic.mapreduce.MarkLogicCounter: 
23:59:25.038 [main] INFO  c.m.contentpump.LocalJobRunner - INPUT_RECORDS: 19
23:59:25.038 [main] INFO  c.m.contentpump.LocalJobRunner - OUTPUT_RECORDS: 19
23:59:25.038 [main] INFO  c.m.contentpump.LocalJobRunner - OUTPUT_RECORDS_COMMITTED: 0
23:59:25.038 [main] INFO  c.m.contentpump.LocalJobRunner - OUTPUT_RECORDS_FAILED: 19
23:59:25.038 [main] INFO  c.m.contentpump.LocalJobRunner - Total execution time: 4 sec`

To clarify, my MLCP command is:

`mlcp.bat import -mode local -host localhost -port 8010 -username admin -password ***** -input_file_path D:\Users\KWITTICK\cg-expertfinder\cg-ef-datahub\input\silhouette\consultant -input_file_type "delimited_text" -output_collections "consultants,in_consult_silh,silhouette,input,data" -output_permissions "rest-reader,read,rest-writer,update" -output_uri_prefix "/silhouette/consultants" -output_uri_replace "/D:/Users/KWITTICK/cg-expertfinder/cg-ef-datahub/input/silhouette/consultant,''" -document_type "xml" -generate_uri true -delimited_root_name "consultant" -transform_module "/com.marklogic.hub/mlcp-flow-transform.xqy" -transform_namespace "http://marklogic.com/data-hub/mlcp-flow-transform" -transform_param "entity=Employee,flow=in_consult_silh,flowType=input"`

Apologies in advance for any crucial information I may have missed as this is my first time posting on this community!

**Comment by paxtonhare** [comment]
@ODMResonance as of 2.0.0 we changed some of the parameters for the `transform_param` piece. the release notes for 2.0.0 mention the change.

See the docs here: https://github.com/marklogic-community/marklogic-data-hub/wiki/Advanced-Hub-Usage#running-input-flows


-transform_param "entity-name=YourEntityName,flow-name=YourFlowName,job-id=someString"

**Comment by damonfeldman** [comment]
Note: the specific issue here is that the old param was "entity" and the new is "entity-name".

Can we add a check for all required params, to give explicit info such as "parameter 'entity-name' not found" or similar when this happens?

**Comment by paxtonhare** [comment]
@damonfeldman I think we should rename this ticket yet again. Doing so now.

**Comment by aebadirad** [comment]
Closing due to the fact the issue has no relation to the current major version and is from a deprecated version of DHF.
