### ISSUE TITLE
Allow Flow creation without an Entity Services definition in QuickStart

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#573]
#### The issue
Often, a developer cannot model their data in the way Entity Services specifies it, due to attributes, namespaces or grouping sub-elements that are not (yet) supported by ES. 

Also, some groups can but do not want to use that format for modeling, preferring to edit .xsds, use UML or OWL. 

In these cases it should be easier and more obvious to create a flow that is not driven by an ES specification. The DHF supports this already from the command line via a gradle task, but the GUI does not expose it.

### Option
One option would be a "new flow" or "new entity" button on the "Flows" tab to create an entity/flow that does not correspond to an entity in the graphical Entities tab.

### Workarounds
Today, people can create new flows via an ml-gradle task, rather than the QuickStart GUI, without creating an entity services spec

Also, people can create a simple entity in the Entities tab, with no fields or configuration just to represent a category of flows, and create flows without using the entities spec (via the radio buttons on the create flow dialog)

-
Related to #537 where people want to create input flows that are not related to a particular entity. [https://github.com/marklogic-community/marklogic-data-hub/issues/537]

**Comment by aebadirad** [comment]
Can do in Data Hub 5.
