### ISSUE TITLE
`stepEndTime` values of individual steps in flow's job file are wrong [BUG] 

### ISSUE THREAD

**Issue by plackowk** [marklogic/marklogic-data-hub#5733]
## The steps to reproduce the issue:

1) Create a flow with multiple steps
2) Run it
3) Search for job file in jobs database

[actuallJobFile.txt](https://github.com/marklogic/marklogic-data-hub/files/6571247/actuallJobFile.txt)

From the above file you can see there that `stepEndTime` values of individual steps are almost equal to `timeEnded` value of full flow execution, what suggests that all steps were finished at the same time. I believe that in reality steps are run in a sequence, so that step X+1 is started after step X finishes, and `stepEndTime` values should indicate that.

## What behavior were you expecting? 

I expected that `stepStartTime` and `stepEndTime` values of all ordered steps will  build **a monotonic sequence**, like it is in the below example file:

[expectedJobFile.txt](https://github.com/marklogic/marklogic-data-hub/files/6571248/expectedJobFile.txt)

## Technical details

Please provide the following version information:

- Operating System = win10
- MarkLogic = 9.0-13.2
- Data Hub = 5.4.1

**Comment by Sanjeevani19** [comment]
Thanks @plackowk for noticing this bug, this issue has already been addressed as a part of this PR https://github.com/marklogic/marklogic-data-hub/pull/5683 and will be a part of 5.5 release
