### ISSUE TITLE
Deploying temporal configuration in DHF final DB

### ISSUE THREAD

**Issue by ltnd** [marklogic/marklogic-data-hub#574]
The task mlDeployTemporal is associated to default database (<appName>-content) and not the final database of the DHF.
We should be able to define the target DB  to deploy the temporal config.

**Comment by jkerr5** [comment]
A partner ran into this issue in the last week.

**Comment by popzip** [comment]
Is this the same as #443? This was [logged and closed](https://github.com/marklogic-community/ml-app-deployer/issues/171) on ml-app-deployer. @rjrudin to your understanding is above issue resolved or does DHF need to do something? documentation on our part needed?

**Comment by rjrudin** [comment]
Yes, my understanding is that this should be possible in DHF - the temporal stuff would be in a directory of "databases/(name of database)/temporal".

**Comment by aebadirad** [comment]
This should now work with vanilla ml-gradle for the final database, as that's tied to the vanilla ml-gradle bundled with DHF.

Please place the settings in there, and reopen this issue if those do not deploy to final correctly.
