### ISSUE TITLE
Revisit the default names of the database - "staging" and "final"

### ISSUE THREAD

**Issue by popzip** [marklogic/marklogic-data-hub#584]
This is misleading as harmonized data is not necessarily final. 
Get input from others - @damonfeldman ? @grechaw @jmakeig 

Understand the impacts and the extent of the change (grep). 
Documentation impacts.

This is just for the design work and conversation. 
We should bundle this up with other potentially breaking changes.

**Comment by grechaw** [comment]
My sense so far is that final is not a bad name for the role this database plays within the hub.  You're right that harmonized data need not be final, but to me that means that harmonized data might have other destinations than the final database.

We've considered the various names a lot in the data integration group too, and there are different axes that cut across the databases, and we think there's also one database role missing from the data hub framework that will come into play next year:

staging -- the place where you put data that is not ready for final use.  It might be as-is, partially harmonized, reference data, or harmonized.
final -- the data that you're going to use for backing end-user queries.  My guess is that this is a combination of harmonized data, content that needs just to be served to APIs (not from DHF workflow), and reference data.  Maybe also application state data (but that's out of scope for data hub).
discovery -- this is not in DHF.  We think there's some database to consider which is not within a production flow.  A production system is engineered, and you can't muck with it too much.  But data discovery is potentially messy, experimental, requiring lots of change, and perhaps just one person working at a time.   A discovery process might need access to staging or final data, but it also might be a sample.

**Comment by popzip** [comment]
Good point on harmonized data not being the only data in the "final" db.

The goal of that second database (in today's world, not with the potential third one you mentioned) is to have a place data is ready to be consumed.
Other thoughts on wording:
* delivery
* serving
* consume

**Comment by aebadirad** [comment]
We ended up sticking with it.
