### ISSUE TITLE
[BUG] Merging step failing, Time limit exceeded

### ISSUE THREAD

**Issue by radaniba** [marklogic/marklogic-data-hub#5863]
Hi everyone,

I am using the latest 5.5.1 version of DH.
I have a very simple flow that is unfortunately failing because of time limit apparently exceeded 

![Screen Shot 2021-07-04 at 9 46 07 pm](https://user-images.githubusercontent.com/1666443/124387530-9c378980-dd11-11eb-93da-67142b1deb59.png)

Any idea whether or not it is a settings that I need to fix or this is rather an issue ?

Thanks

R.

**Comment by devinnicholson** [comment]
Hi!

Could you provide the steps you took so I can reproduce this, and provide the project with sample input data?

Thank you,
Devin

**Comment by dmcassel** [comment]
@radaniba I've seen this happen if the collection query finds a large number of documents (too many to handle in a single request). The solution has been external orchestration. For example, we use Apache NiFi to batch URIs that need processing into groups of 100 or so and call the flow that way.
