### ISSUE TITLE
Catch errors in indexing

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#589]
After a document is inserted with a writer, there can be errors with indexing that happen. Make sure we catch these.

**Comment by popzip** [comment]
per group chat - comment from Damon on one case is: "looks like nulls in the data mapped to non-nullable relational views."

**Comment by dmcassel** [comment]
scope is limited to catching the errors and bubble up to caller.

set up test with indexing error to see if user notified.

for reject setting

example is TDE, could be range index.

**Comment by aajacobs** [comment]
+1

**Comment by aebadirad** [comment]
Reporting errors has changed with data hub 5.0, so closing for this outdated version.
