### ISSUE TITLE
Deleting an entity does not remove the related code from the modules DB

### ISSUE THREAD

**Issue by dmcassel** [marklogic/marklogic-data-hub#594]
#### The issue

Short description of the problem:
I deleted an entity, then saw that the input and harmonize flows related to it were still in the modules database, although they had been deleted from the filesystem. 

What behavior are you expecting?
On deleting an entity, all references to it should be gone. 

Workaround: redeploy modules, which clears the modules database before reloading. Can be done from the Flows tab (click "REDEPLOY" button). 

#### Tech details

Which Operating System are you using?
Mac

Which version of MarkLogic are you using?
9.0-2

Which version of the Data Hub Framework are you using?
2.0-1

Is this a QuickStart UI bug? If so, which browser are you using?
Yes; Chrome.

**Comment by popzip** [comment]
deletes locally only

**Comment by aebadirad** [comment]
Closing out old issue that no longer applies to the latest major release. Redeploy is the default behavior for data hub 4.x and below.
