### ISSUE TITLE
No way to set a custom forest path for gradle deployment

### ISSUE THREAD

**Issue by hellznrg** [marklogic/marklogic-data-hub#5976]
The documentation at https://docs.marklogic.com/datahub/5.5/refs/data-hub-properties.html says that mlCustomForestPath is deprecated. However there is no alternative offered. Should DataHub databases only be created on the OS disk?

**Comment by rjrudin** [comment]
The ml-gradle properties will all work for DHF databases - https://github.com/marklogic-community/ml-gradle/wiki/Creating-forests . mlCustomForestsPath is still supported in the 5.x timeframe too.
