### ISSUE TITLE
QuickStart - advanced init settings - user and role names

### ISSUE THREAD

**Issue by bciano** [marklogic/marklogic-data-hub#612]
#### The issue

I would expect that the QuickStart init - Advanced Settings would allow me to also specific the names for the data-hub-user, and data-hub-role.  

In order to run multiple project data hubs on a single MarkLogic instance, we need to be able to uniquely identify all of the db names, ports, but also the user and role names.

The workaround right now is to edit the gradle properties before installing the data hub, or uninstalling it, edit the gradle properties, and reinstalling it.

#### Tech details

Which Operating System are you using? OSX

Which version of MarkLogic are you using? 9.0-2

Which version of the Data Hub Framework are you using? 2.0.2

Is this a QuickStart UI bug? If so, which browser are you using? no

**Comment by smclean** [comment]
We tried the work-around and apparently there is a hard-coded "data-hub-role" which prevented us from renaming the role to avoid conflict with another project on the same host.

Which Operating System are you using? Windows 10 running Gradle, Linux on server (version unknown)
Which version of MarkLogic are you using? 9.0-6.2
Which version of the Data Hub Framework are you using? 4.1.0
Is this a QuickStart UI bug? No

**Comment by aebadirad** [comment]
This should now be resolved in 4.3.1 and 5.0. Reopen if that's not the case.
