### ISSUE TITLE
[BUG] Java API changed from DHF testing example

### ISSUE THREAD

**Issue by laquereric** [marklogic/marklogic-data-hub#6149]
If you are a licensed MarkLogic customer, please contact Support first. 

If you are a MarkLogic employee, please use our internal JIRA instance to report an issue of type Bug in the DHFPROD project. 

Otherwise, please use this template to report the bug you've run into.
### The issue

Please provide reproducible steps for the issue and a description of what behavior you expected instead.

The steps to reproduce the issue (use as many numbered steps as you need):

1) Follow the suggestions to install https://github.com/marklogic-community/marklogic-unit-test
2) See:
 - import com.marklogic.hub.deploy.commands.DeployHubOtherServersCommand not found.
 
What behavior were you expecting?

Expected it to work

### Technical details

Please provide the following version information:

- Operating System = Any
- MarkLogic = 
- Data Hub = 5.5.3

If this is a Hub Central or QuickStart issue, please provide the browser version too:  

DHF Local

### Additional details

File was removed between DataHub between 4.x and 5.x**:
See: https://github.com/marklogic-community/marklogic-unit-test/issues/140

**Comment by ryanjdew** [comment]
The recommended way to write DH unit tests can be found here: https://github.com/marklogic/marklogic-data-hub/tree/master/examples/reference-entity-model#marklogic-unit-test-examples

The Java APIs found in that example aren't considered supported.
