### ISSUE TITLE
quickstart doesn't create the REST folders under the entities

### ISSUE THREAD

**Issue by joecrean** [marklogic/marklogic-data-hub#615]
### Welcome Hub enthusiast!
Let's get the most out of this ticket.

#### The issue
when using quickstart to create entities and their flows the REST folder under <entity> is not created. 

What behavior are you expecting?
Under each entity there should be a REST/options folder with the respective options file for final and staging dbs. The generated options in final-entity-options.xml and staging-entity-options are not copied over.

#### Tech details
Which Operating System are you using?  windows 7

Which version of MarkLogic are you using? 9.0-3.1

Which version of the Data Hub Framework are you using? 2.0.2

Is this a QuickStart UI bug? If so, which browser are you using?

#### The devil is in the details...
built initially with 2.0.1

**Comment by joecrean** [comment]
maybe potentially because i created the intial project with quickstart 2.0.0?

**Comment by dmcassel** [comment]
Have you upgraded to 2.0.2? If so, have you created an entity since then?

**Comment by joecrean** [comment]
yes i have been on 2.0.2 for a while now and have created new entities. No directory structure was created.

**Comment by paxtonhare** [comment]
@joecrean we don't create that folder on purpose. You can create it if you like and put code in it.

the *-entity-options should not be copied over. They are deployed from the entity-config/ folder.

**Comment by aebadirad** [comment]
This is now backed out to the place you'd expect it to be for vanilla ml-gradle's ml-modules. The entity-config/*-entity-options are still being deployed from the entity-config folder not to cause conflation.
