### ISSUE TITLE
Fix issue for mlcp ingest flows when ingesting filenames with spaces in it

### ISSUE THREAD

**Issue by peetkes** [marklogic/marklogic-data-hub#642]
#### The issue

When I create an ingest flow that ingests files with spaces in the filename, those spaces are transformed to %20 characters in the uris. 
If you ingest a file with spaces in the name, those spaces are transformed to %20
So ingestion of file '/var/lib/This is a file with spaces in the name.xml"
wil create a uri of '/var/lib/This%20is%20a%20file%20with%20spaces%20in%20the%20name.xml'

If you select that file in the dh browser, you will get an error in the console output and the file cannot be displayed.

21:01:51.242 [http-nio-9080-exec-9] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.marklogic.client.ResourceNotFoundException: Local message: Could not read non-existent document. Server Message: RESTAPI-NODOCUMENT: (err:FOER0000) Resource or document does not exist:  category: content message: /Russian/Air Defense/ZSU-23-4M4   (Shilka).docx] with root cause
com.marklogic.client.ResourceNotFoundException: Local message: Could not read non-existent document. Server Message: RESTAPI-NODOCUMENT: (err:FOER0000) Resource or document does not exist:  category: content message: /Russian/Air Defense/ZSU-23-4M4   (Shilka).docx

Expected behaviour: File should be displayable, no error in the console output.

#### Tech details

Which Operating System are you using?
MacOs El Capitan
Which version of MarkLogic are you using?
Version 9.0-3

Which version of the Data Hub Framework are you using?
2.0.2
Is this a QuickStart UI bug? If so, which browser are you using?
No, it is a transform bug

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by peetkes** [comment]
Yes I do, but I'm having some issues with running the tests.

**Comment by popzip** [comment]
@peetkes do you still see this?

**Comment by peetkes** [comment]
Hi Casey,

Sorry for the late response but I think this is solved in dhf 4.1.1

Regards,

Peter
