### ISSUE TITLE
Filename is not displayed on the UI file/folder path but displayed on MLCP command

### ISSUE THREAD

**Issue by ayuwono** [marklogic/marklogic-data-hub#655]
OS: Mac
Browser: Chrome
ML version: 9.0 (Jan 12)
DHF version: 2.0.2

Steps:
1) Go to Flows tab
2) Add an Input Flow to load the documents
3) When selecting the current folder, you can actually select a single file, although it's not shown on the UI path (it's showing ../examples/online-store/input/products). But on MLCP command section, the selected file is displayed
Example:
```
mlcp.sh import -mode local -host -port 8010 -username -password ***** -input_file_path /Users/ayuwono/builds/macosx-64/b9_0/marklogic-data-hub/examples/online-store/input/products/board_games.csv
```

After you run the import, the job will show that it only loaded one document

Expected behavior:
It should show the file name on the UI path to make it consistent

<img width="1392" alt="screen shot 2018-01-15 at 4 25 34 pm" src="https://user-images.githubusercontent.com/7096668/34966648-21b6d23c-fa12-11e7-910a-e13d68d91452.png">

**Comment by aebadirad** [comment]
I'm closing this out as the design of the current UI, this is intentional, as it's nudging users to import from directory, not individual files. We should probably address this as part of a larger issue of having MLCP embedded within quickstart.
