### ISSUE TITLE
Track mapping between source document to conformed document.

### ISSUE THREAD

**Issue by HemantPuranik** [marklogic/marklogic-data-hub#7]
Plugins will incorporate transformed data into a standard envelope pattern. Source to conformed doc mapping should be tracked. 
The envelope structure should be mostly hidden for most operations. People should primarily engage with raw and conformed data, headers and triples - not envelopes.

Create a helper function that plops in the link for the user.

**Comment by aebadirad** [comment]
We've included in the new 4.0 scaffolding generated code to drive the user right to the content section of the envelope, without denying access to the envelope.

This pattern can be repeated through headers/triples (or any custom plugin), and now it's all xpathable as we return elements and objectnodes (both Nodes in marklogic's world) so there's parity in accessing what you need whether in JS or XQY dealing with xml or json.

If 4.0.0 doesn't address the need, please reopen and give specific feedback on what could be done better with regards to 4.0's offering.
