### ISSUE TITLE
Enable namespace support in quickstarter

### ISSUE THREAD

**Issue by peetkes** [marklogic/marklogic-data-hub#714]
Enable namespace support when creating entities in quickstarter

Create new entities and add fields for namespace and namespace prefix in the UI
Regenerate db settings for all entities on change

#### Tech details
Running on MacOs 10.11.6

Which version of MarkLogic are you using?
MarkLogic 9.0.4

Which version of the Data Hub Framework are you using?
2.0.3

Is this a QuickStart UI bug? If so, which browser are you using?

Working on Chrome

**Comment by dmcassel** [comment]
We see a couple commits on his fork. Ask him to do a PR, then review, add tests, etc., and merge.
