### ISSUE TITLE
Swagger JSON Endpoint

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#74]
provide an extension that returns the swagger definition of the Hub REST APIs

**Comment by maeisabelle** [comment]
Hi @paxtonhare,

This is already implemented in https://github.com/marklogic/marklogic-data-hub/issues/75. The swagger JSON endpoint can be found by default in http://localhost:8080/v2/api-docs. The Swagger UI takes this URL to display the API docs page. Kindly review the implementation I made for #75 and close this once finished. Thanks!
