### ISSUE TITLE
Creating EntityServices model artifacts

### ISSUE THREAD

**Issue by ravi-b-m** [marklogic/marklogic-data-hub#744]
I am using datahub '2.0.4'. I created entity models in the directory tree, plugins/entities/entity1/entity1.json and plugins/entities/entity2/entity2.json.

When I issue the following gradle command `gradlew.bat -i mlGenerateModelArtifacts`.   No entity services artifacts are being generated . How do I generate the modle artifacts ?

**Comment by dmcassel** [comment]
We need to adjust the ml-gradle command to put the outputs in the right directory.

**Comment by dmcassel** [comment]
➤ Charles Greer commented:

I recommend we wait to take action on this issue -- it's a little more complex than you think.

mlGenerateModelArtifacts works great given its assumptions -- it expects to find model descriptors in a certain place and runs the entity services functions on them.

DHF's models however are actually model fragments -- all of DHF operations on entities union the models first into a single valid 'uber-model' which it uses to call entity services functions.  We'd have to do this same thing to make mlGenerateModelArtifacts, or something like it, work.

So really, we want an enhancement in DHF to do the things that mlGenerateModelArtifacts does.  Or we want to revamp DHF to align with entity services.  At present, there's ambiguity that prevents easy action.

**Comment by dmcassel** [comment]
➤ Charles Greer commented:

Note that DHF already provides tasks that do some of the code generation that mlGenerateArtifacts does.
For example 'hubGenerateTDETemplates'  takes entity names and puts the templates into the right directory.

DHF also runs the index generation and search options independently of this gradle task.

**Comment by popzip** [comment]
is this too big for 3.0? is the fix bigger than just this issue?
