### ISSUE TITLE
Populate job-id on $options map

### ISSUE THREAD

**Issue by miguelrgonzalez** [marklogic/marklogic-data-hub#753]
it would be interesting to have the $job-id in the options just like we get the flow or entity names.

I'm interested in getting this information in particular in the triples step, as I need it to generate a complete provenance set for the document.

**Comment by dmcassel** [comment]
➤ Kasey Alderete commented:

Automatically pass job-id into flow so you can call it from within the flow. Where the options map is passed into the job. User is able to use job-id for provenance, tracking, other metadata operations. XQuery code only, no UI impact.

**Comment by peetkes** [comment]
What's the status on this issue?
I would also like to get a hold of the job-id for the import flows and the harmonization flows.
Same reason as beforementioned=> provenance

**Comment by grechaw** [comment]
Never even considered this issue until the recent conversations -- please work with @sbayatpur-ml to prioritize... it certainly doesn't look like a complex request.

**Comment by iowusu** [comment]
The workaround for job-Id does not work for JavaScript.

**Comment by josvanroosmalen** [comment]
+1. Please get this solved. In addition, job-id should be added by default to the collection at ingest. See also #1534

**Comment by mchiarelli** [comment]
+1. Access to the jobid would also greatly simplify validation checking and reporting.

**Comment by kosed** [comment]
+1 tracing
