### ISSUE TITLE
Generating STAGING DB config using Quickstart duplicates the config of FINAL

### ISSUE THREAD

**Issue by joecrean** [marklogic/marklogic-data-hub#758]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:

When you update the entity model in quickstart (all versions) it writes the config for STAGING to ``staging-database.json``. Also it duplicates the config of FINAL. This makes STAGING quite a large and in my case all that config wont be used as I only load the raw content to STAGING and do not perform application like searching. 

You can define your own config for this database but as Pax shared with us on Hipchat there is an order of precedence

the staging db is a merge of 3 files.
```
$dir/hub-internal-config/databases/staging-database.json
$dir/user-config/databases/staging-database.json
$dir/entity-config/databases/staging-database.json
```

So the user can define some config but it will be overwritten by like items in the ``entity-config`` dir. 

I want to configure STAGING with a minimal config to speed up loading and conserve high performance disk space. So I will specify that minimum config in my user config and make sure the entity config is always empty.. if i hit save on the quickstart entity model page I will need to manually clean out this file which is not good. 

It would be nice to have the user config competely override anything in that entity config. Like if the user file exists it is taken and the entity config file is ignored. 

#### Tech details

Which Operating System are you using?

Linux/Windows

Which version of MarkLogic are you using?

9.0-4

Which version of the Data Hub Framework are you using?

LATEST

Is this a QuickStart UI bug? If so, which browser are you using?

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

┆Status: New

**Comment by popzip** [comment]
@dmcassel did you intend to mark this fixed in dev? i dont see other activity/commits on it so just checking

**Comment by popzip** [comment]
(or could be unito)

**Comment by dmcassel** [comment]
@popzip I think that was unito

**Comment by popzip** [comment]
please triage @aebadirad

**Comment by grechaw** [comment]
@joecrean seems to me you can just remove the file under entity-config if you don't want it deployed.   quick-start of course might be re-creating it, but i think we should treat that as a separate issue.

**Comment by grechaw** [comment]
Looks like i just wrote exactly what you describe as the behavior, @joecrean . 
I'll log this as an enhancement request and put it in the jira backlog.  I'll include a link here to the internal system where backlog and enhancements are managed.

https://project.marklogic.com/jira/browse/DHFPROD-563
