### ISSUE TITLE
mlDeploy fails when run by an LDAP user with full admin rights

### ISSUE THREAD

**Issue by mikrovvelle** [marklogic/marklogic-data-hub#759]
#### The issue

If I run `gradle mlDeploy` from a project using credentials from a MarkLogic local admin user, the deployment completes successfully.

If I do the same thing as an LDAP user mapped to the full admin role in MarkLogic, on that same instance, the operation fails.

This is with:

- all ports (8000-8002, and DHF App Servers) running BASIC authentication
- SSL enabled (but seems unrelated to this issue)

##### Which Operating System are you using?

- Windows 7 Enterprise running gradle command
- Linux hosted MarkLogic

##### Which version of the Data Hub Framework are you using?

2.0.4

#### The devil is in the details...

In the 8000 Access Logs, I see:

> External User(quinland) is Mapped to Temp User(quinland) with Role(s): admin

The output with `--info --stacktrace` is attached, starting a little before the failure occurs.

[LDAP-failure.txt](https://github.com/marklogic-community/marklogic-data-hub/files/1751609/LDAP-failure.txt)

**Comment by mikrovvelle** [comment]
Problem was that the servers (final, staging, trace, jobs) did not have external security turned on. If you do this with gradle, you need to have the following line in their config JSONs:

```json
"external-security": [ "%%mlLDAPName%%" ],
```

and then add a line with the `mlLDAPName` to the appropriate properties files.

**Comment by aebadirad** [comment]
This should now work with vanilla ml-gradle settings in the gradle props file, so closing this issue unless an something turns up to reveal an incompatibility.
