### ISSUE TITLE
Custom forest configurations not being deployed

### ISSUE THREAD

**Issue by tternquist** [marklogic/marklogic-data-hub#774]
#### The issue
Short description of the problem:
I am trying to define a custom forest configuration for the purpose of establishing HA with local disk failover.

I have created a custom forest configuration for the final database and placed it under user-config/forests/final-forest.json and it is not being picked up. I also tried putting the configuration under hub-internal-config/forests and it also did not work.

What behavior are you expecting?
I expect that the the task detects the presense of the custom forest file and will use that instead of the default forest layour

#### Tech details
Which Operating System are you using?
MacOS Sierra

Which version of MarkLogic are you using?
9.0-3

Which version of the Data Hub Framework are you using?
2.0.4
Is this a QuickStart UI bug? If so, which browser are you using?
No

**Comment by dmcassel** [comment]
To do: investigate how ml-app-deployer expects this to be expressed.

**Comment by mflatscher** [comment]
I had a similar use case today, albeit without replicas.

I was able to get custom forests to work for all DHF databases by following instructions here: https://github.com/marklogic-community/marklogic-data-hub/wiki/Customizing-Forest-Configurations

This appears slightly different from default mlgradle's array payload convention for custom forests.

My DHF: 2.0.2
My ML: 9.0-4

**Comment by grechaw** [comment]
I added needs info label because it's not clear what the course of action here is.  I think elsewhere it was recommended that we align DHF with ml-gradle wrt forest configuration, but I don't see that decision here.

Either way, since @mflatscher verified that DHF does work, albeit unexpectedly, shouldn't this be a story/enhancement?

**Comment by grechaw** [comment]
@tternquist do you have a (non-dhf) gradle project that can deploy the forests how you want to?

**Comment by aebadirad** [comment]
This should now work for 'final' forests out of the box vanilla ml-gradle, and for 'staging' forests following the same settings just inside the hub-internal-config directory

Please reopen if there's a bug or incompatibility from ml-gradle's method in DHF.
