### ISSUE TITLE
Remove mimetypes from gradle config

### ISSUE THREAD

**Issue by dmcassel** [marklogic/marklogic-data-hub#780]
Currently we have some mimetypes in the ml-gradle configuration, but these are going to be included in MarkLogic itself. Remove them from the ml-gradle config. This will remove all mimetypes from a hub's ml-gradle config.

┆Status: Closed

**Comment by dmcassel** [comment]
➤ Alexander Ebadirad commented:

[~cgreer] has tackled/is tackling this.

**Comment by dmcassel** [comment]
➤ Charles Greer commented:

Now that server side is complete, I think this PR will once again work.

**Comment by dmcassel** [comment]
➤ Charles Greer commented:

This fix has been merged now, tomorrow we should see whether it's worked.  If there's no regression then the task is done.

**Comment by dmcassel** [comment]
➤ Rahul Vudutala commented:

Datahub framework is installing without any issue after moving the mimetypes into the MarkLogic server.

**Comment by aebadirad** [comment]
Fixed with release of 3.0.0
