### ISSUE TITLE
Need ability to disable auto deployment when running quick start

### ISSUE THREAD

**Issue by sjiang99** [marklogic/marklogic-data-hub#783]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem: right now when quick start is running, it detects for any changes that happened, and does an auto redeployment. This is an issue when we have multiple people working on the same data hub, and the machine is relatively slow.

What behavior are you expecting? When starting quick start, provide an option to disable auto redeployment. Any re-deployment will be kicked off manually.

#### Tech details

Which Operating System are you using?

Which version of MarkLogic are you using?

Which version of the Data Hub Framework are you using? 2.0.0

Is this a QuickStart UI bug? If so, which browser are you using?

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by aebadirad** [comment]
Multi-tenant development is not supported with QuickStart as of yet. It's designed for local development and using version control, things are shared between developers, much like an IDE.

So closing this out as a shared development environment isn't QuickStart was designed to do.
