### ISSUE TITLE
When inserting a document from java, allow a flow to run

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#79]
When I insert a document into the staging database from Java I want to be able to run a flow.

With PUT /v1/documents you can specify a transform which would work similar to the MLCP transform.

http://docs.marklogic.com/REST/PUT/v1/documents

We should consider multiple ways that people may run this. 1) they may be running from a Java container that is accepting real-time inputs, or is consuming data from a queue. 2) someone may want to call MarkLogic directly. The PUT call requires a little extra knowledge about which transform to invoke that "makes it work." 3) a REST Extension or other entry method may be used and it should be easy to get that REST Extension to put data directly into the Prod database as a conformed doc (perhaps also storing to Staging, or perhaps not). 4) lastly, some raw ingest may want to automatically run a conform step, and may want to skip the RAW persist step in staging.

**Comment by maeisabelle** [comment]
Hi @paxtonhare and @damonfeldman,

I'm quite new in document ingestion with transforms and I have several questions regarding this issue as follows:
1. How would I know which flow will be run when inserting a document? 
2. I can see that we want to run the flow whenever we insert a document done from a Java container, direct call from MarkLogic, etc. Is running a flow automatic whenever we insert a document or explicitly called? I'm assuming the latter given my question on 1. 

Tagging @gmarintes for visibility.

**Comment by paxtonhare** [comment]
Mae,

 See http://docs.marklogic.com/guide/rest-dev/documents#id_84475

when you call PUT /v1/documents you specify a custom transform (which you need to write). That transform would look similar to Glenn's MLCP transform https://github.com/marklogic/data-hub-in-a-box/blob/master/data-hub/src/main/resources/ml-modules/root/com.marklogic.hub/mlcp-flow-transform.xqy

The docs I linked above describe how to pass parameters to the transform itself.  trans:paramname

That will allow you to specify which flow to run.

**Comment by paxtonhare** [comment]
Also, your custom transform would live here: https://github.com/marklogic/data-hub-in-a-box/tree/master/data-hub/src/main/resources/ml-modules/transforms

**Comment by damonfeldman** [comment]
Should we make this transform customizable like another plugin? That would be consistent with other customizable code, and would allow real-time ingest to behave differently from batch ingest. E.g. it could look for any related docs needed and kick off the transform immediately, so Final data is created right away. Also more logging or different security could be added.

**Comment by paxtonhare** [comment]
I vote we leave any such customizations as an exercise for the user. They can write their own transform.

Also, I'm not clear what you mean. The nature of this transform is that the document content is sent to MarkLogic in a PUT. That content is fed through this transform which happens to send the content through a flow. The output of the flow is then written to disk.

**Comment by damonfeldman** [comment]
Is the transform hard-coded and internal or visible/edit-able? I'm suggesting it be generated into the scaffolding like a plugin, with a default implementation that invokes the input flow on the content.

So I'm thinking of one default transform per flow with a default implementation that runs the flow that the transform (e.g. "realtime-ingest.xqy") is part of.

Are we saying the same thing?

**Comment by paxtonhare** [comment]
We are saying similar things. I was proposing we place the "realtime-ingest.xqy" in the DHIB Jar thus making it unaccessible to the end user. We are in agreement on what that transform should do.

My fear with putting said transform into the scaffolding is that we are making it very easy for users to break the ingest by messing with the file. Also, we would need to supply an xqy and an sjs version of it depending on their prefs.

I would rather just document that you can write your own transform if you need to. Make it an "off the rails" kind of feature.

What type of customizations do you see the end user making to this transform? Perhaps that will help me better see your perspective.

**Comment by damonfeldman** [comment]
Great point (I think). To confirm what you're saying - we will have custom REST extensions available for flows, including Ingest flows, so people can build an alternative ingest flow that does something different, and use that. The default real-time ingest endpoint will still be there.

We'll need to document how to call a flow so people can build a custom REST extension that calls the ingest flow, but I've always assumed a run-flow() function will be in scope so people can use flows in alternative ways.

is that the idea? If so I'm good with that.

About what people may do differently for real-time: I can imagine that real-time ingest would be immediately fed to the conformance flow (perhaps following Sam's pattern where it looks for related docs to see if the full package is ready for transform). Also, different logging and data provenance may be added. Errors may be handled somewhat differently to give realtime feedback rather than batch feedback.

**Comment by maeisabelle** [comment]
Hi @paxtonhare  and @damonfeldman,

I am now able to understand what you are discussing in this page. As discussed, the new custom transform will be added under https://github.com/marklogic/data-hub-in-a-box/tree/master/data-hub/src/main/resources/ml-modules/transforms. I can see that the content of that directory is already being deployed in MarkLogic during install (DataHub.install()). Given such, I only need to create the transform xqy inside it (I'm thinking of "runFlow.xqy" as a filename instead as it is what is actually doing) and I can name the transform to be "runFlow". I'll pattern "runFlow.xqy" with https://github.com/marklogic/data-hub-in-a-box/blob/master/data-hub/src/main/resources/ml-modules/root/com.marklogic.hub/mlcp-flow-transform.xqy as it is already running the flow (though it's running it using mlcp) then check what else needs to be done to capture all scenarios described in the ticket.

I'll keep you posted. Let me know if I missed anything and if you have comments.
