### ISSUE TITLE
Bug detection and message for code in QuickStart not updating or clearing

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#793]
#### The issue
A bug, such as undefined variable, is not cleared quickly or in a predictable way. It is difficult to know in the editors (e.g. for content.xqy) if the bug is still valid.

Specifically, "undefined variable $ident" was fixed but still reported. (this could be easily verified by a search, but other bugs are more subtle, making it hard to know if they are fixed or not).

What behavior are you expecting?
But should update as soon as the file is saved.

#### Tech details

Which Operating System are you using?

Which version of MarkLogic are you using?
9.0-3.1

Which version of the Data Hub Framework are you using?
2.0-4
Is this a QuickStart UI bug? If so, which browser are you using?
Chrome on OSX

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by damonfeldman** [comment]
here is an image. The file is saved (save button greyed out, confirmed in file-system) but bug remains for minutes after:

![image](https://user-images.githubusercontent.com/700633/37256601-70348e1c-2533-11e8-8297-b6d6df010d3b.png)

**Comment by damonfeldman** [comment]
Restarting QuickStart clears the bug (and moves on to the next bug).

**Comment by aebadirad** [comment]
This should be resolved in Data Hub 4.3.1, but also no longer applies to Data Hub 5. Closing issue, reopen if its discovered on 4.3.1.
