### ISSUE TITLE
quickstart harmonize flow view elides tab labels to meaninglessness

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/marklogic-data-hub#798]
OK, this is probably a deliberate design choice, rather than a bug, but I think it is horrible so I'm going to whine about it anyway:

If your browser window is too narrow (where too narrow is pretty darned wide, IMO), the plugin tab labels get elided to `</>` on the QuickStart Flows view when viewing a harmonization flow. These are the ones that should say Collector, Content, etc. That is super unhelpful.

![quickstart_flow_tabs](https://user-images.githubusercontent.com/1951367/37314746-08db1c6e-2613-11e8-9924-fc451c98a407.jpg)
 
I only figured it out it was a sizing problem because Aries said he'd seen it before when resizing his browser windows.  It looks like the break point is around 1270px, so I was probably just a bit below the threshold, but certainly with a width where I expect things to Just Work.

I guess `</>` is an icon, but it is one that meant nothing to me.  How is the new user supposed to intuit that `</>` means the title has been elided, instead of that something is randomly broken?

Less whitespace between the tabs, a smaller font, or a fallback that involved narrowing the labels incrementally instead completely would be nice. Yes, I know, first world problems. :) At least, once you figure out the cause it is.

This was QuickStart 2.0.3 running in Chrome on Windows.

┆Status: Done

**Comment by dmcassel** [comment]
➤ Alexander Ebadirad commented:

Make font smaller, not vanish so we can read what the tabs are instead of </>

**Comment by dmcassel** [comment]
➤ Alexander Ebadirad commented:

720p -> 4k? Ask [~sbrooks] for what is used and supported on for qconsole and adapt the fix to this.

Add estimates for hours too.

**Comment by dmcassel** [comment]
➤ Scott Brooks commented:

[~aebadira] (720p = 1280px, 4k = 3840px width) Query Console's minimum supported width is 1024px.

**Comment by dmcassel** [comment]
➤ Scott Brooks commented:

Change merged.  Passing to QA.

**Comment by dmcassel** [comment]
➤ Aries Yuwono commented:

Verified passed on develop for both input and harmonize flow

**Comment by aebadirad** [comment]
Fixed with release of 3.0.0
