### ISSUE TITLE
Integrate with Rob's sql migrator

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#80]
https://github.com/rjrudin/ml-sql-migrator

**Comment by jmakeig** [comment]
Probably an implementation detail of #78.

**Comment by popzip** [comment]
@rjrudin curious on status of above project.

I'm considering closing for now as this will likely be addressed by either a nifi connector or our roadmap for Ingestion capabilities into Data Hub Service.
