### ISSUE TITLE
Tutorial link hard coded to old (2.0.3) release

### ISSUE THREAD

**Issue by popzip** [marklogic/marklogic-data-hub#801]
Tutorial links to 2.0.3 wAR. Please remove hard link 
https://marklogic-community.github.io/marklogic-data-hub/tutorial/install/

┆Status: Closed

**Comment by popzip** [comment]
High priority (and easy fix) since can get people started with the wrong version that we know we already fixed bugs for.

**Comment by aebadirad** [comment]
Fixed with release of 3.0.0
