### ISSUE TITLE
[BUG] Documentation Bug

### ISSUE THREAD

**Issue by DavidEnnis-17llamas** [marklogic/marklogic-data-hub#8013]
DHF 6.0 is released:

https://github.com/marklogic/marklogic-data-hub/releases/tag/v6.0.0

The page above points out that One should be able to see the full release notes here:
https://docs.marklogic.com/datahub/release-notes.html

However, that redirects to the 5.8 docs and manual changing of the URL does not help.

**So, the expectation is:** Documentation for 6.0
**Actual result:** Documentation for 5.8

**Comment by Sanjeevani19** [comment]
The docs link is redirected to 6.0.0.

**Comment by DavidEnnis-17llamas** [comment]
Great.  Thank You for updating the docs!
