### ISSUE TITLE
arrow labels between entity can get hidden behind boxes

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/marklogic-data-hub#806]
It would seem that the Entities view in QuickStart has a problem with the placement of labels on lines connecting entities.

When running the tutorial, I created the Order and Product entities, as directed.  QuickStart wants to render an arrow from Order to Product. Fine.

However, I ended moving the entities around because the Order box was generated under the Product box. The label on the arrow from Order to Product is mostly hidden under the Order box if the arrow points "down and to the right", but OK if it points "down and to the left". See screenshot below. 

There doesn't seem to be a problem if the arrow points upward, oddly enough.

QuickStart/DHF v 2.0.4 via Chrome on Windows. ML running on RHEL 7.

![quickstart_arrow_label](https://user-images.githubusercontent.com/1951367/37376571-088f26d6-26e2-11e8-997d-d8ffe3002a78.jpg)

**Comment by aebadirad** [comment]
Due to age of issue, closing out. Please reopen if it is discovered on 5.0.1. Thanks!
