### ISSUE TITLE
Getting Started Tutorial

### ISSUE THREAD

**Issue by gfurbush** [marklogic/marklogic-data-hub#817]
In Step 2, the path name should be **store-data**/products.
 
https://marklogic-community.github.io/marklogic-data-hub/tutorial/load-products-as-is/

Same issue here:

https://marklogic-community.github.io/marklogic-data-hub/tutorial/load-orders-as-is/

┆Status: Done

**Comment by popzip** [comment]
May depend on if follow instructions to put in input path. Need to confirm.

**Comment by gfurbush** [comment]
Yeah, I skipped that step.  Maybe we should just say the folder holding the unzipped store-data.zip files.
