### ISSUE TITLE
Getting Started Tutorial, "Harmonizing the Order Data"

### ISSUE THREAD

**Issue by gfurbush** [marklogic/marklogic-data-hub#821]
The code shown for collector.sjs is significantly different from what I see.
https://marklogic-community.github.io/marklogic-data-hub/tutorial/harmonizing-order-data/

What's the drill here?  Should I update all of the code to match that shown in the Quick Start?

This is what I see:

/*
 * Collect IDs plugin
 *
 * @param options - a map containing options. Options are sent from Java
 *
 * @return - an array of ids or uris
 */
function collect(options) {
  // by default we return the URIs in the same collection as the Entity name
  return cts.uris(null, null, cts.collectionQuery(options.entity));
}

module.exports = {
  collect: collect
};

┆Status: New

**Comment by ayuwono** [comment]
Yes, you have to change the collector.sjs to:

```
/*
 * Collect IDs plugin
 *
 * @param options - a map containing options. Options are sent from Java
 *
 * @return - an array of ids or uris
 */
function collect(options) {
	const jsearch = require('/MarkLogic/jsearch.sjs');
  return jsearch
    .values('id')
    .where(cts.collectionQuery(options.entity))
    .slice(0, Number.MAX_SAFE_INTEGER)
    .result();
}

module.exports = {
  collect: collect
};
```
The tutorial says "the final collector.sjs should look like"

**Comment by aebadirad** [comment]
Closing out old issue that no longer applies to the latest major release.
