### ISSUE TITLE
Getting Started Tutorial, "Check out the Harmonized Orders"

### ISSUE THREAD

**Issue by gfurbush** [marklogic/marklogic-data-hub#822]
The harmonized orders don't have any data in the 'products' array.  They all look like this:

{
  "envelope": {
    "headers": {},
    "triples": [],
    "instance": {
      "Order": {
        "id": "792",
        "price": 8.99,
        "products": []
      },
      "info": {
        "title": "Order",
        "version": "0.0.1"
      }
    },
    "attachments": {
      "id": "792",
      "customer": "849",
      "order_date": "08/26/2017",
      "ship_date": "09/05/2017",
      "product_id": "1000102",
      "sku": "148979734999",
      "price": "8.99",
      "quantity": "2.0",
      "discounted_price": "7.06",
      "title": "unfair fact",
      "description": ""
    }
  }
}

**Comment by popzip** [comment]
Opportunity to show how to harmonize products and add data here
