### ISSUE TITLE
Expose the ability to set the writer plugin's target database in the QuickStart UI

### ISSUE THREAD

**Issue by eouthwaite** [marklogic/marklogic-data-hub#831]
Short description of the problem:

Expose the ability to set the writer plugin's database in the QuickStart UI

Following the excellent work in #319 and #423 it is possible to direct a harmonisation flow into a database other than FINAL

From a development standpoint, it would be useful to have the ability to do this from the UI - the Flow Info tab for a given Harmonize Flow (along with Batch Size and Thread count) seems a logical site

#### Tech details

Which Operating System are you using? Linux

Which version of MarkLogic are you using? 9.0-4

Which version of the Data Hub Framework are you using? 2.0.4

**Comment by aebadirad** [comment]
Done for Data Hub 5.0.0 and later.
