### ISSUE TITLE
defaults are missing on hub init tab

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#833]
Looks like the HubConfig refactor got rid of a bunch of the exposed properties that the /projects/{id}/defaults endpoint uses to populate the hub initialization tab of quickstart.

PR incoming shortly.

┆Status: Closed

**Comment by popzip** [comment]
@paxtonhare @aebadirad fixed in dev? please add label if so.

**Comment by dmcassel** [comment]
➤ Alexander Ebadirad commented:

[~ayuwono] confirm this is fixed, I see that it is on my 3.x dev branch

**Comment by dmcassel** [comment]
➤ Aries Yuwono commented:

Confirmed that this is fixed on both develop and 3.x-develop

**Comment by aebadirad** [comment]
Fixed with release of 3.0.0
