### ISSUE TITLE
Example in documentation is incorrect

### ISSUE THREAD

**Issue by eouthwaite** [marklogic/marklogic-data-hub#845]
The detail in the input flow via [REST API example](https://github.com/marklogic-community/marklogic-data-hub/wiki/Advanced-Hub-Usage#2-via-the-marklogic-rest-api) contains:

`trans:entity=YourEntityName&trans:flow=YourFlowName`

The correct parameters should be:

`trans:entity-name=YourEntityName&trans:flow-name=YourFlowName`

┆Status: Done

**Comment by dmcassel** [comment]
➤ Mike Wooldridge commented:

Fixed here:

https://github.com/marklogic-community/marklogic-data-hub/wiki/Advanced-Hub-Usage

**Comment by dmcassel** [comment]
➤ Aries Yuwono commented:

The example still shows:

trans:entity-name=YourEntityName&trans:flow=YourFlowName

It's still trans:flow instead of trans:flow-name

**Comment by popzip** [comment]
@wooldridge @ayuwono we should not be making updates to the wiki, these will shortly be deprecated. Update the github.io pages.

**Comment by dmcassel** [comment]
➤ Mike Wooldridge commented:

Thanks, [~ayuwono]. I made a final update to that page to fix that issue so we can close this bug. The corresponding page on github.io has the correct information (i.e., "entity-name" and "flow-name":

https://marklogic-community.github.io/marklogic-data-hub/ingest/rest/

**Comment by dmcassel** [comment]
➤ Aries Yuwono commented:

[https://marklogic-community.github.io/marklogic-data-hub/ingest/rest/](https://marklogic-community.github.io/marklogic-data-hub/ingest/rest/) has the correct params

**Comment by aebadirad** [comment]
Fixed with release of 3.0.0
