### ISSUE TITLE
remove explicit references to "hub in a box" and use "dhib"

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#85]
In time, the "in a box" name may no longer accurately reflect the nature of the project, or it might not give potential users a good idea of what it is for. 

Use "DHIB" in code (namespaces, functions, filenames) so it is not hard to re-brand as needed to accurately reflect and inform.

I think we can leave the logo alone for now.

**Comment by maeisabelle** [comment]
Hi @damonfeldman and @paxtonhare,

There are several occurrences of "in a box", "in-a-box" to be exact as follows:

1. Namespace "http://marklogic.com/hub-in-a-box" - will become "http://marklogic.com/dhib"
2. MarkLogic database, forest, app server names: "data-hub-in-a-box-STAGING*", "data-hub-in-a-box-FINAL*", "data-hub-in-a-box-FINAL*", "data-hub-in-a-box-content*", "data-hub-in-a-box-triggers*", "data-hub-in-a-box-modules*" - will replace "data-hub-in-a-box" with "dhib"

This will be replaced accordingly. Let me know if my understanding is correct. I'll be updating the codes afterwards.

**Comment by paxtonhare** [comment]
I vote for data-hub instead of dhib.

**Comment by maeisabelle** [comment]
I vote for **data-hub** as well. Given such, the following will be replaced:

1. Namespace "http://marklogic.com/hub-in-a-box" - will become "
    http://marklogic.com/data-hub"

2. MarkLogic database, forest, app server names:
    "data-hub-in-a-box-STAGING*", "data-hub-in-a-box-FINAL*",
    "data-hub-in-a-box-FINAL*", "data-hub-in-a-box-content*",
    "data-hub-in-a-box-triggers*", "data-hub-in-a-box-modules*" - will
    replace "data-hub-in-a-box" with "data-hub" 

Let me know if everyone agrees.
