### ISSUE TITLE
Tutorial: version numbers don't match

### ISSUE THREAD

**Issue by sbuxton** [marklogic/marklogic-data-hub#852]
In the DHF tutorial, during install, at https://marklogic-community.github.io/marklogic-data-hub/tutorial/install/ , the version numbers in the instructions no longer match the version numbers in e.g. filenames.
Example: quick-start-2.0.2.war is now quick-start-2.0.4.war

┆Status: Done

**Comment by popzip** [comment]
I believe @ayuwono may have also flagged similar. I'll group that as part of 3.0 release we need to update all docs/screenshots.

**Comment by popzip** [comment]
Future proof versions - don't hard link to version or reference specific version. if screenshot has version mention to update for your latest version.

**Comment by aebadirad** [comment]
Fixed with release of 3.0.0
