### ISSUE TITLE
Tutorial: content plugin instructions don’t quite match the default code

### ISSUE THREAD

**Issue by sbuxton** [marklogic/marklogic-data-hub#853]
At https://marklogic-community.github.io/marklogic-data-hub/tutorial/harmonizing-product-data/
-- instructions text says “let sku = xs.string(source.sku || source.SKU);” – default code says “let sku = …”; code under the heading “Here is the Final content.sjs file:” says
… “var sku = …”

  Also that code under the heading “Here is the Final content.sjs file:” includes a title, and the default code doesn’t (were we supposed to add that somewhere?)

┆Status: Closed

**Comment by wooldridge** [comment]
This is fixed in the 3.x version of the tutorial.

**Comment by wooldridge** [comment]
@kcoleman-marklogic, yes, thanks for reviewing!
