### ISSUE TITLE
Tutorial: Stage documents are not raw data

### ISSUE THREAD

**Issue by sbuxton** [marklogic/marklogic-data-hub#860]
#### The issue

When I load the Product data in the tutorial, the documents I see in stage are envelope documents with all data in the "instance" property.

I expected to see the Stage documents as raw data - that is, the Products loaded as-is - not as envelope documents.

I do see "raw" documents - as I'd expect - when I go to Jobs-Traces-click on a document.
"Content Plugin" shows me the raw documents as both rawContent and output.
(Even this isn't quite what I expected - the input documents are .CSV, so I'd expect to see a .CSV under "rawContent"). 

But when I click on Browse Data-Staging and click on a document, I see an envelope document like this:

{
  "envelope": {
    "headers": {},
    "triples": [],
    "instance": {
      "id": "9",
      "sku": "372801441675",
      "title": "Sunglasses",
      "game_title": "liable greenhouse",
      "description": "sunglasses for liable greenhouse",
      "price": "15.0",
      "game_id": "1000194",
      "game_SKU": "105698185919"
    },
    "attachments": null
  }
}

  That's before I do any Harmonize flow - I've only done the Load.

  What am I missing?

#### Tech details

Which Operating System are you using?
Linix
Which version of MarkLogic are you using?
9.0-4 nightly
Which version of the Data Hub Framework are you using?
2.0.4
Is this a QuickStart UI bug? If so, which browser are you using?
Chrome

**Comment by grechaw** [comment]
Hi @sbuxton , DHF chooses to wrap documents even on ingest. There's no raw ingest at all.

**Comment by lifan0127** [comment]
I think this is by design. See: https://github.com/marklogic-community/marklogic-data-hub/wiki/Overall-Data-Flow

![data flow](https://github.com/marklogic-community/marklogic-data-hub/wiki/images/OverallDataFlow.png)

**Comment by wooldridge** [comment]
Similar to issue https://github.com/marklogic/marklogic-data-hub/issues/895

**Comment by aebadirad** [comment]
We always wrap in an envelope by default, unless the user takes steps to truly 'load as is'. This is intentional and serves as a way for us to put relationships and metadata with the document without modifying the original document's structure and context.
