### ISSUE TITLE
Tutorial: screenshot incorrect

### ISSUE THREAD

**Issue by sbuxton** [marklogic/marklogic-data-hub#861]
At https://marklogic-community.github.io/marklogic-data-hub/tutorial/modeling-product-entity
the screenshot shows 0 documents in every database.
At this stage of the process, the database document counts should be 450 - 1 - 450 - 1 (starting at top left and reading clockwise).

┆Status: New

**Comment by wooldridge** [comment]
This is fixed in the 3.x docs, the screenshot shows the counts described above: 
https://marklogic.github.io/marklogic-data-hub/tutorial/modeling-product-entity/
