### ISSUE TITLE
Entity rendering is unreliable - edit, delete, description

### ISSUE THREAD

**Issue by sbuxton** [marklogic/marklogic-data-hub#862]
#### The issue

When I click on Entities, the rendering of each entity is unstable.

1. I see the edit icon in top right, but I've also seen that disappear
2. I've never seen the delete icon, though I've found it accidentally
3. the description in the middle of the icon - "No description yet" and "No Base URI yet" - is unreadable unless I make characters smaller (click CTRL-Minus twice).
#### Tech details

Which Operating System are you using?
windows for the browser
Which version of MarkLogic are you using?
9.0-4 nightly
Which version of the Data Hub Framework are you using?
2.0.4
Is this a QuickStart UI bug? If so, which browser are you using?
Chrome

**Comment by sbuxton** [comment]
I'm now using V3 of the Quickstart, MarkLogic 9.07-2, and I just updated Chrome to the latest version ( 71.0.3578.80), and the Entities editor doesn't work at all for me.

http://localhost:8080/#/entities
Click "Entities", and I see a very small icon for the Entity I've created (Product).
I can't click on any of the buttons, including the edit button (pen) - clicking anywhere on the Entity icon grabs the whole thing as if I were going to move it.  I see a cross with arrows. If I "move" the icon, it doesn't actually go anywhere until I refresh the screen.

I can edit the entity fine from Firefox.

![image](https://user-images.githubusercontent.com/887112/49618383-3faf3a80-f96d-11e8-919a-0b51bb94f361.png)

**Comment by sbuxton** [comment]
Reopening this issue - I never saw it resolved, and with V3 it seems worse.

**Comment by ayuwono** [comment]
This could be browser version issue. I use chrome version 70 and it looks fine

**Comment by aebadirad** [comment]
These issues should be resolved with Data Hub 5.
