### ISSUE TITLE
Entities rendering: link is unstable

### ISSUE THREAD

**Issue by sbuxton** [marklogic/marklogic-data-hub#863]
#### The issue

Following the Quickstart Tutorial, when I have Products + Orders under the Entities tab, the link between the two is unstable.
If I move the Orders box around, the link switches between:
-- no link
-- link with no arrow, no label
-- link with arrow, no label, does not reach the Products box
-- link with arrow, label 1..INF, reaches Product box

#### Tech details

Which Operating System are you using?
Linux
Which version of MarkLogic are you using?
9.0-4 nightly
Which version of the Data Hub Framework are you using?
2.0.4
Is this a QuickStart UI bug? If so, which browser are you using?
Chrome on Windows

**Comment by aebadirad** [comment]
Duplicate of issue #806 so closing to consolidate issues
