### ISSUE TITLE
com.marklogic.quickstart.service.FlowManagerServiceTest failing

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-data-hub#866]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

com.marklogic.quickstart.service.FlowManagerServiceTest  test is failing

#### Tech details

Which Operating System are you using?
Windows

Which version of MarkLogic are you using?
9.0-20180405

Which version of the Data Hub Framework are you using?
latest develop code as of 4/4

Is this a QuickStart UI bug? If so, which browser are you using?
Yes

The mlcp transform fails  with 
```
<error:format-string xmlns:error="http://marklogic.com/xdmp/error" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">error (MISSING_CURRENT_TRACE): fn.error(xs.QName("MISSING_CURRENT_TRACE")); -- </error:format-string>
```

The mlcp transform function (mlcp-flow-transform.xqy) calls flow:run-flow() and finally when main.sjs is called , the run flow context(rfc) is empty causing the dhf.run() to fail . If main.sjs is modified to load dhf.xqy module  instead of dhf.sjs in main.sjs , the test runs fine.
const dhf = require('/MarkLogic/data-hub-framework/dhf.xqy'); 

 Run flow context is empty if dhf.sjs is loaded whereas it is 
```
{"trace":{"plugin-label":"triples", "plugin-input":{"content":{"testing":123}, "headers":{"a":1, "b":2}}, "created":"2018-04-05T12:22:57.3417593-07:00", "traceId":"13190221625523839751"}, "identifier":"/input.json", "options":{"triplesTest":"triples", "flowType":"input", "headersTest":"headers", "flow":"sjs-json-input-flow", "entity":"test-entity", "dataFormat":"json"}, "content":{"testing":123}}
```
when dhf.xqy is loaded as expected

┆Status: New

**Comment by grechaw** [comment]
Thanks for this error report.  Good to have more information to track it down.  I'm actively working on addressing our errors in tests.

**Comment by grechaw** [comment]
This issue is fixed in my most recent PR #875 , although there will be another change or two in that commit before it gets merged.

**Comment by grechaw** [comment]
My fix for this issue caused a problem with quickstart's initialization.
https://project.marklogic.com/jira/browse/DHFPROD-762

**Comment by grechaw** [comment]
Hi @srinathgit this is fixed in develop and 3x now.
We have yet to see if the  mlcp error is fixed though

**Comment by popzip** [comment]
also does it need Quickstart label?
