### ISSUE TITLE
RFE: Support writing of custom metadata to a job

### ISSUE THREAD

**Issue by tternquist** [marklogic/marklogic-data-hub#869]
#### The issue
For our application we need to write custom metadata our jobs. 

#### Tech details
As a work around we needed to create our own job model (same one as referenced in #868 ). Some examples of metadata we write:

- JSON schema validation errors
- % passing as of step in workflow (we have multiple flow steps)

An interface to pass in JSON or XML in the collector and flows would be ideal.

**Comment by aebadirad** [comment]
Good suggestion. Job/batch documents in 5.0 could use this capability instead of the static values (other than errors/notices/warnings) we save. Raises the request level with product if this is still desired in 5.0
