### ISSUE TITLE
RFE: Ability to log all errors to error log

### ISSUE THREAD

**Issue by tternquist** [marklogic/marklogic-data-hub#870]
#### The issue
The use of the tracing database for errors can be confusing to a developer, especially one who is used to finding errors in the ErrorLog. It would be create if all errors could be configured to go to error log, with option of also going to tracing. This is also important for integrating with log aggregators like splunk. It would be a challenge to look in both the ErrorLog and tracing db for errors and would like require a custom process to pull the tracing ones.

#### Tech details
To work around this, we extensively use try/catch in our application and log in the catch. We also have a separate Error model that we write to when we choose to record a failure. This would be a record that indicates which record may have failed processing and why, e.g., validation failure.

**Comment by aebadirad** [comment]
Data Hub 5 now allows for this, including recording the error to the batch document at various levels with the built in datahub.debug library.
