### ISSUE TITLE
RFE: Write custom metadata to tracing records

### ISSUE THREAD

**Issue by tternquist** [marklogic/marklogic-data-hub#871]
#### The issue
In our application it is important to be able to write custom metadata to tracing db. This would include information such as schema validation failures and general reasons why a record may have failed to process.  It would be be great to have an interface to write these metadata in XML/JSON within collector, flows.

This is related to RFE #870, #869 

#### Tech details
As a workaround, we write custom error records. Note that these records have application specific permissions

**Comment by mchiarelli** [comment]
+1. Would like to see the ability to write a custom trance message to the jobs db without turning on all traces.  Would expect to see, with general flow tracing turned off, only error traces (for specific doc with doc in error, and user defined trace. This would be used to support validation errors that are not programming exceptions.

**Comment by aebadirad** [comment]
Closing out old issue that no longer applies to the latest major release - tracing has been removed for 5.x and instead batch documents have been introduced, which can run in production.

Data Hub 5 also supports the recording of debug/error messages and capturing them both to the log and batch documents.
