### ISSUE TITLE
RFE: Use consistent REST extension directory structure between DHF and ml-gradle

### ISSUE THREAD

**Issue by tternquist** [marklogic/marklogic-data-hub#872]
#### The issue
The convention of where REST extensions must reside is different between vanilla ml-gradle and DHF ml-gradle:

Vanilla ml-gradle:
```src/main/ml-modules/ext/services```

DHF ml-gradle
```plugins/entities/input/REST/services```

This discrepancy can be confusing to developers and is difficult to explain why it has to be this way. I believe there should be a consistent and configurable way to specify where REST extensions must reside.

This is related to #666

**Comment by miguelrgonzalez** [comment]
Also,
sometimes we need to create cross-entity REST extensions. Meaning: extensions that do not belong to a particular entity, but a group of them.

This can be currently achieved in a somewhat hacky way, placing rest extensions under the following folder: ./buildSrc/src/main/resource/ml-modules/services/

**Comment by iowusu** [comment]
RESTextension should not be input. On my current project, we are forced to put all different REST ext. into a single input flow even when the REST ext has nothing to do with that specify input flow.  Is there a technical reason for this partner in DHF?

**Comment by grechaw** [comment]
In 4.0.0, just put services in src/main/ml-modules/services for FINAL and src/main/ml-modules-staging/services for STAGING.   Thanks for prodding us along in this direction.
