### ISSUE TITLE
RFE: Better documentation and guidance on using DHF in production

### ISSUE THREAD

**Issue by tternquist** [marklogic/marklogic-data-hub#874]
#### The issue
I have found that there is a fair bit of work required to plan and integrate DHF in a production environment. For example, Quick Start or gradle tasks would not be sufficient to run in a production environment where human is not directly involved.

A use case we are currently dealing with is the need to trigger harmonization flows when a new file lands and notify systems/users of flow run and its results. Result of one flow may dictate the next flow to be run.

To support this, we had to use entirely REST and have a separate job control application to handle control flow and notifying users of progress. The stack does not include Java so we have less to go on without the Java client. 

It would be great to have some guides/tutorials on how customers get their DHF application into production and operational.

**Comment by grechaw** [comment]
An excellent point @tternquist . From a dev perspective, and in the short term, we're stuck in tooling/capability land for a little while, but DHF has to turn into a more production-ready tool over the next months.

I'll be curious how the new "Data Integration Guide" helps address some of this. 

As far as job control goes, I think we're still targeting Java --- so PM will be interested to hear whether there's some missing info about what field/customers need.
