### ISSUE TITLE
Better file browsing on load-data

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#88]
Sort of two tickets

1) use a file-chooser dialog to choose the input directory. Someday it may be a single document file or .zip of many documents, but for now, one directory is good.

2) remember the previous location per input flow. Certainly within one run of QuickStart, perhaps longer (across runs).

**Comment by maeisabelle** [comment]
Hi @damonfeldman and @paxtonhare,

I've been thinking about the file-chooser dialog use cases. The HTML-based file chooser dialog opens a file chooser based on the client's filesystem. Are we going to support remote deployment of quick-start? If the quick-start application is deployed remotely, loading of data coming from the client's filesystem will not work unless we upload the file before the actual loading. Else, we need to support browsing of the server's file system (where quick start is deployed) to select the folder where to get the data to load. 

Let me know which will be the intended behavior. 

Tagging @gmarintes  for visibility. 

Please advise. Thanks!

**Comment by damonfeldman** [comment]
Client filesystem is fine.

We talked this over a while ago, and decided that while remote MarkLogic is worth supporting (hence the IP address of the server, rather than hardcoded localhost) QuickStart will be a local machine developer tool, so you can use the browser's file chooser.
