### ISSUE TITLE
Getting intermittent errors when enabling workflows

### ISSUE THREAD

**Issue by SDFowler** [marklogic/marklogic-data-hub#888]
Short description of the problem:
I get an intermittent error where I can't use the workflows.  I Have only experienced it with the input flow, But because the input flow failsI don't get to try out my harmonization scripts.   

What behavior are you expecting?
Load of the content from the folder I specify.  I have selected the correct type of upload for the file type.
#### Tech details

Which Operating System are you using?
OSX 10.12.6
Which version of MarkLogic are you using?
9.0.4
Which version of the Data Hub Framework are you using?
2.0.4
Is this a QuickStart UI bug? If so, which browser are you using?
Not a UI issue.

If possible, rerun the command with -d for debugging output and attach the output:

It is an intermittent problem so hard to replicate, But I was able to Grab this From the Console output.

[DHF_Error.txt](https://github.com/marklogic-community/marklogic-data-hub/files/1916208/DHF_Error.txt)

**Comment by popzip** [comment]
The error has some text about TDE failing. Can you share your template? Maybe test your templates using TDE validate API in Query Console?

**Comment by aebadirad** [comment]
Closing for lack of response, if you still need help, please do reopen!
