### ISSUE TITLE
Quickstart: Start time for Job and associated Trace "created" time are not consistent if DHF framework and Marklogic db timezones are different

### ISSUE THREAD

**Issue by danielholgate** [marklogic/marklogic-data-hub#892]
DHF quick start 2.0.4 running on Mac. Database is MarkLogic 9.0.4 running in a CentOS 7 Vagrant-created VM.

Not really a bug, more a niche scenario behaviour and just noting here: Jobs and Tasks record their start times differently which can be confusing if the timezone on the server where DHF quickstart is running and MarkLogic db server timezone are different.

I noticed this when I accidentally used DHF on my local Mac against MarkLogic running on a Vagrant box where the system time was set to a different timezone. When you submit a Job the start time used is the DHF current time and so shows correctly in the UI (ie. 1 minute ago) however the Task seems to get its start time from the Marklogic db time (in this case, shows 19 hours ago). Here are some screen shots to show this:

<img width="1171" alt="jobs_tab" src="https://user-images.githubusercontent.com/13762269/38924453-46372718-42fd-11e8-90b2-bc916a70ae57.png">
<img width="1106" alt="traces_tab" src="https://user-images.githubusercontent.com/13762269/38924458-490ea790-42fd-11e8-8eff-98979ea54858.png">

I looked in the JOBS database and the startTime and endTime properties in the Job document looked like this for a job I ran at 9:13am

"jobId": "826c0a20-1a89-403e-a405-b05ffcb2f728", 
"flowType": "input", 
"flowName": "Load Opta Data", 
"entityName": "Match", 
"jobName": null, 
"startTime": "2018-04-18T09:13:43.135Z", 
"endTime": "2018-04-18T09:13:46.120Z", 

However the associated Trace for that Job records its start time from the MarkLogic database server  time so show 19 hours ago. The associated document from the TRACE database looks like this:

<trace>
<jobId>826c0a20-1a89-403e-a405-b05ffcb2f728</jobId>
<format>xml</format>
<traceId>15263764422695050320</traceId>
<created>2018-04-17T15:59:44.560328+02:00</created>

This scenario is a niche but worth noting for future improvement.

**Comment by aebadirad** [comment]
Data Hub 5 handles all of this on the server, so timezones should be consistent with the server, instead of like in 4.x where the client wrote the update sometimes.
