### ISSUE TITLE
 QuickStart shows incorrect installation progress during failure

### ISSUE THREAD

**Issue by nishantsingh1** [marklogic/marklogic-data-hub#984]
Short description of the problem:
Installation progress shows "100% complete" while there is an installation error at step 23 of 41. 
This is related to #983 

What behavior are you expecting?
It should show actual installation progress (up to step 22, for completed steps)

#### Tech details
Which Operating System are you using?
Linux (RHEL 7)

Which version of MarkLogic are you using?
MarkLogic 9.0-4

Which version of the Data Hub Framework are you using?
3.x (quick-start-3.0.0.war)

Is this a QuickStart UI bug? If so, which browser are you using?
Firefox and Chrome

#### The devil is in the details...
![data](https://user-images.githubusercontent.com/11027324/39754956-90460722-52e1-11e8-8870-65fbe907cbb3.jpg)UNITO-UNDERSCORE!hub!UNITO-UNDERSCORE!quickstart!UNITO-UNDERSCORE!issues!

**Comment by ayuwono** [comment]
A fix is implemented in 4.1.1
