### ISSUE TITLE
writer function in harmonization flow not executed in 9.0-5

### ISSUE THREAD

**Issue by joecrean** [marklogic/marklogic-data-hub#998]
#### The issue

Short description of the problem:

Upon upgrading to ML 9.0-5 i noticed that when i run the harmonisation flows the output documents are not to be found in the database. On closer examination it seems the writer function  is not executed.

#### Tech details

Which Operating System are you using?

windows 7 

Which version of MarkLogic are you using?
9.0-5

Which version of the Data Hub Framework are you using?
3.0.0

#### The devil is in the details...

The implementation of `dhf:run-writer` in my default installation is 

```
declare function dhf:run-writer(
  $writer-function,
  $id as xs:string+,
  $envelope as item(),
  $options as map:map)
{
  flow:queue-writer($writer-function, $id, $envelope, $options)
};

```

it simply never calls the writer function..  I think it needs to call something like `flow:run-writer`

**Comment by joecrean** [comment]
looks like the ml packaged DHF libs do not correspond to the master in DHF github... where the above mention function looks correct

**Comment by joecrean** [comment]
" ml packaged DHF" ... i mean the DHF libraries that are now installed with the MarkLogic product

**Comment by grechaw** [comment]
The code in 9.0-5 under /MarkLogic/Modules/MarkLogic/data-hub-framework should certainly match what's in master.

@aebadirad remarked to me yesterday that the upgradeHub() method in the Java project is supposed to update your writer to use the new function signature, which has indeed changed.  Did you run any upgrade code on your project?

**Comment by joecrean** [comment]
The update task does nothing in my project. There is quite a difference between the code installed by ML 9.0-5 and the master branch in the github project. I am going to look at this again now to see if i can resolve.

**Comment by joecrean** [comment]
ok first of all my bad - data hub master and `/MarkLogic/Modules/MarkLogic/data-hub-framework` are in sync.

However there is a real problem in that the writer function is not being called. I have not seen any difference in the writer function signature. 

I have gotten my application to work again by making the following changes: 

`MarkLogic/data-hub-framework/dhf.xqy`

```
declare function dhf:run-writer(
  $writer-function,
  $id as xs:string+,
  $envelope as item(),
  $options as map:map)
{
  flow:queue-writer($writer-function, $id, $envelope, $options)
  (: bug 998 START of changes:)
  ,
  flow:run-writers($id)
  (: bug 998 END of changes:)
};
```

`MarkLogic/data-hub-framework/impl/flow-lib.xqy`

```
declare function flow:run-writers(
  $identifiers as xs:string*)
{
  (: bug 998 START of changes:)
  let $item-context :=
        rfc:new-item-context()
        => rfc:with-id($identifiers[1])
        => rfc:with-trace(trace:new-trace())
  let $_ := map:put($context-queue, $identifiers[1], $item-context)
  (: bug 998 END of changes:)

  let $updated-settings .....  as before
```

**Comment by joecrean** [comment]
hey @grechaw  do you need anything else from me on this?

**Comment by grechaw** [comment]
Those changes should not be needed to run your writers.  The structure of writer plugins themselves changed in 3.0, and now it's the main module of the plugin that calls dhf:run-writer().

```
  })

  let $triple-context := dhf:triples-context($content, $headers)
  let $triples := dhf:run($triple-context, function() {
    triples:create-triples($id, $content, $headers, $options)
  })

  let $envelope := dhf:make-envelope($content, $headers, $triples, map:get($options, "dataFormat"))
  return
    (: writers must be invoked this way.
     see: https://github.com/marklogic/marklogic-data-hub/wiki/dhf-lib#run-writer :)
    dhf:run-writer(xdmp:function(xs:QName("writer:write")), $id, $envelope, $options)
};
```

Something about upgrade did not work -- I heard that it's transparent in quickstart but that we missed upgrade step for people just using the java or ml-gradle.  Do you think that's what's happened to you?

**Comment by grechaw** [comment]
@aebadirad you have a lot more experience with the 2 vs 3 and made the upgrade code -- can you tell me whether we need to grab a repro of Joe's issue, because I also don't understand what's going on here

**Comment by joecrean** [comment]
@aebadirad @grechaw 
i would have to do a lot of sanitising before handing over the project.. is there any documentation on the upgrade... otherwise i willl look in the souce code (of the upgrader).

**Comment by joecrean** [comment]
@aebadirad  @grechaw 
ok i have checked out the upgrader and see that it changes all the paths of the dhf modules , i have already done that. Also it updates legacy flows to add a main.xqy module..mine do not quallify for this. So... the real question here is how the flow structure has changed because when i look at the examples I do not see any change, however something is clearly wrong ...probably in my project . I  have implemented workaround within ML source xqy so that we can continue to work productively and can wait for documentation which hopefully shed light on this.

**Comment by popzip** [comment]
@sbayatpur-ml flagging as upgrade related. pls respond if applicable to planned work.

**Comment by joecrean** [comment]
@grechaw 
i have done some more testing with this. I created a noddy little flow and was able to recreate the problem (am on 9.0-6.1 iin the meantime). I attach it below - just drop the expanded directory into your `entities` folder. 
[Product.zip](https://github.com/marklogic/marklogic-data-hub/files/2294376/Product.zip)

You will need to change the collector to pick up some documents,, just add a small xml doc in staging with a collection that you set in the collector then you can execute the flow. The issue is in `main.xqy` : as long as you do not try to change the outgoing uri in the `id` parameter all is good. However if you try to set a `uri` and pass that the `write` function is never called. The process is running as `admin`. 
Even if I assign `id` to `uri` it will not work witjhout applying `xdmp:eager` to `uri`. As I said if i try to create a completely different `uri` it is always ignored. Of course in my actual application i am doing exactly this i.e. setting the uri of the document to be written (different from the `id` param). 

I verified this on the customer laptop where i first witnessed the problem (it is cross platform) and also on my ML laptop with a completely fresh environment (9.0-6.1) and DHF 3.0.

Would appreciate some help on this - I think it is an DHF bug or maybe I am using it wrong. Should I not be setting the uri in this way?

**Comment by grechaw** [comment]
Hi @joecrean this is good info.  Let's see if the team can triage and repro.

**Comment by joecrean** [comment]
@grechaw 
i see you have changed the tag on this one Charles, does this mean you were able to repro?

**Comment by grechaw** [comment]
IHi @joecrean no, not personally, I just think you have enough info to go on here.  I don't see being able to triage until Thursday or Friday unfortunately.

**Comment by aebadirad** [comment]
Finally tracked this down and it's fixed in dev and will be available in the 4.0.1 release

The updater regex was not aggressive enough to catch every instance of run-writer

**Comment by joecrean** [comment]
hey @aebadirad , i know this ticket is closed but i am currently upgrading to 4.1.1 from 2.0.6.. and i see the same issue in my harmonisation flows (xqy). Very specifically, in main.xqy if I pass anything other than the input parameter $id to `dhf:run-writer` then it does not execute the writer. That means if I recalculate $id or a different variable $uri for that matter and try to pass that then I see this effect. Are we having some sort of context problem, where it uses the original value of $id as a key in this queue writer thing? I wlll try to debug.

**Comment by joecrean** [comment]
@aebadirad 

for example - this wont work in `main.xqy`
```
    let $id := make-uri($envelope/asset-id)
    return   dhf:run-writer(xdmp:function(xs:QName("writer:write")), $id, $envelope, $options)
```
if i leave `$id` unchanged and place the line above directly in the writer.. it is all good.
```
    let $id := make-uri($envelope/asset-id)
    return
    xdmp:document-insert($id, $envelope, cfg:get-insert-doc-options($options) )

```

**Comment by aebadirad** [comment]
The resolution to this is now a part of Data Hub 5.0 where the URI can be modified on each content object before being written.
